### ISSUE TITLE
Cassandra driver upgrade breaks compatibility

### ISSUE THREAD

**Issue by castorm** [testcontainers/testcontainers-java#1011]
Cassandra DataStax driver version 3.5 breaks compatibility due to its metrics dependency.

More details can be found here:
https://docs.datastax.com/en/developer/java-driver/3.5/manual/metrics/

I would assume the simple way out can be taken as for most people metrics in general, and JMX reporter specifically, aren't needed when running tests:

On `CassandraContainer`:
```
    public static Cluster getCluster(ContainerState containerState) {
        return Cluster.builder()
                .addContactPoint(containerState.getContainerIpAddress())
                .withPort(containerState.getMappedPort(CQL_PORT))
+               .withoutMetrics()
+               .withoutJMXReporting()
                .build();
    }
```

The exception raised unless doing the above would look like:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/codahale/metrics/JmxReporter
    at com.datastax.driver.core.Metrics.<init>(Metrics.java:103)
    at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1402)
    at com.datastax.driver.core.Cluster.init(Cluster.java:159)
    at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:330)
    at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:305)
    at com.datastax.durationtest.core.DurationTest.createSessions(DurationTest.java:360)
        ....
Caused by: java.lang.ClassNotFoundException: com.codahale.metrics.JmxReporter
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
    ... 8 more
```

**Comment by castorm** [comment]
I actually couldn't find it on a first search, but duplicate: #905
