### ISSUE TITLE
ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [1883] should be listening)

### ISSUE THREAD

**Issue by uskova** [testcontainers/testcontainers-java#1153]
Hi!
I'm facing this error when trying to use testcontainers to start mqtt broker vernemq for tests:
```
java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [32900, 1883] should be listening)

	at org.rnorth.ducttape.timeouts.Timeouts.callFuture(Timeouts.java:68)
	at org.rnorth.ducttape.timeouts.Timeouts.doWithTimeout(Timeouts.java:60)
	at org.testcontainers.containers.wait.strategy.WaitAllStrategy.waitUntilReady(WaitAllStrategy.java:17)
	at org.testcontainers.containers.DockerComposeContainer.waitUntilServiceStarted(DockerComposeContainer.java:190)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at org.testcontainers.containers.DockerComposeContainer.waitUntilServiceStarted(DockerComposeContainer.java:170)
	at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:154)
	at org.testcontainers.containers.DockerComposeContainer.starting(DockerComposeContainer.java:121)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [32900, 1883] should be listening)
	at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:47)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.wait.strategy.WaitAllStrategy.lambda$waitUntilReady$0(WaitAllStrategy.java:19)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

My docker-compose file:
```yaml
version: '2'
services:
  vernemq:
    image: erlio/docker-vernemq
    ports:
      - "1883:1883"
    environment:
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
```

And here is the code:
```java
@ClassRule
public static DockerComposeContainer vernemq = new DockerComposeContainer(new File("src/test/resources/docker-compose.yaml"))
      .withExposedService("vernemq", 1883);
```

I configured testcontainers to run mongo or nginx and it worked fine, so the problem seems to be not in docker or environment configuration. 
So could you please suggest how to solve this problem?

**Comment by bsideup** [comment]
Hi @uskova,

Does it fail if you remove static port binding (change from `"1883:1883"` to `"1883"`)?

**Comment by uskova** [comment]
Yes, the same error:
java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [32903] should be listening)

	at org.rnorth.ducttape.timeouts.Timeouts.callFuture(Timeouts.java:68)
	at org.rnorth.ducttape.timeouts.Timeouts.doWithTimeout(Timeouts.java:60)
	at org.testcontainers.containers.wait.strategy.WaitAllStrategy.waitUntilReady(WaitAllStrategy.java:17)
	at org.testcontainers.containers.DockerComposeContainer.waitUntilServiceStarted(DockerComposeContainer.java:190)
	at java.base/java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603)
	at org.testcontainers.containers.DockerComposeContainer.waitUntilServiceStarted(DockerComposeContainer.java:170)
	at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:154)
	at org.testcontainers.containers.DockerComposeContainer.starting(DockerComposeContainer.java:121)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [32903] should be listening)
	at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:47)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.wait.strategy.WaitAllStrategy.lambda$waitUntilReady$0(WaitAllStrategy.java:19)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by uskova** [comment]
Sure, fixed formatting, sorry for that. This is my first issue =)
Here is my logs: {% gist 501235160bc4d1caa754cb13ab479d56 %}

**Comment by uskova** [comment]
Sure, fixed formatting, sorry for that. This is my first issue =)
Here is my logs: https://gist.github.com/uskova/501235160bc4d1caa754cb13ab479d56{% gist 501235160bc4d1caa754cb13ab479d56 %}

**Comment by bsideup** [comment]
@uskova,

It seems that the script attempts to auto-detect the IP address to listen on:
https://github.com/vernemq/docker-vernemq/blob/bea60e3af15c2118e4cc27e498fcee50cd6cffd4/bin/vernemq.sh#L4

Try adding `DOCKER_IP_ADDRESS=0.0.0.0` to listen on all interfaces :)

**Comment by uskova** [comment]
My tests have finally passed! Thank you a lot!!! I've been struggling with it for several days. You save my day =)

**Comment by bsideup** [comment]
@uskova happy to help :)
