### ISSUE TITLE
Couchbase container startup fails

### ISSUE THREAD

**Issue by adamdyga** [testcontainers/testcontainers-java#1179]
Hello, 

I'm using TestContainers 1.10.5 to run Couchbase 5.1.3 container.
Unfortunately the container startup *randomly* fails, with the following logs:

```
build	25-Jan-2019 09:56:18	    [INFO] [org.testcontainers.dockerclient.DockerClientProviderStrategy] Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy from ~/.testcontainers.properties, will try it first
build	25-Jan-2019 09:56:18	    [INFO] [org.testcontainers.dockerclient.DockerClientProviderStrategy] Will use 'okhttp' transport
build	25-Jan-2019 09:56:20	    [INFO] [org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy] Found docker client settings from environment
build	25-Jan-2019 09:56:20	    [INFO] [org.testcontainers.dockerclient.DockerClientProviderStrategy] Found Docker environment with Environment variables, system properties and defaults. Resolved:
build	25-Jan-2019 09:56:20	        dockerHost=unix:///var/run/docker.sock
build	25-Jan-2019 09:56:20	        apiVersion='{UNKNOWN_VERSION}'
build	25-Jan-2019 09:56:20	        registryUrl='https://index.docker.io/v1/'
build	25-Jan-2019 09:56:20	        registryUsername='xxxx'
build	25-Jan-2019 09:56:20	        registryPassword='null'
build	25-Jan-2019 09:56:20	        registryEmail='null'
build	25-Jan-2019 09:56:20	        dockerConfig='DefaultDockerClientConfig[dockerHost=unix:///var/run/docker.sock,registryUsername=xxxx,registryPassword=<null>,registryEmail=<null>,registryUrl=https://index.docker.io/v1/,dockerConfigPath=/home/xxxx/.docker,sslConfig=<null>,apiVersion={UNKNOWN_VERSION},dockerConfig=<null>]'
build	25-Jan-2019 09:56:20
build	25-Jan-2019 09:56:23	    [INFO] [org.testcontainers.DockerClientFactory] Docker host IP address is 172.17.0.1
build	25-Jan-2019 09:56:23	    [INFO] [org.testcontainers.DockerClientFactory] Connected to docker:
build	25-Jan-2019 09:56:23	      Server Version: 18.06.1-ce
build	25-Jan-2019 09:56:23	      API Version: 1.38
build	25-Jan-2019 09:56:23	      Operating System: Debian GNU/Linux 9 (stretch) (containerized)
build	25-Jan-2019 09:56:23	      Total Memory: 7987 MB
build	25-Jan-2019 09:56:24	    [WARN] [org.testcontainers.utility.ResourceReaper] Can not connect to Ryuk at 172.17.0.1:32824
build	25-Jan-2019 09:56:24	    java.net.ConnectException: Connection refused (Connection refused)
build	25-Jan-2019 09:56:24	    	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
build	25-Jan-2019 09:56:24	    	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:400)
build	25-Jan-2019 09:56:24	    	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:243)
build	25-Jan-2019 09:56:24	    	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:225)
build	25-Jan-2019 09:56:24	    	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:402)
build	25-Jan-2019 09:56:24	    	at java.base/java.net.Socket.connect(Socket.java:591)
build	25-Jan-2019 09:56:24	    	at java.base/java.net.Socket.connect(Socket.java:540)
build	25-Jan-2019 09:56:24	    	at java.base/java.net.Socket.<init>(Socket.java:436)
build	25-Jan-2019 09:56:24	    	at java.base/java.net.Socket.<init>(Socket.java:213)
build	25-Jan-2019 09:56:24	    	at org.testcontainers.utility.ResourceReaper.lambda$start$1(ResourceReaper.java:112)
build	25-Jan-2019 09:56:24	    	at java.base/java.lang.Thread.run(Thread.java:844)

<<< above exception repeated multiple times >>>

build	25-Jan-2019 09:56:25	    [INFO] [org.testcontainers.DockerClientFactory] Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
build	25-Jan-2019 09:56:25	            ?? Checking the system...
build	25-Jan-2019 09:56:25	            ? Docker version should be at least 1.6.0
build	25-Jan-2019 09:56:25	            ? Docker environment should have more than 2GB free disk space
build	25-Jan-2019 09:56:25	    [INFO] [docker[alpine/socat:latest]] Creating container for image: alpine/socat:latest
build	25-Jan-2019 09:56:25	    [INFO] [docker[alpine/socat:latest]] Starting container with ID: f03ebcffa9a037ca36c0bd372667affd460aeed7e620a26ec6843b69c0238c54
build	25-Jan-2019 09:56:25	    [INFO] [docker[alpine/socat:latest]] Container alpine/socat:latest is starting: f03ebcffa9a037ca36c0bd372667affd460aeed7e620a26ec6843b69c0238c54
build	25-Jan-2019 09:56:25	    [INFO] [docker[alpine/socat:latest]] Container alpine/socat:latest started
build	25-Jan-2019 09:56:26	    [INFO] [docker[couchbase/server:5.1.3]] Creating container for image: couchbase/server:5.1.3
build	25-Jan-2019 09:56:27	    [INFO] [docker[couchbase/server:5.1.3]] Starting container with ID: fc4456a5fd76bbfe809567cdea3534ec90b79d51ecd6faf3f7e4bdba9dcd3ada
build	25-Jan-2019 09:56:28	    [INFO] [docker[couchbase/server:5.1.3]] Container couchbase/server:5.1.3 is starting: fc4456a5fd76bbfe809567cdea3534ec90b79d51ecd6faf3f7e4bdba9dcd3ada
build	25-Jan-2019 09:56:28	    [INFO] [org.testcontainers.containers.wait.strategy.HttpWaitStrategy] /festive_yonath: Waiting for 120 seconds for URL: http://172.17.0.1:32838/ui/index.html
build	25-Jan-2019 09:58:28	    [ERROR] [docker[couchbase/server:5.1.3]] Could not start container
build	25-Jan-2019 09:58:28	    org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://172.17.0.1:32838/ui/index.html should return HTTP 200)
build	25-Jan-2019 09:58:28	    	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:197)
build	25-Jan-2019 09:58:28	    	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
build	25-Jan-2019 09:58:28	    	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:591)
build	25-Jan-2019 09:58:28	    	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:263)
build	25-Jan-2019 09:58:28	    	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:216)
build	25-Jan-2019 09:58:28	    	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
build	25-Jan-2019 09:58:28	    	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:214)
build	25-Jan-2019 09:58:28	    	at org.testcontainers.couchbase.CouchbaseContainer.doStart(CouchbaseContainer.java:140)
build	25-Jan-2019 09:58:28	    	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:203)

build	25-Jan-2019 09:58:28	    [ERROR] [docker[couchbase/server:5.1.3]] Container log output (if any) will follow:
build	25-Jan-2019 09:58:28	    [INFO] [docker[couchbase/server:5.1.3]] STDOUT: Starting Couchbase Server -- Web UI available at http://<ip>:8091
build	25-Jan-2019 09:58:28	    [INFO] [docker[couchbase/server:5.1.3]] STDOUT: and logs available in /opt/couchbase/var/lib/couchbase/logs
```

The container is started with the following code:

```
final CouchbaseContainer container = //
        new CouchbaseContainer("couchbase/server:5.1.3") //
                .withNewBucket(bucketSettings)
                .withStartupTimeout(Duration.ofSeconds(120))
                .withLogConsumer(dataFrame -> {
                    LOG.info("Container: " + dataFrame.getUtf8String());
                });
                
container.start();   
```

As you can see that right after the start-up times out, there are cointaner logs that Couchbase started on port 8091, but for some reason TestContainers didn't notice that.
The main issue is that this is happening randomly - often the container starts-up properly, usually after a couple of seconds (in my code I increased the startup timeout but it didn't help).
Is there any way to debug it more? The container logs unfortunately do not say much.

**Comment by rnorth** [comment]
@tchlyah do you think you could have a look into this, as I'm afraid my Couchbase knowledge is limited.

**Comment by tchlyah** [comment]
I launched the tests several times, and it seems ok. Did you give enough CPU and memory to Docker ? Maybe your configuration isn't enough for starting Couchbase.
I invite you to read the [minimal hardware requirements](https://docs.couchbase.com/server/5.1/install/pre-install.html)
