### ISSUE TITLE
Docker compose: Container name with '-' in it fails

### ISSUE THREAD

**Issue by monowai** [testcontainers/testcontainers-java#124]
Affects 1.0.3 & 1.0.4
Looping stack trace appears. The log reports the problem as being in the `search` container while it's actually in the previous container - `engine`. This makes the trace uninformative and misleading for DockerCompose configuration parsing issues using TC.

```
org.testcontainers.shaded.com.github.dockerjava.api.InternalServerErrorException: Could not get container for 8ml4tj_fdsearch_1

        at org.testcontainers.shaded.com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
        at org.testcontainers.shaded.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
        at org.testcontainers.shaded.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
        at org.testcontainers.shaded.org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
        at org.testcontainers.shaded.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
        at org.testcontainers.shaded.org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
        at org.testcontainers.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.testcontainers.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.testcontainers.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.testcontainers.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
```

**Comment by monowai** [comment]
Am nearing the end of this super journey.  I have the integration stack testing flawlessly and repeatedly on my local machine - blessed be the correct configuration settings. When I run the exact same build via the bamboo cloud agent on AWS (ubuntu), maven fails with the same repeating error condition as above. I can happily standup the stack from the artefacts created, but TC is erroring over something. Hoping I don't have to setup remote debug access to that box!

**Comment by rnorth** [comment]
Argh, sorry about this. I think there's a need for some better diagnostics output for compose containers. If you're using jitpack to run with the master-SNAPSHOT version, you should at least be getting the log output from the `docker-compose up -d` command. Does that yield any extra info?

**Comment by bsideup** [comment]
Closing due to inactivity.
