### ISSUE TITLE
upgrade docker-compose image to 1.6.0 or newer

### ISSUE THREAD

**Issue by rivasdiaz** [testcontainers/testcontainers-java#127]
DockerComposeContainer requires dduportal/docker-compose:1.3.1, which doesn't support the new docker-compose YAML format. Users don't see a clear error, just nothing works. It took me some time to figure out what was the problem, specially because I'm new to compose too.

Please consider upgrading DockerComposeContainer to require dduportal/docker-compose:1.6.0 or later.

**Comment by rnorth** [comment]
@rivasdiaz, you're right, it would be worth upgrading to the latest version. Thanks for this.

I'm slightly concerned that you weren't getting any log output to help you diagnose this; I think I can imagine where the gap might be. Please can you confirm that you're running v1.0.3, and I'll try and reproduce.

**Comment by kuzemchik** [comment]
Have same issue.

Here is compose file that will fail.
```
version: '2'

services:
  cassandra:
    container_name: 'consumer-cassandra'
    image: 'cassandra:3.3'
```

The output looks like this:
```
16/04/15 16:58:18 INFO 🐳 [richnorth/ambassador:latest]: Creating container for image: richnorth/ambassador:latest
16/04/15 16:58:18 ERROR 🐳 [richnorth/ambassador:latest]: Could not start container
org.testcontainers.shaded.com.github.dockerjava.api.InternalServerErrorException: Could not get container for cufghy_cassandra_1

	at org.testcontainers.shaded.com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
	at org.testcontainers.shaded.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:134)
	at org.testcontainers.shaded.org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:123)
	at org.testcontainers.shaded.org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)
	at org.testcontainers.shaded.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:251)
	at org.testcontainers.shaded.org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
	at org.testcontainers.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.testcontainers.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.testcontainers.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.testcontainers.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.testcontainers.shaded.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
	at org.testcontainers.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435)
	at org.testcontainers.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338)
	at org.testcontainers.shaded.com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:32)
	at org.testcontainers.shaded.com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:14)
	at org.testcontainers.shaded.com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:23)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:142)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:144)
	at org.testcontainers.containers.GenericContainer.lambda$start$0(GenericContainer.java:122)
	at org.testcontainers.containers.GenericContainer$$Lambda$13/2006835220.call(Unknown Source)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:119)
	at org.testcontainers.containers.DockerComposeContainer.lambda$start$0(DockerComposeContainer.java:80)
	at org.testcontainers.containers.DockerComposeContainer$$Lambda$29/1831705084.call(Unknown Source)
	at org.rnorth.ducttape.unreliables.Unreliables.lambda$retryUntilSuccess$2(Unreliables.java:41)
	at org.rnorth.ducttape.unreliables.Unreliables$$Lambda$9/1667534569.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Only after looking at created (but not deleted) compose container I saw:
```
Unsupported config option for services service: 'cassandra'
```
