### ISSUE TITLE
Disable STDOUT or redirect due to Maven Surefire error

### ISSUE THREAD

**Issue by sporkisfaster** [testcontainers/testcontainers-java#1304]
When running test containers with Maven Surefire I get the following error: https://maven.apache.org/surefire/maven-failsafe-plugin/faq.html#corruptedstream looking in the logs it seems Testcontainers and Surefire are trying to write to stdout at the same time. How can I disable this in Testcontainers?

**Comment by kiview** [comment]
Hey @sporkisfaster,
Are you by any chance missing a logging implementation in your tests, e.g. logback?

**Comment by sporkisfaster** [comment]
Looks like that's the case! Thanks for the heads up. Might be noteworthy in the documentation under a "quirks" type of section when using multiple testing suites (in the case here it was JUnit Vintage, 5, and Spock) and I believe unless you forcefully turn off these logs, it will continuously cause this error.

**Comment by sporkisfaster** [comment]
New issue, my .testcontainers.properties file on Mac OS Mojave is being ignored and is causing the same stdout issue as before. This is currently what I have: `#Modified by Testcontainers
#Wed Mar 06 15:57:42 CST 2019
docker.client.strategy=org.testcontainers.dockerclient.UnixSocketClientProviderStrategy
checks.disable=true`

But I still get the following output:

`[INFO] Running com.package.TestDelete
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0`

Which under the multi-testing configuration causes the following:

`Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream '        [32m✔ Docker version should be at least 1.6.0[0m'.
java.lang.IllegalArgumentException: Stream stdin corrupted. Expected comma after third character in command '        [32m✔ Docker version should be at least 1.6.0[0m'.
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient$OperationalData.<init>(ForkClient.java:507)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.processLine(ForkClient.java:210)
	at org.apache.maven.plugin.surefire.booterclient.output.ForkClient.consumeLine(ForkClient.java:177)
	at org.apache.maven.plugin.surefire.booterclient.output.ThreadedStreamConsumer$Pumper.run(ThreadedStreamConsumer.java:88)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by kiview** [comment]
For further reference, this is what Maven Failsafe says about this in their FAQ:
https://maven.apache.org/surefire/maven-failsafe-plugin/faq.html#corruptedstream

And some discussion in the Surefire JIRA:
https://issues.apache.org/jira/browse/SUREFIRE-1359?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&focusedCommentId=15996112#comment-15996112

The actual check happens here:
https://github.com/testcontainers/testcontainers-java/blob/ca4505acef4415a7dbe8cd21cf02287acfee0c1b/core/src/main/java/org/testcontainers/DockerClientFactory.java#L129-L132

Since we are using https://github.com/rnorth/visible-assertions library for this log, this problem might be simply the use of `System.out`, though I'm not entirely sure.
However, after following the JIRA discussion, it seems that this error should be more a DEBUG level log?

Which version of Testcontainers are you using? The flag behavior regarding disable of Docker version check has been fixed in a recent version.

**Comment by sporkisfaster** [comment]
I'll give it a shot, I'll have to sanitize some things from my workplace code but I'll throw something up. I'm on 1.10.6 but can update and try again.

**Comment by sporkisfaster** [comment]
Aha. Updating to the new version fixes the docker check so thats good! That serves as a workaround for now. I'll also get that project for you to demonstrate the system out issue. Thanks for your help!

**Comment by kiview** [comment]
Alright, that's good to know, I knew we should have fixed that by now :sweat_smile: 
Thanks for providing an example.

**Comment by saikiranchalla1** [comment]
@sporkisfaster What did you do to fix the logging issue? Thank you!
