### ISSUE TITLE
Huge MountableFiles result in OutOfMemoryError

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#1348]
This is a bug we've encountered when using `ImageFromDockerFile` and `withFileFromPath` to make the entire working directory available to the docker build. We want to _try_ and avoid the need to specifically pick every file that needs to be available to the docker build process. Using `"."` for the paths seems to work quite well.

However, when there are huge files under the working directory this approach falls apart. These huge files are listed in `.dockerignore`.

We probably need to look at docker-java's support for `.dockerignore`; I'm not sure whether it automatically filters the tar stream or whether we need to do something differently to benefit from it.

```
Java heap space
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:3236)
    at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
    at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
    at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
    at org.apache.commons.compress.utils.CountingOutputStream.write(CountingOutputStream.java:48)
    at org.apache.commons.compress.utils.FixedLengthBlockOutputStream$BufferAtATimeOutputChannel.write(FixedLengthBlockOutputStream.java:244)
    at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.writeBlock(FixedLengthBlockOutputStream.java:92)
    at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.maybeFlush(FixedLengthBlockOutputStream.java:86)
    at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.write(FixedLengthBlockOutputStream.java:122)
    at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.write(TarArchiveOutputStream.java:454)
    at java.nio.file.Files.copy(Files.java:2909)
    at java.nio.file.Files.copy(Files.java:3069)
    at org.testcontainers.utility.MountableFile.recursiveTar(MountableFile.java:318)
    at org.testcontainers.utility.MountableFile.recursiveTar(MountableFile.java:327)
    at org.testcontainers.utility.MountableFile.recursiveTar(MountableFile.java:327)
    at org.testcontainers.utility.MountableFile.recursiveTar(MountableFile.java:327)
    at org.testcontainers.utility.MountableFile.transferTo(MountableFile.java:292)
    at org.testcontainers.containers.GenericContainer.copyFileToContainer(GenericContainer.java:1072)
    at org.testcontainers.containers.GenericContainer.copyFileToContainer(GenericContainer.java:1052)
    at org.testcontainers.containers.GenericContainer$$Lambda$67/1727045694.accept(Unknown Source)
    at java.util.HashMap.forEach(HashMap.java:1289)
    at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:238)
    at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:216)
    at org.testcontainers.containers.GenericContainer$$Lambda$51/494859408.call(Unknown Source)
    at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
    at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:214)
    at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:203)
    at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:723)
    at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
```

**Comment by jandry** [comment]
I proposed a working workaround here https://github.com/testcontainers/testcontainers-java/issues/7239#issuecomment-1746603941

**Comment by jandry** [comment]
Seems same as https://github.com/testcontainers/testcontainers-java/issues/7239

**Comment by gba-foundever** [comment]
A fix proposal has been pushed here https://github.com/testcontainers/testcontainers-java/issues/7239
it's working for me

**Comment by eddumelendez** [comment]
#8409 has been merged and it should fix the issue.
