### ISSUE TITLE
iptables v1.8.2 (legacy): unknown option --dport

### ISSUE THREAD

**Issue by nickaleks** [testcontainers/testcontainers-java#1513]
When starting a container I get the following exception (I've removed spring-related part of the stack trace since it's useless):
```
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy96.exec(Unknown Source)
	at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:86)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:125)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:138)
	at org.testcontainers.containers.JdbcDatabaseContainer.<init>(JdbcDatabaseContainer.java:45)
	at org.testcontainers.containers.PostgreSQLContainer.<init>(PostgreSQLContainer.java:32)
	at com.kazanexpress.account.component.ComponentTestFixture$Companion$KPostgreSQLContainer.<init>(ComponentTestFixture.kt:41)
	at com.kazanexpress.account.component.ComponentTestFixture$Companion.definePostgreSQLContainer(ComponentTestFixture.kt:45)
	at com.kazanexpress.account.component.ComponentTestFixture$Companion.access$definePostgreSQLContainer(ComponentTestFixture.kt:38)
	at com.kazanexpress.account.component.ComponentTestFixture$Companion$container$2.invoke(ComponentTestFixture.kt:43)
	at com.kazanexpress.account.component.ComponentTestFixture$Companion$container$2.invoke(ComponentTestFixture.kt:38)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.kazanexpress.account.component.ComponentTestFixture$Companion.getContainer(ComponentTestFixture.kt)
	at com.kazanexpress.account.component.ComponentTestFixture$Companion.access$getContainer$p(ComponentTestFixture.kt:38)
	at com.kazanexpress.account.component.ComponentTestFixture$Initializer.initialize(ComponentTestFixture.kt:58)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:649)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:127)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	... 33 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testcontainers.dockerclient.AuditLoggingDockerClient.lambda$wrappedCommand$14(AuditLoggingDockerClient.java:98)
	... 54 more
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"driver failed programming external connectivity on endpoint testcontainers-ryuk-8ac1d4b6-fc92-4527-966a-c165104becd4 (1148dbdf6a4ee1b7eaf22d5c467146bd8bc186bfb1eae35b2728dd5814a1201d):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 32837 -j DNAT --to-destination 172.17.0.2:8080 ! -i docker0: iptables v1.8.2 (legacy): unknown option \"--dport\"\nTry `iptables -h' or 'iptables --help' for more information.\n (exit status 2))"}

	at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:276)
	at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:254)
	at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:115)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:28)
	at com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:11)
	at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:46)
	... 59 more
```

This happened after one of the system upgrades. Before that everything worked as expected.
iptables v1.8.2
`uname -r`: 5.1.1-2-MANJARO
`docker -v`: Docker version 18.09.6-ce, build 481bc77156

Testcontainers library:
```
<dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>postgresql</artifactId>
            <version>1.11.3</version>
            <scope>test</scope>
</dependency>
```

**Comment by rnorth** [comment]
Hi @nickaleks - this looks very much like a Docker incompatibility with your updated version of iptables. It seems there's already an issue open against Docker for this: https://github.com/moby/moby/issues/38759

I'll close this ticket, but please reopen if you find something that indicates this is a Testcontainers-specific issue!

**Comment by nickaleks** [comment]
I see, thanks for the swift answer
