### ISSUE TITLE
Container Startup Failure due to UnrecognizedPropertyException in docker config file

### ISSUE THREAD

**Issue by pedro93** [testcontainers/testcontainers-java#1548]
Hello,

I tried to run the [Dockerfile DSL example](https://www.testcontainers.org/features/creating_images/) but it failed on my machine. I have a docker configuration for a private registry which I think may be cause of the problem, see below for more information.

Thank you for taking the time.

Tried to run the following code:
```java
@ClassRule
    public static GenericContainer container = new GenericContainer(
            new ImageFromDockerfile()
                    .withDockerfileFromBuilder(builder ->
                                                       builder
                                                               .from("alpine:3.2")
                                                               .run("apk add --update nginx")
                                                               .cmd("nginx", "-g", "daemon off;")
                                                               .build()))
            .withExposedPorts(80);
```

What happened: Whilst trying to build the image I got a jackson exception.

Test Container Version: 1.11.3

Stack Trace:
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed

	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:217)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:199)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:714)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: org.testcontainers.images.builder.ImageFromDockerfile@5b43fbf6
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:964)
	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:335)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:206)
	... 10 more
Caused by: com.github.dockerjava.api.exception.DockerClientException: Failed to parse docker configuration file
	at com.github.dockerjava.core.DefaultDockerClientConfig.getDockerConfig(DefaultDockerClientConfig.java:243)
	at com.github.dockerjava.core.DefaultDockerClientConfig.getAuthConfigurations(DefaultDockerClientConfig.java:280)
	at org.testcontainers.dockerclient.auth.AuthDelegatingDockerClientConfig.getAuthConfigurations(AuthDelegatingDockerClientConfig.java:21)
	at com.github.dockerjava.core.exec.AbstrDockerCmdExec.getBuildAuthConfigs(AbstrDockerCmdExec.java:37)
	at com.github.dockerjava.core.exec.BuildImageCmdExec.resourceWithOptionalAuthConfig(BuildImageCmdExec.java:27)
	at com.github.dockerjava.core.exec.BuildImageCmdExec.execute0(BuildImageCmdExec.java:111)
	at com.github.dockerjava.core.exec.BuildImageCmdExec.execute0(BuildImageCmdExec.java:18)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec.execute(AbstrAsyncDockerCmdExec.java:56)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec.exec(AbstrAsyncDockerCmdExec.java:21)
	at com.github.dockerjava.core.exec.AbstrAsyncDockerCmdExec.exec(AbstrAsyncDockerCmdExec.java:12)
	at com.github.dockerjava.core.command.AbstrAsyncDockerCmd.exec(AbstrAsyncDockerCmd.java:21)
	at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:118)
	at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:29)
	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:27)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:962)
	... 12 more
Caused by: java.io.IOException: Failed to parse docker config.json
	at com.github.dockerjava.core.DockerConfigFile.loadCurrentConfig(DockerConfigFile.java:149)
	at com.github.dockerjava.core.DockerConfigFile.loadConfig(DockerConfigFile.java:117)
	at com.github.dockerjava.core.DefaultDockerClientConfig.getDockerConfig(DefaultDockerClientConfig.java:241)
	... 27 more
Caused by: org.testcontainers.shaded.com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "identitytoken" (class com.github.dockerjava.api.model.AuthConfig), not marked as ignorable (6 known properties: "serveraddress", "username", "auth", "password", "email", "registrytoken"])
 at [Source: /home/pedro.cardoso/.docker/config.json; line: 5, column: 22] (through reference chain: com.github.dockerjava.core.DockerConfigFile["auths"]->java.util.LinkedHashMap["docker.feedzai.com"]->com.github.dockerjava.api.model.AuthConfig["identitytoken"])
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:839)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1045)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1352)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1330)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:264)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:495)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:341)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:258)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2620)
	at com.github.dockerjava.core.DockerConfigFile.loadCurrentConfig(DockerConfigFile.java:147)
	... 29 more
```

Docker Config:
```
{
    "auths": {
        "private.docker.registry.com": {
            "auth": "...",
            "identitytoken": "..."
        },
        "https://index.docker.io/v1/": {
            "auth": "..."
        }
    },  
    "HttpHeaders": {
        "User-Agent": "Docker-Client/18.06.0-ce (linux)"
    }   
}
```

**Comment by pedro93** [comment]
It seems that this is a problem with the docker-java dependency: https://github.com/docker-java/docker-java/issues/921. Looks like to have been fixed in a following release candidate patch (3.1.0-rc-5).

**Comment by pedro93** [comment]
FYI Can confirm this is fixed, thank you @bsideup !

**Comment by bsideup** [comment]
@pedro93 thank a lot for checking! 👍
