### ISSUE TITLE
Attempting to run in teamcity

### ISSUE THREAD

**Issue by sean-abbott** [testcontainers/testcontainers-java#1609]
It was working with an initial setup, but we moved to mounting /var/lib/docker, and now we get

```
[19:13:38]
[Step 1/4] 2019-07-12 19:13:38.394  INFO   --- [           main] o.t.d.DockerClientProviderStrategy       : Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy from ~/.testcontainers.properties, will try it first
[19:13:38]
[Step 1/4] 2019-07-12 19:13:38.442  INFO   --- [           main] o.t.d.DockerClientProviderStrategy       : Will use 'okhttp' transport
[19:13:39]
[Step 1/4] 2019-07-12 19:13:39.236  INFO   --- [           main] tAndSystemPropertyClientProviderStrategy : Found docker client settings from environment
[19:13:39]
[Step 1/4] 2019-07-12 19:13:39.273  INFO   --- [           main] o.t.d.DockerClientProviderStrategy       : Found Docker environment with Environment variables, system properties and defaults. Resolved: 
[19:13:39]
[Step 1/4]     dockerHost=unix:///var/run/docker.sock
[19:13:39]
[Step 1/4]     apiVersion='{UNKNOWN_VERSION}'
[19:13:39]
[Step 1/4]     registryUrl='https://index.docker.io/v1/'
[19:13:39]
[Step 1/4]     registryUsername='root'
[19:13:39]
[Step 1/4]     registryPassword='null'
[19:13:39]
[Step 1/4]     registryEmail='null'
[19:13:39]
[Step 1/4]     dockerConfig='DefaultDockerClientConfig[dockerHost=unix:///var/run/docker.sock,registryUsername=root,registryPassword=<null>,registryEmail=<null>,registryUrl=https://index.docker.io/v1/,dockerConfigPath=/root/.docker,sslConfig=<null>,apiVersion={UNKNOWN_VERSION},dockerConfig=<null>]'
[19:13:39]
[Step 1/4] 
[19:13:39]
[Step 1/4] 2019-07-12 19:13:39.489  WARN   --- [           main] o.t.utility.RegistryAuthLocator          : Failure when attempting to lookup auth config (dockerImageName: alpine:3.5, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory)
[19:13:40]
[Step 1/4] 2019-07-12 19:13:40.334 ERROR   --- [ream-1343796587] c.g.d.core.async.ResultCallbackTemplate  : Error during callback
[19:13:40]
[Step 1/4] 
[19:13:40]
[Step 1/4] com.github.dockerjava.api.exception.DockerException: {"message":"configured logging driver does not support reading"}
[19:13:40]
[Step 1/4] 
[19:13:40]
[Step 1/4] 	at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:278)
[19:13:40]
[Step 1/4] 	at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.lambda$executeAndStream$1(OkHttpInvocationBuilder.java:292)
[19:13:40]
[Step 1/4] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bsideup** [comment]
Hi @sean-abbott,

Could you please explain the difference between "initial setup" and "we moved to mounting /var/lib/docker"?

Also, mounting "/var/lib/docker" is a dangerous idea because it cannot be properly shared between multiple Docker daemons

**Comment by sean-abbott** [comment]
Hi, so this is on me. I found out my co-worker had changed the docker daemon to use the awslogs driver, which is unreadable.
