### ISSUE TITLE
Cassandra module fails without data center configuration using newer datastax driver

### ISSUE THREAD

**Issue by FSeidinger** [testcontainers/testcontainers-java#1630]
Hi there,

I had some trouble running a very simple test with the cassandra module. I use the following environment:

# Docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

# Maven dependencies:
org.testcontainers:cassandra:1.11.4
org.testcontainers:testcontainers:1.11.4

com.datastax.cassandra:cassandra-driver-core:4.0.0

# Test code
I have a simple JUnit5 testcase with the following code:

```Java
class CassandraDbMigratorIT {
    private CassandraContainer container;
    private CqlSession session;

    @BeforeEach
    private void setup() {
        this.container = new CassandraContainer();
        this.container.start();

        final String containerIpAddress = container.getContainerIpAddress();
        final int containerPort = container.getMappedPort(9042);
        final InetSocketAddress containerEndPoint = new InetSocketAddress(containerIpAddress, containerPort);

        this.session = CqlSession.builder()
                .addContactPoint(containerEndPoint)
                .withLocalDatacenter("local")
                .build();

        createKeySpace();
    }

    @AfterEach
    private void teardown() {
        this.session.close();
        this.container.stop();
    }

    @Test
    void doesntWork() {
        Assertions.assertNotNull(session);
    }

    private void createKeySpace() {
        if (!session.getKeyspace().isPresent()) {
            final String createKeyspaceQuery = "CREATE KEYSPACE event_store WITH REPLICATION = { 'class':'SimpleStrategy', 'replication_factor' : 3 }";
            session.execute(createKeyspaceQuery);

            final String useKeyspaceQuery = "USE event_store";
            session.execute(useKeyspaceQuery);
        }
    }
}
```

# Expected behavior
Test executes with no errors

# Actual behvior
The test fails wit the following stack trace

```
com.datastax.oss.driver.api.core.DriverExecutionException
	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:115)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:336)
	at de.rheinfeld.infrastructure.eventstore.cassandra.CassandraDbMigratorIT.setup(CassandraDbMigratorIT.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeMethodInExtensionContext(ClassTestDescriptor.java:439)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$15(ClassTestDescriptor.java:427)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachMethods$3(TestMethodTestDescriptor.java:149)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:169)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachMethods(TestMethodTestDescriptor.java:148)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:123)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	Suppressed: java.lang.NullPointerException
		at de.rheinfeld.infrastructure.eventstore.cassandra.CassandraDbMigratorIT.teardown(CassandraDbMigratorIT.java:34)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
		at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
		at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeMethodInExtensionContext(ClassTestDescriptor.java:439)
		at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$synthesizeAfterEachMethodAdapter$16(ClassTestDescriptor.java:431)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachMethods$10(TestMethodTestDescriptor.java:227)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:245)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:243)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachMethods(TestMethodTestDescriptor.java:226)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
		... 41 more
Caused by: java.lang.IllegalStateException: You provided explicit contact points, the local DC must be specified (see basic.load-balancing-policy.local-datacenter in the config)
	at com.datastax.oss.driver.internal.core.loadbalancing.DefaultLoadBalancingPolicy.init(DefaultLoadBalancingPolicy.java:138)
	at com.datastax.oss.driver.internal.core.metadata.LoadBalancingPolicyWrapper.init(LoadBalancingPolicyWrapper.java:121)
	at com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.afterInitialSchemaRefresh(DefaultSession.java:386)
	at com.datastax.oss.driver.internal.core.session.DefaultSession$SingleThreaded.lambda$afterInitialNodeListRefresh$4(DefaultSession.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at com.datastax.oss.driver.internal.core.metadata.MetadataManager$SingleThreaded.lambda$startSchemaRequest$2(MetadataManager.java:413)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The root cause `You provided explicit contact points, the local DC must be specified (see basic.load-balancing-policy.local-datacenter in the config)` gives the hint, why this simple test fails.

# Cause explained
Due to changes in the datastax driver a data center must be configured, if the contact point is changed from the default `17.0.0.1:9042`. This includes changing the port to something other than `9042`.

The nature of testcontainers is to test in isolation. For this reason testcontainers maps exposed ports like `9042` to a free port on the local machine (e.g. `32794`). Hence the changed port.

# Solutions
The container must be configured with a data center and the corresponding endpoint snitch as outlined in the docker hub cassandra image documentation and the datastax documentation. Additionally the data center must be set on the session properties. With the following modifications using the data center `local` my test code runs as expected:

```Java
    private void setup() throws InterruptedException {
        this.container = new CassandraContainer();
        this.container.addEnv("CASSANDRA_DC", "local");
        this.container.addEnv("CASSANDRA_ENDPOINT_SNITCH", "GossipingPropertyFileSnitch");
        this.container.start();

        final String containerIpAddress = container.getContainerIpAddress();
        final int containerPort = container.getMappedPort(9042);
        final InetSocketAddress containerEndPoint = new InetSocketAddress(containerIpAddress, containerPort);

        this.session = CqlSession.builder()
                .addContactPoint(containerEndPoint)
                .withLocalDatacenter("local")
                .build();

        createKeySpace();
    }
```

## Solution A
Just add an example in the description of the cassandra module. This is not breaking the current module and helps people with first steps.

## Solution B
Add a method on the `CassandraContainer` class to add the configuration for the data center. As a pro it doesn't break the current module and gives the user the decision.

## Solution C
Add this new configuration to the default constructor. This might be a breaking change but could help new users to avoid pitfalls.

Kind regards,

Frank

**Comment by FSeidinger** [comment]
I investigated further and came to the conclusion that my described error is also due to the fact, that the driver version starting with version 4 had some significant changes.

More details can be found here:

https://docs.datastax.com/en/developer/java-driver/4.0/upgrade_guide/

Mainly that the `Cluster` class doesn't exist anymore and is substituted by the `CqlSession` coming with a changed protocol negotiation.

So maybe there's a need here to support different versions of the datastax drivers for the cassandar module.

**Comment by raphaelbrugier** [comment]
I faced the same issue and resolved it without having to pass environment variables to the container.
The only difference in my code is to set the `localDataCenter` option to the default name of a DC: `datacenter1`

The following code creates a Session successfully:

```
            GenericContainer CASSANDRA_CONTAINER =
                new GenericContainer("cassandra:3.11.5")
                    .waitingFor(Wait.forListeningPort().withStartupTimeout(Duration.ofSeconds(30)))
                    .withExposedPorts(9042);

            CASSANDRA_CONTAINER.start();

            InetSocketAddress cassandraContainerAddress = new InetSocketAddress("127.0.0.1", CASSANDRA_CONTAINER.getMappedPort(9042));
            Session session = CqlSession.builder()
                .addContactPoint(cassandraContainerAddress)
                .withLocalDatacenter("datacenter1")
                .build();
```
