### ISSUE TITLE
How to specify port for container to be exposed on

### ISSUE THREAD

**Issue by Asisranjan** [testcontainers/testcontainers-java#1659]
Is there a way to run test container running in different port than 8080

**Comment by bsideup** [comment]
Testcontainers does not run anything on port 8080. It uses random ports for every container it starts

**Comment by Asisranjan** [comment]
Thanks. I misunderstood. As part testcontainer, ryuk docker container was running on port 8080. Is there a way to run/control ryuk to run on different port. I am able to disable it by setting TESTCONTAINERS_RYUK_DISABLED environment variable to true.
https://www.testcontainers.org/features/configuration/

**Comment by bsideup** [comment]
the process inside Ryuk listens on port 8080, but the exposed port is random and does not conflict with the ports on your host

**Comment by Asisranjan** [comment]
I am getting this exception.
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:217)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:199)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:714)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:83)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:210)
	... 42 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:277)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:212)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
	... 43 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080] should be listening)
	at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:47)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.wait.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:23)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:582)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:259)
	... 45 more

**Comment by bsideup** [comment]
but that's not Ryuk but your container

**Comment by Asisranjan** [comment]
Yes, but why it is timed out.
Timed out waiting for container port to open (localhost ports: [8080] should be listening)

when i used to run same docker image using docker run, there is no issue. when using genericcontainer, i am getting above exception. 
public GenericContainer app = new GenericContainer(
            "app:latest")
            .withExposedPorts(8080)
            .withCreateContainerCmdModifier(cmd1);

Consumer<CreateContainerCmd> cmd1 = e -> {
        e.withPortBindings(new PortBinding(Ports.Binding.bindPort(8080),
                new ExposedPort(8080)));
        e.withHostName("app-host");
        e.withName("app-container-name");
    };

**Comment by rnorth** [comment]
I don't think this is anything to do with Ryuk.

This bit:
```
e.withPortBindings(new PortBinding(Ports.Binding.bindPort(8080),
new ExposedPort(8080)));
```
should really be avoided - are you trying to make it run with a fixed port?

The recommended way is to not do this; instead have

```
...
.withExposedPorts(8080)
...
```

on your container definition, *remove* use of `withPortBindings`, and then:

```
int actualPort = app.getMappedPort(8080)
```

to find out which random port the container is available on. You'd then use `actualPort` when creating a connection to the container.

This is documented further [here](https://www.testcontainers.org/features/networking/#exposing-container-ports-to-the-host).

**Comment by voipp** [comment]
what is ryak? I cannot find information about it

**Comment by KyleAure** [comment]
@voipp  Ryuk is a container that starts alongside the testcontainers you specify in your test suite.  It is able to take down itself and any testcontainers running if your test was to crash and was not able to take it down normally.  Project and documentation: https://github.com/testcontainers/moby-ryuk

**Comment by makushatnik** [comment]
I have the same issue.
The message about timeout in 3 minutes (should I change it somewhere?),
and I have a problem with 8080 and random port on the other side. How can I use a pair of fixed ports?
