### ISSUE TITLE
"Could not start container" even though it did start

### ISSUE THREAD

**Issue by hectorj** [testcontainers/testcontainers-java#1669]
Hi!

I started using `testcontainers` recently, and I love it.

But sometimes (it seems random, but I can't say for sure), I get a little problem: It says `Could not start container` even though the logs show that the container did start, and is `ready for connections`.

<details><summary>Logs</summary>

```

2019-07-26 15:57:51.665 ERROR 30218 --- [           main] 🐳 [mariadb:10.4.6]                      : Could not start container

org.rnorth.ducttape.TimeoutException: org.rnorth.ducttape.TimeoutException: java.util.concurrent.TimeoutException
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:53)
        at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:129)
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:259)
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:212)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:210)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:199)
        at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:117)
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:365)
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:194)
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:460)
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:534)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:180)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:94)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:237)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
        at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:152)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:286)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:243)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:214)
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:179)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:119)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:904)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:935)
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:57)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:390)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:377)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
        at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:127)
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
        at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
        at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
        at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
        at org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener.prepareTestInstance(SpringBootDependencyInjectionTestExecutionListener.java:44)
        at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:246)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: org.rnorth.ducttape.TimeoutException: java.util.concurrent.TimeoutException
        at org.rnorth.ducttape.timeouts.Timeouts.callFuture(Timeouts.java:70)
        at org.rnorth.ducttape.timeouts.Timeouts.getWithTimeout(Timeouts.java:43)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:38)
        ... 81 common frames omitted
Caused by: java.util.concurrent.TimeoutException: null
        at java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at org.rnorth.ducttape.timeouts.Timeouts.callFuture(Timeouts.java:65)
        ... 83 common frames omitted

2019-07-26 15:57:51.708 ERROR 30218 --- [           main] 🐳 [mariadb:10.4.6]                      : Log output from the failed container:
Initializing database

2019-07-26 13:55:52 0 [Warning] option 'table_open_cache': unsigned value 4 adjusted to 10





PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !

To do so, start the server, then issue the following commands:



'/usr/bin/mysqladmin' -u root password 'new-password'

'/usr/bin/mysqladmin' -u root -h  password 'new-password'



Alternatively you can run:

'/usr/bin/mysql_secure_installation'



which will also give you the option of removing the test

databases and anonymous user created by default.  This is

strongly recommended for production servers.



See the MariaDB Knowledgebase at http://mariadb.com/kb or the

MySQL manual for more instructions.



Please report any problems at http://mariadb.org/jira



The latest information about MariaDB is available at http://mariadb.org/.

You can find additional information about the MySQL part at:

http://dev.mysql.com

Consider joining MariaDB's strong and vibrant community:

https://mariadb.org/get-involved/



Database initialized

MySQL init process in progress...

2019-07-26 13:56:04 0 [Warning] option 'table_open_cache': unsigned value 4 adjusted to 10

2019-07-26 13:56:04 0 [Note] mysqld (mysqld 10.4.6-MariaDB-1:10.4.6+maria~bionic) starting as process 108 ...

2019-07-26 13:56:04 0 [Note] InnoDB: Using Linux native AIO

2019-07-26 13:56:04 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins

2019-07-26 13:56:04 0 [Note] InnoDB: Uses event mutexes

2019-07-26 13:56:04 0 [Note] InnoDB: Compressed tables use zlib 1.2.11

2019-07-26 13:56:04 0 [Note] InnoDB: Number of pools: 1

2019-07-26 13:56:04 0 [Note] InnoDB: Using SSE2 crc32 instructions

2019-07-26 13:56:04 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)

2019-07-26 13:56:04 0 [Note] InnoDB: Initializing buffer pool, total size = 16M, instances = 1, chunk size = 16M

2019-07-26 13:56:04 0 [Note] InnoDB: Completed initialization of buffer pool

2019-07-26 13:56:04 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().

MySQL init process in progress...

2019-07-26 13:56:05 0 [Note] InnoDB: 128 out of 128 rollback segments are active.

2019-07-26 13:56:05 0 [Note] InnoDB: Creating shared tablespace for temporary tables

2019-07-26 13:56:05 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...

2019-07-26 13:56:05 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.

2019-07-26 13:56:05 0 [Note] InnoDB: Waiting for purge to start

2019-07-26 13:56:05 0 [Note] InnoDB: 10.4.6 started; log sequence number 139925; transaction id 21

2019-07-26 13:56:05 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool

2019-07-26 13:56:05 0 [Note] Plugin 'FEEDBACK' is disabled.

2019-07-26 13:56:05 0 [Warning] 'user' entry 'root@e4cbcb48e84f' ignored in --skip-name-resolve mode.

2019-07-26 13:56:05 0 [Warning] 'user' entry '@e4cbcb48e84f' ignored in --skip-name-resolve mode.

2019-07-26 13:56:05 0 [Warning] 'proxies_priv' entry '@% root@e4cbcb48e84f' ignored in --skip-name-resolve mode.

2019-07-26 13:56:05 0 [Note] InnoDB: Buffer pool(s) load completed at 190726 13:56:05

2019-07-26 13:56:06 0 [Note] Reading of all Master_info entries succeeded

2019-07-26 13:56:06 0 [Note] Added new Master_info '' to hash table

2019-07-26 13:56:06 0 [Note] mysqld: ready for connections.

Version: '10.4.6-MariaDB-1:10.4.6+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution

Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.

```

</details>

After this it hangs a bit and retries, creating a new container.

My env : 
- Java 8 ( :crying_cat_face: )
- Spring Boot v2.1.4.RELEASE, Spring v5.1.6.RELEASE
- Testcontainers v1.11.3
- MariaDB driver version 2.4.2
- Docker v19.03.0
- ```yaml

  datasource:
    jdbcUrl: jdbc:tc:mariadb:10.4.6://somehostname:someport/databasename
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

If anyone has a clue on why this happens, I'll be glad :smiley:

**Comment by bsideup** [comment]
hi @hectorj,

Could you please try Testcontainers 1.12.0? We now have a slightly better detection of JDBC failures related to drivers, it may show the problem

**Comment by hectorj** [comment]
Thanks for the quick answer. I didn't saw I was already late 2 releases, you guys move fast!

Just upgraded and I saw the same error once (with more logs), but I can't seem to reproduce it anymore.

Closing for now, I'll reopen if it comes back.

Thanks again.
