### ISSUE TITLE
an not connect to Ryuk

### ISSUE THREAD

**Issue by lburgazzoli** [testcontainers/testcontainers-java#1679]
I'm working on upgrading testcontainers to the latest version (1.12.0) in etcd-io/jetcd and after the upgrade I'm not more able to run tests because of:

```
[main] INFO org.testcontainers.dockerclient.DockerClientProviderStrategy - Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy from ~/.testcontainers.properties, will try it first
[main] INFO org.testcontainers.dockerclient.DockerClientProviderStrategy - Will use 'okhttp' transport
[main] INFO org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy - Found docker client settings from environment
[main] INFO org.testcontainers.dockerclient.DockerClientProviderStrategy - Found Docker environment with Environment variables, system properties and defaults. Resolved: 
    dockerHost=unix:///var/run/docker.sock
    apiVersion='{UNKNOWN_VERSION}'
    registryUrl='https://index.docker.io/v1/'
    registryUsername='lburgazz'
    registryPassword='null'
    registryEmail='null'
    dockerConfig='DefaultDockerClientConfig[dockerHost=unix:///var/run/docker.sock,registryUsername=lburgazz,registryPassword=<null>,registryEmail=<null>,registryUrl=https://index.docker.io/v1/,dockerConfigPath=/home/lburgazz/.docker,sslConfig=<null>,apiVersion={UNKNOWN_VERSION},dockerConfig=<null>]'

[main] INFO org.testcontainers.DockerClientFactory - Docker host IP address is localhost
[main] INFO org.testcontainers.DockerClientFactory - Connected to docker: 
  Server Version: 1.13.1
  API Version: 1.26
  Operating System: Fedora 30 (Thirty)
  Total Memory: 11705 MB
[testcontainers-ryuk] WARN org.testcontainers.utility.ResourceReaper - Can not connect to Ryuk at localhost:32773
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at org.testcontainers.utility.ResourceReaper.lambda$start$1(ResourceReaper.java:113)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bsideup** [comment]
I think @jonathanvila had the same issue, but not related to the upgrade.

Is it consistent and breaks only with 1.12.0, but works with 1.11.4?

**Comment by lburgazzoli** [comment]
I got it from ci so I assumed it was working before, let me try

**Comment by lburgazzoli** [comment]
same issue also on 1.11.4

**Comment by bsideup** [comment]
@jonathanvila has reported a success by replacing "docker" page (2.5y.o., version 1.13.1) with "docker-ce" (the latest stable)

**Comment by lburgazzoli** [comment]
I have docker from fedora:

```
$ rpm -qa | grep docker
docker-1.13.1-67.git1185cfd.fc30.x86_64
docker-rhel-push-plugin-1.13.1-67.git1185cfd.fc30.x86_64
docker-common-1.13.1-67.git1185cfd.fc30.x86_64
```

**Comment by lburgazzoli** [comment]
I'm a little bit reluctant to install from docker itself as for example it does not list fedora 30 in the installation instructions:

     https://docs.docker.com/install/linux/docker-ce/fedora/

**Comment by bsideup** [comment]
Thanks for confirming that it is not 1.12.0 specific 👍 

 I think your colleagues were having the same sort of conversation about "docker" vs "docker-ce" [here](https://github.com/project-xavier/xavier-integration/pull/20), and came to the conclusion that "docker-ce" is fine. You may want to follow their conversation :)

**Comment by lburgazzoli** [comment]
so yeah, setting the property works

**Comment by bsideup** [comment]
@lburgazzoli thanks again for confirming! 💯
