### ISSUE TITLE
Pulling of images and Selenium startup failures more likely to cause container startup timeout in v1.1.0

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#172]
See https://github.com/testcontainers/testcontainers-java/issues/170#issuecomment-232561092. Thanks to @IhabSoliman for finding this.

**Comment by rnorth** [comment]
I'm also going to reinstate startup retries to aid with #172; another source of random failures is Selenium browser containers failing to start correctly. I've seen this numerous times and there doesn't appear to be any pattern to it; retrying startup of the selenium containers specifically seems to be the least risky option.

As such, I'm reinstating the container startup retry that I removed for v1.1.0, *but* am making it optional (defaulting to only one attempt). This allows flexibility without forcing all container usage into using startup retries.

**Comment by rnorth** [comment]
V1.1.1 released just now includes fixes for this issue

**Comment by IhabSoliman** [comment]
So I was just testing the new version and I got this

```
java.lang.NoSuchMethodError: org.testcontainers.containers.PostgreSQLContainer.withStartupAttempts(I)V
	at com.jive.jci.commons.itest.AbstractJdbcIntegrationTestLauncher.initDb(AbstractJdbcIntegrationTestLauncher.java:90)
	at com.jive.jci.commons.itest.AbstractJdbcIntegrationTestLauncher.init(AbstractJdbcIntegrationTestLauncher.java:65)
	at com.jive.jci.ambassador.itest.AbstractJdbcAmbassadorTestLauncher.init(AbstractJdbcAmbassadorTestLauncher.java:65)
	at com.jive.jci.ambassador.itest.providers.ProvidersIntegrationTestLauncher.init(ProvidersIntegrationTestLauncher.java:34)
	at com.jive.jci.ambassador.itest.providers.AbstractProvidersIT.setupClass(AbstractProvidersIT.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```
