### ISSUE TITLE
Would be helpful to have a way to test OSType for your assumeTrue.

### ISSUE THREAD

**Issue by casz** [testcontainers/testcontainers-java#1765]
Would like a way to have a to detect what OSType is on the Windows Docker host. ie. `TestEnvironment.isDockerOSType("linux")`

See this PR for reference
https://github.com/jenkinsci/configuration-as-code-plugin/pull/986/files#diff-1f76c3e79f43f462a54019703a6a40e5R47

**Comment by bsideup** [comment]
Hi @casz,

Since Testcontainers only supports Linux module, I don't think this method makes sense.

However, you can use:
```java
DockerClientFactory.instance().client().infoCmd().exec().getOperatingSystem()
```

Does it work for you?

**Comment by casz** [comment]
Sure does, but would be helpful to have a more descriptive method that returns true if OSType is Linux than.

**Comment by bsideup** [comment]
The only change I could see here is too fail fast if Docker OS is not "Linux".

There was an attempt to support Windows Containers (see #870) but we have too many Linux-based components before we can even think of it

**Comment by casz** [comment]
Your suggestion is actually incorrect
```
DockerClientFactory.instance().client().infoCmd().exec().getOsType();
```
This is what I wanted :)
If I run `docker info`
This is what I get
```
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
```
and if I switch to Windows containers
```
 Kernel Version: 10.0 18362 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Pro Version 1903 (OS Build 18362.295)
 OSType: windows
```

**Comment by casz** [comment]
This does not help me cause apparently I run into this issue:

```
java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.junit.runners.model.FrameworkField.get(FrameworkField.java:73)
	at org.junit.runners.model.TestClass.getAnnotatedFieldValues(TestClass.java:230)
	at org.junit.runners.ParentRunner.classRules(ParentRunner.java:255)
	at org.junit.runners.ParentRunner.withClassRules(ParentRunner.java:244)
	at org.junit.runners.ParentRunner.classBlock(ParentRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:362)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer \\?\C:\ProgramData\Docker\windowsfilter\79158aef4e7a3f9d44a641a25dca8473357d8dd0e8907e800469e7ec94b73729: The system cannot find the path specified.
	at com.github.dockerjava.core.command.PullImageResultCallback.checkDockerClientPullSuccessful(PullImageResultCallback.java:96)
	at com.github.dockerjava.core.command.PullImageResultCallback.throwFirstError(PullImageResultCallback.java:111)
	at com.github.dockerjava.core.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:91)
	at com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:124)
	at org.testcontainers.DockerClientFactory.checkAndPullImage(DockerClientFactory.java:223)
	at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:70)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:125)
	at io.jenkins.plugins.casc.vault.VaultTestUtil.dockerOSTypeIsLinux(VaultTestUtil.java:57)
	at io.jenkins.plugins.casc.vault.VaultTestUtil.hasDockerDaemon(VaultTestUtil.java:50)
	at io.jenkins.plugins.casc.vault.VaultTestUtil.createVaultContainer(VaultTestUtil.java:64)
	at io.jenkins.plugins.casc.vault.VaultSecretSourceTest.<clinit>(VaultSecretSourceTest.java:53)
	... 17 more
```

**Comment by casz** [comment]
I think the client should fail fast if OSType is not Linux if the plan is to not support Windows containers for now.

**Comment by casz** [comment]
Having issues to set `TESTCONTAINERS_RYUK_DISABLED` during running my commands inside `hasDockerDaemon` so I'll look into contributing a fix into the client initialization.

**Comment by bsideup** [comment]
> I think the client should fail fast if OSType is not Linux if the plan is to not support Windows containers for now.

Implementation hint - I would suggest adding this check to the strategies, so that it will fail with "no valid environment" if none of the discovered environments support Linux containers
