### ISSUE TITLE
Intermittent Toxiproxy tests in CI

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#1769]
See https://dev.azure.com/testcontainers/testcontainers-java/_build/results?buildId=1265&view=logs:

```
Gradle Test Executor 22 > org.testcontainers.containers.ToxiproxyTest > testLatencyViaProxy FAILED
    redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
        at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:205)
        at redis.clients.jedis.util.RedisInputStream.readByte(RedisInputStream.java:43)
        at redis.clients.jedis.Protocol.process(Protocol.java:154)
        at redis.clients.jedis.Protocol.read(Protocol.java:219)
        at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:309)
        at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:236)
        at redis.clients.jedis.Jedis.set(Jedis.java:149)
        at org.testcontainers.containers.ToxiproxyTest.testLatencyViaProxy(ToxiproxyTest.java:54)

        Caused by:
        java.net.SocketTimeoutException: Read timed out
            at java.base/java.net.SocketInputStream.socketRead0(Native Method)
            at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
            at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
            at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
            at java.base/java.net.SocketInputStream.read(SocketInputStream.java:126)
            at redis.clients.jedis.util.RedisInputStream.ensureFill(RedisInputStream.java:199)
            ... 7 more
```

I'm not sure of the cause at present; I wonder if there is some time lag on creation of the proxy that we need to take into account.

It would be worth investigating further, but I'll add a `@Flaky` annotation for now.

**Comment by slovdahl** [comment]
I have no idea if it's the same problem, but we're getting occasional timeouts using Toxiproxy between a test and a mockserver instance started locally in the same JVM as the test. No success in reproducing it locally yet, so not much to go on (yet). :shrug:
