### ISSUE TITLE
Container not starting with @ClassRule

### ISSUE THREAD

**Issue by raffig** [testcontainers/testcontainers-java#1774]
When container is assigned to field annotated with @ClassRule it does not start automatically before first test. When @Rule annotation used everything works fine.

Code not working:
```java
import org.junit.ClassRule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;
import org.testcontainers.containers.GenericContainer;

@RunWith(Parameterized.class)
public class PersistenceTestContainersTestBase {

	@ClassRule
	public static GenericContainer<?> db;
	
	@Parameters
	public static Object[][] getDbEnginesData() {
		return new Object[][] {
			{new MySqlContainerFactory()}
		};
	}
	
	public PersistenceTestContainersTestBase(PersistenceContainerFactory containerFactory) {
		db = containerFactory.createContainer();
	}
	
	@Test
	public void testContainerIsUp() {
		System.out.println(db.getContainerIpAddress());
		System.out.println(db.getFirstMappedPort());
	}
}
```

Log output is as follows:

```
2019-08-22 22:30:23,954  INFO - Loaded org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first [[org.testcontainers.dockerclient.DockerClientProviderStrategy]]
2019-08-22 22:30:24,101  INFO - Will use 'okhttp' transport [[org.testcontainers.dockerclient.DockerClientProviderStrategy]]
2019-08-22 22:30:25,689  INFO - Accessing docker with local Npipe socket (npipe:////./pipe/docker_engine) [[org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy]]
2019-08-22 22:30:25,689  INFO - Found Docker environment with local Npipe socket (npipe:////./pipe/docker_engine) [[org.testcontainers.dockerclient.DockerClientProviderStrategy]]
2019-08-22 22:30:25,692  INFO - Docker host IP address is localhost [[org.testcontainers.DockerClientFactory]]
2019-08-22 22:30:26,044  INFO - Connected to docker: 
  Server Version: 19.03.1
  API Version: 1.40
  Operating System: Docker Desktop
  Total Memory: 1999 MB [[org.testcontainers.DockerClientFactory]]
2019-08-22 22:30:26,399  INFO - Credentials not found for host (quay.io) when using credential helper/store (docker-credential-desktop) [[org.testcontainers.utility.RegistryAuthLocator]]
2019-08-22 22:30:27,622  INFO - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit [[org.testcontainers.DockerClientFactory]]
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
localhost
```

Last method causes exception:

```
java.lang.IllegalStateException: Mapped port can only be obtained after the container is started
	at org.testcontainers.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at org.testcontainers.containers.ContainerState.getMappedPort(ContainerState.java:107)
	at java.util.Optional.map(Unknown Source)
	at org.testcontainers.containers.ContainerState.getFirstMappedPort(ContainerState.java:96)
	at [...]
```

The same code with @Rule annotation works fine:

```java
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;
import org.testcontainers.containers.GenericContainer;

@RunWith(Parameterized.class)
public class PersistenceTestContainersTestBase {

	@Rule
	public GenericContainer<?> db;
	
	@Parameters
	public static Object[][] getDbEnginesData() {
		return new Object[][] {
			{new MySqlContainerFactory()}
		};
	}
	
	public PersistenceTestContainersTestBase(PersistenceContainerFactory containerFactory) {
		db = containerFactory.createContainer();
	}
	
	@Test
	public void testContainerIsUp() {
		System.out.println(db.getContainerIpAddress());
		System.out.println(db.getFirstMappedPort());
	}
}
```

And in this case output is as follows:

```
2019-08-22 22:35:01,531  INFO - Loaded org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first [[org.testcontainers.dockerclient.DockerClientProviderStrategy]]
2019-08-22 22:35:01,694  INFO - Will use 'okhttp' transport [[org.testcontainers.dockerclient.DockerClientProviderStrategy]]
2019-08-22 22:35:03,405  INFO - Accessing docker with local Npipe socket (npipe:////./pipe/docker_engine) [[org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy]]
2019-08-22 22:35:03,405  INFO - Found Docker environment with local Npipe socket (npipe:////./pipe/docker_engine) [[org.testcontainers.dockerclient.DockerClientProviderStrategy]]
2019-08-22 22:35:03,407  INFO - Docker host IP address is localhost [[org.testcontainers.DockerClientFactory]]
2019-08-22 22:35:03,752  INFO - Connected to docker: 
  Server Version: 19.03.1
  API Version: 1.40
  Operating System: Docker Desktop
  Total Memory: 1999 MB [[org.testcontainers.DockerClientFactory]]
2019-08-22 22:35:04,100  INFO - Credentials not found for host (quay.io) when using credential helper/store (docker-credential-desktop) [[org.testcontainers.utility.RegistryAuthLocator]]
2019-08-22 22:35:05,260  INFO - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit [[org.testcontainers.DockerClientFactory]]
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
2019-08-22 22:35:05,598  INFO - Creating container for image: mysql:5.6.29 [[🐳 [mysql:5.6.29]]]
2019-08-22 22:35:05,725  INFO - Credentials not found for host (index.docker.io) when using credential helper/store (docker-credential-desktop) [[org.testcontainers.utility.RegistryAuthLocator]]
2019-08-22 22:35:06,246  INFO - Starting container with ID: 7dabbc7f381882f6bda4ae36a32f7a5ab41b9779b608bbfa54354f78d643694f [[🐳 [mysql:5.6.29]]]
2019-08-22 22:35:06,997  INFO - Container mysql:5.6.29 is starting: 7dabbc7f381882f6bda4ae36a32f7a5ab41b9779b608bbfa54354f78d643694f [[🐳 [mysql:5.6.29]]]
2019-08-22 22:35:07,044  INFO - Waiting for database connection to become available at jdbc:mysql://localhost:32783/test using query 'SELECT 1' [[🐳 [mysql:5.6.29]]]
2019-08-22 22:35:17,405  INFO - Obtained a connection to container (jdbc:mysql://localhost:32783/test) [[🐳 [mysql:5.6.29]]]
2019-08-22 22:35:17,406  INFO - Container mysql:5.6.29 started [[🐳 [mysql:5.6.29]]]
localhost
32783
```

I found related entry:
https://github.com/testcontainers/testcontainers-java/issues/694

But author didn't explain clearly what solved the problem.

Test Containers version with such behavior is: 1.11.4 and 1.12.0.

**Comment by raffig** [comment]
Oh, of course workaround is to use JUnit @BeforeClass and @AfterClass to manually start and stop container with start() and stop() methods.

**Comment by raffig** [comment]
I did some more digging and I have an inkling that it may be related to the way BeforeClass and AfterClass work with Parametrized tests. It seems that those methods are called before anything gets parametrized, thus when container is parametrized everything falls apart. When test is not parametrized @ClassRule works fine as in following code:

```java
import org.junit.ClassRule;
import org.junit.Test;
import org.testcontainers.containers.GenericContainer;

public class PersistenceTestContainersTestBase2 {

	@ClassRule
	public static GenericContainer<?> db = new MySqlContainerFactory().createContainer();
	
	@Test
	public void testContainerIsUp() {
		System.out.println(db.getContainerIpAddress());
		System.out.println(db.getFirstMappedPort());
	}
}
```

**Comment by raffig** [comment]
The only workaround I've found was to start container on constructor. Container will be destroyed on JVM exit, however on many tests there will be probably hundrends of running containers before JVM with tests stops and gets containers stopped and removed. This may case running into some resource issues.

It seems there is missing @BeforePram and @AfterParam annotation and there is ongoing debate in JUnit for such feature:
https://github.com/junit-team/junit4/pull/1435

It seems it could be included in JUnit 4.13. Currently there is a JUnit 4.13-beta-3 available with that feature and it seems to solve the problem with following implementation:

```java
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.AfterParam;
import org.junit.runners.Parameterized.Parameters;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testcontainers.containers.GenericContainer;

@RunWith(Parameterized.class)
public class PersistenceTestContainersTestBase {

	public static final Logger logger = LoggerFactory.getLogger(PersistenceTestContainersTestBase.class);
	
	public static GenericContainer<?> db;
	
	@AfterParam
	public static void stopContainer() {
		logger.info("Stopping container");
		db.stop();
	}
	
	@Parameters
	public static Object[][] getDbEnginesData() {
		return new Object[][] {
			{new MySqlContainerFactory()}
		};
	}
	
	public PersistenceTestContainersTestBase(PersistenceContainerFactory containerFactory) {
		logger.info("Creating test for param");
		db = containerFactory.createContainer();
		db.start();
	}
	
	@Test
	public void testContainerIsUp() {
		System.out.println(db.getContainerIpAddress());
		System.out.println(db.getFirstMappedPort());
	}
}
```

**Comment by bsideup** [comment]
the field is static and has to be initialized. Setting it in the constructor does not make any sense.

I'm closing this issue as it is not related to Testcontainers

**Comment by raffig** [comment]
First of all field annotated with @ClassRule must be static.
Second: any method annotated with @AfterClass or @AfterParam must be static as well, so it will have access to the container if it is in static field.

Well, this issue maybe isn't actually directly related to Test Containers library (or maybe there is bug in TestRule implementation), however TC library states that is may be used with JUnit. And it seems that it is hard to use TC with Parametrized tests and has some known-issues/limitations what should be clearly indicated in TC documentation.

I assume that it would be convenient to use TC in following case:
Application using JPA exists. It is expected to properly startup on few database engines, lets say: MySQL, PostgreSQL and Oracle-XE. I would like to be able to prepare ONE test method checkStartup() in Parametrized test which provides container as parameter. This way I could test all expected engines. However as for today:
1. ClassRule will not work correctly as shown.
2. Workaround is possible leaving the containers running, but it may cause resource issues when dealing with significant number of tests.
3. Second workaround is possible, but it requires field with container to be static, and I don't know if it will cause problems with e.g. parallel test execution.

Even if this issue is not directly related to TestContainers JUnit team is working on some features that could help resolve such case properly and They are in beta stage, so it is probably a good moment to take a deeper look into their solution if it solves the problem.

**Comment by raffig** [comment]
After consulting JUnit team I have a better workaround (@BeforeParam/@AfterParam methods optionally accept the test parameter), but is still requires using JUnit 4.13 (currently beta).

First define interface for container provider:

```java
import org.testcontainers.containers.JdbcDatabaseContainer;

public interface PersistenceContainerProvider {

	/**
	 * <p>
	 * Gets container instance - always the same instance.
	 * </p>
	 * 
	 * <p>
	 * This method must be idempotent and always return the same instance of
	 * provided container.
	 * </p>
	 * 
	 * @return Container instance
	 */
	JdbcDatabaseContainer<?> getContainer();
}
```

Then prepare the tests:

```java
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.AfterParam;
import org.junit.runners.Parameterized.BeforeParam;
import org.junit.runners.Parameterized.Parameters;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testcontainers.containers.JdbcDatabaseContainer;

@RunWith(Parameterized.class)
public class PersistenceTestContainersTestBase {

	public static final Logger logger = LoggerFactory.getLogger(PersistenceTestContainersTestBase.class);

	public JdbcDatabaseContainer<?> db;
	
	@BeforeParam
	public static void setupContainer(PersistenceContainerProvider containerProvider) {
		logger.info("Starting container for tests: {}", containerProvider.getClass().getSimpleName());
		containerProvider.getContainer().start();
	}

	@AfterParam
	public static void stopContainer(PersistenceContainerProvider containerProvider) {
		logger.info("Stopping container: {}", containerProvider.getClass().getSimpleName());
		containerProvider.getContainer().stop();
	}
	
	@Parameters
	public static Object[][] getDbEnginesData() {
		return new Object[][] {
			{new MySql5_6_29ContainerProvider()},
			{new MySql5_7_27ContainerProvider()},
		};
	}
	
	public PersistenceTestContainersTestBase(PersistenceContainerProvider containerProvider) {
		logger.info("Preparing container for tests: {}", containerProvider.getClass().getSimpleName());
		db = containerProvider.getContainer();
	}
	
	@Test
	public void testContainerIsUp() {
		logger.info("testContainerIsUp");
		Assert.assertTrue(db.isRunning());
	}

	@Test
	public void testContainerIsCreated() {
		logger.info("testContainerIsCreated");
		Assert.assertTrue(db.isCreated());
	}
}
```

Enjoy working parametrized test as logged:

```
2019-08-23 11:54:53,617  INFO - Loaded org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first [[org.testcontainers.dockerclient.DockerClientProviderStrategy]]
2019-08-23 11:54:53,805  INFO - Will use 'okhttp' transport [[org.testcontainers.dockerclient.DockerClientProviderStrategy]]
2019-08-23 11:54:55,251  INFO - Accessing docker with local Npipe socket (npipe:////./pipe/docker_engine) [[org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy]]
2019-08-23 11:54:55,251  INFO - Found Docker environment with local Npipe socket (npipe:////./pipe/docker_engine) [[org.testcontainers.dockerclient.DockerClientProviderStrategy]]
2019-08-23 11:54:55,254  INFO - Docker host IP address is localhost [[org.testcontainers.DockerClientFactory]]
2019-08-23 11:54:55,611  INFO - Connected to docker: 
  Server Version: 19.03.1
  API Version: 1.40
  Operating System: Docker Desktop
  Total Memory: 1999 MB [[org.testcontainers.DockerClientFactory]]
2019-08-23 11:54:56,041  INFO - Credentials not found for host (quay.io) when using credential helper/store (docker-credential-desktop) [[org.testcontainers.utility.RegistryAuthLocator]]
2019-08-23 11:54:57,451  INFO - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit [[org.testcontainers.DockerClientFactory]]
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
2019-08-23 11:54:57,780  INFO - Starting container for tests: MySql5_6_29ContainerProvider [[PersistenceTestContainersTestBase]]
2019-08-23 11:54:57,787  INFO - Creating container for image: mysql:5.6.29 [[🐳 [mysql:5.6.29]]]
2019-08-23 11:54:57,924  INFO - Credentials not found for host (index.docker.io) when using credential helper/store (docker-credential-desktop) [[org.testcontainers.utility.RegistryAuthLocator]]
2019-08-23 11:54:58,343  INFO - Starting container with ID: 7a128339a1e96ea3eea484d0c23d91124076c26b35c8802011c87dbeb4782be2 [[🐳 [mysql:5.6.29]]]
2019-08-23 11:54:59,187  INFO - Container mysql:5.6.29 is starting: 7a128339a1e96ea3eea484d0c23d91124076c26b35c8802011c87dbeb4782be2 [[🐳 [mysql:5.6.29]]]
2019-08-23 11:54:59,237  INFO - Waiting for database connection to become available at jdbc:mysql://localhost:32835/test using query 'SELECT 1' [[🐳 [mysql:5.6.29]]]
2019-08-23 11:55:09,379  INFO - Obtained a connection to container (jdbc:mysql://localhost:32835/test) [[🐳 [mysql:5.6.29]]]
2019-08-23 11:55:09,380  INFO - Container mysql:5.6.29 started [[🐳 [mysql:5.6.29]]]
2019-08-23 11:55:09,388  INFO - Preparing container for tests: MySql5_6_29ContainerProvider [[PersistenceTestContainersTestBase]]
2019-08-23 11:55:09,391  INFO - testContainerIsUp [[PersistenceTestContainersTestBase]]
2019-08-23 11:55:09,399  INFO - Preparing container for tests: MySql5_6_29ContainerProvider [[PersistenceTestContainersTestBase]]
2019-08-23 11:55:09,399  INFO - testContainerIsCreated [[PersistenceTestContainersTestBase]]
2019-08-23 11:55:09,415  INFO - Stopping container: MySql5_6_29ContainerProvider [[PersistenceTestContainersTestBase]]
2019-08-23 11:55:10,322  INFO - Starting container for tests: MySql5_7_27ContainerProvider [[PersistenceTestContainersTestBase]]
2019-08-23 11:55:10,324  INFO - Creating container for image: mysql:5.7.27 [[🐳 [mysql:5.7.27]]]
2019-08-23 11:55:10,497  INFO - Credentials not found for host (index.docker.io) when using credential helper/store (docker-credential-desktop) [[org.testcontainers.utility.RegistryAuthLocator]]
2019-08-23 11:55:10,895  INFO - Starting container with ID: ab671dc18099049dd7a5886521b75093a1fbafb4527998b5ae0806bf81349d8d [[🐳 [mysql:5.7.27]]]
2019-08-23 11:55:11,708  INFO - Container mysql:5.7.27 is starting: ab671dc18099049dd7a5886521b75093a1fbafb4527998b5ae0806bf81349d8d [[🐳 [mysql:5.7.27]]]
2019-08-23 11:55:11,733  INFO - Waiting for database connection to become available at jdbc:mysql://localhost:32837/test using query 'SELECT 1' [[🐳 [mysql:5.7.27]]]
2019-08-23 11:55:24,444  INFO - Obtained a connection to container (jdbc:mysql://localhost:32837/test) [[🐳 [mysql:5.7.27]]]
2019-08-23 11:55:24,445  INFO - Container mysql:5.7.27 started [[🐳 [mysql:5.7.27]]]
2019-08-23 11:55:24,445  INFO - Preparing container for tests: MySql5_7_27ContainerProvider [[PersistenceTestContainersTestBase]]
2019-08-23 11:55:24,446  INFO - testContainerIsUp [[PersistenceTestContainersTestBase]]
2019-08-23 11:55:24,453  INFO - Preparing container for tests: MySql5_7_27ContainerProvider [[PersistenceTestContainersTestBase]]
2019-08-23 11:55:24,453  INFO - testContainerIsCreated [[PersistenceTestContainersTestBase]]
2019-08-23 11:55:24,472  INFO - Stopping container: MySql5_7_27ContainerProvider [[PersistenceTestContainersTestBase]]
```
