### ISSUE TITLE
Waitstrategy not applied

### ISSUE THREAD

**Issue by HaMatthias** [testcontainers/testcontainers-java#1827]
I have the following setup:

```
@Container
  private static final DockerComposeContainer stack =
      new DockerComposeContainer(
              new File("../docker-compose.yml"), new File("../docker-compose.override.yml"))
          .withExposedService(
              "party-parrot_1",
              10001,
              Wait.forHealthcheck().withStartupTimeout(Duration.ofSeconds(200)));
```

And the following test:

```
@Test
  public void receiveWelcomeMessage() {
    Assert.assertThat(stack.getServicePort("party-parrot_1", 10001), Is.is(10001));
  }
```

My log output is the following:

```
/usr/lib/jvm/java-11-openjdk-amd64/bin/java -ea -Djavax.net.ssl.trustStore=src/test/resources/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Didea.test.cyclic.buffer.size=1048576 -javaagent:/home/mhahn/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/191.8026.42/lib/idea_rt.jar=40791:/home/mhahn/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/191.8026.42/bin -Dfile.encoding=UTF-8 -classpath /home/mhahn/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/191.8026.42/lib/idea_rt.jar:/home/mhahn/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/191.8026.42/plugins/junit/lib/junit-rt.jar:/home/mhahn/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/191.8026.42/plugins/junit/lib/junit5-rt.jar:/home/mhahn/workspace/won-prototype/archy/out/test/classes:/home/mhahn/workspace/won-prototype/archy/out/test/resources:/home/mhahn/.m2/repository/org/junit/platform/junit-platform-commons/1.5.1/junit-platform-commons-1.5.1.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/org.rnorth.duct-tape/duct-tape/1.0.8/92edc22a9ab2f3e17c9bf700aaee377d50e8b530/duct-tape-1.0.8.jar:/home/mhahn/.m2/repository/org/apiguardian/apiguardian-api/1.1.0/apiguardian-api-1.1.0.jar:/home/mhahn/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/home/mhahn/.m2/repository/org/junit/platform/junit-platform-engine/1.5.1/junit-platform-engine-1.5.1.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-core/1.2.3/864344400c3d4d92dfeb0a305dc87d953677c03c/logback-core-1.2.3.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/org.rnorth/tcp-unix-socket-proxy/1.0.2/cf53989130986c60113032e25185f4496ffbc186/tcp-unix-socket-proxy-1.0.2.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.26/77100a62c2e6f04b53977b9f541044d7d722693d/slf4j-api-1.7.26.jar:/home/mhahn/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/17.0.0/8ceead41f4e71821919dbdb7a9847608f1a938cb/annotations-17.0.0.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/javax.annotation/javax.annotation-api/1.3.2/934c04d3cfef185a8008e7bf34331b79730a9d43/javax.annotation-api-1.3.2.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.2.3/7c4f3c474fb2c041d8028740440937705ebb473a/logback-classic-1.2.3.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/javax.xml.bind/jaxb-api/2.3.1/8531ad5ac454cc2deb9d4d32c40c4d7451939b5d/jaxb-api-2.3.1.jar:/home/mhahn/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.5.1/junit-jupiter-engine-5.5.1.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/org.rnorth.visible-assertions/visible-assertions/2.1.2/20d31a578030ec8e941888537267d3123c2ad1c1/visible-assertions-2.1.2.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna-platform/5.3.1/925049dd00b3def5ab561709a56b96055fa67011/jna-platform-5.3.1.jar:/home/mhahn/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/javax.activation/javax.activation-api/1.2.0/85262acf3ca9816f9537ca47d5adeabaead7cb16/javax.activation-api-1.2.0.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/net.java.dev.jna/jna/5.3.1/6eb9d07456c56b9c2560722e90382252f0f98405/jna-5.3.1.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/com.kohlschutter.junixsocket/junixsocket-native-common/2.0.4/726bd66a934dea39c817382986496fa4eda96411/junixsocket-native-common-2.0.4.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/com.kohlschutter.junixsocket/junixsocket-common/2.0.4/b4d1870bf903412533e0b79c6fcd402defcfc05b/junixsocket-common-2.0.4.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/org.testcontainers/junit-jupiter/1.12.0/c8c9acc3109f277a54c3bd75b8055630817851d2/junit-jupiter-1.12.0.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/org.testcontainers/testcontainers/1.12.0/ac89643ce1ddde504da09172086aba0c7df10bff/testcontainers-1.12.0.jar:/home/mhahn/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.5.1/junit-jupiter-api-5.5.1.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-compress/1.18/1191f9f2bc0c47a8cce69193feb1ff0a8bcb37d5/commons-compress-1.18.jar:/home/mhahn/.gradle/caches/modules-2/files-2.1/org.scijava/native-lib-loader/2.0.2/1451fa03954c5e31a358b411147de472b4dab92c/native-lib-loader-2.0.2.jar com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit4 com.etracker.archy.componentTests.SubscribeTest
10:32:02.741 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/home/mhahn/workspace/won-prototype/archy/out/test/resources/testcontainers.properties
10:32:02.744 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/home/mhahn/workspace/won-prototype/archy/out/test/resources/testcontainers.properties
10:32:02.745 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/home/mhahn/.testcontainers.properties
10:32:02.745 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides loaded from TestcontainersConfiguration(properties={compose.container.image=docker/compose:1.24.0, ryuk.container.privileged=true, docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy})
10:32:02.775 [main] INFO org.testcontainers.dockerclient.DockerClientProviderStrategy - Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy from ~/.testcontainers.properties, will try it first
10:32:02.813 [main] INFO org.testcontainers.dockerclient.DockerClientProviderStrategy - Will use 'okhttp' transport
10:32:03.062 [ducttape-0] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - Pinging docker daemon...
10:32:03.220 [ducttape-0] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: org.testcontainers.dockerclient.transport.okhttp.OkHttpDockerCmdExecFactory$1@3f617aaa
10:32:03.374 [main] INFO org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy - Found docker client settings from environment
10:32:03.389 [main] INFO org.testcontainers.dockerclient.DockerClientProviderStrategy - Found Docker environment with Environment variables, system properties and defaults. Resolved: 
    dockerHost=unix:///var/run/docker.sock
    apiVersion='{UNKNOWN_VERSION}'
    registryUrl='https://index.docker.io/v1/'
    registryUsername='mhahn'
    registryPassword='null'
    registryEmail='null'
    dockerConfig='DefaultDockerClientConfig[dockerHost=unix:///var/run/docker.sock,registryUsername=mhahn,registryPassword=<null>,registryEmail=<null>,registryUrl=https://index.docker.io/v1/,dockerConfigPath=/home/mhahn/.docker,sslConfig=<null>,apiVersion={UNKNOWN_VERSION},dockerConfig=<null>]'

10:32:03.390 [main] INFO org.testcontainers.DockerClientFactory - Docker host IP address is localhost
10:32:03.392 [main] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: com.github.dockerjava.core.exec.InfoCmdExec@3a93b025
10:32:03.562 [main] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: com.github.dockerjava.core.exec.VersionCmdExec@4e7912d8
10:32:03.599 [main] INFO org.testcontainers.DockerClientFactory - Connected to docker: 
  Server Version: 19.03.1
  API Version: 1.40
  Operating System: Ubuntu 18.04.3 LTS
  Total Memory: 16011 MB
10:32:03.602 [main] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: ListImagesCmdImpl[imageNameFilter=quay.io/testcontainers/ryuk:0.2.3,showAll=false,filters=com.github.dockerjava.core.util.FiltersBuilder@0,execution=com.github.dockerjava.core.exec.ListImagesCmdExec@1b6e1eff]
10:32:03.635 [main] DEBUG org.testcontainers.utility.RegistryAuthLocator - Looking up auth config for image: quay.io/testcontainers/ryuk:0.2.3
10:32:03.635 [main] DEBUG org.testcontainers.utility.RegistryAuthLocator - RegistryAuthLocator has configFile: /home/mhahn/.docker/config.json (exists) and commandPathPrefix: 
10:32:03.639 [main] DEBUG org.testcontainers.utility.RegistryAuthLocator - registryName [quay.io] for dockerImageName [quay.io/testcontainers/ryuk:0.2.3]
10:32:03.639 [main] DEBUG org.testcontainers.utility.RegistryAuthLocator - Executing docker credential provider: docker-credential-secretservice to locate auth config for: quay.io
10:32:03.645 [main] DEBUG org.testcontainers.shaded.org.zeroturnaround.exec.ProcessExecutor - Executing [docker-credential-secretservice, get].
10:32:03.650 [main] DEBUG org.testcontainers.shaded.org.zeroturnaround.exec.ProcessExecutor - Started Process[pid=16072, exitValue="not exited"]
10:32:03.657 [WaitForProcess-Process[pid=16072, exitValue="not exited"]] DEBUG org.testcontainers.shaded.org.zeroturnaround.exec.WaitForProcess - Process[pid=16072, exitValue=1] stopped with exit code 1
10:32:03.659 [main] DEBUG org.testcontainers.shaded.org.zeroturnaround.exec.ProcessExecutor - Executing [docker-credential-secretservice, get].
10:32:03.660 [main] DEBUG org.testcontainers.shaded.org.zeroturnaround.exec.ProcessExecutor - Started Process[pid=16082, exitValue="not exited"]
10:32:03.684 [WaitForProcess-Process[pid=16082, exitValue="not exited"]] DEBUG org.testcontainers.shaded.org.zeroturnaround.exec.WaitForProcess - Process[pid=16082, exitValue=1] stopped with exit code 1
10:32:03.685 [main] DEBUG org.testcontainers.utility.RegistryAuthLocator - Got credentials not found error message from docker credential helper - credentials not found in native keychain
10:32:03.686 [main] INFO org.testcontainers.utility.RegistryAuthLocator - Credential helper/store (docker-credential-secretservice) does not have credentials for quay.io
10:32:03.686 [main] DEBUG org.testcontainers.utility.RegistryAuthLocator - no matching Auth Configs - falling back to defaultAuthConfig [null]
10:32:03.686 [main] DEBUG org.testcontainers.dockerclient.auth.AuthDelegatingDockerClientConfig - Effective auth config [null]
10:32:03.702 [main] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: com.github.dockerjava.core.command.CreateContainerCmdImpl@72035809[name=testcontainers-ryuk-c9389a4b-2ee7-4ba0-adb2-b06947a682c8,hostName=<null>,domainName=<null>,user=<null>,attachStdin=<null>,attachStdout=<null>,attachStderr=<null>,portSpecs=<null>,tty=<null>,stdinOpen=<null>,stdInOnce=<null>,env=<null>,cmd=<null>,healthcheck=<null>,argsEscaped=<null>,entrypoint=<null>,image=quay.io/testcontainers/ryuk:0.2.3,volumes=com.github.dockerjava.api.model.Volumes@606e4010,workingDir=<null>,macAddress=<null>,onBuild=<null>,networkDisabled=<null>,exposedPorts=com.github.dockerjava.api.model.ExposedPorts@8458f04,stopSignal=<null>,stopTimeout=<null>,hostConfig=com.github.dockerjava.api.model.HostConfig@48075da3[binds=com.github.dockerjava.api.model.Binds@cc43f62,blkioWeight=<null>,blkioWeightDevice=<null>,blkioDeviceReadBps=<null>,blkioDeviceWriteBps=<null>,blkioDeviceReadIOps=<null>,blkioDeviceWriteIOps=<null>,memorySwappiness=<null>,nanoCPUs=<null>,capAdd=<null>,capDrop=<null>,containerIDFile=<null>,cpuPeriod=<null>,cpuRealtimePeriod=<null>,cpuRealtimeRuntime=<null>,cpuShares=<null>,cpuQuota=<null>,cpusetCpus=<null>,cpusetMems=<null>,devices=<null>,deviceCgroupRules=<null>,diskQuota=<null>,dns=<null>,dnsOptions=<null>,dnsSearch=<null>,extraHosts=<null>,groupAdd=<null>,ipcMode=<null>,cgroup=<null>,links=<null>,logConfig=<null>,lxcConf=<null>,memory=<null>,memorySwap=<null>,memoryReservation=<null>,kernelMemory=<null>,networkMode=<null>,oomKillDisable=<null>,init=<null>,autoRemove=true,oomScoreAdj=<null>,portBindings=<null>,privileged=true,publishAllPorts=true,readonlyRootfs=<null>,restartPolicy=<null>,ulimits=<null>,cpuCount=<null>,cpuPercent=<null>,ioMaximumIOps=<null>,ioMaximumBandwidth=<null>,volumesFrom=<null>,mounts=<null>,pidMode=<null>,isolation=<null>,securityOpts=<null>,storageOpt=<null>,cgroupParent=<null>,volumeDriver=<null>,shmSize=<null>,pidsLimit=<null>,runtime=<null>,tmpFs=<null>,utSMode=<null>,usernsMode=<null>,sysctls=<null>,consoleSize=<null>],labels={org.testcontainers=true},shell=<null>,networkingConfig=<null>,ipv4Address=<null>,ipv6Address=<null>,aliases=<null>,authConfig=<null>,execution=com.github.dockerjava.core.exec.CreateContainerCmdExec@5b218417]
10:32:03.965 [main] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 15172ab10e1a6091506467c645264250319fbb3dd9ecc12ec4cebbfee5272425,com.github.dockerjava.core.exec.StartContainerCmdExec@7dc19a70
10:32:04.365 [main] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 15172ab10e1a6091506467c645264250319fbb3dd9ecc12ec4cebbfee5272425,false,com.github.dockerjava.core.exec.InspectContainerCmdExec@69ee81fc
10:32:04.365 [main] DEBUG com.github.dockerjava.core.exec.InspectContainerCmdExec - GET: OkHttpWebTarget(okHttpClient=org.testcontainers.shaded.okhttp3.OkHttpClient@6e2aa843, baseUrl=http://docker.socket/, path=[/containers/15172ab10e1a6091506467c645264250319fbb3dd9ecc12ec4cebbfee5272425/json], queryParams={})
10:32:04.427 [testcontainers-ryuk] DEBUG org.testcontainers.utility.ResourceReaper - Sending 'label=org.testcontainers%3Dtrue&label=org.testcontainers.sessionId%3Dc9389a4b-2ee7-4ba0-adb2-b06947a682c8' to Ryuk
10:32:04.427 [testcontainers-ryuk] DEBUG org.testcontainers.utility.ResourceReaper - Received 'ACK' from Ryuk
10:32:04.428 [main] INFO org.testcontainers.DockerClientFactory - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
10:32:04.435 [main] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 15172ab10e1a6091506467c645264250319fbb3dd9ecc12ec4cebbfee5272425,<null>,true,<null>,<null>,<null>,<null>,{df,-P},<null>,<null>,com.github.dockerjava.core.exec.ExecCreateCmdExec@dc9876b
10:32:04.555 [tc-okhttp-stream-1865516976] DEBUG com.github.dockerjava.core.command.ExecStartResultCallback - STDOUT: Filesystem           1024-blocks    Used Available Capacity Mounted on
overlay              238798492  60830444 165768012  27% /
tmpfs                    65536         0     65536   0% /dev
tmpfs                  8197816         0   8197816   0% /sys/fs/cgroup
shm                      65536         0     65536   0% /dev/shm
/dev/sda2            238798492  60830444 165768012  27% /etc/resolv.conf
/dev/sda2            238798492  60830444 165768012  27% /etc/hostname
/dev/sda2            238798492  60830444 165768012  27% /etc/hosts
tmpfs                  1639564      3004   1636560   0% /run/docker.sock
        ✔ Docker environment should have more than 2GB free disk space
10:32:04.610 [main] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: ListImagesCmdImpl[imageNameFilter=<null>,showAll=false,filters=com.github.dockerjava.core.util.FiltersBuilder@0,execution=com.github.dockerjava.core.exec.ListImagesCmdExec@f627d13]
HI

java.lang.IllegalStateException: Mapped port can only be obtained after the container is started

	at org.testcontainers.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at org.testcontainers.containers.ContainerState.getMappedPort(ContainerState.java:107)
	at org.testcontainers.containers.DockerComposeContainer.getServicePort(DockerComposeContainer.java:450)
	at com.etracker.archy.componentTests.SubscribeTest.receiveWelcomeMessage(SubscribeTest.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255
```

My testcontainers.properties:

```
compose.container.image=docker/compose:1.24.0
ryuk.container.privileged=true
```

Why does the container not apply the wait strategy? It seems that the test method is immediately executed.
I am using java 11.

**Comment by bsideup** [comment]
> Mapped port can only be obtained after the container is started

This means that you should start the container / compose before trying to obtain the ports. It can be done manually (with `.start()`), or with `@ClassRule`/`@Testcontainers + @Container` if you're using JUnit 4/5 accordingly.

> at org.junit.runners.BlockJUnit4ClassRunner
> @Container

You're using Jupiter support (`@Container`) with JUnit 4 which obviously does not work. Replace `@Container` with `@ClassRule` and it should work.

**Comment by HaMatthias** [comment]
Resolved.
Thank you. Quite simple :+1:

**Comment by bsideup** [comment]
I will close the issue then :) Happy that it is resolved!
