### ISSUE TITLE
DockerComposeContainer does does not start containers from compose.yml

### ISSUE THREAD

**Issue by tmstff** [testcontainers/testcontainers-java#1893]
Hi,

I'm trying to use the docker compose module of Testcontainers, but until now without luck. No container seems to start. Here is my setup:

I have a tryout Spock Test:

```
package com.tarent.tryout

import org.testcontainers.containers.DockerComposeContainer
import org.testcontainers.containers.wait.strategy.Wait
import org.testcontainers.spock.Testcontainers
import spock.lang.Specification

@Testcontainers
class DockerComposeTryoutSpec extends Specification {

    public static final File composeFile = new File("src/test/resources/compose-test.yml")

    public static DockerComposeContainer environment =
            new DockerComposeContainer(composeFile)
                    .withExposedService("httpd_1", 80, Wait.forHttp("/"))

    def "can access apache"() {
        given:
        assert composeFile.exists()
        String url = "http://${environment.getServiceHost("httpd_1", 80)}:" +
                "${environment.getServicePort("httpd_1", 80)}"

        expect:
        url =~ /http:\/\/.*:\d+/

        when:
        HttpURLConnection connection = (HttpURLConnection) new URL(url).openConnection()
        connection.setRequestMethod("GET")
        String result = connection.getInputStream().text

        then:
        result.contains("It works!")
    }

}
```

When I run this test, I get:

```
java.lang.IllegalStateException: Mapped port can only be obtained after the container is started

	at org.testcontainers.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at org.testcontainers.containers.ContainerState.getMappedPort(ContainerState.java:107)
	at org.testcontainers.containers.DockerComposeContainer.getServicePort(DockerComposeContainer.java:450)
	at com.tarent.tryout.DockerComposeTryoutSpec.can access apache(DockerComposeTryoutSpec.groovy:21)
```

excerpt from build.gradle:

```
    implementation 'org.codehaus.groovy:groovy-all:2.5.7'

    testImplementation 'org.spockframework:spock-core:1.3-groovy-2.5'

    testImplementation 'org.testcontainers:testcontainers:1.12.1'

    testImplementation 'org.testcontainers:spock:1.12.1'
```

compose-test.yml:

```
version: '3'

services:
  httpd:
    image: "httpd"
```

which works by itself:

```
➜  resources git:(master) ✗ docker-compose -f compose-test.yml up
Creating network "resources_default" with the default driver
Creating resources_httpd_1_6d83e68752bf ... done
Attaching to resources_httpd_1_22cd0a24b5e2
httpd_1_22cd0a24b5e2 | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.20.0.2. Set the 'ServerName' directive globally to suppress this message
httpd_1_22cd0a24b5e2 | AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.20.0.2. Set the 'ServerName' directive globally to suppress this message
httpd_1_22cd0a24b5e2 | [Thu Sep 19 13:46:04.094145 2019] [mpm_event:notice] [pid 1:tid 140171944379520] AH00489: Apache/2.4.41 (Unix) configured -- resuming normal operations
httpd_1_22cd0a24b5e2 | [Thu Sep 19 13:46:04.095668 2019] [core:notice] [pid 1:tid 140171944379520] AH00094: Command line: 'httpd -D FOREGROUND'
```

Interestingly, this also happens when I supply an incorrect compose file name (no other error message). But you can see in the test that I made sure that the file really exists.

Also interesting is that actually apart from the ryuk container, no other container seems to start:

when I add ```Thread.sleep(100000)``` to the test before trying to get the port mapping and then check on the console, I see

```
➜  testcontainers-tryout git:(master) ✗ docker ps
CONTAINER ID        IMAGE                               COMMAND             CREATED             STATUS              PORTS                     NAMES
2a57083fccea        quay.io/testcontainers/ryuk:0.2.3   "/app"              14 seconds ago      Up 14 seconds       0.0.0.0:32786->8080/tcp   testcontainers-ryuk-28e3d86c-810b-4ec9-8d67-57ee8c9d6fcb
```

when I call ```environment.start()``` explicitly, I get:

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed

	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:290)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:272)
	at org.testcontainers.containers.ContainerisedDockerCompose.invoke(DockerComposeContainer.java:610)
	at org.testcontainers.containers.DockerComposeContainer.runWithCompose(DockerComposeContainer.java:230)
	at org.testcontainers.containers.DockerComposeContainer.createServices(DockerComposeContainer.java:174)
	at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:156)
	at com.tarent.tryout.DockerComposeTryoutSpec.can access apache(DockerComposeTryoutSpec.groovy:20)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:283)
	... 6 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:350)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:285)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 7 more
Caused by: java.lang.IllegalStateException: Container did not start correctly.
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:328)
	... 9 more
```

Any suggestions?

**Comment by CyborTronik** [comment]
It's little demotivating to have such error usability:
``````
java.lang.ExceptionInInitializerError
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
Caused by: java.lang.IllegalStateException: Container did not start correctly.
``````

**Comment by ravenblackdusk** [comment]
@tmstff I had the same problem and it seems you do have to `start` the `DockerComposeContainer` which the docs fail to mention. After doing that, it seems that your container failed to start before the default timeout(which I think is one minute).
have you tried `Wait.forHttp("/").withStartupTimeout(ofMinutes(10))`?

**Comment by tmstff** [comment]
@ravenblackdusk Thanx for your answer! I tried it out, but I still get
```
Container startup failed
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:290)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:272)
	at org.testcontainers.containers.ContainerisedDockerCompose.invoke(DockerComposeContainer.java:610)
	at org.testcontainers.containers.DockerComposeContainer.runWithCompose(DockerComposeContainer.java:230)
	at org.testcontainers.containers.DockerComposeContainer.createServices(DockerComposeContainer.java:174)
	at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:156)
	at IntegrationSpec.setupSpec(IntegrationSpec.groovy:22)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:283)
	... 6 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:350)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:285)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 7 more
Caused by: java.lang.IllegalStateException: Container did not start correctly.
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:328)
	... 9 more
```

**Comment by rnorth** [comment]
We normally emit logs (including container stdout/stderr) to aid in debugging this kind of situation. What do the logs, as opposed to stack traces, say?

There's an example [Logback config file](https://www.testcontainers.org/supported_docker_environment/logging_config/) which can be used as a reasonable baseline configuration, if you don't have one?

**Comment by CyborTronik** [comment]
Looks like the best way to go is just using clean docker-compose commands which makes no point in this library.

**Comment by kiview** [comment]
@tmstff 
Can you try to the Spock `@Shared` annotation instead of static modifier? Should make it work.

Calling `start()` is not required when using the Spock extension, but since we access fields by reflection in case of the extension, it might be possible we don't pick up static fields.

With regards to your other issue, please try out using `withLocalCompose(true)`.

**Comment by tmstff** [comment]
@kiview Thanks, I will try that out!

**Comment by tmstff** [comment]
@CyborTronik Thanks for your input, - but I'm not sure if I understand what you mean. Do you mean "use (command line) docker compose command instead of the test containers library?" And if you: why?

**Comment by tmstff** [comment]
@rnorth Good point, thank you! Sorry, somehow I missed reacting on your comment. I will try that out in case the suggestion by @kiview should not solve my problem.

**Comment by tmstff** [comment]
With the suggestion from @kiview it now works, issue can be closed :-) Thanks for all your help!
