### ISSUE TITLE
Unable to connect to ElasticsearchContainer from inside Docker

### ISSUE THREAD

**Issue by davismariotti** [testcontainers/testcontainers-java#1926]
My local environment:
- MacOS 10.14.6
- Docker Desktop 2.0.1.2
- Docker Engine 19.03.2
- Compose Engine 1.24.1
- Test containers 1.12.1

I'm trying to run a testcontainer with ElasticSearch inside a docker container for running integration tests on my project, but can't seem to get my test to connect to this container after following the steps from [here](https://www.testcontainers.org/supported_docker_environment/continuous_integration/dind_patterns/). Note that outside of a docker container in my local environment, everything has been working fine.

I'm running my tests with `docker run -it --rm -v $PWD:$PWD -w $PWD -v /var/run/docker.sock:/var/run/docker.sock --env testbot:68F75D8FD4C7003772C7E52B87B774F5 /bin/bash /testproject/build/wrapper.sh` where `testbot:68F75D8FD4C7003772C7E52B87B774F5` is an image I've built. wrapper.sh cleans, compiles my project and runs `sbt test` on the project.

The error I'm getting:
```[warn] o.t.u.RegistryAuthLocator - Failure when attempting to lookup auth config (dockerImageName: alpine:3.5, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory)
[warn] o.t.u.RegistryAuthLocator - Failure when attempting to lookup auth config (dockerImageName: quay.io/testcontainers/ryuk:0.2.3, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory)
        ?? Checking the system...
        ? Docker version should be at least 1.6.0
        ? Docker environment should have more than 2GB free disk space
[warn] o.t.u.RegistryAuthLocator - Failure when attempting to lookup auth config (dockerImageName: docker.elastic.co/elasticsearch/elasticsearch:7.1.1, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory)
[error] d.e.c.1.1] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://172.17.0.1:32911/ should return HTTP [200])
    at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:197)
    at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
    at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:675)
    at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:332)
    at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:285)
    at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
    at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:283)
    at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:272)
    at controllers.HomeControllerTest.setup(HomeControllerTest.java:56)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

The code running the test is inside a Play Framework app, newly created with `sbt new playframework/play-java-seed.g8` as documented [here](https://www.playframework.com/documentation/2.7.x/NewApplication).
```
package controllers;

import org.junit.BeforeClass;
import org.junit.Test;
import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.elasticsearch.ElasticsearchContainer;
import org.testcontainers.junit.jupiter.Testcontainers;
import play.Application;
import play.Logger;
import play.inject.guice.GuiceApplicationBuilder;
import play.mvc.Http;
import play.mvc.Result;
import play.test.WithApplication;

import static org.junit.Assert.assertEquals;
import static play.mvc.Http.Status.OK;
import static play.test.Helpers.GET;
import static play.test.Helpers.route;

@Testcontainers
public class HomeControllerTest extends WithApplication {
    
    @BeforeClass
    public static void setup() {
        GenericContainer elasticsearchContainer =
                new ElasticsearchContainer("docker.elastic.co/elasticsearch/elasticsearch:7.1.1")
                        .waitingFor(Wait.forHttp("/")
                                .forStatusCode(200));
        elasticsearchContainer.start();

    }

    @Override
    protected Application provideApplication() {
        return new GuiceApplicationBuilder().build();
    }

    @Test
    public void testIndex() {
        Logger.debug("Test start");
        Http.RequestBuilder request = new Http.RequestBuilder()
                .method(GET)
                .uri("/");

        Result result = route(app, request);
        assertEquals(OK, result.status());
        Logger.debug("Test finish");
    }

}
```

Full output logs are [here](https://hastebin.com/weqabunido.cs)

As far as I can tell, the container is starting correctly, just can't connect properly to it.

Things I've tried to resolve the issue:

- Tested the same setup, but instead using a Postgres testcontainer. This worked fine, connection was successful, tests passed.
- Using a GenericContainer and defining exposed ports manually, same error as above.
- Running `docker exec -it <container id> /bin/bash`, then curling the elastic search container that testcontainers made. It was running normally, so no issues connecting to the container from inside my testbot container.

Any ideas?

**Comment by bsideup** [comment]
> Tested the same setup, but instead using a Postgres testcontainer. This worked fine, connection was successful, tests passed.


Are you sure that Elasticsearch does not crash at startup? It is memory greedy and, if other containers work, may be the case

**Comment by pkrajanand** [comment]
Hi @davismariotti : did you get a solution for the problem?

I have a similar requirement to run the test maven tests within the docker container, that uses elastic-search-test-container with the following error
```
ping failed with configuration Environment variables, system properties and defaults. Resolved dockerHost=unix:///var/run/docker.sock due to org.rnorth.ducttape.TimeoutException: Timeout waiting for result with exception

org.rnorth.ducttape.TimeoutException: Timeout waiting for result with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:54) ~[duct-tape-1.0.8.jar:na]
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.ping(DockerClientProviderStrategy.java:183) [testcontainers-1.13.0.jar:na]
```
It works fine when running from outside the docker, though(same as your experience) !!

**Comment by rnorth** [comment]
@pkrajanand that looks like a quite different problem (the stack trace is different)

By the looks of it, your Docker daemon inside your container is not responding. I’d suggest checking that - try replacing your Java build with a `docker ps` invocation, for example.

**Comment by K-You** [comment]
Hi @davismariotti, I have the same issue, if you have resolved it i'm interested 😁 

Running from a docker, I have a timeout error when trying to reach the elastic container : 

```
16:54:27.346 [main] INFO  org.testcontainers.DockerClientFactory.client() @114 - Docker host IP address is 172.17.0.1
16:54:27.379 [main] INFO  org.testcontainers.DockerClientFactory.client() @122 - Connected to docker: 
  Server Version: 19.03.5
  API Version: 1.40
  Operating System: Docker Desktop
  Total Memory: 10984 MB
16:54:27.414 [main] WARN  org.testcontainers.utility.RegistryAuthLocator.lookupAuthConfig() @135 - Failure when attempting to lookup auth config (dockerImageName: quay.io/testcontainers/ryuk:0.2.3, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory)
16:54:28.523 [main] INFO  org.testcontainers.DockerClientFactory.client() @132 - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
16:54:28.723 [main] INFO  🐳 [container-remote.artifactory.aqme.ca/elasticsearch/elasticsearch-oss:6.7.2].<init>() @49 - Starting an elasticsearch container using [container-remote.artifactory.aqme.ca/elasticsearch/elasticsearch-oss:6.7.2]
16:54:28.731 [main] INFO  🐳 [container-remote.artifactory.aqme.ca/elasticsearch/elasticsearch-oss:6.7.2].tryStart() @334 - Creating container for image: container-remote.artifactory.aqme.ca/elasticsearch/elasticsearch-oss:6.7.2
16:54:28.731 [main] WARN  org.testcontainers.utility.RegistryAuthLocator.lookupAuthConfig() @135 - Failure when attempting to lookup auth config (dockerImageName: container-remote.artifactory.aqme.ca/elasticsearch/elasticsearch-oss:6.7.2, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory)
16:54:28.890 [main] INFO  🐳 [container-remote.artifactory.aqme.ca/elasticsearch/elasticsearch-oss:6.7.2].tryStart() @378 - Starting container with ID: de971392a1a4a5905b385bf38f35319504701582c39caf74483d348f57081df5
16:54:29.430 [main] INFO  🐳 [container-remote.artifactory.aqme.ca/elasticsearch/elasticsearch-oss:6.7.2].tryStart() @382 - Container container-remote.artifactory.aqme.ca/elasticsearch/elasticsearch-oss:6.7.2 is starting: de971392a1a4a5905b385bf38f35319504701582c39caf74483d348f57081df5
16:54:29.447 [main] INFO  org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady() @138 - /kind_dubinsky: Waiting for 120 seconds for URL: http://172.17.0.1:33311/
16:56:29.314 [main] ERROR 🐳 [container-remote.artifactory.aqme.ca/elasticsearch/elasticsearch-oss:6.7.2].tryStart() @405 - Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://172.17.0.1:33311/ should return HTTP 200)
        at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:197) ~[testcontainers-1.12.3.jar:?]

``` 

But when I run a `docker ps` in the meantime, I can see that the container is running 

```
docker ps
CONTAINER ID        IMAGE                                                                              COMMAND                  CREATED              STATUS              PORTS                                              NAMES
de971392a1a4        container-remote.artifactory.aqme.ca/elasticsearch/elasticsearch-oss:6.7.2   "/usr/local/bin/dock…"   46 seconds ago       Up 45 seconds       0.0.0.0:33311->9200/tcp, 0.0.0.0:33310->9300/tcp   kind_dubinsky
eb20e275b66d        quay.io/testcontainers/ryuk:0.2.3                                                  "/app"                   47 seconds ago       Up 46 seconds       0.0.0.0:33309->8080/tcp                            testcontainers-ryuk-50f54862-832b-4fd0-a65d-b7d702883a64
131ba768677c        d90d3cb6a6f9                                                                       "/usr/local/bin/mvn-…"   About a minute ago   Up 59 seconds                                                          agitated_bell
```

And I can curl the container without problem 

```
docker run -v $PWD:$PWD -w $PWD -v /var/run/docker.sock:/var/run/docker.sock container.artifactory.aqme.ca/ms/base/maven-builder-362/branch_master:latest curl http://172.17.0.1:33311/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   493  100   493    0     0  35376      0 --:--:-- --:--:-- --:--:-- 37923
{
  "name" : "BjZatWV",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "8rUvSgfmTsaX4ZcHyZJ8YQ",
  "version" : {
    "number" : "6.7.2",
    "build_flavor" : "oss",
    "build_type" : "docker",
    "build_hash" : "56c6e48",
    "build_date" : "2019-04-29T09:05:50.290371Z",
    "build_snapshot" : false,
    "lucene_version" : "7.7.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

I don't understand why the waitStrategy cannot reach the container, as it seems to have the right address :/

**Comment by einarjohnson** [comment]
having a very similar issue here. everything runs fine in IntelliJ but once I use mvn the wait for the Elasticsearch container sporadically fails. Any ideas/suggestions?

**Comment by rmolina10** [comment]
I also have the same problem. Any solution?
