### ISSUE TITLE
Exception 'Can find dockerfile' when running gadle test

### ISSUE THREAD

**Issue by yarafed** [testcontainers/testcontainers-java#1929]
When I execute tests from Intellij IDEA, docker runs successfully and all tests pass.
However, when I execute tests from gradle by command _gradle clean test_ I get the exception 'Dockerfile does not exist'.

My code:
``` 
@BeforeSuite
    public void runDocker() {
        int wireMockPort = 9999;
        int proxyPort = Integer.parseInt(applicationConfig.getPort());
        //Specifying host port
        Path path = Paths.get("serviceSetUp/Dockerfile").toAbsolutePath();
        Consumer<CreateContainerCmd> cmd = e -> e.withPortBindings(new PortBinding(Ports.Binding.bindPort(wireMockPort),
                new ExposedPort(wireMockPort)));
        ImageFromDockerfile image = new ImageFromDockerfile().withDockerfile(path);
        proxyContainer = new GenericContainer("wiremock:latest").withExposedPorts(wireMockPort).withCreateContainerCmdModifier(cmd)
                .waitingFor(Wait.forHttp("/health").forStatusCode(200));
        proxyContainer.start();
        Slf4jLogConsumer logConsumer = new Slf4jLogConsumer(log);
        proxyContainer.followOutput(logConsumer);
    }
```
Stacktrace:
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:290)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:272)
	at com.edunav.testing.BaseTest.runDocker(BaseTest.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: org.testcontainers.images.builder.ImageFromDockerfile@18e3614a
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1061)
	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:410)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:279)
	... 47 more
Caused by: java.lang.IllegalArgumentException: Dockerfile does not exist
	at com.github.dockerjava.core.command.BuildImageCmdImpl.withDockerfile(BuildImageCmdImpl.java:327)
	at com.github.dockerjava.core.command.BuildImageCmdImpl.withDockerfile(BuildImageCmdImpl.java:24)
	at org.testcontainers.images.builder.ImageFromDockerfile.lambda$configure$0(ImageFromDockerfile.java:142)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.testcontainers.images.builder.ImageFromDockerfile.configure(ImageFromDockerfile.java:142)
	at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:107)
	at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:37)
	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:27)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1059)
	... 49 more
```

**Comment by rnorth** [comment]
It seems like your working directory is different in between your IDEA run config and gradle. In Gradle, your code will probably be expecting your ‘serviceSetUp’ directory to sit next to (in the same directory as) build.gradle. 

Is that the case?

BTW, I’d really advise you not to bind the container port to a fixed host port as you’re doing - we deliberately don’t make it easy to do that, as it leads to test reproducibility/parallelisation issues. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yarafed** [comment]
@rnorth thank you so much for your response!
Yes, ‘serviceSetUp’ folder is the same directory as build.gradle
Could you, please, tell, if you have other ideas?

**Comment by martinda** [comment]
I too have this issue, I hope with this example it will give @yarafed more ideas for locating the custom Dockerfile. The test points to the right file, the file exists, but unfortunately it fails with almost the same stacktrace:
```groovy
@Testcontainers
class BasicTest extends Specification {

    // File originally under src/test/resources/Dockerfile
    // Gradle copies it to build/test/resources as it launches the test
    // The next line gets it from build/test/resources
    File dockerfile = new File(this.class.getClassLoader().getResource("Dockerfile").getFile())

    @Rule
    public GenericContainer myContainer = new GenericContainer(
        new ImageFromDockerfile()
            .withDockerfilePath(dockerfile.getAbsolutePath()))
```
Then: `gradle test`

Stacktrace:
```
BasicTest > jenkins is accessible FAILED
    org.testcontainers.containers.ContainerLaunchException: Container startup failed
        Caused by:
        org.testcontainers.containers.ContainerFetchException: Can't get Docker image: org.testcontainers.images.builder.ImageFromDockerfile@1bb5ab57
            Caused by:
            com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Cannot locate specified Dockerfile: /home/martinda/myproject/build/resources/test/Dockerfile"}
```
The file does exist, and so I am confused by the error message.

**Comment by martinda** [comment]
Changing the code to use `withDockerfile(dockerfile.toPath())` fixes my issue.
