### ISSUE TITLE
How to configuration to connection docker daemon in VMware Workstation on Windows?

### ISSUE THREAD

**Issue by itning** [testcontainers/testcontainers-java#1945]
1. I have centos7 system in vmware
2. I installed docker in centos7
3. I got an exception when I run this code
```java
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.testcontainers.containers.GenericContainer;

/**
 * @author itning
 * @date 2019/7/3 8:59
 */
public class TestRest {

    // rule {
    @Rule
    public GenericContainer redis = new GenericContainer<>("redis:5.0.3-alpine")
            .withExposedPorts(6379);
    // }


    @Before
    public void setUp() {
        System.out.println(System.getenv("DOCKER_HOST"));
        String address = redis.getContainerIpAddress();
        Integer port = redis.getFirstMappedPort();

        System.out.println(address);
        System.out.println(port);
    }

    @Test
    public void testSimplePutAndGet() {

    }
}
```
```
15:08:35.711 [main] DEBUG o.t.u.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/C:/Users/a/.testcontainers.properties
15:08:36.738 [ducttape-0] DEBUG o.t.d.DockerClientProviderStrategy - Pinging docker daemon...
15:08:37.017 [ducttape-0] DEBUG c.g.d.core.command.AbstrDockerCmd - Cmd: org.testcontainers.dockerclient.transport.okhttp.OkHttpDockerCmdExecFactory$1@7e01aff8
15:08:46.747 [main] DEBUG o.t.d.DockerClientProviderStrategy - NpipeSocketClientProviderStrategy: failed with exception InvalidConfigurationException (ping failed). Root cause TimeoutException (null)
15:08:46.750 [ducttape-2] DEBUG o.t.d.DockerClientProviderStrategy - Pinging docker daemon...
15:08:46.751 [ducttape-2] DEBUG c.g.d.core.command.AbstrDockerCmd - Cmd: org.testcontainers.dockerclient.transport.okhttp.OkHttpDockerCmdExecFactory$1@c1d3d36
15:08:51.276 [ducttape-2] DEBUG o.t.d.DockerClientProviderStrategy - Pinging docker daemon...
15:08:51.276 [ducttape-2] DEBUG c.g.d.core.command.AbstrDockerCmd - Cmd: org.testcontainers.dockerclient.transport.okhttp.OkHttpDockerCmdExecFactory$1@4591ba6c
15:08:51.752 [main] DEBUG o.t.d.DockerClientProviderStrategy - WindowsClientProviderStrategy: failed with exception TimeoutException (Timeout waiting for result with exception). Root cause ConnectException (Connection refused: connect)
15:08:51.753 [main] ERROR o.t.d.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
15:08:51.754 [main] ERROR o.t.d.DockerClientProviderStrategy -     NpipeSocketClientProviderStrategy: failed with exception InvalidConfigurationException (ping failed). Root cause TimeoutException (null)
15:08:51.754 [main] ERROR o.t.d.DockerClientProviderStrategy -     WindowsClientProviderStrategy: failed with exception TimeoutException (Timeout waiting for result with exception). Root cause ConnectException (Connection refused: connect)
15:08:51.754 [main] ERROR o.t.d.DockerClientProviderStrategy - As no valid configuration was found, execution cannot continue

java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration

	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$3(DockerClientProviderStrategy.java:158)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:150)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:111)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:175)
	at top.itning.TestRest.<init>(TestRest.java:15)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:217)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:266)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

I already config docker host in ``C:/Users/a/.testcontainers.properties``
```
DOCKER_HOST=tcp://dockervm:2376
```

**Comment by bsideup** [comment]
> I already config docker host in C:/Users/a/.testcontainers.properties

You should set it as an environment variable, not property
