### ISSUE TITLE
Error when exists container image without tag

### ISSUE THREAD

**Issue by mariomourao** [testcontainers/testcontainers-java#198]
I caught the following exception:

```
org.testcontainers.containers.ContainerFetchException: Can't get Docker image name from org.testcontainers.images.RemoteDockerImage@4463d9d3

	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:674)
	at org.testcontainers.containers.GenericContainer.setDockerImageName(GenericContainer.java:662)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:139)
	at org.testcontainers.containers.FixedHostPortGenericContainer.<init>(FixedHostPortGenericContainer.java:16)
	at eu.decsis.robots.MessagingServiceTest.$spock_initializeSharedFields(MessagingServiceTest.groovy:30)
Caused by: java.lang.NullPointerException
	at java.util.Collections.addAll(Collections.java:5400)
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:59)
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:21)
	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:27)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:672)
	... 4 more
```

after some tests, I found the reason, I had a container image without tag.

**Comment by outofcoffee** [comment]
@mariomourao this is fixed in https://github.com/testcontainers/testcontainers-java/commit/cd15becf1ef907ad41843554aef5924a9a1b1b3b but there's a related issue #199
