### ISSUE TITLE
Connection Refused while trying to connect MariaDB

### ISSUE THREAD

**Issue by formsworld** [testcontainers/testcontainers-java#2028]
Hi,

Not able to execute the Query. 
I am using Maria  DB test container. while i am trying to execute query i am facing connection refused error.

Details:
@Test
    public void testSimple() throws SQLException {
		
        MariaDBContainer mariadb = new MariaDBContainer();
        mariadb.addEnv("MYSQL_ROOT_PASSWORD", "root");
        mariadb.withDatabaseName("mariadbdkr");
        mariadb.start();
        

        try {
            mariadb.withInitScript("jdbc:tc:mariadb:10:3:6///mariadbdkr?TC_INITSCRIPT=file:src/main/resources/init_mariadb.sql");
            
            ResultSet resultSet = performQuery(mariadb, "SELECT count(*) from bar" );
            int resultSetInt = resultSet.getInt(1);

            Assert.assertEquals(0, resultSetInt);
        } catch (Exception ex) {
        	System.out.println("Execution  - >" + ex.getMessage());
        }
        
        finally {
            mariadb.stop();
        }

Base Class

private final Set<HikariDataSource> datasourcesForCleanup = new HashSet<>();

    ResultSet performQuery(JdbcDatabaseContainer container, String sql) throws SQLException {
        DataSource ds = getDataSource(container);
        Statement statement = ds.getConnection().createStatement();
        statement.execute(sql);
        ResultSet resultSet = statement.getResultSet();

        resultSet.next();
        return resultSet;
    }

    DataSource getDataSource(JdbcDatabaseContainer container) {
        HikariConfig hikariConfig = new HikariConfig();
        hikariConfig.setJdbcUrl(container.getJdbcUrl());
        hikariConfig.setUsername(container.getUsername());
        hikariConfig.setPassword(container.getPassword());
        hikariConfig.setDriverClassName(container.getDriverClassName());

        final HikariDataSource dataSource = new HikariDataSource(hikariConfig);
        datasourcesForCleanup.add(dataSource);

        return dataSource;
    }

    @After
    public void teardown() {
        datasourcesForCleanup.forEach(HikariDataSource::close);
    }

init_mariadb.sql
CREATE TABLE bar (
  foo VARCHAR(255)
);

Error
======

02:50:20.960 [main] INFO 🐳 [mariadb:10.3.6] - Container mariadb:10.3.6 started in PT11.542S
02:50:25.965 [main] DEBUG com.zaxxer.hikari.HikariConfig - Driver class org.mariadb.jdbc.Driver found in Thread context class loader sun.misc.Launcher$AppClassLoader@27973e9b
02:50:25.968 [main] DEBUG com.zaxxer.hikari.HikariConfig - HikariPool-1 - configuration:
02:50:25.973 [main] DEBUG com.zaxxer.hikari.HikariConfig - allowPoolSuspension.............false
02:50:25.973 [main] DEBUG com.zaxxer.hikari.HikariConfig - autoCommit......................true
02:50:25.973 [main] DEBUG com.zaxxer.hikari.HikariConfig - catalog.........................none
02:50:25.973 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionInitSql...............none
02:50:25.973 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTestQuery.............none
02:50:25.973 [main] DEBUG com.zaxxer.hikari.HikariConfig - connectionTimeout...............30000
02:50:25.973 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSource......................none
02:50:25.973 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceClassName.............none
02:50:25.973 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceJNDI..................none
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - dataSourceProperties............{password=<masked>}
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - driverClassName................."org.mariadb.jdbc.Driver"
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckProperties...........{}
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - healthCheckRegistry.............none
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - idleTimeout.....................600000
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - initializationFailTimeout.......1
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - isolateInternalQueries..........false
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - jdbcUrl.........................jdbc:mariadb://localhost:32869/mariadbdkr
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - leakDetectionThreshold..........0
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - maxLifetime.....................1800000
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - maximumPoolSize.................10
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricRegistry..................none
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - metricsTrackerFactory...........none
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - minimumIdle.....................10
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - password........................<masked>
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - poolName........................"HikariPool-1"
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - readOnly........................false
02:50:25.974 [main] DEBUG com.zaxxer.hikari.HikariConfig - registerMbeans..................false
02:50:25.975 [main] DEBUG com.zaxxer.hikari.HikariConfig - scheduledExecutor...............none
02:50:25.975 [main] DEBUG com.zaxxer.hikari.HikariConfig - schema..........................none
02:50:25.975 [main] DEBUG com.zaxxer.hikari.HikariConfig - threadFactory...................internal
02:50:25.975 [main] DEBUG com.zaxxer.hikari.HikariConfig - transactionIsolation............default
02:50:25.975 [main] DEBUG com.zaxxer.hikari.HikariConfig - username........................"test"
02:50:25.975 [main] DEBUG com.zaxxer.hikari.HikariConfig - validationTimeout...............5000
02:50:25.976 [main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
02:50:25.987 [main] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.mariadb.jdbc.MariaDbConnection@306e95ec
02:50:25.988 [main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
**Execution - >(conn=9) Table 'mariadbdkr.bar' doesn't exist**
02:50:25.994 [main] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 6b57aedb78ca4028cba5e213a265fa23100f3335a408ccb649c42dcd2e530ce4,false,com.github.dockerjava.core.exec.InspectContainerCmdExec@17497425
02:50:25.995 [main] DEBUG com.github.dockerjava.core.exec.InspectContainerCmdExec - GET: OkHttpWebTarget(okHttpClient=org.testcontainers.shaded.okhttp3.OkHttpClient@351d00c0, baseUrl=http://docker.socket/, path=[/containers/6b57aedb78ca4028cba5e213a265fa23100f3335a408ccb649c42dcd2e530ce4/json], queryParams={})
02:50:25.998 [main] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 6b57aedb78ca4028cba5e213a265fa23100f3335a408ccb649c42dcd2e530ce4,<null>,com.github.dockerjava.core.exec.KillContainerCmdExec@31fa1761
02:50:26.088 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=1, active=1, idle=0, waiting=0)
02:50:26.115 [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Failed to create/setup connection: Could not connect to address=(host=localhost)(port=32869)(type=master) : Could not connect to localhost:32869 : unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
02:50:26.118 [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Cannot acquire connection from data source
java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=32869)(type=master) : Could not connect to localhost:32869 : unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1241)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:610)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:142)
	at org.mariadb.jdbc.Driver.connect(Driver.java:86)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to localhost:32869 : unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:87)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:524)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1236)
	... 14 common frames omitted
Caused by: java.io.EOFException: unexpected end of stream, read 0 bytes from 4 (socket was closed by server)
	at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacketArray(StandardPacketInputStream.java:243)
	at org.mariadb.jdbc.internal.io.input.StandardPacketInputStream.getPacket(StandardPacketInputStream.java:212)
	at org.mariadb.jdbc.internal.com.read.ReadInitialHandShakePacket.<init>(ReadInitialHandShakePacket.java:90)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:480)
	... 15 common frames omitted
02:50:26.369 [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Cannot acquire connection from data source
java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=32869)(type=master) : Socket fail to connect to host:localhost, port:32869. Connection refused (Connection refused)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1241)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:610)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:142)
	at org.mariadb.jdbc.Driver.connect(Driver.java:86)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:localhost, port:32869. Connection refused (Connection refused)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:87)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:218)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:474)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1236)
	... 14 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:213)
	... 16 common frames omitted
02:50:26.745 [HikariPool-1 connection adder] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Cannot acquire connection from data source
java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=32869)(type=master) : Socket fail to connect to host:localhost, port:32869. Connection refused (Connection refused)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1241)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:610)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:142)
	at org.mariadb.jdbc.Driver.connect(Driver.java:86)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:713)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:localhost, port:32869. Connection refused (Connection refused)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:241)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.connException(ExceptionMapper.java:87)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:218)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:474)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1236)
	... 14 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:213)
	... 16 common frames omitted
02:50:27.107 [main] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 6b57aedb78ca4028cba5e213a265fa23100f3335a408ccb649c42dcd2e530ce4,false,com.github.dockerjava.core.exec.InspectContainerCmdExec@957e06
02:50:27.107 [main] DEBUG com.github.dockerjava.core.exec.InspectContainerCmdExec - GET: OkHttpWebTarget(okHttpClient=org.testcontainers.shaded.okhttp3.OkHttpClient@351d00c0, baseUrl=http://docker.socket/, path=[/containers/6b57aedb78ca4028cba5e213a265fa23100f3335a408ccb649c42dcd2e530ce4/json], queryParams={})
02:50:27.111 [main] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 6b57aedb78ca4028cba5e213a265fa23100f3335a408ccb649c42dcd2e530ce4,true,true,com.github.dockerjava.core.exec.RemoveContainerCmdExec@23c30a20
02:50:27.233 [main] DEBUG org.testcontainers.utility.ResourceReaper - Removed container and associated volume(s): mariadb:10.3.6
02:50:27.234 [main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
02:50:27.234 [main] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Before shutdown stats (total=1, active=1, idle=0, waiting=0)
02:50:27.313 [main] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - After shutdown stats (total=0, active=0, idle=0, waiting=0)
02:50:27.313 [main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.

POM.xml
<dependency>
			<groupId>com.zaxxer</groupId>
			<artifactId>HikariCP</artifactId>
			<version>3.4.1</version>
		</dependency>
		<dependency>
			<groupId>org.mariadb.jdbc</groupId>
			<artifactId>mariadb-java-client</artifactId>
			<version>2.5.1</version>
		</dependency>

Please correct me, what i am missing here.

Thanks in advance,,

**Comment by SaltOfTheFlame** [comment]
I get same exception while working on MariaDB
