### ISSUE TITLE
NullPointer in ComposeServiceWaitStrategyTarget

### ISSUE THREAD

**Issue by LukasBroetje** [testcontainers/testcontainers-java#2069]
I may found a bug in connection with the waitingFor() method of the DockerComposeContainer class. 

We try to enable remote debugging in or working environment. 

We have opened one port for the service: 8080
To enable remote debugging we open another port: 5000.

In the compose file it looks like this:
```
ports:
      - "8080:8080"
      - "5000:5000"
```
Before adding remote debugging we waited for the service like this:
```java
Wait.forHttp("").forStatusCodeMatching(statusCodeMatcher).withStartupTimeout(TIMEOUT));
```
The waiting worked there, because there was just one port and it selected that one port. After adding another port, it just randomly selected one of the two ports. Problem was, that the statusCodeMather does not work on the remote debugging port. But we need it to ensure things were running like they suppose to.

To wait on the specific port 8080, we added the method forPort(). Now we wait like this:
```java
Wait.forHttp("").forPort(service.port).forStatusCodeMatching(statusCodeMatcher).withStartupTimeout(TIMEOUT));
```
The service port looks like following:
```java
SPRINGIO("springio", 8080),
```
And that's where the bug happens. 
In the ComposeServiceWaitStrategyTarget a NullPointer is thrown: 
```
java.lang.RuntimeException: java.lang.NullPointerException

	at org.rnorth.ducttape.timeouts.Timeouts.callFuture(Timeouts.java:68)
	at org.rnorth.ducttape.timeouts.Timeouts.doWithTimeout(Timeouts.java:60)
	at org.testcontainers.containers.wait.strategy.WaitAllStrategy.waitUntilReady(WaitAllStrategy.java:53)
	at org.testcontainers.containers.DockerComposeContainer.waitUntilServiceStarted(DockerComposeContainer.java:202)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at org.testcontainers.containers.DockerComposeContainer.waitUntilServiceStarted(DockerComposeContainer.java:182)
	at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:158)
	at org.testcontainers.containers.DockerComposeContainer.starting(DockerComposeContainer.java:125)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NullPointerException
	at org.testcontainers.containers.ComposeServiceWaitStrategyTarget.getMappedPort(ComposeServiceWaitStrategyTarget.java:50)
	at java.util.Optional.map(Optional.java:215)
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:125)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.wait.strategy.WaitAllStrategy.waitUntilNestedStrategiesAreReady(WaitAllStrategy.java:61)
	at org.testcontainers.containers.wait.strategy.WaitAllStrategy.lambda$waitUntilReady$0(WaitAllStrategy.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I run it with maven and in the test phase the test fails.
I have made a small example project to recreate the bug, you can find it here:
https://github.com/LukasBroetje/testTestcontainers

**Comment by maxhomann** [comment]
We have the same problem. The mapped ports seem to be empty although they are explicitly exposed in the docker-compose.yml

**Comment by bsideup** [comment]
Exposing the ports in docker-compose.yml is not enough, you need to use `withExposedService`. You will find some examples here:
https://www.testcontainers.org/modules/docker_compose/

**Comment by LukasBroetje** [comment]
Thank you, that fixed the NullPointer for me. But now i'm running into an other error:
After one IntegrationTest run successfully, i get this error:
Aborting attempt to link to container j4hupdws2x8n_(containername)_1 as it is not running. The problem here is, that this container was used in the first test. So he uses the old container, which was removed.  
And for the 2nd test this one j4hupd5nkw4a_(containername)_1 is being created, but not used, instead the container j4hupdws2x8n_(containername)_1.

This is really confusing. Testcontainers tries to use an removed container.

**Comment by LukasBroetje** [comment]
I found another potential problem the docker compose module. 
When i use the compose module and the forPort() method of HttpWaitStrategy, testcontainers generates a new port instead of the port given by the forPort() method. 
I debugged it and the optional for the port is set, but then testcontainers generates a new port and does not take the given port. 

Is it intended to use the docker compose module method withExposedService() and the forPort() method or just one of both?

**Comment by tgeens** [comment]
> Exposing the ports in docker-compose.yml is not enough, you need to use withExposedService. You will find some examples here: https://www.testcontainers.org/modules/docker_compose/

Isn't that a totally different use case ? From the docs:

> Note that it is not necessary to define ports to be exposed in the YAML file; this would inhibit reuse/inclusion of the file in other contexts. Instead, Testcontainers will spin up a small 'ambassador' container, which will proxy between the Compose-managed containers and ports that are accessible to your tests. This is done using a separate, minimal container that runs socat as a TCP proxy.

That is exactly what the `getServiceHost(serviceName, servicePort)` and `getServicePort(serviceName, servicePort)` provides - access to ports exposed for tests via `withExposedService`

But compose files can expose services on random ports in a production context too! (They would get registered in a service catalog like Consul)

I don't want or need an 'ambassador' container to proxy this port, I really want to find out what the mapped port is.

The information is actually available through the `ContainerState.getMappedPort(int originalPort)` default method implementation. It's just that `ComposeServiceWaitStrategyTarget` overrides the default implementation, without considering the use case described above ?

**Comment by pontus-eliason** [comment]
In my application the main endpoint is running on port 8080, but the status check endpoint is running on 9090. So I want to expose the service on 8080, but I want to do the liveness check on port 9090. I don't see how I could do that as things currently stand?
