### ISSUE TITLE
Can not connect to Ryuk error.

### ISSUE THREAD

**Issue by rashmi-ibm** [testcontainers/testcontainers-java#2093]
Getting the below error when running the tests of infinispan on ppc64le Rhel vm.

Error log:-
java.lang.IllegalStateException: Can not connect to Ryuk
        at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:150)
        at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:131)
        at org.infinispan.server.test.ContainerInfinispanServerDriver.getDockerBridgeAddress(ContainerInfinispanServerDriver.java:70)
        at org.infinispan.server.test.ContainerInfinispanServerDriver.<init>(ContainerInfinispanServerDriver.java:64)
        at org.infinispan.server.test.ServerRunMode$2.newDriver(ServerRunMode.java:17)
        at org.infinispan.server.test.LazyInfinispanServerDriver.get(LazyInfinispanServerDriver.java:23)
        at org.infinispan.server.test.InfinispanServerRule.getServerDriver(InfinispanServerRule.java:52)

**Comment by bsideup** [comment]
Hi @rashmi-ibm,

Only Linux x64 containers architecture is supported by Testcontainers at the moment.
Windows containers or ppc64le won't work.
