### ISSUE TITLE
NullPointerException when followOutput() called before start()

### ISSUE THREAD

**Issue by findepi** [testcontainers/testcontainers-java#2223]
```
container.followOutput(new Slf4jLogConsumer(org.slf4j.LoggerFactory.getLogger("...")));
container.start();
```

### Observed

```
Exception in thread "main" java.lang.NullPointerException: containerId was not specified
	at org.testcontainers.shaded.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
	at com.github.dockerjava.core.command.LogContainerCmdImpl.withContainerId(LogContainerCmdImpl.java:78)
	at com.github.dockerjava.core.command.LogContainerCmdImpl.<init>(LogContainerCmdImpl.java:38)
	at com.github.dockerjava.core.DockerClientImpl.logContainerCmd(DockerClientImpl.java:364)
	at org.testcontainers.dockerclient.AuditLoggingDockerClient.logContainerCmd(AuditLoggingDockerClient.java:23)
	at org.testcontainers.utility.LogUtils.attachConsumer(LogUtils.java:88)
	at org.testcontainers.utility.LogUtils.followOutput(LogUtils.java:36)
	at org.testcontainers.utility.LogUtils.followOutput(LogUtils.java:51)
	at org.testcontainers.containers.Container.followOutput(Container.java:391)
```

### Expected

`followOutput` should accept the log consumer before `start()` is called.
`start()` is blocking, so calling `followOutput` seems like the right way to install the log consumer so it can get logs during startup phase too.

**Comment by bsideup** [comment]
I think the exception's message is self explanatory. You cannot get the logs of a non-started container.

If you want to provide a consumer at setup time, use `withLogConsumer`.

**Comment by findepi** [comment]
Thanks for the advice. 

BTW message is explanatory enough to convey "this doesn't work".
to me, if it was an IllegalStateException, it would also convey "this intentionally doesn't work".

**Comment by yeroc** [comment]
This messed me up as well.  I wonder if it would be worth splitting the setup methods into a separate Builder-style API so the setup functions are separated from the runtime methods?

**Comment by bsideup** [comment]
@yeroc 
We're working on it :) In fact, last month we had a very productive hackathon with @rnorth where we prototyped such API. Stay tuned!

**Comment by yeroc** [comment]
@bsideup Awesome!  Look forward to seeing it.  Regards, Corey

**Comment by renannprado** [comment]
@bsideup is the API now available...? I'm in the same situation.

**Comment by sebialex** [comment]
> I think the exception's message is self explanatory. You cannot get the logs of a non-started container.
> 
> If you want to provide a consumer at setup time, use `withLogConsumer`.

This should be handled by the builder pattern, there would be no followOutput on a builder, but the withLogConsumer would, leaving followOutput to only be available to the built instance. No confusion.

**Comment by FelixZY** [comment]
I found this issue after having the same issue myself. The solution is fairly obvious in hindsight but maybe the docs at https://java.testcontainers.org/features/container_logs/#streaming-container-output-to-an-slf4j-logger could be made a little clearer?
