### ISSUE TITLE
Display name for GenericContainer

### ISSUE THREAD

**Issue by findepi** [testcontainers/testcontainers-java#2246]
When using regular containers, the image name is usually sufficient for identifying which container given log line is about.
However, when using 2+ `GenericContainer` instances with same image, it's no longer so:

```
2020-01-13T13:32:45.298+0100	INFO	testcontainers-lifecycle-2	🐳 [centos:7]	Creating container for image: centos:7
2020-01-13T13:32:45.297+0100	INFO	testcontainers-lifecycle-1	🐳 [centos:7]	Creating container for image: centos:7
2020-01-13T13:32:45.297+0100	INFO	testcontainers-lifecycle-0	🐳 [centos:7]	Creating container for image: centos:7
...
2020-01-13T13:37:46.946+0100	ERROR	testcontainers-lifecycle-1	🐳 [centos:7]	Could not start container
java.lang.IllegalStateException: Container exited with code 1
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:457)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:317)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:315)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:302)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Neither the log line, nor the exception provide information which container failed.

**Comment by findepi** [comment]
Proposed solutions:

1. mention `command` besides `image` in log messages

2. provide optional "display name" property (defaulting to image name), that will be used in logging.

I offer to work on this, but I'd like to hear maintainers' preferences first.

**Comment by findepi** [comment]
.

**Comment by findepi** [comment]
I have only "Comment" button available. How can i reopen?

**Comment by bsideup** [comment]
@findepi I reopened it for you :)

**Comment by bsideup** [comment]
@findepi we're talking only about the logs, right? Not container's name?

**Comment by findepi** [comment]
@bsideup  Yes, this issue is about the logs only.

**Comment by findepi** [comment]
However, if we allow configuring container name (which would be nice in itself), this could be used in logging too.

**Comment by findepi** [comment]
.

**Comment by findepi** [comment]
.

**Comment by bedla** [comment]
PR here https://github.com/testcontainers/testcontainers-java/pull/11367
