### ISSUE TITLE
Spring Boot Tests with JUnit5 Jupiter and Shared Containers

### ISSUE THREAD

**Issue by KaiStapel** [testcontainers/testcontainers-java#2290]
Currently, a typical test setup with Spring Boot tests and shared containers does not work anymore with JUnit 5: Using static testcontainers with Spring Boot's `ApplicationContextInitializer` to configure the server's ports in the Spring context.

The problem is that the Spring application context gets initialized during Jupiter extension's post processing while testcontainers are started during before all callbacks. The latter happens after post processing. 

See 
https://github.com/junit-team/junit5/blob/c9ae6e261550481362f17d21e88137a8c71fc7c8/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassBasedTestDescriptor.java#L184
vs.
https://github.com/junit-team/junit5/blob/c9ae6e261550481362f17d21e88137a8c71fc7c8/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/ClassBasedTestDescriptor.java#L189

One approach to solve this could be to start the testcontainers also during post processing (`TestInstancePostProcesso#postProcessTestInstancer`)

Then the only remaining problem would be to ensure that the `TestcontainersExtension` always gets created before the `SpringExtension`.

What do you think?

**Comment by holiakho** [comment]
Hi, did you try to put ```@TestInstance(TestInstance.Lifecycle.PER_CLASS)``` annotation on your test class?
This should allow you to create BeforeAll/AfterAll as non-static methods.

**Comment by KaiStapel** [comment]
Hi, yes I did. That is exactly how I came accross this problem.

**Comment by KaiStapel** [comment]
I updated the initial request with an example that shows the problem.

**Comment by fullkomnun** [comment]
Two possible workarounds I can think of:
1. [if makes sense] Use the [Singleton Container Pattern](https://www.testcontainers.org/test_framework_integration/manual_lifecycle_control/).
2. Explicitly start the container in 'initialize' and make it a reusable container as explained [here](https://github.com/testcontainers/testcontainers-java/pull/1781) if applicable (will not currently work for a docker-compose container for instance).

**Comment by bsideup** [comment]
it doesn't have to be marked as reusable if you only need to use the same container between the tests. Reusable Containers feature is for reusing containers between the test runs (think running `mvn test` twice)

**Comment by bsideup** [comment]
@KaiStapel you can remove `@Container` from `postgreSQLContainer` and call `postgreSQLContainer.start()` in `Initializer`.

Also, in your particular example, you don't need all of it, just use the JDBC URL support:
https://www.testcontainers.org/modules/databases/#database-containers-launched-via-jdbc-url-scheme

**Comment by KaiStapel** [comment]
@fullkomnun  and @bsideup  Thanks for proposing these workarounds. We were already using the singleton container pattern to make it work.

Still, imo, this ticket makes sense to fix the [TestcontainersExtension](https://github.com/testcontainers/testcontainers-java/blob/master/modules/junit-jupiter/src/main/java/org/testcontainers/junit/jupiter/TestcontainersExtension.java) to work for shared containers with JUnit5 or at least mention its limitations in [the documentation](https://www.testcontainers.org/test_framework_integration/junit_5/).

**Comment by byrd-railroad19** [comment]
Hi all.  I would support @KaiStapel's position here.  I ran down his same path trying to add `@TestInstance(TestInstance.Lifecycle.PER_CLASS)` to class this morning.  The setup is somewhat expensive. It would be nice to execute it once.

The order dependence between the extensions is a big down side, but I don't see an easy way around that.

**Comment by bsideup** [comment]
Can you try https://spring.io/blog/2020/03/27/dynamicpropertysource-in-spring-framework-5-2-5-and-spring-boot-2-2-6 ?

**Comment by yanivnahoum** [comment]
@bsideup I tried your suggestion and still get the same exception. The test continues and refreshes the context **after** waiting for db to be ready, so it succeeds. But it would be nice if the context were initialized for the first time only once the db is ready.

**Comment by bsideup** [comment]
@yanivnahoum 

>  But it would be nice if the context were initialized for the first time only once the db is ready.

That's how it works already. Please check your setup (and share a reproducer otherwise)

**Comment by yanivnahoum** [comment]
Thanks @bsideup, here you go:

```java
@SpringBootTest
@Testcontainers
class MySqlTest {

    @Container
    private static final MySQLContainer<?> mySqlContainer = new MySQLContainer<>("mysql:8.0.20");

    static {
        // mySqlContainer.start();
    }

    @DynamicPropertySource
    static void mySqlProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", mySqlContainer::getJdbcUrl);
        registry.add("spring.datasource.username", mySqlContainer::getUsername);
        registry.add("spring.datasource.password", mySqlContainer::getPassword);
    }

    @Test
    void test(@Autowired Environment env) {
        System.out.println("#test - spring.datasource.url=" + env.getProperty("spring.datasource.url"));
    }
}
```

This results in an exception with the following root cause:
```
java.lang.IllegalStateException: Mapped port can only be obtained after the container is started
	at org.testcontainers.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at org.testcontainers.containers.ContainerState.getMappedPort(ContainerState.java:141)
	at org.testcontainers.containers.MySQLContainer.getJdbcUrl(MySQLContainer.java:73)
	at org.springframework.test.context.support.DynamicValuesPropertySource.getProperty(DynamicValuesPropertySource.java:43)
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:85)
	at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:62)
	at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:535)
	at org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$EmbeddedDatabaseCondition.hasDataSourceUrlProperty(DataSourceAutoConfiguration.java:147)
	at org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$EmbeddedDatabaseCondition.getMatchOutcome(DataSourceAutoConfiguration.java:130)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
```

after which the context loads **again**, the properties are set correctly and the test passes

**Comment by bsideup** [comment]
@yanivnahoum please share full example (with imports).

**Comment by yanivnahoum** [comment]
@bsideup I edited the comment above

**Comment by bsideup** [comment]
@yanivnahoum I just tried your example and got a successful result:
```
#test - spring.datasource.url=jdbc:postgresql://localhost:33492/test?loggerLevel=OFF
```

Have you tried running it? Can you share a full project that reproduces the issue?

**Comment by yanivnahoum** [comment]
@bsideup you switched to Postgres? Anyway, in my example, the test also succeeds and prints the url, but only after the exception stated above occurs. Does the same happen to you?

**Comment by bsideup** [comment]
@yanivnahoum I did (I only had postgres module on classpath), but it does not change anything

> Anyway, in my example, the test also succeeds and prints the url, but only after the exception stated above occurs. Does the same happen to you?

No, I did not get any exception in the logs.

**Comment by yanivnahoum** [comment]
@bsideup then I'll create a repo with just that example and share it

**Comment by KaiStapel** [comment]
Please note that this ticket is only about the problem when adding `@TestInstance(TestInstance.Lifecycle.PER_CLASS)` on the test class. Without it everything seems to work fine and as expected (including only starting the container once).

**Comment by yanivnahoum** [comment]
While trying to create a minimal example to reproduce the issue, I found the culprit: [`org.springframework.cloud.contract.wiremock.WireMockTestExecutionListener`](https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockTestExecutionListener.java#L41) from spring-cloud-contract-wiremock. It forces the application context to load before the tc db is ready....
@bsideup thanks for your help!

**Comment by frankjkelly** [comment]
This is an important issue - any chance it might have been fixed or addressed in a more recent release 
I am seeing it with 
SpringBoot 2.3.0
TestContainers 1.14.3

using both
1) ```PostgreSQLContainer```
2) ```DockerComposeContainer```

**Comment by bsideup** [comment]
@sbrannen can it be an issue with Spring Boot's Lifecycle and not Testcontainers' extension?

**Comment by driverpt** [comment]
Any updates on this ?

**Comment by amirmv2006** [comment]
I had a similar problem with a JUnit 5 extension I wrote and I found out when tests are run in `TestInstance.Lifecycle.PER_CLASS` Spring's application context will be loaded before the `org.junit.jupiter.api.extension.BeforeAllCallback#beforeAll` is called. So I solved the problem by moving my logic to `org.junit.jupiter.api.extension.TestInstancePostProcessor#postProcessTestInstance`.

Does it also make sense to start the "Shared Containers" on `postProcessTestInstance`? If yes, I'd be glad to create a pull request from my fork

**Comment by driverpt** [comment]
I would say this needs to be solved with a `TestExecutionListener`

**Comment by amirmv2006** [comment]
I think that'd be a spring-specific solution. There's a already a junit 5 annotation `@Testcontainers` which is loading TestContainer's junit extension `TestcontainersExtension` and this extension is doing the handling of containers

**Comment by amirmv2006** [comment]
@bsideup your thoughts?

**Comment by nickcaballero** [comment]
Used an extension coupled with a context customizer:

```java

public class DatabaseExtension implements BeforeAllCallback, AfterAllCallback {
    private static final ThreadLocal<CustomContainer> THREAD_CONTAINER = new ThreadLocal<>();

    @Override
    public void beforeAll(ExtensionContext context) {
        // This can come from a custom extension, or a hard coded default if that makes sense in your project
        String imageName = "";

        // Custom container can be a vanilla MySQLContainer, or something custom if you need a specific JDBC URL, etc
        CustomContainer container = new CustomContainer(DockerImageName.parse(imageName).asCompatibleSubstituteFor(MySQLContainer.NAME));
        THREAD_CONTAINER.set(container);

        container.start();
    }

    @Override
    public void afterAll(ExtensionContext context) {
        CustomContainer container = THREAD_CONTAINER.get();
        if (container != null) {
            // You should clear the thread local at this stage
            container.stop();
        }
    }

    // This class should be added to META-INF/spring.factories
    public static class CustomizerFactory implements ContextCustomizerFactory {
        @Override
        public ContextCustomizer createContextCustomizer(Class<?> testClass, List<ContextConfigurationAttributes> configAttributes) {
            return (context, mergedConfig) -> {
                // This is where we use the thread local since I couldn't figure out how to get the container reference across to Spring
                CustomContainer container = THREAD_CONTAINER.get();
                if (container != null) {
                    TestPropertyValues.of("spring.datasource.url=" + container.getJdbcUrl(),
                            "spring.datasource.username=" + container.getUsername(),
                            "spring.datasource.password=" + container.getPassword())
                            .applyTo(context.getEnvironment());
                }
            };
        }
    }
```

**Comment by nightswimmings** [comment]
> it doesn't have to be marked as reusable if you only need to use the same container between the tests. Reusable Containers feature is for reusing containers between the test runs (think running `mvn test` twice)

I am very surprised about this statement @bsideup . In the documentation it says https://www.testcontainers.org/test_framework_integration/junit_5/ that:

- an static @Container is reused across whole test class
- a dynamic @Container is not reused at all

So if reuse is for reusing across JVMs, what is the setup to reuse the container across test classes (/ JVM-wise?)

**Comment by bsideup** [comment]
@nightswimmings see https://www.testcontainers.org/test_framework_integration/manual_lifecycle_control/#singleton-containers

**Comment by nightswimmings** [comment]
The problem with this approach is that I tend to discard parent abstract IT classes due to some problems in the past (at least on Spring-Boot). When all inherited test classes have the same context key it is not a problem, but sometimes you have different test classes with different context ids, for instance with different args or properties, and then they are all cached an parent abstract resources become fragile.. at least in my experience

**Comment by bsideup** [comment]
@nightswimmings it doesn't have to be tests' parent class, really. The key here is containers defined as static variables that you only start once, either on class loading or on a first use :)

**Comment by nightswimmings** [comment]
Amazing news. I personally think this should be better stated in the documentation, as I clearly believe it to be the most convenient default for spring boot apps builds

**Comment by nightswimmings** [comment]
@bsideup  And just to complete the approach, do we need to take care of manually .stopping() the container, or can we rely safely on shutdown to close resources after JVM stop?

**Comment by bsideup** [comment]
@nightswimmings yeah, we need to polish the docs a little (contributions are welcome, btw! :))

> do we need to take care of manually .stopping() the container,

Not at all - Testcontainers has multiple layers to make sure that the containers are stopped after the test, in-JVM (shutdown hook) and out-process (watchdog sidecar container called Ryuk). See the paragraph at the bottom of the singleton container pattern docs.

**Comment by nightswimmings** [comment]
You rock guys, that is amazing. Finally, I designed my initialisation using an enum for the singleton pattern. If only the following was allowed, I could wrap it into a single meta-annotation and forget about the @DynamicPropertySource fuzz in each tes: https://github.com/spring-projects/spring-boot/issues/29757
Let's see

**Comment by nightswimmings** [comment]
Reopened suggestion in Spring Framework, which seems the actual proejct that owns it: https://github.com/spring-projects/spring-framework/issues/28046

**Comment by kiview** [comment]
@nightswimmings We are in no way involved with the [docker-maven-plugin](https://github.com/fabric8io/docker-maven-plugin). I am not sure if @rhuss is still the one maintaining it, but if he wants he (or whoever maintains it nowadays) can reach out to us and we can discuss if it makes sense to use Testcontainers as the general Docker abstraction.

**Comment by rhuss** [comment]
Unfortunately, I'm not actively working on docker-maven-plugin anymore (not because of lack of interest, but because of lack of time). The great @rohanKanojia takes care of it these days (but note, that no big features are planned).

As you might know, d-m-p provides support for two main aspects for Docker integration into the Java build process:

* *Building container images* in a Maven-like way, with a lot of bells and whistles to make for a smooth experience (like pushing to registry with support a tons of authentication mechanisms)
* *Running containers for testing* using the images that has been built.

While I consider the building part still the sweet spot of d-m-p which still has its value these days, I'm not so sure anymore about the running part, as it is very tricky to support all the runtime environments and lifecycle dependencies (as you can see of some long outstanding issues), and I definitely recommend testcontainers for this as it is much more momentum behind it to tackle these challenges properly (and is more advanced in its capabilities since quite some time).

Said that my vision for the future of d-m-p would be to sunset the "run container" part (possibly renaming it into something like "container-image-plugin" and support even more build mechanisms besides plain Docker, podman, and JIB) and improve the collaboration with test containers (however this could look like, e.g. to share configuration information).

Unfortunately, I won't be that guy to push this forward for the foreseeable future.

**Comment by yanivnahoum** [comment]
@vspiliop Yes, it's in my example (commented out): 
```java
static {
    // mySqlContainer.start();
}
```
If you uncomment it you'll force the container to start very early, before the WireMockTestExecutionListener loads the context. But as I said there - even if you don't do that, the context will load once again and the test will complete successfully.

**Comment by vspiliop** [comment]
@yanivnahoum Thanks for the help! By the way in my case I am not using wiremock, as I am doing contract testing for messaging, and the following worked for me as well:

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-contract-stub-runner</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.cloud</groupId>
					<artifactId>spring-cloud-contract-wiremock</artifactId>
				</exclusion>
			</exclusions>
			<scope>test</scope>
		</dependency>

**Comment by sbrannen** [comment]
Hi @bsideup,

Sorry for the belated reply. @odrotbohm pinged me about https://github.com/spring-projects/spring-modulith/issues/272 which brought _this_ issue to my attention.

> @sbrannen can it be an issue with Spring Boot's Lifecycle and not Testcontainers' extension?

As pointed out in https://github.com/testcontainers/testcontainers-java/issues/2290#issuecomment-757456913, whenever a test class is configured with `@TestInstance(PER_CLASS)` semantics, the `SpringExtension` will be invoked via JUnit Jupiter's `TestInstancePostProcessor` API to perform dependency injection (which requires Spring to load the `ApplicationContext`) **before** JUnit Jupiter invokes registered extensions via the `BeforeAllCallback` API.

So if an extension needs to prepare something in a `BeforeAllCallback` **before** the `SpringExtension` loads the `ApplicationContext`, that simply won't work with `@TestInstance(PER_CLASS)` semantics.

As suggested in https://github.com/testcontainers/testcontainers-java/issues/2290#issuecomment-757456913, it's worth investigating if the Testcontainers extension for JUnit Jupiter could implement the necessary setup via the `TestInstancePostProcessor` API instead. However, there could still be an issue with extension registration order: the Testcontainers extension would then have to be registered before the `SpringExtension`.

**Comment by homich1991** [comment]
I had very same issue with following code: (spring 3.2.2/ Testcontainers: 1.19.3)
`
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
@AutoConfigureMockMvc
@Testcontainers
public abstract class AbstractWithTestContainerIT {


    private static String LOCALSTACK_IMAGE_VERSION = "localstack/localstack:3.1.0";

     @Container
    protected static LocalStackContainer localStack  = new LocalStackContainer(
                DockerImageName.parse(LOCALSTACK_IMAGE_VERSION))
                .withServices(S3);


    static final String BUCKET_NAME = UUID.randomUUID().toString();

    @DynamicPropertySource
    static void overrideProperties(DynamicPropertyRegistry registry) throws InterruptedException {
        registry.add("app.bucket", () -> BUCKET_NAME);
        registry.add(
                "spring.cloud.aws.region.static",
                () -> localStack.getRegion()
        );
        registry.add(
                "spring.cloud.aws.credentials.access-key",
                () -> localStack.getAccessKey()
        );
        registry.add(
                "spring.cloud.aws.credentials.secret-key",
                () -> localStack.getSecretKey()
        );
        registry.add(
                "spring.cloud.aws.s3.endpoint",
                () -> localStack.getEndpointOverride(S3).toString()
        );
    }

}
`

Nothing really helps, except comment from this thread to remove contract-wiremock,

so I removed this dependency from pom.xml
`        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-contract-wiremock</artifactId>
            <scope>test</scope>
        </dependency>
`
and everything works now.

so +1 to @vspiliop  and thanks to @yanivnahoum for hint!

**Comment by alex-arana** [comment]
> @nightswimmings yeah, we need to polish the docs a little (contributions are welcome, btw! :))
> 
> > do we need to take care of manually .stopping() the container,
> 
> Not at all - Testcontainers has multiple layers to make sure that the containers are stopped after the test, in-JVM (shutdown hook) and out-process (watchdog sidecar container called Ryuk). See the paragraph at the bottom of the singleton container pattern docs.

According to the [testcontainers commit](https://github.com/testcontainers/testcontainers-java/commit/39f02190c01702fb3121b080f29c72bbdf7c78ea) that introduced this issue last October:

> Currently, `Ryuk` container finishes after around 10s. This commit register
> a shutdown hook which will send a sigterm to the Ryuk container when JVM
> is terminating causing Ryuk to finish sooner

As per the above description, this change was aimed at expediting Ryuk's finalisation routine which has introduced a whole raft of other issues when other components such as Spring JMS or Camel routes that depend on the services monitored by Ryuk are suddenly terminated; akin to having the rug pulled from under them while they are busy in the process of coalescing.

![Screenshot from 2024-04-05 14-11-29](https://github.com/testcontainers/testcontainers-java/assets/2107295/4f29fa5a-e575-49de-a45d-cd9b1f439ae6)

Should we consider configuring the shutdown hook above as an _opt-in_ until such time a more permanent solution has been found?

**Comment by lberoiza** [comment]
> Used an extension coupled with a context customizer:
> 
> ```java
> public class DatabaseExtension implements BeforeAllCallback, AfterAllCallback {
>     private static final ThreadLocal<CustomContainer> THREAD_CONTAINER = new ThreadLocal<>();
> 
>     @Override
>     public void beforeAll(ExtensionContext context) {
>         // This can come from a custom extension, or a hard coded default if that makes sense in your project
>         String imageName = "";
> 
>         // Custom container can be a vanilla MySQLContainer, or something custom if you need a specific JDBC URL, etc
>         CustomContainer container = new CustomContainer(DockerImageName.parse(imageName).asCompatibleSubstituteFor(MySQLContainer.NAME));
>         THREAD_CONTAINER.set(container);
> 
>         container.start();
>     }
> 
>     @Override
>     public void afterAll(ExtensionContext context) {
>         CustomContainer container = THREAD_CONTAINER.get();
>         if (container != null) {
>             // You should clear the thread local at this stage
>             container.stop();
>         }
>     }
> 
>     // This class should be added to META-INF/spring.factories
>     public static class CustomizerFactory implements ContextCustomizerFactory {
>         @Override
>         public ContextCustomizer createContextCustomizer(Class<?> testClass, List<ContextConfigurationAttributes> configAttributes) {
>             return (context, mergedConfig) -> {
>                 // This is where we use the thread local since I couldn't figure out how to get the container reference across to Spring
>                 CustomContainer container = THREAD_CONTAINER.get();
>                 if (container != null) {
>                     TestPropertyValues.of("spring.datasource.url=" + container.getJdbcUrl(),
>                             "spring.datasource.username=" + container.getUsername(),
>                             "spring.datasource.password=" + container.getPassword())
>                             .applyTo(context.getEnvironment());
>                 }
>             };
>         }
>     }
> ```
> 
> The test class can then use `@ExtendWith({DatabaseExtension.class, SpringExtension.class})` without any additional changes.

Thank you very much for your Idea, that direct me in the right way.

Gracias
