### ISSUE TITLE
ORA-01882: timezone region not found with wnameless/docker-oracle-xe-11g-r2

### ISSUE THREAD

**Issue by JimRichards22** [testcontainers/testcontainers-java#2313]
I'm running the new `wnameless/docker-oracle-xe-11g-r2` inside Bitbucket pipelines. I can run the test locally on my machine and there are no issues, but when run in Pipelines I get `ORA-01882: timezone region not found`.

I'm calling it with
```
OracleContainer("wnameless/oracle-xe-11g-r2:latest").withEnv("TZ", "GMT");
```
The timezone environment variable is the recommeded fix for this issue, but it's not working. I'm not sure if the ORA-01882 is a byproduct of something else not working, or if it's the actual issue.

The stack trace I get is
```
05:50:49.213 [DEBUG] [TestEventLogger]     2020-01-31 05:50:49 ERROR 🐳 [wnameless/oracle-xe-11g-r2:latest]:268 - Could not start container
05:50:49.213 [DEBUG] [TestEventLogger]     org.rnorth.ducttape.TimeoutException: Timeout waiting for result with exception
05:50:49.213 [DEBUG] [TestEventLogger]     	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:51)
05:50:49.213 [DEBUG] [TestEventLogger]     	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:129)
05:50:49.213 [DEBUG] [TestEventLogger]     	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:263)
05:50:49.213 [DEBUG] [TestEventLogger]     	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:216)
05:50:49.213 [DEBUG] [TestEventLogger]     	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
05:50:49.213 [DEBUG] [TestEventLogger]     	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:214)
05:50:49.214 [DEBUG] [TestEventLogger]     	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:203)
05:50:49.214 [DEBUG] [TestEventLogger]     	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:723)
05:50:49.214 [DEBUG] [TestEventLogger]     	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
05:50:49.214 [DEBUG] [TestEventLogger]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
05:50:49.214 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
05:50:49.214 [DEBUG] [TestEventLogger]     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
05:50:49.214 [DEBUG] [TestEventLogger]     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
05:50:49.214 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
05:50:49.215 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
05:50:49.215 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
05:50:49.215 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
05:50:49.215 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
05:50:49.215 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
05:50:49.215 [DEBUG] [TestEventLogger]     	at org.junit.runners.Suite.runChild(Suite.java:128)
05:50:49.215 [DEBUG] [TestEventLogger]     	at org.junit.runners.Suite.runChild(Suite.java:27)
05:50:49.216 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
05:50:49.216 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
05:50:49.216 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
05:50:49.216 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
05:50:49.216 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
05:50:49.216 [DEBUG] [TestEventLogger]     	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
05:50:49.216 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
05:50:49.216 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
05:50:49.217 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
05:50:49.217 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
05:50:49.217 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
05:50:49.217 [DEBUG] [TestEventLogger]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:50:49.217 [DEBUG] [TestEventLogger]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05:50:49.217 [DEBUG] [TestEventLogger]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:50:49.217 [DEBUG] [TestEventLogger]     	at java.lang.reflect.Method.invoke(Method.java:498)
05:50:49.217 [DEBUG] [TestEventLogger]     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
05:50:49.218 [DEBUG] [TestEventLogger]     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
05:50:49.218 [DEBUG] [TestEventLogger]     	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
05:50:49.218 [DEBUG] [TestEventLogger]     	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
05:50:49.218 [DEBUG] [TestEventLogger]     	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
05:50:49.218 [DEBUG] [TestEventLogger]     	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:117)
05:50:49.218 [DEBUG] [TestEventLogger]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
05:50:49.218 [DEBUG] [TestEventLogger]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
05:50:49.218 [DEBUG] [TestEventLogger]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
05:50:49.219 [DEBUG] [TestEventLogger]     	at java.lang.reflect.Method.invoke(Method.java:498)
05:50:49.219 [DEBUG] [TestEventLogger]     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
05:50:49.219 [DEBUG] [TestEventLogger]     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
05:50:49.223 [DEBUG] [TestEventLogger]     	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
05:50:49.223 [DEBUG] [TestEventLogger]     	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
05:50:49.223 [DEBUG] [TestEventLogger]     	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
05:50:49.223 [DEBUG] [TestEventLogger]     	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
05:50:49.223 [DEBUG] [TestEventLogger]     	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
05:50:49.223 [DEBUG] [TestEventLogger]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
05:50:49.223 [DEBUG] [TestEventLogger]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
05:50:49.224 [DEBUG] [TestEventLogger]     	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
05:50:49.224 [DEBUG] [TestEventLogger]     	at java.lang.Thread.run(Thread.java:748)
05:50:49.224 [DEBUG] [TestEventLogger]     Caused by: java.sql.SQLException: Could not create new connection
05:50:49.224 [DEBUG] [TestEventLogger]     	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:194)
05:50:49.224 [DEBUG] [TestEventLogger]     	at org.testcontainers.containers.JdbcDatabaseContainer.lambda$waitUntilContainerStarted$0(JdbcDatabaseContainer.java:135)
05:50:49.225 [DEBUG] [TestEventLogger]     	at org.rnorth.ducttape.unreliables.Unreliables.lambda$retryUntilSuccess$0(Unreliables.java:41)
05:50:49.225 [DEBUG] [TestEventLogger]     	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05:50:49.225 [DEBUG] [TestEventLogger]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
05:50:49.226 [DEBUG] [TestEventLogger]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
05:50:49.226 [DEBUG] [TestEventLogger]     	... 1 more
05:50:49.226 [DEBUG] [TestEventLogger]     Caused by: org.rnorth.ducttape.TimeoutException: Timeout waiting for result with exception
05:50:49.226 [DEBUG] [TestEventLogger]     	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:51)
05:50:49.226 [DEBUG] [TestEventLogger]     	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:190)
05:50:49.226 [DEBUG] [TestEventLogger]     	... 6 more
05:50:49.227 [DEBUG] [TestEventLogger]     Caused by: java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
05:50:49.227 [DEBUG] [TestEventLogger]     ORA-01882: timezone region not found
```

**Comment by AnEmortalKid** [comment]
I recall reading somewhere that you couldn’t change the time zone for the XE instance. It might be somewhere in this repo: https://github.com/oracle/docker-images/blob/master/OracleDatabase/SingleInstance/FAQ.md#how-do-i-change-the-timezone-of-my-container

**Comment by JimRichards22** [comment]
So, I got something working with
```
    public MyOracleContainer(String dockerImageName) {
        super(dockerImageName);
        System.setProperty("oracle.jdbc.timezoneAsRegion", "false");
    }
```

**Comment by rnorth** [comment]
We should probably add this to the docs for the Oracle module - would anybody care to contribute that?

**Comment by AnEmortalKid** [comment]
@rnorth I can do that, should I create a `Known Issues` section here: https://github.com/testcontainers/testcontainers-java/blob/master/docs/modules/databases/oraclexe.md ?

**Comment by Jorge2M** [comment]
> So, I got something working with
> 
> ```
>     public MyOracleContainer(String dockerImageName) {
>         super(dockerImageName);
>         System.setProperty("oracle.jdbc.timezoneAsRegion", "false");
>     }
> ```

Thank you @JimRichards22 , this works fine for me!
