### ISSUE TITLE
Cassandra Module Wait Strategy doesn't work with Authentication Enabled

### ISSUE THREAD

**Issue by KraTos5589** [testcontainers/testcontainers-java#2373]
Code
```
CassandraContainer CASSANDRA_CONTAINER = new CassandraContainer<>("cassandra:3.11.4")
            .withConfigurationOverride("cassandra-config")
            .waitingFor(new CassandraQueryWaitStrategy());
```
cassandra-config folder contains cassandra.yml. This was copy pasted from [example](https://github.com/testcontainers/testcontainers-java/blob/master/modules/cassandra/src/test/resources/cassandra-test-configuration-example/cassandra.yaml) with one line changed.
```
authenticator: AllowAllAuthenticator
```
was changed to 
```
authenticator: PasswordAuthenticator
```

I get an exception
```
Exception in thread "main" org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:322)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:302)
	at com.walmart.services.offer.listing.BaseOfferStoreIT.main(BaseOfferStoreIT.java:70)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:315)
	... 2 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:485)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:317)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 3 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for Cassandra to be accessible for query execution
	at org.testcontainers.containers.wait.CassandraQueryWaitStrategy.waitUntilReady(CassandraQueryWaitStrategy.java:36)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:876)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:428)
	... 5 more
```

The Simplest explanation seems to be the getCluster method in [CassandraContainer](https://github.com/testcontainers/testcontainers-java/blob/master/modules/cassandra/src/main/java/org/testcontainers/containers/CassandraContainer.java)
```
public static Cluster getCluster(ContainerState containerState, boolean enableJmxReporting) {
        final Cluster.Builder builder = Cluster.builder()
            .addContactPoint(containerState.getContainerIpAddress())
            .withPort(containerState.getMappedPort(CQL_PORT));
        if (!enableJmxReporting) {
            builder.withoutJMXReporting();
        }
        return builder.build();
    }
```

OS - Mac
testcontainer version - 1.12.5
docker version - 2.1.0.3 (38240)

**Comment by mkjensen** [comment]
I think there is a similar issue for the init script functionality. It does not seem possible to supply username/password authentication.

**Comment by KraTos5589** [comment]
@mkjensen - you are correct. I have fixed that issue as well with the PR that I have created, but nobody seems to have reviewed it for 10 days.

**Comment by bsideup** [comment]
@KraTos5589 we are 100% community driven project and although we would like to review every PR we receive ASAP, sometimes we simply don't have enough capacity for that, please keep it in mind. I hope you will understand.

**Comment by KraTos5589** [comment]
@bsideup I understand,

**Comment by KraTos5589** [comment]
@bsideup @rnorth Can you guys please review the PR associated with this
