### ISSUE TITLE
Tomcat testcontainer cannot connect to a testcontainer running a database

### ISSUE THREAD

**Issue by keenmueller** [testcontainers/testcontainers-java#2391]
I have a simple Postgresql testcontainer, and it runs fine:
```java
@Container
 public static PostgreSQLContainer postgres = new PostgreSQLContainer<>()
         .withDatabaseName("postgres")
         .withPassword("test")
         .withUsername("test")
         ;
```
But when I created a testcontainer with a tomcat docker image, it is refusing to connect:
```java
  webservice = new GenericContainer<>("tomcat:9.0.31")
          .withEnv(env)
          .withFileSystemBind(Paths.get("stat-descriptives-ws/target/stat-descriptives-ws-" +
                       version +
                       ".war").toAbsolutePath().toString(),
               "/usr/local/tomcat/webapps/stat-descriptives-ws.war")
          .withExposedPorts(8080)
          .waitingFor(Wait.forHttp("/stat-descriptives-ws").forPort(8080))
          ;
  webservice.start();
```
The web app starts up fine but whenever it tries to connect to the database I receive this error:
```
02-Mar-2020 17:33:05.349 SEVERE [main] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [SparkFilter]

java.sql.SQLException: Cannot create PoolableConnectionFactory (Connection to localhost:32838 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.)

at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:735)

at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:605)

at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:809)

at com.ca.stat.desc.TestDatabaseModule.createCustomDataSource(TestDatabaseModule.kt:53)

at com.ca.stat.desc.TestDatabaseModule.statClassDataSource(TestDatabaseModule.kt:24)

at com.ca.stat.desc.TestDatabaseModule_StatClassDataSourceFactory.statClassDataSource(TestDatabaseModule_StatClassDataSourceFactory.java:33)

at com.ca.stat.desc.TestDatabaseModule_StatClassDataSourceFactory.get(TestDatabaseModule_StatClassDataSourceFactory.java:25)

at com.ca.stat.desc.TestDatabaseModule_StatClassDataSourceFactory.get(TestDatabaseModule_StatClassDataSourceFactory.java:8)

at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)

at com.ca.stat.desc.StatusModule_ProvideStatusRegisterFactory.get(StatusModule_ProvideStatusRegisterFactory.java:38)

at com.ca.stat.desc.StatusModule_ProvideStatusRegisterFactory.get(StatusModule_ProvideStatusRegisterFactory.java:10)

at com.ca.stat.desc.DaggerTestServiceComponent.getStatusResource2(DaggerTestServiceComponent.java:73)

at com.ca.stat.desc.DaggerTestServiceComponent.getStatusResource(DaggerTestServiceComponent.java:76)

at com.ca.stat.desc.DaggerTestServiceComponent.resources(DaggerTestServiceComponent.java:137)

at com.ca.stat.desc.Application.init(Application.kt:35)

at spark.servlet.SparkFilter.init(SparkFilter.java:70)

at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:270)

at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:251)

at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102)

at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4533)

at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5172)

at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)

at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)

at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)

at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)

at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)

at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849)

at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)

at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)

at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)

at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)

at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)

at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)

at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)

at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)

at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)

at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)

at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)

at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)

at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)

at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)

at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)

at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)

at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)

at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)

at org.apache.catalina.startup.Catalina.start(Catalina.java:633)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:566)

at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)

at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)

Caused by: org.postgresql.util.PSQLException: Connection to localhost:32838 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:280)

at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)

at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)

at org.postgresql.Driver.makeConnection(Driver.java:458)

at org.postgresql.Driver.connect(Driver.java:260)

at org.apache.commons.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:53)

at org.apache.commons.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355)

at org.apache.commons.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:116)

at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:731)

... 60 more

Caused by: java.net.ConnectException: Connection refused (Connection refused)

at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)

at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)

at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)

at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)

at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)

at java.base/java.net.Socket.connect(Socket.java:609)

at org.postgresql.core.PGStream.<init>(PGStream.java:75)

at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:91)

at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)

... 68 more

02-Mar-2020 17:33:05.350 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more Filters failed to start. Full details will be found in the appropriate container log file
```

I pass in the host, database name, and port through environment variables, and I have verified that the jdbc url is correct (ex: jdbc:postresql://localhost:32838/postgres). Just to make sure I could connect to the postgresql database, I kept the test suspended with a debugger and used my IDE to connect to the database, which it did successfully. I also ran the web app outside of a testcontainer and it could connect just fine. Is there an issue with testcontainers connecting to each other? Is this a race condition? I made sure to start the container in the @BeforeAll method just to make sure it started after the database

**Comment by bsideup** [comment]
the JDBC URL is not correct, it is only valid for you host. When you have container-to-container communication, you need to use `Network`s and `withNetworkAlias` and then use the alias + original ports.

**Comment by keenmueller** [comment]
Thanks for the help!
Just as a quick clarification, would the url look like:
 jdbc:postresql://networkname:32838/postgres
after setting the network Alias to networkname? And by original ports, do you mean ports that I exposed?

**Comment by keenmueller** [comment]
Thanks for the help!
Just for clarification, the url should instead look like jdbc:postresql://networkname:32838/postgres
with networkname being what the network alias was set to? By original ports, do you mean a port that I exposed on the container?
