### ISSUE TITLE
improved logging when unable to fetch docker image

### ISSUE THREAD

**Issue by dbyron0** [testcontainers/testcontainers-java#2443]
From https://testcontainers.slack.com/archives/C1SUBPZK6/p1584131893103200:

I’m trying to debug a struggle with pulling a docker image in a CI environment.  At the moment, I see this:
```
[21:30:36][docker]         Caused by:
[21:30:36][docker]         org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageNameFuture=java.util.concurrent.CompletableFuture@55d9985c[Completed normally], imagePullPolicy=DefaultPullPolicy(), dockerClient=LazyDockerClient.INSTANCE)
[21:30:36][docker]             at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1265)
[21:30:36][docker]             at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:600)
[21:30:36][docker]             at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:311)
[21:30:36][docker]             ... 2 more
[21:30:36][docker] 
[21:30:36][docker]             Caused by:
[21:30:36][docker]             com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://quay.io/v2/: Forbidden"}
```
but no where in there do I actually get to see the name of the image that’s failing.  The relevant code (from https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/GenericContainer.java#L1265) is:
```
        try {
            return image.get();
        } catch (Exception e) {
            throw new ContainerFetchException("Can't get Docker image: " + image, e);
        }
```
Any thoughts on how to improve it to see the image name?

**Comment by bsideup** [comment]
Hi @dbyron0,

I marked it as "good first issue". One way of implementing it would be to improve `RemoteDockerImage` and/or `imageNameFuture`, so that it is included in the output.

**Comment by dbyron0** [comment]
Like [this](https://github.com/testcontainers/testcontainers-java/pull/2450) ?

**Comment by jhonathan-007** [comment]
hello...
can anyone help me to become a bug hunter ???
