### ISSUE TITLE
DockerComposeContainer.stop() always fails (for non local docker-compose)

### ISSUE THREAD

**Issue by trexinc** [testcontainers/testcontainers-java#2465]
From first impression the flow doesn't seem to be correct, DockerComposeContainer.stop() shouldn't try to start the container first

`Exception in thread "main" org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:322)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:302)
	at org.testcontainers.containers.ContainerisedDockerCompose.invoke(DockerComposeContainer.java:593)
	at org.testcontainers.containers.DockerComposeContainer.runWithCompose(DockerComposeContainer.java:262)
	at org.testcontainers.containers.DockerComposeContainer.stop(DockerComposeContainer.java:298)
`

**Comment by bsideup** [comment]
non-local Compose uses a container with the docker-compose binary. To stop the containers, it needs to be started to run the command.

**Comment by trexinc** [comment]
Thanks for the info. I looked deeper and it was actually my fault, I created several DockerComposeContainer's with shared networks and was stopping them in the wrong order.
