### ISSUE TITLE
testcontainers junit-jupiter 1.13.0 causes  org.apache.maven.surefire.booter.SurefireBooterForkException in Java 11 and also in Java 14

### ISSUE THREAD

**Issue by findinpath** [testcontainers/testcontainers-java#2490]
When trying to run tests with the testcontainers junit-jupiter 1.13.0 library in the classpath of a simple project, the tests don't seem to work:

```
[INFO] --- maven-surefire-plugin:3.0.0-M4:test (default-test) @ testcontainers-junit-bug ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[ERROR] org/junit/platform/engine/EngineDiscoveryListener
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.999 s
[INFO] Finished at: 2020-03-29T08:24:38+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M4:test (default-test) on project testcontainers-junit-bug: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/marius/findinpath/testcontainers-junit-bug/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked processorg/junit/platform/engine/EngineDiscoveryListener
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked processorg/junit/platform/engine/EngineDiscoveryListener
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:675)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:248)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1217)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1063)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:889)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Issue was tested with both JDK 11 and JDK 14 (Open JDK)

Test Git repository:

https://github.com/findinpath/testcontainers-junit-bug

Use

```
mvn test
```

to reproduce the issue.

NOTE that the test run just fine when working with  testcontainers junit-jupiter 1.12.5 library. This seems to be a regression issue.

**Comment by findinpath** [comment]
Nevermind, I've just noticed through `mvn dependency:tree` that this seems to be linked to a breaking change in `junit-jupiter-api` between the version `5.5.2` and `5.6.0`

```
[[1;34mINFO[m] com.findinpath:testcontainers-junit-bug:jar:1.0-SNAPSHOT
[[1;34mINFO[m] +- org.testcontainers:junit-jupiter:jar:1.13.0:compile
[[1;34mINFO[m] |  +- org.testcontainers:testcontainers:jar:1.13.0:compile
[[1;34mINFO[m] |  |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[[1;34mINFO[m] |  |  +- org.jetbrains:annotations:jar:17.0.0:compile
[[1;34mINFO[m] |  |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[[1;34mINFO[m] |  |  +- org.apache.commons:commons-compress:jar:1.20:compile
[[1;34mINFO[m] |  |  +- javax.xml.bind:jaxb-api:jar:2.3.1:compile
[[1;34mINFO[m] |  |  |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[[1;34mINFO[m] |  |  +- org.rnorth.duct-tape:duct-tape:jar:1.0.8:compile
[[1;34mINFO[m] |  |  +- org.rnorth.visible-assertions:visible-assertions:jar:2.1.2:compile
[[1;34mINFO[m] |  |  +- org.rnorth:tcp-unix-socket-proxy:jar:1.0.2:compile
[[1;34mINFO[m] |  |  |  +- com.kohlschutter.junixsocket:junixsocket-native-common:jar:2.0.4:compile
[[1;34mINFO[m] |  |  |  |  \- org.scijava:native-lib-loader:jar:2.0.2:compile
[[1;34mINFO[m] |  |  |  \- com.kohlschutter.junixsocket:junixsocket-common:jar:2.0.4:compile
[[1;34mINFO[m] |  |  \- net.java.dev.jna:jna-platform:jar:5.5.0:compile
[[1;34mINFO[m] |  |     \- net.java.dev.jna:jna:jar:5.5.0:compile
[[1;34mINFO[m] |  \- org.junit.jupiter:junit-jupiter-api:jar:5.6.0:compile
[[1;34mINFO[m] |     +- org.opentest4j:opentest4j:jar:1.2.0:compile
[[1;34mINFO[m] |     \- org.junit.platform:junit-platform-commons:jar:1.6.0:compile
[[1;34mINFO[m] \- org.junit.jupiter:junit-jupiter-engine:jar:5.5.2:test
[[1;34mINFO[m]    +- org.apiguardian:apiguardian-api:jar:1.1.0:compile
[[1;34mINFO[m]    \- org.junit.platform:junit-platform-engine:jar:1.5.2:test
```

I've updated the `junit-jupiter-engine` dependency to `5.6.0` and the tests work again :).
