### ISSUE TITLE
HostPortWaitStrategy does not support UDP ports

### ISSUE THREAD

**Issue by pravussum** [testcontainers/testcontainers-java#2532]
I have a testcontainer where I want to expose a UPD port, therefor I used GenericContainers addFixedExposedPort method (only that allows to specify the protocol). 

    addFixedExposedPort(5775, 6831, InternetProtocol.UDP);
    addExposedPort(16686);

The container fails to come up with this error: 

    Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [32790, 5775] should be listening)
    at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:47)
    at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
    at org.testcontainers.containers.wait.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:23)
    at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
    at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:582)
    at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:259)
    ... 35 more

It looks to me like 
https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/wait/strategy/HostPortWaitStrategy.java or rather 
https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/wait/internal/ExternalPortListeningCheck.java 
is only supporting TCP ports when checking the port availability (DatagramSocket should be used depending on the used protocol).

**Comment by mkrzywanski** [comment]
I think this is covered by this [PR](https://github.com/testcontainers/testcontainers-java/pull/2989)

**Comment by nathsomdatta59** [comment]
@mkrzywanski I tried to add a UDP port.  But I think in the testcontainer approach, it tries to bind the UDP port.  When it does that my host application is not able to listen to the UDP port and get traffic.  My use case is as follows :
I have a containerized application which is sending traffic to a UDP port.  In my test case using the test container, I would like to get the traffic from the UDP port.  
I can do that in my unit test by just opening up a socket connection to that port.  But when I use test container approach and try to expose a UDP port, it gets bound, and I am "address/port already in use" exception.
