### ISSUE TITLE
Sudden issues with AWS Codebuild

### ISSUE THREAD

**Issue by mustafashabib** [testcontainers/testcontainers-java#2765]
Hi everyone

I've had my tests running with testcontainers for a while now and am suddenly seeing these issues in AWS Codebuild.

I set up my container here like so

~~~java
private static final PostgreSQLContainer db =
      new PostgreSQLContainer("postgres:11.7");
~~~

and when I start it, I'm seeing errors with it trying to pull the image.

~~~

org.testcontainers.containers.ContainerLaunchException: Container startup failed
--
440 | at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:320)
441 | at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:300)
442 | at com.surely.planner.backend.data.BaseDataTest$Companion.setup(BaseDataTest.kt:68)
443 | at com.surely.planner.backend.data.BaseDataTest.setup(BaseDataTest.kt)
444 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
445 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
446 | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
447 | at java.base/java.lang.reflect.Method.invoke(Method.java:566)
448 | at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
449 | at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
450 | at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeBeforeAllMethods$9(ClassTestDescriptor.java:376)
451 | at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
452 | at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeBeforeAllMethods(ClassTestDescriptor.java:375)
453 | at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:201)
454 | at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:77)
455 | at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
456 | at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
457 | at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
458 | at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
459 | at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
460 | at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
461 | at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
462 | at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
463 | at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
464 | at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
465 | at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
466 | at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
467 | at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
468 | at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
469 | at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
470 | at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
471 | at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
472 | at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
473 | at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
474 | at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
475 | at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
476 | at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
477 | at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
478 | at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
479 | at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
480 | at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
481 | at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
482 | at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
483 | at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
484 | at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
485 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
486 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
487 | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
488 | at java.base/java.lang.reflect.Method.invoke(Method.java:566)
489 | at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
490 | at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
491 | at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
492 | at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
493 | at com.sun.proxy.$Proxy5.stop(Unknown Source)
494 | at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
495 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
496 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
497 | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
498 | at java.base/java.lang.reflect.Method.invoke(Method.java:566)
499 | at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
500 | at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
501 | at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
502 | at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
503 | at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
504 | at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
505 | at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
506 | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
507 | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
508 | at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
509 | at java.base/java.lang.Thread.run(Thread.java:834)
510 |  
511 | Caused by:
512 | org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=postgres:11.7, imagePullPolicy=DefaultPullPolicy())
513 | at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1268)
514 | at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:603)
515 | at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:309)
516 | ... 69 more
517 |  
518 | Caused by:
519 | com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://quay.io/v2/: EOF"}
520 | at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:293)
521 | at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.lambda$executeAndStream$4(OkHttpInvocationBuilder.java:317)
522 | ... 1 more

~~~

Any idea what we can do here to resolve this?

**Comment by bsideup** [comment]
see #2763
