### ISSUE TITLE
"Self-suppression not permitted" when pulling images fails

### ISSUE THREAD

**Issue by findepi** [testcontainers/testcontainers-java#2781]
```
java.lang.IllegalArgumentException: Self-suppression not permitted
        at java.lang.Throwable.addSuppressed(Throwable.java:1072)
        at io.prestosql.tests.product.launcher.env.Environments.pruneEnvironment(Environments.java:44)
        at io.prestosql.tests.product.launcher.cli.EnvironmentUp$Execution.run(EnvironmentUp.java:107)
        at io.prestosql.tests.product.launcher.cli.Commands.runCommand(Commands.java:40)
        at io.prestosql.tests.product.launcher.cli.EnvironmentUp.run(EnvironmentUp.java:62)
        at io.prestosql.tests.product.launcher.cli.Launcher.run(Launcher.java:48)
        at io.prestosql.tests.product.launcher.cli.Launcher.main(Launcher.java:25)
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: no matching manifest for unknown in the manifest list entries
        at com.github.dockerjava.core.command.PullImageResultCallback.checkDockerClientPullSuccessful(PullImageResultCallback.java:96)
        at com.github.dockerjava.core.command.PullImageResultCallback.throwFirstError(PullImageResultCallback.java:111)
        at com.github.dockerjava.core.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:94)
        at org.testcontainers.images.TimeLimitedLoggedPullImageResultCallback.awaitCompletion(TimeLimitedLoggedPullImageResultCallback.java:52)
        at org.testcontainers.DockerClientFactory.checkAndPullImage(DockerClientFactory.java:262)
        at org.testcontainers.DockerClientFactory.runInsideDocker(DockerClientFactory.java:279)
        at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:172)
        at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
        at org.testcontainers.LazyDockerClient.listContainersCmd(LazyDockerClient.java:12)
```

**Comment by bsideup** [comment]
Worth mentioning that this happened on rhel 7.6 / ppc64le, so the underlying issue is "no matching manifest for unknown in the manifest list entries" that comes from Docker when you try to pull an image that does not support this arch.

FYI also, the error comes from `docker-java`, which is a 3rd party project that we use in Testcontainers, so I'll close it anyways.
