### ISSUE TITLE
Cannot add/copy resources using DockerfileBuilder

### ISSUE THREAD

**Issue by kunickiaj** [testcontainers/testcontainers-java#288]
Take the example:

```
@ClassRule
  public static GenericContainer server = new GenericContainer(
      new ImageFromDockerfile("xyz/ldap", false)
          .withDockerfileFromBuilder(builder -> {
            builder
                .from("osixia/openldap:1.1.7").cmd("--loglevel", "trace")
                .copy(
                    <source file location>,
                    "/container/service/slapd/assets/config/bootstrap/ldif/ldap-server2-entries.ldif"
                )
                .build();
          })
      )
      .withExposedPorts(LDAP_PORT);
```

Where I've tried <source file location> as:
* `"/tmp/ldap-server2-entries.ldif"`
* `"/ldif/ldap-server2-entries.ldif"` (where ldif is a subdirectory in src/test/resources)
* `new File(LdapAuthenticationIT.class.getClassLoader().getResource("/tmp/ldap-server2-entries.ldif")).getAbsolutePath()`

All three choices above result in this stacktrace:

```
org.testcontainers.containers.ContainerFetchException: Can't get Docker image name from org.testcontainers.images.builder.ImageFromDockerfile@638ef7ed
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:729)
	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:274)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:159)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:516)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:28)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: org.testcontainers.shaded.com.github.dockerjava.api.exception.DockerClientException: Could not build image: lstat tmp/ldap-server2-entries.ldif: no such file or directory
	at org.testcontainers.shaded.com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:71)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:48)
	at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:146)
	at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:31)
	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:27)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:727)
	... 13 more
```

The references paths do exist. Have tried both ADD and COPY. Also tried simply using `.withFileFromClasspath()` on the resulting Dockerfile after `withDockerfileFromBuilder()` but while it does not result in an error, the file does not appear to be added to the container either. The environment is Docker for Mac 1.13 Stable Channel 0c6d765c54 and Testcontainers 1.1.8

**Comment by coutoPL** [comment]
I have the same problem. Also, Docker for Mac 1.13 and testcontainers-java 1.1.9-SNAPSHOT.

**Comment by martin-g** [comment]
@coutoPL Why do you use 1.1.9-SNAPSHOT ? 1.1.9 has been released few days ago.

**Comment by coutoPL** [comment]
sorry, 1.1.10-SNAPSHOT

**Comment by rnorth** [comment]
Sorry for the long delay on this. I've been working on [a change](!313) to how the docker context is made available, which allows straightforward use of directories. I'm hoping to get this out soon.

If you'd like to try it, a jitpack build of the `285-recursive-tar-copy` should give you a preview.

**Comment by PGryllos** [comment]
I am not sure if this the same issue but when trying to build a container using 

```
    @Rule
    public GenericContainer dslContainer = new GenericContainer(
        new ImageFromDockerfile()
            .withFileFromFile("Dockerfile", new File("service/Dockerfile")))
```

the `COPY` statements in my Dockerfile fail with a similar message

> COPY failed: stat /var/lib/docker/tmp/docker-builder276737305/docker-entrypoint.sh: no such file or directory
