### ISSUE TITLE
MSSQL Container not working in 1.14.3

### ISSUE THREAD

**Issue by wjglerum** [testcontainers/testcontainers-java#2966]
We got the following error when upgrading to 1.14.3 for MSSQL testcontainer with DEBUG logging enabled:

```
18:29:17 DEBUG [or.te.im.AbstractImagePullPolicy] (Agroal_10500229751) Using locally available and not pulling image: mcr.microsoft.com/mssql/server:latest
18:29:17 INFO  [🐳.mi.com/mssql/server:latest]] (Agroal_10500229751) Creating container for image: mcr.microsoft.com/mssql/server:latest
18:29:17 DEBUG [or.te.ut.RegistryAuthLocator] (Agroal_10500229751) Looking up auth config for image: mcr.microsoft.com/mssql/server:latest
18:29:17 DEBUG [or.te.ut.RegistryAuthLocator] (Agroal_10500229751) RegistryAuthLocator has configFile: /Users/wjglerum/.docker/config.json (exists) and commandPathPrefix: 
18:29:17 DEBUG [or.te.ut.RegistryAuthLocator] (Agroal_10500229751) registryName [mcr.microsoft.com] for dockerImageName [mcr.microsoft.com/mssql/server:latest]
18:29:17 DEBUG [or.te.ut.RegistryAuthLocator] (Agroal_10500229751) Executing docker credential provider: docker-credential-desktop to locate auth config for: mcr.microsoft.com
18:29:17 DEBUG [or.te.sh.or.ze.ex.ProcessExecutor] (Agroal_10500229751) Executing [docker-credential-desktop, get].
18:29:17 DEBUG [or.te.sh.or.ze.ex.ProcessExecutor] (Agroal_10500229751) Started Process[pid=19674, exitValue="not exited"]
18:29:17 DEBUG [or.te.sh.or.ze.ex.WaitForProcess] (WaitForProcess-Process[pid=19674, exitValue="not exited"]) Process[pid=19674, exitValue=1] stopped with exit code 1
18:29:17 INFO  [or.te.ut.RegistryAuthLocator] (Agroal_10500229751) Credential helper/store (docker-credential-desktop) does not have credentials for mcr.microsoft.com
18:29:17 DEBUG [or.te.ut.RegistryAuthLocator] (Agroal_10500229751) no matching Auth Configs - falling back to defaultAuthConfig [null]
18:29:17 DEBUG [or.te.do.au.AuthDelegatingDockerClientConfig] (Agroal_10500229751) Effective auth config [null]
18:29:17 INFO  [🐳.mi.com/mssql/server:latest]] (Agroal_10500229751) Starting container with ID: e0a18cb4cc95c9c8b4d3f0000547da9dd8fbdf6de993a485e4eb2cfc13f7ca7c
18:29:18 INFO  [🐳.mi.com/mssql/server:latest]] (Agroal_10500229751) Container mcr.microsoft.com/mssql/server:latest is starting: e0a18cb4cc95c9c8b4d3f0000547da9dd8fbdf6de993a485e4eb2cfc13f7ca7c
18:11:02 ERROR [io.qu.application] (main) Failed to start application: java.lang.NoSuchMethodError: 'java.lang.String org.testcontainers.containers.MSSQLServerContainer.getHost()'
	at org.testcontainers.containers.MSSQLServerContainer.getJdbcUrl(MSSQLServerContainer.java:66)
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:127)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:428)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:317)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:315)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:302)
	at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:118)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:200)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:419)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:401)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:65)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

This happens on my local machine and on our CI.

The container does get created, see:
```
e0a18cb4cc95        mcr.microsoft.com/mssql/server:latest   "/opt/mssql/bin/perm…"   7 seconds ago       Up 6 seconds        0.0.0.0:32776->1433/tcp                           zealous_hermann
```

We define the dependency as:
```
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>mssqlserver</artifactId>
            <version>1.14.3</version>
        </dependency>
```

Any idea what is going wrong here? I'm happy to help or provide more information.

**Comment by bsideup** [comment]
You have an issue with the classpath. org.testcontainers:testcontainers dependency must also be updated to 1.14.3 (you should get it transitively)
