### ISSUE TITLE
Failed to start component [/manager]

### ISSUE THREAD

**Issue by jj-vicente** [testcontainers/testcontainers-java#3121]
Hi,

I have installed pinpoint web 2.0.3 into  Apache Tomcat/7.0.72. Then renamed pinpoint-web-2.0.3.war to ROOT.war and it was deployed successfully without error. But after checking my Collector logs which is also running on different tomcat instance on the same server I got below error. Is anyone encounter these error?

Aug 18, 2020 8:33:28 AM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2020-08-18T08:33:29.029 PinpointCollectorApplicationInitializer::ActiveProfile:release
2020-08-18 08:33:31 [WARN ](o.a.h.u.NativeCodeLoader           ) Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2020-08-18 08:33:38 [WARN ](c.n.p.c.m.j.JMXCollectorManagerList) not activating jmx api for admin.
Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /opt/CTCOppCollector203/webapps/ppCollector203.war has finished in 15,474 ms
Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /opt/CTCOppCollector203/webapps/docs
Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /opt/CTCOppCollector203/webapps/docs has finished in 28 ms
Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /opt/CTCOppCollector203/webapps/ROOT
Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /opt/CTCOppCollector203/webapps/ROOT has finished in 28 ms
Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /opt/CTCOppCollector203/webapps/examples
Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /opt/CTCOppCollector203/webapps/examples has finished in 140 ms
Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /opt/CTCOppCollector203/webapps/manager
Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.HostConfig deployDirectory
SEVERE: The web application with context path [/manager] was not deployed because it contained a deployment descriptor [/opt/CTCOppCollector203/webapps/manager/META-INF/context.xml] which may include configuration necessary for the secure deployment of the application but processing of deployment descriptors is prevented by the deployXML setting of this host. An appropriate descriptor should be created at [/opt/CTCOppCollector203/conf/Catalina/localhost/manager.xml] to deploy this application.
Aug 18, 2020 8:33:40 AM org.apache.catalina.core.ContainerBase addChildInternal
SEVERE: ContainerBase.addChild: start:
org.apache.catalina.LifecycleException: Failed to start component [/manager]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1260)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2002)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.catalina.LifecycleException: Failed to process either the global, per-host or context-specific context.xml file therefore the [/manager] Context cannot be started.
        at org.apache.catalina.startup.FailedContext.startInternal(FailedContext.java:158)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        ... 10 more

Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.HostConfig deployDirectory
SEVERE: Error deploying web application directory /opt/CTCOppCollector203/webapps/manager
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [/manager]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:903)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1260)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2002)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /opt/CTCOppCollector203/webapps/manager has finished in 25 ms
Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /opt/CTCOppCollector203/webapps/host-manager
Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.HostConfig deployDirectory
SEVERE: The web application with context path [/host-manager] was not deployed because it contained a deployment descriptor [/opt/CTCOppCollector203/webapps/host-manager/META-INF/context.xml] which may include configuration necessary for the secure deployment of the application but processing of deployment descriptors is prevented by the deployXML setting of this host. An appropriate descriptor should be created at [/opt/CTCOppCollector203/conf/Catalina/localhost/host-manager.xml] to deploy this application.
Aug 18, 2020 8:33:40 AM org.apache.catalina.core.ContainerBase addChildInternal
SEVERE: ContainerBase.addChild: start:
org.apache.catalina.LifecycleException: Failed to start component [/host-manager]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1260)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2002)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.catalina.LifecycleException: Failed to process either the global, per-host or context-specific context.xml file therefore the [/host-manager] Context cannot be started.
        at org.apache.catalina.startup.FailedContext.startInternal(FailedContext.java:158)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        ... 10 more

Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.HostConfig deployDirectory
SEVERE: Error deploying web application directory /opt/CTCOppCollector203/webapps/host-manager
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [/host-manager]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:903)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1260)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2002)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /opt/CTCOppCollector203/webapps/host-manager has finished in 5 ms
Aug 18, 2020 8:33:40 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8081"]
Aug 18, 2020 8:33:40 AM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8010"]
Aug 18, 2020 8:33:40 AM org.apache.catalina.startup.Catalina start
INFO: Server startup in 15866 ms

**Comment by jj-vicente** [comment]
add deployXML="true" to the Host element in server.xml
