### ISSUE TITLE
org.testcontainers.containers.ContainerFetchException: Retry limit reached while trying to pull image: selenium/standalone-chrome-debug:3.3.1

### ISSUE THREAD

**Issue by iirekm** [testcontainers/testcontainers-java#319]
```
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image name from org.testcontainers.images.RemoteDockerImage@5254d860
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:739)
	at org.testcontainers.containers.GenericContainer.setDockerImageName(GenericContainer.java:727)
	at org.testcontainers.containers.BrowserWebDriverContainer.configure(BrowserWebDriverContainer.java:86)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:166)
	... 30 more
Caused by: org.testcontainers.containers.ContainerFetchException: Retry limit reached while trying to pull image: selenium/standalone-chrome-debug:3.3.1
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:79)
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:21)
	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:27)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:737)
	... 33 more
```

The latest version available at DockerHub (today) is 3.3.0, not 3.3.1. Why it wants to pull 3.3.1?

**Comment by iirekm** [comment]
Ok, I found that the version is determined from version of webdriver:
```
testCompile group: 'org.seleniumhq.selenium', name: 'selenium-remote-driver', version: '3.3.1'
```
Recent webdriver in maven repo is 3.3.1, but on docker hub is 3.3.0.

Shouldn't webdriver be added as a transitive dependency to TestContainers? It would solve the problem, and be easier for the programmer.

**Comment by rnorth** [comment]
Re the transitive dependency, I didn't want to lock testcontainers users into a single version of selenium. I worried that if we did that, we'd quickly become a bottleneck and source of frustration for users. 

With the automatic fetch of the matching version container we are at the mercy of the selenium team to keep their container images released in sync with the Java libs. But for the most part they're fairly good, and are better placed to keep things in line than we are.

In this situation, you have the choice of using the 3.3.0 Selenium Java library with the 3.3.0 Docker image (which I'd strongly recommend), or the 3.3.1 library with the 3.3.0 container. You can force this with: `new BrowserWebDriverContainer("selenium/standalone-chrome-debug:3.3.1") ...`

I'd recommend using the same versions though - part of the reason for testcontainers' selenium support existing is painful experiences of mismatched library/browser extension versions!

Does this answer the question?

**Comment by rnorth** [comment]
I'll close this as I hope this answers the question - please re-open if not.
