### ISSUE TITLE
 Can not connect to Ryuk at localhost:32768 issue on Docker Edge

### ISSUE THREAD

**Issue by joao-dantas** [testcontainers/testcontainers-java#3241]
I'm getting this error while trying to run tests with Test Containers in Docker 2.3.7.0 Edge.
Version: 1.14.3

`Sep 19, 2020 4:13:41 PM org.testcontainers.utility.ResourceReaper lambda$null$1
WARN: Can not connect to Ryuk at localhost:32768
java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:608)
        at java.base/java.net.Socket.connect(Socket.java:557)
        at java.base/java.net.Socket.<init>(Socket.java:453)
        at java.base/java.net.Socket.<init>(Socket.java:230)
        at org.testcontainers.utility.ResourceReaper.lambda$null$1(ResourceReaper.java:138)
        at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
        at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:136)
        at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by bsideup** [comment]
fixed in #3159

**Comment by joao-dantas** [comment]
Nice. @bsideup where I can find details about release plan?

**Comment by bsideup** [comment]
@joao-dantas we plan to release a new RC that includes that PR later this week. For now, consider switching back the stable channel of Docker
