### ISSUE TITLE
Cannot use KMS GenerateDataKeyPair command with localstack

### ISSUE THREAD

**Issue by gaggarwal21** [testcontainers/testcontainers-java#3294]
I am using localstack for mocking KMS locally to test my APIs and I need to generate data key pairs. When calling generateDataKeyPair(), I get the following exception. Is it not supported currently?

    com.amazonaws.services.kms.model.AWSKMSException: null (Service: AWSKMS; Status Code: 501; Error Code: null; Request ID: null; Proxy: null)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1811)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1395)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1371)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1145)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:802)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:770)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:744)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:704)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:686)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:550)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:530)
        at com.amazonaws.services.kms.AWSKMSClient.doInvoke(AWSKMSClient.java:5863)
        at com.amazonaws.services.kms.AWSKMSClient.invoke(AWSKMSClient.java:5830)
        at com.amazonaws.services.kms.AWSKMSClient.invoke(AWSKMSClient.java:5819)
        at com.amazonaws.services.kms.AWSKMSClient.executeGenerateDataKeyPair(AWSKMSClient.java:3047)
        at com.amazonaws.services.kms.AWSKMSClient.generateDataKeyPair(AWSKMSClient.java:3018)

**Comment by rnorth** [comment]
I'm afraid I'll have to bounce you over to the Localstack project. Testcontainers just uses the Docker image they provide, so if there's a limitation in what they support you'd need to ask them: https://github.com/localstack/localstack
