### ISSUE TITLE
Can't start WebDriverContainers

### ISSUE THREAD

**Issue by rmarinsky** [testcontainers/testcontainers-java#339]
I see following exeption`Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:90)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:83)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:111)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:146)
	at org.testcontainers.containers.BrowserWebDriverContainer.<init>(BrowserWebDriverContainer.java:57)
	at utils.BaseUITest.<clinit>(BaseUITest.java:20)`

I have Windows 10 Pro, in hyper-v manager i see that runnig 2 machines 'default' and 'MobyLinuxVM'
But when i run docker-machine ls - i see only 'default' machine running

I have installed DockerToolbox. 
Docker version: 17.03.1-ce

**Comment by rnorth** [comment]
Hi @rmarinsky 

It sounds like it's having trouble identifying your Docker setup I'm afraid. Would I be right in thinking that `default` is a docker machine VM, but you also have Docker for Windows installed as `MobyLinuxVM`?

Could you share earlier logs, perhaps at debug level for `org.testcontainers`? Just before the message you've posted there should be a description of what it tried and what the outcomes were.
Thanks
Richard

**Comment by rmarinsky** [comment]
That is all log:
`java.lang.ExceptionInInitializerError
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:90)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:83)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:111)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:146)
	at org.testcontainers.containers.BrowserWebDriverContainer.<init>(BrowserWebDriverContainer.java:57)
	at BaseTest.<clinit>(BaseTest.java:14)`

`deafult` docker machine with a hyperv driver

**Comment by rmarinsky** [comment]
So, who can help me?

**Comment by bsideup** [comment]
Does it happen with Docker for Windows?

**Comment by rmarinsky** [comment]
@bsideup yes, Docker for Windows, not the Docker Toolbox

**Comment by rmarinsky** [comment]
@bsideup How can I configure that I don't want to start containers if it needed for some machines?
because in GenericContainer's constructor used DockerClientFactory.instance().client(); - and it always check strategy for starting containers even if I create my custom BrowserWebDriverContainer rules for start tests

**Comment by rmarinsky** [comment]
So... It was almost my totally fault. I'va fully uninstal "Docker for Windows" and install "Docker Toolbox" (which on site docker marked as "For old windows OSs and for macos")
And after works fine

And about configuration i used ? : and it work perfectly
```
@ClassRule
    public static BrowserWebDriverContainer chromeDockerContainer = startWebDriverDocker() ? new BrowserWebDriverContainer().withDesiredCapabilities(DesiredCapabilities.chrome())
            .withRecordingMode(BrowserWebDriverContainer.VncRecordingMode.RECORD_FAILING, new File("./build/")) : null;
```

Thanks and sorry for attantion :(
