### ISSUE TITLE
Make SolrContainer reusable

### ISSUE THREAD

**Issue by as-design** [testcontainers/testcontainers-java#3436]
Please make SolrContainer reusable. The container needs a bit of time to startup. For local testing it would be helpful if the container could be reused.

Maybe only the method `containerIsStarted(InspectContainerResponse containerInfo, boolean reused)` needs to be overridden like in the following way
```  
  @Override
  protected void containerIsStarted(InspectContainerResponse containerInfo, boolean reused) {
    if(!reused){
      super.containerIsStarted(containerInfo);
    }
  }
```

**Comment by eddumelendez** [comment]
The issue is not in Testcontainers itself but in the creation of the dummy collection in Solr.

Logs displayed the attempt to reuse the container

```
18:54:25.038 INFO  tc.solr:8.5.0 - Reusing container with ID: 51c7b6cb2382256188ec85a2d5377857188b38e03d29c1ec3e854d747c54d236 and hash: d97776dd97aaceef5bb5f9b16837d7ee92195f23
18:54:25.038 INFO  tc.solr:8.5.0 - Reusing existing container (51c7b6cb2382256188ec85a2d5377857188b38e03d29c1ec3e854d747c54d236) and not creating a new one
```

However, the failure reason is

```
2023-07-13 00:54:26.263 ERROR (OverseerThreadFactory-9-thread-2-processing-n:localhost:8983_solr) [   ] o.a.s.c.a.c.OverseerCollectionMessageHandler Collection: dummy operation: create failed:org.apache.solr.common.SolrException: collection already exists: dummy
	at org.apache.solr.cloud.api.collections.CreateCollectionCmd.call(CreateCollectionCmd.java:116)
	at org.apache.solr.cloud.api.collections.OverseerCollectionMessageHandler.processMessage(OverseerCollectionMessageHandler.java:263)
	at org.apache.solr.cloud.OverseerTaskProcessor$Runner.run(OverseerTaskProcessor.java:504)
```

Don't know much about Solr but if there is a way to disable the dummy creation then I think the container can be reused.
