### ISSUE TITLE
Shading issue in selenium testcontainer

### ISSUE THREAD

**Issue by pawel-kowalski** [testcontainers/testcontainers-java#353]
Hi ,

First of all congratulate you great library I'm excited to use it, however I have issue with dependencies. 
Selenium testcontainer (v 1.2.1) does not shade some dependencies. Especially in my case I have conflict with jackson-databind causing error:
```
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.datatype.jsr310.deser.JSR310DateTimeDeserializerBase.findFormatOverrides(Lcom/fasterxml/jackson/databind/DeserializationContext;Lcom/fasterxml/jackson/databind/BeanProperty;Ljava/lang/Class;)Lcom/fasterxml/jackson/annotation/JsonFormat$Value;
at com.fasterxml.jackson.datatype.jsr310.deser.JSR310DateTimeDeserializerBase.createContextual(JSR310DateTimeDeserializerBase.java:32) ~[jackson-datatype-jsr310-2.8.8.jar:2.8.8]
at com.fasterxml.jackson.datatype.jsr310.deser.InstantDeserializer.createContextual(InstantDeserializer.java:227) ~[jackson-datatype-jsr310-2.8.8.jar:2.8.8]
at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:669) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:430) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:947) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:439) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:428) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:164) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(CollectionDeserializer.java:25) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.DeserializationContext.handleSecondaryContextualization(DeserializationContext.java:669) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:430) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.deser.std.StdDeserializer.findDeserializer(StdDeserializer.java:947) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(BeanDeserializerBase.java:439) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:296) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:461) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.ObjectReader._prefetchRootDeserializer(ObjectReader.java:1791) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.ObjectReader.<init>(ObjectReader.java:205) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.ObjectMapper._newReader(ObjectMapper.java:623) ~[selenium-1.2.1.jar:na]
at com.fasterxml.jackson.databind.ObjectMapper.reader(ObjectMapper.java:3317) ~[selenium-1.2.1.jar:na]
```
JSR310DateTimeDeserializer in my case (v 2.8.8) calls method from StdDeserializer that is loaded from testcontainer:selenium jar and this version does not provide this method :( 

Is there chance to have shaded version released ? 
Best regards,
Pawel

**Comment by bsideup** [comment]
Hi @pawel-kowalski,

Thanks for reporting! This is indeed a bug, we will take a look. 

FYI we just released 1.3.0, could you please try it?
