### ISSUE TITLE
Cannot run on ubuntu 20.04

### ISSUE THREAD

**Issue by strowk** [testcontainers/testcontainers-java#3553]
I am using jdk8 

```
$JAVA_HOME/bin/java -version 
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
```
and maven
```
mvn  --version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 1.8.0_275, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-42-generic", arch: "amd64", family: "unix"
```
with testcontainers `1.15.0`
and have `docker` installed
```
docker --version
Docker version 19.03.14, build 5eb3275d40
```
and it configured to work without sudo.

I am getting "Could not find a valid Docker environment".

I expect it to be able to use socket `srw-rw---- 1 root docker 0 Dez  4 12:11 /var/run/docker.sock`
, but I see in log 

```
2020-12-04T12:29:51,433 [ERROR] [d.DockerClientProviderStrategy]     UnixSocketClientProviderStrategy: failed with exception TimeoutException (Timeout waiting for result with exception). Root cause IOException (native connect() failed : Permission denied) 
```

This is stacktrace:
```
        Exception encountered when invoking run on a nested suite - Could not find a valid Docker environment. Please see logs and check configuration
        java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:214)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:206)
        at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:134)
        at org.testcontainers.DockerClientFactory.getTransportConfig(DockerClientFactory.java:140)
        at org.testcontainers.DockerClientFactory.getRemoteDockerUnixSocketPath(DockerClientFactory.java:150)
        at org.testcontainers.containers.localstack.LocalStackContainer.<init>(LocalStackContainer.java:96)
    at org.testcontainers.containers.localstack.LocalStackContainer.<init>(LocalStackContainer.java:82)
        at org.testcontainers.containers.localstack.LocalStackContainer.<init>(LocalStackContainer.java:75)
            at com.dimafeng.testcontainers.LocalStackContainer.<init>(LocalStackContainer.scala:13)
                at com.dimafeng.testcontainers.LocalStackContainer$Def.createContainer(LocalStackContainer.scala:40)
                at com.dimafeng.testcontainers.LocalStackContainer$Def.createContainer(LocalStackContainer.scala:30)
                at com.dimafeng.testcontainers.ContainerDef.start(ContainerDef.scala:13)
                at com.dimafeng.testcontainers.ContainerDef.start$(ContainerDef.scala:12)
                at com.dimafeng.testcontainers.LocalStackContainer$Def.start(LocalStackContainer.scala:30)
```

What should I do to make it see the docker? 

When I run `docker ps` there is no problem and it works quite fast.

**Comment by strowk** [comment]
fixed after rebooting (no idea why honestly)

**Comment by bsideup** [comment]
@strowk I guess you just installed Docker and added your user to the `docker` group, but it requires a re-login to be applied. That said, I am glad that you get it solved 👍
