### ISSUE TITLE
Could not connect to Ryuk - Linux, Docker 20.10.0, 1.15.0-rc2

### ISSUE THREAD

**Issue by ullrichp** [testcontainers/testcontainers-java#3572]
As this is my first issue i would like to say "Thank you" to all maintainers and contributors.

Apparently, out of nothing my tests started to throw:
```
Caused by: java.lang.IllegalStateException: Could not connect to Ryuk at localhost:49160
	at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:171)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:201)
	at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
	at org.testcontainers.LazyDockerClient.listImagesCmd(LazyDockerClient.java:12)
	at org.testcontainers.images.LocalImagesCache.maybeInitCache(LocalImagesCache.java:68)
	at org.testcontainers.images.LocalImagesCache.get(LocalImagesCache.java:32)
	at org.testcontainers.images.AbstractImagePullPolicy.shouldPull(AbstractImagePullPolicy.java:18)
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:65)
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:26)
	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:17)
	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:39)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1280)
	... 266 more
```

I am on Linux with:
openjdk 11.0.8 2020-07-14
testcontainers 1.15.0-rc2
docker 20.10.0

The container seems to start:
```
$ docker ps -a
CONTAINER ID   IMAGE                       COMMAND   CREATED        STATUS                  PORTS                     NAMES
85335add1def   testcontainers/ryuk:0.3.0   "/app"    1 second ago   Up Less than a second   0.0.0.0:49160->8080/tcp   testcontainers-ryuk-2b08ab75-8559-48fc-8f73-8d233b45c430
```

and the logs do not seem too wrong:
```
$ docker logs 85335add1def
2020/12/09 09:47:37 Pinging Docker...
2020/12/09 09:47:37 Docker daemon is available!
2020/12/09 09:47:37 Starting on port 8080...
2020/12/09 09:47:37 Started!
```

Still, the above exception happens after the default timeout of 30 seconds.

Let me know if you need more information, stack traces or logs.

**Comment by bsideup** [comment]
Hi @ullrichp,

Thanks for your kind words! :)

Have you tried the latest release (1.15.0)? Also, does it work if you attempt to connect to Ryuk from CLI?

**Comment by arhohuttunen** [comment]
Experiencing the same out of the blue when executing in EC2, this was still working this morning. The stack trace has this:

```
Caused by:
3530                        org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=postgres:11.8-alpine, imagePullPolicy=DefaultPullPolicy())
3531                            at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1278)
3532                            at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:612)
3533                            at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:317)
3534                            ... 114 more
3535                            Caused by:
3536                            com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"No such image: testcontainers/ryuk:0.3.0"}
```

But looking at the Docker Hub that image does exists there.

**Comment by bsideup** [comment]
@arhohuttunen you issue seems to be different and caused by the registry returning 404 for an image that exists.

**Comment by arhohuttunen** [comment]
My mistake, was too hasty to draw conclusions between the two issues.

**Comment by swierszczu4j** [comment]
I have exactly the same issue on latest (1.15.0). What is more seems to be not-deterministic one :/ Anyway seems like they are some compatibility issues with the newest docker.

**Comment by amelnikov-mylivn** [comment]
> Experiencing the same out of the blue when executing in EC2, this was still working this morning. The stack trace has this:
> 
> ```
> Caused by:
>     org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=postgres:11.8-alpine, imagePullPolicy=DefaultPullPolicy())
>     at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1278)
>     at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:612)
>     at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:317)
>     ... 114 more
>         Caused by:
>         com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"No such image: testcontainers/ryuk:0.3.0"}
> ```
> 
> But looking at the Docker Hub that image does exists there.

We had the same issue today. Temporary fixed by pinning docker version to 19.03.

**Comment by jdelucaa** [comment]
@amelnikov-mylivn what does it have to do with the docker version? have they changed anything in the latest version?

**Comment by KyleAure** [comment]
I am also seeing the same issue with the stack trace: 
```
[12/09/2020 11:09:31:957 CST] 040 ResourceReaper                 lambda$null$1                  W Can not connect to Ryuk at localhost:32769
java.net.SocketException: Protocol wrong type for socket (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:138)
	at org.testcontainers.utility.ResourceReaper$FilterRegistry.register(ResourceReaper.java:406)
	at org.testcontainers.utility.ResourceReaper.lambda$null$1(ResourceReaper.java:135)
	at org.testcontainers.utility.ResourceReaper$$Lambda$131/000000002833D020.run(Unknown Source)
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
	at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:119)
	at org.testcontainers.utility.ResourceReaper$$Lambda$130/00000000279F0A20.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by croudet** [comment]
Also got {{com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"No such image: testcontainers/ryuk:0.3.0"}}}

Looks like related to docker version:
Working version:
{noformat}
13:02:20.718 [main] INFO org.testcontainers.DockerClientFactory - Connected to docker: 
  Server Version: 19.03.14
  API Version: 1.40
  Operating System: Ubuntu 16.04.4 LTS
  Total Memory: 31907 MB
{noformat}
Non working version:
{noformat}
19:03:20.528 [main] INFO org.testcontainers.DockerClientFactory - Connected to docker: 
  Server Version: 20.10.0
  API Version: 1.41
  Operating System: Ubuntu 16.04.4 LTS
  Total Memory: 31907 MB
{noformat}

**Comment by jdelucaa** [comment]
I am also seeing this `com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: quay.io/testcontainers/ryuk:0.3.0"}`

**Comment by amelnikov-mylivn** [comment]
> @amelnikov-mylivn what does it have to do with the docker version? have they changed anything in the latest version?

Honestly idk, I did not dig enough into. Our CI runs on spot EC2 instances which are created for each task. Today builds started to fail with `404 No such image`. We wasted most of the day, nothing helped, but when found that docker 20.10 appeared in repos yesterday, we pinned its version to an old one, and it worked. 

P.S. Sorry for the off-topic.

**Comment by gesellix** [comment]
A manual `docker pull testcontainers/ryuk:0.3.0` helps. Without having debugged the issue, yet, it seems like docker-java doesn't transparently pull the missing image on status code 404. This should be the default behaviour.
I'm also running into this issue using the recent Docker for Mac 2.5.4/Docker Engine 20.10.0-rc2.

**Comment by bsideup** [comment]
> Without having debugged the issue, yet, it seems like docker-java doesn't transparently pull the missing image on status code 404.

It doesn't, yes.

> This should be the default behaviour.

Why? `404` is "not found" and 4xx type of an http code, non-retriable. I don't think registries should return 404 for images that exist.

**Although** the original issue report is talking about some other, TCP related issue, so please consider reporting 404 separately, **this is some other issue**.

**Comment by gesellix** [comment]
Filed an issue for "No such image: testcontainers/ryuk:0.3.0" (Status 404) at #3574.
Sorry for the spam.

**Comment by rnorth** [comment]
I'm trying to reproduce this TCP/connection to Ryuk issue, but haven't managed to so far 😬 

Using a fresh VM with Ubuntu 20.04 (LTS) x64 and Docker version 20.10.0, build 7287ab3

I'm testing with 1.15-0rc2, 1.15.0 and master/HEAD and so far not able to reproduce. Will continue to try.

**Comment by ullrichp** [comment]
> Have you tried the latest release (1.15.0)?

Yes, i get the same exception.

> Also, does it work if you attempt to connect to Ryuk from CLI?

I assume you mean `$ docker attach` -> Apparenlty, no. That seems not to be possible:
```
$ docker ps -a
CONTAINER ID        IMAGE                       COMMAND             CREATED                  STATUS              PORTS               NAMES
e2fa3727c9aa        testcontainers/ryuk:0.3.0   "/app"              Less than a second ago   Created                                 testcontainers-ryuk-e31ea349-ae04-4762-9c9d-c45e600d4b19
$ docker attach e2fa3727c9aa
panic: Timed out waiting for the initial connection

goroutine 1 [running]:
main.main()
        /go/src/github.com/testcontainers/moby-ryuk/main.go:104 +0xce7
```

**Comment by rnorth** [comment]
@ullrichp your last docker ps output doesn't seem to have any listening ports listed for ryuk, whereas your first does. This seems very strange.

Out of interest, which Linux distro and version are you using?

**Comment by ullrichp** [comment]
I played a little with my docker installation and are now back to version 19.03.14. Maybe the output changes because of that.

I am using Gentoo.

**Comment by asaikali** [comment]
I am having the same issue on ubuntu 20.04 with 
 
```
$ docker --version
Docker version 20.10.0, build 7287ab3
```

Test containers 1.14.3 works but 1.15.0 I get the exception saying there is no ryuk image. Stack trace below 

 ```
       Caused by:
        java.lang.IllegalStateException: Failed to load ApplicationContext
            at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132)
            at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:123)
            at org.springframework.test.context.junit.jupiter.SpringExtension.getApplicationContext(SpringExtension.java:207)
            at org.springframework.test.context.junit.jupiter.SpringExtension.resolveParameter(SpringExtension.java:193)
            at org.junit.jupiter.engine.execution.ExecutableInvoker.resolveParameter(ExecutableInvoker.java:216)
            ... 65 more

            Caused by:
            org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Container startup failed
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
                at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
                at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
                at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
                at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
                at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1161)
                at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915)
                at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588)
                at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
                at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
                at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
                at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
                at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:122)
                at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
                at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
                ... 69 more

                Caused by:
                com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Container startup failed
                    at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:595)
                    at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:581)
                    at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
                    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
                    at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:57)
                    at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:69)
                    at org.flywaydb.core.Flyway.execute(Flyway.java:475)
                    at org.flywaydb.core.Flyway.migrate(Flyway.java:164)
                    at com.programmingmastery.database.schema.SchemaManagerImpl.migrate(SchemaManagerImpl.java:72)
                    at com.programmingmastery.database.schema.SchemaManagerImpl.migrate(SchemaManagerImpl.java:54)
                    at com.programmingmastery.database.schema.MigrationStrategy.migrate(MigrationStrategy.java:24)
                    at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:62)
                    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1847)
                    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784)
                    ... 87 more

                    Caused by:
                    org.testcontainers.containers.ContainerLaunchException: Container startup failed
                        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:327)
                        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:308)
                        at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:118)
                        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
                        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
                        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
                        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
                        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
                        ... 99 more

                        Caused by:
                        org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=postgres:12, imagePullPolicy=DefaultPullPolicy())
                            at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1278)
                            at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:612)
                            at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:317)
                            ... 106 more

                            Caused by:
                            com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"No such image: testcontainers/ryuk:0.3.0"}
                                at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:241)
                                at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:125)
                                at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:33)
                                at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13)
                                at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
                                at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
                                at org.testcontainers.shaded.com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:595)
                                at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:91)
                                at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:203)
                                at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
                                at org.testcontainers.LazyDockerClient.listImagesCmd(LazyDockerClient.java:12)
                                at org.testcontainers.images.LocalImagesCache.maybeInitCache(LocalImagesCache.java:68)
                                at org.testcontainers.images.LocalImagesCache.get(LocalImagesCache.java:32)
                                at org.testcontainers.images.AbstractImagePullPolicy.shouldPull(AbstractImagePullPolicy.java:18)
                                at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:66)
                                at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:27)
                                at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:17)
                                at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:39)
                                at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1276)
                                ... 108 more

```

**Comment by youagree** [comment]
i have the same problem

![image_2020_12_11T10_59_01_182Z](https://user-images.githubusercontent.com/53233091/101896104-861d7c80-3bb9-11eb-8399-47f41228ffce.png)
![image_2020_12_11T10_58_19_649Z](https://user-images.githubusercontent.com/53233091/101896144-92a1d500-3bb9-11eb-99e5-22e0d7d1071e.png)

**Comment by sparsick** [comment]
Same here with Ubuntu 20.04, Docker 20.10 and Testcontainer 1.15.0. With a downgrade to docker version 19.03.14 everything is fine.

**Comment by bsideup** [comment]
FYI 1.15.1 is released and fixes "No such image" issue (#3574). Please only comment if you still see the issue with 1.15.1 *and* and it related to TCP connectivity, not image pulling. Thanks.

**Comment by ullrichp** [comment]
I found out that my issue must be related to the VPN i am connected to.
When i turn if off everything works fine. 
When i am connected i get those connection problems. Will try to figure out whats going on with my networking.

Thanks so far.

**Comment by uzoltan** [comment]
I still get 

`Caused by: java.lang.IllegalStateException: Could not connect to Ryuk at localhost:55003
	at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:198)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:205)
	at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
	at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:310)`

:(

Docker version: 20.10.0 (docker for windows 3.0.0)
+
    testImplementation "org.testcontainers:mysql:1.15.1"
    testImplementation "org.testcontainers:testcontainers:1.15.1"

**Comment by bsideup** [comment]
@uzoltan could you please share full logs?

**Comment by uzoltan** [comment]
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.1.RELEASE)

2020-12-15 10:33:24.017  INFO [ocpi-command,,,] 8572 --- [           main] o.t.d.DockerClientProviderStrategy       : Loaded org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2020-12-15 10:33:24.587  INFO [ocpi-command,,,] 8572 --- [           main] o.t.d.DockerClientProviderStrategy       : Found Docker environment with local Npipe socket (npipe:////./pipe/docker_engine)
2020-12-15 10:33:24.588  INFO [ocpi-command,,,] 8572 --- [           main] org.testcontainers.DockerClientFactory   : Docker host IP address is localhost
2020-12-15 10:33:24.623  INFO [ocpi-command,,,] 8572 --- [           main] org.testcontainers.DockerClientFactory   : Connected to docker: 
  Server Version: 20.10.0
  API Version: 1.41
  Operating System: Docker Desktop
  Total Memory: 1989 MB
2020-12-15 10:33:24.627  INFO [ocpi-command,,,] 8572 --- [           main] o.t.utility.ImageNameSubstitutor         : Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2020-12-15 10:33:24.876  INFO [ocpi-command,,,] 8572 --- [           main] o.t.utility.RegistryAuthLocator          : Credential helper/store (docker-credential-desktop) does not have credentials for index.docker.io
2020-12-15 10:33:28.928  WARN [ocpi-command,,,] 8572 --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Can not connect to Ryuk at localhost:55005

java.net.ConnectException: Connection refused: connect
	at java.base/java.net.PlainSocketImpl.connect0(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at java.base/java.net.Socket.connect(Socket.java:540)
	at java.base/java.net.Socket.<init>(Socket.java:436)
	at java.base/java.net.Socket.<init>(Socket.java:213)
	at org.testcontainers.utility.ResourceReaper.lambda$null$1(ResourceReaper.java:160)
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
	at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:158)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by bsideup** [comment]
@uzoltan thanks! Do you happen to have some VPN or anything else that might affect the network?
Maybe you issue is similar to @ullrichp's:
https://github.com/testcontainers/testcontainers-java/issues/3572#issuecomment-744417283

**Comment by uzoltan** [comment]
No VPN, docker doesn't run local kube cluster either, I only have 1 other mongo container running on 27017.

**Comment by ullrichp** [comment]
FYI: I solved all my issues with correctly configuring strongswan VPN with the bypass-lan plugin. Turns out its not done automatically and all local trafffic was send to the VPN.

**Comment by zapho** [comment]
Same issue here (1.15.1 and TCP connectivity), resolved by stopping VPN (Cisco AnyConnect) then restarting Docker for Windows then (re)starting VPN. Could not reproduce the issue after that though. Did not try 'Allow local LAN access', will do next time.

**Comment by gvandeglind** [comment]
Encountered the same issue (1.15.2, ubuntu 20.04 LTS with ufw enabled). It turns out that the Ryuk container is started on the default bridge network, while my other containers are started in my custom bridge network. Then the ufw firewall doesn't allow communication between these private networks, which I could resolve by adding rules. A nicer solution for me would be if I could specify in which network the Ryuk container is started, but I can't find that anywhere, such that it also starts in my custom bridge network.

**Comment by luke-gee** [comment]
Encountering this issue after updating docker desktop on Windows to the latest version version 3.4.0 (65384)

**Comment by AlexanderArgyriou** [comment]
any update here ?
