### ISSUE TITLE
fixed memory regions require x which is greater than y available for allocation

### ISSUE THREAD

**Issue by conanchen** [testcontainers/testcontainers-java#3692]
I have an springboot project to build an docker image by spring-boot:build-image. 

How can I decrease the memory used by testcontainer docker?

2021-01-18 10:19:23.421 ERROR 99720 --- [ers-lifecycle-0] 🐳 [sample/sample-dockerspringboot:latest]    : Log output from the failed container:
Setting Active Processor Count to 4

unable to calculate memory configuration

Calculating JVM memory based on 523244K available memory

fixed memory regions require 704588K which is greater than 523244K available for allocation: -XX:MaxDirectMemorySize=10M, -XX:MaxMetaspaceSize=192588K, -XX:ReservedCodeCacheSize=240M, -Xss1M * 250 threads

2021-01-18 10:19:23.435 ERROR 99720 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.util.concurrent.CompletionException: org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330) ~[testcontainers-1.15.1.jar:na]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311) ~[testcontainers-1.15.1.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) ~[na:na]
	... 4 common frames omitted

**Comment by artjomka** [comment]
Hello,
I am right that you are using [CNB](https://buildpacks.io/) to build image and then to use that image in some Testcontainers test ?
