### ISSUE TITLE
Testcontainers fails on free disk space of more than 2TB

### ISSUE THREAD

**Issue by chibenwa** [testcontainers/testcontainers-java#379]
```
[Building Java 8] log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[Building Java 8]         ℹ︎ Checking the system... 
[Building Java 8]         ✔ Docker version is newer than 1.6.0 
[Building Java 8] java.lang.NumberFormatException: For input string: "2982480572"
[Building Java 8] 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[Building Java 8] 	at java.lang.Integer.parseInt(Integer.java:583)
[Building Java 8] 	at java.lang.Integer.valueOf(Integer.java:766)
[Building Java 8] 	at org.testcontainers.DockerClientFactory.parseAvailableDiskSpace(DockerClientFactory.java:250)
[Building Java 8] 	at org.testcontainers.DockerClientFactory.checkDiskSpace(DockerClientFactory.java:165)
[Building Java 8] 	at org.testcontainers.DockerClientFactory.lambda$client$1(DockerClientFactory.java:126)
[Building Java 8] 	at org.testcontainers.DockerClientFactory.runInsideDocker(DockerClientFactory.java:229)
[Building Java 8] 	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:117)
[Building Java 8] 	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:110)
[ ............. ]
[Building Java 8] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

IMO disk space should be represented as a long.

**Comment by bsideup** [comment]
Hi @chibenwa,

Wow, that's awkward :D 

I'll fix it now. 
Meanwhile, you can put `checks.disable=true` to `$HOME/.testcontainers.properties` file.

Thanks for reporting!

**Comment by chibenwa** [comment]
Ah ok, thanks for giving me a temporary fix. It seems better than creating a ~ 800GB file, what I was going to do...

However I run testcontainer from a docker container (we have a CI that launches Docker containers for multiple reasons), is there a way to read these kinds of properties from the classpath?

**Comment by bsideup** [comment]
Sure, it will merge home folder's config with classpath's one called `testcontainers.properties`

**Comment by chibenwa** [comment]
Nice ;-) Thanks for your helpfull support!

**Comment by bsideup** [comment]
@chibenwa PR is ready, you can try it with JitPack:
https://jitpack.io/#testcontainers/testcontainers-java/fix_available_space_detection-SNAPSHOT
