### ISSUE TITLE
Could not find the file /newScreen.mp4

### ISSUE THREAD

**Issue by kayb-proxora** [testcontainers/testcontainers-java#3809]
Hi,

Unfortunately, since version 1.15.2 the screen recording is no longer working with the WebDriver container for me:

```
Suppressed: com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"Could not find the file /newScreen.mp4 in container 598d7916dc5277d2ed135ce3de387a4e456b66e8d1965101d2654c785164f92b"}

		at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:241)
		at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:202)
		at org.testcontainers.shaded.com.github.dockerjava.core.exec.CopyArchiveFromContainerCmdExec.execute(CopyArchiveFromContainerCmdExec.java:30)
		at org.testcontainers.shaded.com.github.dockerjava.core.exec.CopyArchiveFromContainerCmdExec.execute(CopyArchiveFromContainerCmdExec.java:13)
		at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
		at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
		at org.testcontainers.shaded.com.github.dockerjava.core.command.CopyArchiveFromContainerCmdImpl.exec(CopyArchiveFromContainerCmdImpl.java:70)
		at org.testcontainers.containers.VncRecordingContainer.streamRecording(VncRecordingContainer.java:108)
		at org.testcontainers.containers.VncRecordingContainer.saveRecordingToFile(VncRecordingContainer.java:116)
		at org.testcontainers.containers.BrowserWebDriverContainer.retainRecordingIfNeeded(BrowserWebDriverContainer.java:343)
		at org.testcontainers.containers.BrowserWebDriverContainer.afterTest(BrowserWebDriverContainer.java:301)
		at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$signalAfterTestToContainersFor$8(TestcontainersExtension.java:106)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
		at org.testcontainers.junit.jupiter.TestcontainersExtension.signalAfterTestToContainersFor(TestcontainersExtension.java:106)
		at org.testcontainers.junit.jupiter.TestcontainersExtension.afterEach(TestcontainersExtension.java:93)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$11(TestMethodTestDescriptor.java:253)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$12(TestMethodTestDescriptor.java:269)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:269)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:268)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:252)
		at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
		... 68 more
```

I think it's related to these changes: https://github.com/testcontainers/testcontainers-java/pull/3180

It seems that it's still using vncrecorder 1.1.0 without ffmpeg.

Minimal example:

```
@Testcontainers
public class BaseTest {

    @Container
    protected BrowserWebDriverContainer<?> container = new BrowserWebDriverContainer<>()
                .withCapabilities(capabilities())
                .withRecordingMode(recordingMode(), recordingFolder(), VncRecordingFormat.MP4);

    private Capabilities capabilities() {
        return new ChromeOptions();
    }

    private BrowserWebDriverContainer.VncRecordingMode recordingMode() {
        return BrowserWebDriverContainer.VncRecordingMode.RECORD_ALL;
    }

    private File recordingFolder() {
        return new File("build/");
    }

    @Test
    public void testOpenUrl() {
        container.getWebDriver().get("https://www.google.com");
    }
}
```

Can someone please check?

Thanks and kind regards,

Kay

**Comment by kayb-proxora** [comment]
I found the issue. We configured the vncrecorder version to 1.1.0 inside testcontainers.properties. 

Sorry for the wrong issue report.
