### ISSUE TITLE
CockroachContainer can't work with cockroachdb/cockroach-unstable images

### ISSUE THREAD

**Issue by lukaseder** [testcontainers/testcontainers-java#3851]
I'd like to run some tests on the next version of CockroachDB:

```java
new CockroachContainer("cockroachdb/cockroach-unstable:v21.1.0-alpha.1")
```

But that fails with:

```
java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
	at java.base/java.lang.reflect.Field.get(Field.java:418)
	at org.junit.runners.model.FrameworkField.get(FrameworkField.java:93)
	at org.junit.runners.model.TestClass.collectAnnotatedFieldValues(TestClass.java:249)
	at org.junit.runners.ParentRunner.classRules(ParentRunner.java:280)
	at org.junit.runners.ParentRunner.withClassRules(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.classBlock(ParentRunner.java:217)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:412)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.IllegalStateException: Failed to verify that image 'cockroachdb/cockroach-unstable:v21.1.0-alpha.1' is a compatible substitute for 'cockroachdb/cockroach'. This generally means that you are trying to use an image that Testcontainers has not been designed to use. If this is deliberate, and if you are confident that the image is compatible, you should declare compatibility in code using the `asCompatibleSubstituteFor` method. For example:
   DockerImageName myImage = DockerImageName.parse("cockroachdb/cockroach-unstable:v21.1.0-alpha.1").asCompatibleSubstituteFor("cockroachdb/cockroach");
and then use `myImage` instead.
	at org.testcontainers.utility.DockerImageName.assertCompatibleWith(DockerImageName.java:248)
	at org.testcontainers.containers.CockroachContainer.<init>(CockroachContainer.java:46)
	at org.testcontainers.containers.CockroachContainer.<init>(CockroachContainer.java:40)
	at org.jooq.test.CockroachDBTCTest.<clinit>(CockroachDBTCTest.java:55)
	... 19 more
```

The workaround is to copy paste the `CockroachContainer` and patch the relevant code.

----
See: https://hub.docker.com/r/cockroachdb/cockroach-unstable/tags

**Comment by bsideup** [comment]
Hey @lukaseder,

Have you tried using the snipped from exception?
```java
new CockroachContainer(DockerImageName.parse("cockroachdb/cockroach-unstable:v21.1.0-alpha.1").asCompatibleSubstituteFor("cockroachdb/cockroach"))
```

**Comment by lukaseder** [comment]
Yeah, why don't I just read the error message, huh? 🤪
