### ISSUE TITLE
Deadlock after updating to latest

### ISSUE THREAD

**Issue by paplorinc** [testcontainers/testcontainers-java#3872]
Updating from `1.15.1` to `1.15.2` seems to block for us now:
```
"docker-java-stream--911883345" #220 daemon prio=5 os_prio=31 tid=0x00007fd8a1d12800 nid=0xae07 waiting for monitor entry [0x000070000f4bb000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.testcontainers.shaded.okio.AsyncTimeout.cancelScheduledTimeout(AsyncTimeout.java:128)
	- waiting to lock <0x00000006c15ef6c0> (a java.lang.Class for org.testcontainers.shaded.okio.AsyncTimeout)
	at org.testcontainers.shaded.okio.AsyncTimeout.exit(AsyncTimeout.java:122)
	at org.testcontainers.shaded.okio.AsyncTimeout.exit(AsyncTimeout.java:285)
	at org.testcontainers.shaded.okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at org.testcontainers.shaded.okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
	at org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
	at org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:224)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.java:489)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.java:471)
	at org.testcontainers.shaded.okhttp3.internal.Util.skipAll(Util.java:204)
	at org.testcontainers.shaded.okhttp3.internal.Util.discard(Util.java:186)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.close(Http1ExchangeCodec.java:511)
	at org.testcontainers.shaded.okio.ForwardingSource.close(ForwardingSource.java:43)
	at org.testcontainers.shaded.okhttp3.internal.connection.Exchange$ResponseBodySource.close(Exchange.java:313)
	at org.testcontainers.shaded.okio.RealBufferedSource.close(RealBufferedSource.java:476)
	at org.testcontainers.shaded.okhttp3.internal.Util.closeQuietly(Util.java:139)
	at org.testcontainers.shaded.okhttp3.ResponseBody.close(ResponseBody.java:192)
	at org.testcontainers.shaded.okhttp3.Response.close(Response.java:290)
	at org.testcontainers.shaded.com.github.dockerjava.okhttp.OkDockerHttpClient$OkResponse.close(OkDockerHttpClient.java:285)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:277)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder$$Lambda$213/803997348.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bsideup** [comment]
Hi @paplorinc,

It looks similar to https://github.com/testcontainers/testcontainers-java/issues/3531

Are you sure it is caused by 1.15.1 -> 1.15.2 update?

**Comment by paplorinc** [comment]
Actually I was just able to reproduce it with 1.15.1 as well:
```
"Thread-435" #802 daemon prio=5 os_prio=31 tid=0x00007fd49dac1800 nid=0xc043 in Object.wait() [0x0000700012821000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.ChannelManager.getChannelData(ChannelManager.java:985)
	- locked <0x000000076e556bc0> (a org.testcontainers.shaded.com.trilead.ssh2.channel.Channel)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:58)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:70)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.StreamForwarder.run(StreamForwarder.java:45)

"Thread-434" #801 daemon prio=5 os_prio=31 tid=0x00007fd44cbda800 nid=0x14c43 runnable [0x000070001261b000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.StreamForwarder.run(StreamForwarder.java:45)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.RemoteAcceptThread.run(RemoteAcceptThread.java:65)

"docker-java-stream--192897647" #799 daemon prio=5 os_prio=31 tid=0x00007fd44daf5000 nid=0x14b43 runnable [0x00007000117f1000]
   java.lang.Thread.State: RUNNABLE
	at org.testcontainers.shaded.com.github.dockerjava.okhttp.UnixDomainSocket.recv(Native Method)
	at org.testcontainers.shaded.com.github.dockerjava.okhttp.UnixDomainSocket$UnixSocketInputStream.read(UnixDomainSocket.java:246)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.testcontainers.shaded.com.github.dockerjava.okhttp.UnixSocketFactory$1$1.read(UnixSocketFactory.java:45)
	at org.testcontainers.shaded.okio.Okio$2.read(Okio.java:140)
	at org.testcontainers.shaded.okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at org.testcontainers.shaded.okio.RealBufferedSource.request(RealBufferedSource.java:72)
	at org.testcontainers.shaded.okio.RealBufferedSource.require(RealBufferedSource.java:65)
	at org.testcontainers.shaded.okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:307)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.java:492)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.java:471)
	at org.testcontainers.shaded.okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
	at org.testcontainers.shaded.okio.RealBufferedSource$1.read(RealBufferedSource.java:436)
	at org.testcontainers.shaded.com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:30)
	at org.testcontainers.shaded.com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:12)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:275)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder$$Lambda$213/471669353.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

"Thread-432" #797 daemon prio=5 os_prio=31 tid=0x00007fd44bc8c000 nid=0x13a4f in Object.wait() [0x0000700012009000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.ChannelManager.getChannelData(ChannelManager.java:985)
	- locked <0x000000076e547ca8> (a org.testcontainers.shaded.com.trilead.ssh2.channel.Channel)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:58)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:70)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.StreamForwarder.run(StreamForwarder.java:45)

"Thread-431" #796 daemon prio=5 os_prio=31 tid=0x00007fd4cdd9c000 nid=0xd24f runnable [0x0000700011e03000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.StreamForwarder.run(StreamForwarder.java:45)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.RemoteAcceptThread.run(RemoteAcceptThread.java:65)

"docker-java-stream--1551979782" #794 daemon prio=5 os_prio=31 tid=0x00007fd4bb833000 nid=0x8abf runnable [0x000070000f791000]
   java.lang.Thread.State: RUNNABLE
	at org.testcontainers.shaded.com.github.dockerjava.okhttp.UnixDomainSocket.recv(Native Method)
	at org.testcontainers.shaded.com.github.dockerjava.okhttp.UnixDomainSocket$UnixSocketInputStream.read(UnixDomainSocket.java:246)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.testcontainers.shaded.com.github.dockerjava.okhttp.UnixSocketFactory$1$1.read(UnixSocketFactory.java:45)
	at org.testcontainers.shaded.okio.Okio$2.read(Okio.java:140)
	at org.testcontainers.shaded.okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at org.testcontainers.shaded.okio.RealBufferedSource.request(RealBufferedSource.java:72)
	at org.testcontainers.shaded.okio.RealBufferedSource.require(RealBufferedSource.java:65)
	at org.testcontainers.shaded.okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:307)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.java:492)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.java:471)
	at org.testcontainers.shaded.okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
	at org.testcontainers.shaded.okio.RealBufferedSource$1.read(RealBufferedSource.java:436)
	at org.testcontainers.shaded.com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:30)
	at org.testcontainers.shaded.com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:12)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:275)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder$$Lambda$213/471669353.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

"Thread-12" #48 daemon prio=5 os_prio=31 tid=0x00007fd49d039000 nid=0x670b in Object.wait() [0x000070000f385000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.ChannelManager.getChannelData(ChannelManager.java:985)
	- locked <0x00000006c197d810> (a org.testcontainers.shaded.com.trilead.ssh2.channel.Channel)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:58)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:70)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.StreamForwarder.run(StreamForwarder.java:45)

"Thread-11" #47 daemon prio=5 os_prio=31 tid=0x00007fd44c315800 nid=0x9327 runnable [0x000070000f282000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.StreamForwarder.run(StreamForwarder.java:45)
	at org.testcontainers.shaded.com.trilead.ssh2.channel.RemoteAcceptThread.run(RemoteAcceptThread.java:65)

"docker-java-stream--228012997" #40 daemon prio=5 os_prio=31 tid=0x00007fd44c98a000 nid=0x470f runnable [0x000070000dd15000]
   java.lang.Thread.State: RUNNABLE
	at org.testcontainers.shaded.com.github.dockerjava.okhttp.UnixDomainSocket.recv(Native Method)
	at org.testcontainers.shaded.com.github.dockerjava.okhttp.UnixDomainSocket$UnixSocketInputStream.read(UnixDomainSocket.java:246)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.testcontainers.shaded.com.github.dockerjava.okhttp.UnixSocketFactory$1$1.read(UnixSocketFactory.java:45)
	at org.testcontainers.shaded.okio.Okio$2.read(Okio.java:140)
	at org.testcontainers.shaded.okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at org.testcontainers.shaded.okio.RealBufferedSource.request(RealBufferedSource.java:72)
	at org.testcontainers.shaded.okio.RealBufferedSource.require(RealBufferedSource.java:65)
	at org.testcontainers.shaded.okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:307)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.java:492)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.java:471)
	at org.testcontainers.shaded.okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
	at org.testcontainers.shaded.okio.RealBufferedSource$1.read(RealBufferedSource.java:436)
	at org.testcontainers.shaded.com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:30)
	at org.testcontainers.shaded.com.github.dockerjava.core.FramedInputStreamConsumer.accept(FramedInputStreamConsumer.java:12)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:275)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder$$Lambda$213/471669353.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

"Thread-10" #39 daemon prio=5 os_prio=31 tid=0x00007fd44b813000 nid=0x3c07 runnable [0x000070000f07c000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.testcontainers.shaded.com.trilead.ssh2.crypto.cipher.CipherInputStream.fill_buffer(CipherInputStream.java:41)
	at org.testcontainers.shaded.com.trilead.ssh2.crypto.cipher.CipherInputStream.internal_read(CipherInputStream.java:52)
	at org.testcontainers.shaded.com.trilead.ssh2.crypto.cipher.CipherInputStream.getBlock(CipherInputStream.java:79)
	at org.testcontainers.shaded.com.trilead.ssh2.crypto.cipher.CipherInputStream.read(CipherInputStream.java:108)
	at org.testcontainers.shaded.com.trilead.ssh2.transport.TransportConnection.receiveMessage(TransportConnection.java:232)
	at org.testcontainers.shaded.com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:672)
	at org.testcontainers.shaded.com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:470)
	at java.lang.Thread.run(Thread.java:748)

"testcontainers-ryuk" #35 daemon prio=5 os_prio=31 tid=0x00007fd4cddff800 nid=0x680f in Object.wait() [0x000070000f17f000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at org.testcontainers.utility.ResourceReaper.lambda$null$1(ResourceReaper.java:167)
	- locked <0x00000006c1c22750> (a java.util.ArrayList)
	at org.testcontainers.utility.ResourceReaper$$Lambda$227/1307606075.run(Unknown Source)
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
	at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:158)
	at org.testcontainers.utility.ResourceReaper$$Lambda$226/1714232519.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)

"OkHttp ConnectionPool" #25 daemon prio=5 os_prio=31 tid=0x00007fd4cbd88000 nid=0x9803 in Object.wait() [0x000070000ee4b000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:460)
	at org.testcontainers.shaded.okhttp3.internal.connection.RealConnectionPool.lambda$new$0(RealConnectionPool.java:62)
	- locked <0x00000006c0b97960> (a org.testcontainers.shaded.okhttp3.internal.connection.RealConnectionPool)
	at org.testcontainers.shaded.okhttp3.internal.connection.RealConnectionPool$$Lambda$177/803300820.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Test worker" #11 prio=5 os_prio=31 tid=0x00007fd4cd090000 nid=0xa103 runnable [0x000070000e52a000]
   java.lang.Thread.State: RUNNABLE
	at org.testcontainers.shaded.okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
	at org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
	at org.testcontainers.shaded.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:224)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.java:489)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.java:471)
	at org.testcontainers.shaded.okhttp3.internal.Util.skipAll(Util.java:204)
	at org.testcontainers.shaded.okhttp3.internal.Util.discard(Util.java:186)
	at org.testcontainers.shaded.okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.close(Http1ExchangeCodec.java:511)
	at org.testcontainers.shaded.okio.ForwardingSource.close(ForwardingSource.java:43)
	at org.testcontainers.shaded.okhttp3.internal.connection.Exchange$ResponseBodySource.close(Exchange.java:313)
	at org.testcontainers.shaded.okio.RealBufferedSource.close(RealBufferedSource.java:476)
	at org.testcontainers.shaded.okhttp3.internal.Util.closeQuietly(Util.java:139)
	at org.testcontainers.shaded.okhttp3.ResponseBody.close(ResponseBody.java:192)
	at org.testcontainers.shaded.okhttp3.Response.close(Response.java:290)
	at org.testcontainers.shaded.com.github.dockerjava.okhttp.OkDockerHttpClient$OkResponse.close(OkDockerHttpClient.java:285)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$null$0(DefaultInvocationBuilder.java:272)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder$$Lambda$214/1219911106.close(Unknown Source)
	at com.github.dockerjava.api.async.ResultCallbackTemplate.close(ResultCallbackTemplate.java:77)
	at org.testcontainers.containers.output.FrameConsumerResultCallback.close(FrameConsumerResultCallback.java:100)
	at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:51)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:892)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:440)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.testcontainers.containers.GenericContainer$$Lambda$232/1311296788.call(Unknown Source)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at org.testcontainers.lifecycle.Startable$start.call(Unknown Source)
[...]
```

**Comment by bsideup** [comment]
@paplorinc ah, okay, must be the same issue then, I will close as a duplicate. Note that with Apache HttpClient5 transport the issue does not seem to be happening (see https://github.com/testcontainers/testcontainers-java/issues/3531#issuecomment-781247559 for how to switch to it)

There was more progress on identifying the cause, but we also plan to switch to HttpClient5 by default :)

**Comment by paplorinc** [comment]
Thanks for the quick response.

Adding `resources/testcontainers.properties` with the mentioned `transport.type=httpclient5` changes the http client in the traces to `com.github.dockerjava.zerodep` from `okhttp3`.

Until now I could reproduce the deadlock after <40 tries, now it's still passing after 100+ runs.

Thank you for your help, it seems this has indeed fixed our issue - will let you know if it didn't!
