### ISSUE TITLE
localstack with S3 is slow to start on windows 10

### ISSUE THREAD

**Issue by joel-costigliola** [testcontainers/testcontainers-java#3876]
### Issue description

I'm using testcontainers 1.15.2 to start S3 in localstack 0.12.7, the test succeeds but the initialization takes around 3min on my machine to start the localstack container as shown in the logs below
```
17:35:13.715 [main] INFO  org.testcontainers.dockerclient.DockerClientProviderStrategy - Loaded org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
17:35:14.208 [main] INFO  org.testcontainers.dockerclient.DockerClientProviderStrategy - Found Docker environment with local Npipe socket (npipe:////./pipe/docker_engine)
17:35:14.218 [main] INFO  org.testcontainers.DockerClientFactory - Docker host IP address is localhost
17:35:14.241 [main] INFO  org.testcontainers.DockerClientFactory - Connected to docker: 
  Server Version: 19.03.1
  API Version: 1.40
  Operating System: Docker Desktop
  Total Memory: 3947 MB
17:35:14.244 [main] INFO  org.testcontainers.utility.ImageNameSubstitutor - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
17:35:14.499 [main] INFO  org.testcontainers.utility.RegistryAuthLocator - Credential helper/store (docker-credential-desktop) does not have credentials for index.docker.io
17:35:15.141 [main] INFO  org.testcontainers.DockerClientFactory - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
17:35:15.141 [main] INFO  org.testcontainers.DockerClientFactory - Checking the system...
17:35:15.141 [main] INFO  org.testcontainers.DockerClientFactory - ✔︎ Docker server version should be at least 1.6.0
17:35:15.297 [main] INFO  org.testcontainers.DockerClientFactory - ✔︎ Docker environment should have more than 2GB free disk space
17:35:15.394 [main] INFO  🐳 [localstack/localstack:0.12.7] - HOSTNAME_EXTERNAL environment variable set to localhost (to match host-routable address for container)
17:35:15.395 [main] INFO  🐳 [localstack/localstack:0.12.7] - Creating container for image: localstack/localstack:0.12.7
        ⚠︎ Unable to mount a file from test host into a running container. This may be a misconfiguration or limitation of your Docker environment. Some features might not work.
17:38:10.004 [main] INFO  🐳 [localstack/localstack:0.12.7] - Starting container with ID: 95286ff48feac01242f8c0a5aa005c11dbc3f3b186e287e4b48050e2d5086b51
17:38:10.498 [main] INFO  🐳 [localstack/localstack:0.12.7] - Container localstack/localstack:0.12.7 is starting: 95286ff48feac01242f8c0a5aa005c11dbc3f3b186e287e4b48050e2d5086b51
17:38:25.474 [main] INFO  🐳 [localstack/localstack:0.12.7] - Container localstack/localstack:0.12.7 started in PT3M10.0797087S
Initializing S3 client
Initializing S3 bucket
```

I obviously noticed the `Unable to mount a file from test host into a running container. This may be a misconfiguration or limitation of your Docker environment. Some features might not work` log but could not find what caused it (due to my lack of docker expertise).

My environment is:
* windows 10 enterprise version 1909
* java : Amazon Corretto - jdk11.0.4_10
* docker desktop version 2.1.0.1 / engine 19.03.1

### Questions

Have I misconfigured localstack? 
Is it more a docker issue than a testcontainters one?
What can I do to investigate further this issue?
Do you need additional information to help finding what causes the issue?
Is there any documentation I should read that would explain the issue?

### More details and investigation
 
Here's a test reproducing the issue (on my machine at least):
```java
package test;

import static org.testcontainers.containers.localstack.LocalStackContainer.Service.S3;

import org.junit.jupiter.api.Test;
import org.testcontainers.containers.localstack.LocalStackContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;

import software.amazon.awssdk.services.s3.S3Client;

@Testcontainers
class LocalstackTest
{
  static S3Client S3_CLIENT;

  @Container
  static final LocalStackContainer LOCALSTACK_CONTAINER = new LocalStackContainer(DockerImageName.parse("localstack/localstack:0.12.7")).withServices(S3);

  @Test
  void should_start_s3()
  {
    System.out.println("done");
  }
}
```

I have run the tests with localstack 0.11.2 and observed the same issue.

I'm able to start the localstack/localstack:0.12.7 image pretty quickly with `docker run localstack/localstack:0.12.7`.
```
$ docker run localstack/localstack:0.12.7
Waiting for all LocalStack services to be ready
2021-03-15 04:40:43,475 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2021-03-15 04:40:43,477 INFO supervisord started with pid 13
2021-03-15 04:40:44,480 INFO spawned: 'dashboard' with pid 19
2021-03-15 04:40:44,482 INFO spawned: 'infra' with pid 20
2021-03-15 04:40:44,486 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2021-03-15 04:40:44,489 INFO exited: dashboard (exit status 0; expected)
(. .venv/bin/activate; exec bin/localstack start --host)
2021-03-15 04:40:45,490 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Starting local dev environment. CTRL-C to quit.
LocalStack version: 0.12.7
2021-03-15T04:40:48:INFO:localstack.utils.analytics.profiler: Execution of "load_plugin_from_path" took 2983.8640689849854ms
2021-03-15T04:40:48:INFO:localstack.utils.analytics.profiler: Execution of "load_plugins" took 2984.4179153442383ms
Starting edge router (https port 4566)...
Starting mock ACM service on http port 4566 ...
[2021-03-15 04:40:48 +0000] [21] [INFO] Running on https://0.0.0.0:4566 (CTRL + C to quit)
2021-03-15T04:40:48:INFO:localstack.multiserver: Starting multi API server process on port 54723
2021-03-15T04:40:48:INFO:hypercorn.error: Running on https://0.0.0.0:4566 (CTRL + C to quit)
[2021-03-15 04:40:48 +0000] [21] [INFO] Running on http://0.0.0.0:54723 (CTRL + C to quit)
2021-03-15T04:40:48:INFO:hypercorn.error: Running on http://0.0.0.0:54723 (CTRL + C to quit)
Waiting for all LocalStack services to be ready
Starting mock API Gateway service on http port 4566 ...
Starting mock CloudFormation service on http port 4566 ...
Starting mock CloudWatch service on http port 4566 ...
Starting mock DynamoDB service on http port 4566 ...
Starting mock DynamoDB Streams service on http port 4566 ...
Starting mock EC2 service on http port 4566 ...
Starting mock ES service on http port 4566 ...
Starting mock Firehose service on http port 4566 ...
Starting mock IAM service on http port 4566 ...
Starting mock STS service on http port 4566 ...
Starting mock Kinesis service on http port 4566 ...
Starting mock KMS service on http port 4566 ...
Starting mock Lambda service on http port 4566 ...
Starting mock CloudWatch Logs service on http port 4566 ...
Starting mock Redshift service on http port 4566 ...
Starting mock Route53 service on http port 4566 ...
Starting mock S3 service on http port 4566 ...
Starting mock Secrets Manager service on http port 4566 ...
Starting mock SES service on http port 4566 ...
Starting mock SNS service on http port 4566 ...
Starting mock SQS service on http port 4566 ...
Starting mock SSM service on http port 4566 ...
Starting mock Cloudwatch Events service on http port 4566 ...
Starting mock StepFunctions service on http port 4566 ...
Starting mock SWF service on http port 4566 ...
Waiting for all LocalStack services to be ready
Ready.
2021-03-15T04:40:59:INFO:localstack.utils.analytics.profiler: Execution of "start_api_services" took 11065.691947937012ms
```

Anyway thanks for this great project, love testing my applications with it! at least my non S3 applications ;-)

**Comment by joel-costigliola** [comment]
One of my colleague runs this test without the 3min delay so it seems to be environmental, 
He is running docker ce 19.03.13 when I'm running 19.03.1, I'll update docker and see if it solves the issue.

**Comment by joel-costigliola** [comment]
Before upgrading docker, here's the test logs with testcontainers at DEBUG level, hope it helps investigating the issue:
```
13:50:30.139 [main] INFO  org.testcontainers.DockerClientFactory - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
13:50:30.139 [main] DEBUG org.testcontainers.DockerClientFactory - Checks are enabled
13:50:30.139 [main] INFO  org.testcontainers.DockerClientFactory - Checking the system...
13:50:30.139 [main] INFO  org.testcontainers.DockerClientFactory - ✔︎ Docker server version should be at least 1.6.0
13:50:30.141 [main] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: de730dc6b09b323e963df6f63f9329bc165434c577ecaf979190f7c59e1b9657,<null>,true,<null>,<null>,<null>,<null>,{df,-P},<null>,<null>
13:50:30.248 [main] INFO  org.testcontainers.DockerClientFactory - ✔︎ Docker environment should have more than 2GB free disk space
13:50:30.248 [main] DEBUG org.testcontainers.utility.PrefixingImageNameSubstitutor - No prefix is configured
13:50:30.248 [main] DEBUG org.testcontainers.utility.ImageNameSubstitutor - Did not find a substitute image for localstack/localstack:0.12.7 (using image substitutor: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor'))
13:50:30.251 [main] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: ListImagesCmdImpl[imageNameFilter=<null>,showAll=false,filters=org.testcontainers.shaded.com.github.dockerjava.core.util.FiltersBuilder@0]
13:50:30.329 [main] DEBUG org.testcontainers.images.LocalImagesCache - repoTags is null, skipping image: Image(created=1602441642, id=sha256:eb14e414ae3bae26aed86367bc14fc39bc276e97a5c95d80fddeab20e51fe815, parentId=, repoTags=null, repoDigests=[174550113169.dkr.ecr.ap-southeast-2.amazonaws.com/software-platforms/airnz-kms-amazoncorretto-jre@sha256:88c03526e229e3cedbfd6201d2fea3e94bb30e494c9f07872e52f129ef456a23], size=271154024, virtualSize=271154024, sharedSize=-1, labels=null, containers=-1)
13:50:30.329 [main] DEBUG org.testcontainers.images.LocalImagesCache - repoTags is null, skipping image: Image(created=1597660972, id=sha256:bb710113a69e69811f1daba25d6d52c87fa46b9c9c80c772949572d1ecd20243, parentId=, repoTags=null, repoDigests=[wurstmeister/kafka@sha256:e350af1cb60724dd26c4561142dcb372ec51ee1bcc7930d865c47a0676ffe876], size=432269106, virtualSize=432269106, sharedSize=-1, labels={maintainer=wurstmeister, org.label-schema.build-date=2020-08-17T10:42:35Z, org.label-schema.description=Apache Kafka, org.label-schema.name=kafka, org.label-schema.schema-version=1.0, org.label-schema.vcs-ref=9a435ae102fd3b75969def55ae732ff7e764f671, org.label-schema.vcs-url=https://github.com/wurstmeister/kafka-docker, org.label-schema.version=2.12_2.4.1}, containers=-1)
13:50:30.329 [main] DEBUG org.testcontainers.images.LocalImagesCache - repoTags is null, skipping image: Image(created=1596574748, id=sha256:bb906711e6e64fb6fffa6b92b9043cbfe12940f150b2b343b4311e70481ee74d, parentId=, repoTags=null, repoDigests=[174550113169.dkr.ecr.ap-southeast-2.amazonaws.com/software-platforms/airnz-kms-amazoncorretto-jre@sha256:a6311fb9242d9e195ea22a246240faf6db2db9a81677f329b8c9e983b590471b], size=243117107, virtualSize=243117107, sharedSize=-1, labels=null, containers=-1)
13:50:30.330 [main] DEBUG org.testcontainers.images.LocalImagesCache - repoTags is null, skipping image: Image(created=1594323926, id=sha256:b17abe49ec141c60534a326225af8b1b45ae7077c3469a2a2d418961dd68077d, parentId=, repoTags=null, repoDigests=[174550113169.dkr.ecr.ap-southeast-2.amazonaws.com/software-platforms/airnz-kms-amazoncorretto-jre@sha256:93e2b405af3eb79e1c6c168ec02e28fb9343123d5639f49b25bb117ab8f02998], size=243284598, virtualSize=243284598, sharedSize=-1, labels=null, containers=-1)
13:50:30.330 [main] DEBUG org.testcontainers.images.LocalImagesCache - repoTags is null, skipping image: Image(created=1588036959, id=sha256:1f696d4690c2e212d5af61c25412d64652561e11286d0b716a156610c5fc2d6f, parentId=, repoTags=null, repoDigests=[174550113169.dkr.ecr.ap-southeast-2.amazonaws.com/software-platforms/airnz-kms-amazoncorretto-jre@sha256:462566a45a2dc273654386351572754e5b91363ab91890741ff6d6d3bce9034e], size=243060724, virtualSize=243060724, sharedSize=-1, labels=null, containers=-1)
13:50:30.330 [main] DEBUG org.testcontainers.images.LocalImagesCache - repoTags is null, skipping image: Image(created=1587229690, id=sha256:75bc37aca6d23d061ff21c1d7452852681430e02dbfe138e41ab072dbec8fea8, parentId=, repoTags=null, repoDigests=[confluentinc/cp-kafka-rest@sha256:c6852aa2d304d0a9c78f174b13ab8e4b89c694f9293d410fa76063b9ff3cb7f0], size=1163847662, virtualSize=1163847662, sharedSize=-1, labels={io.confluent.docker=true, io.confluent.docker.build.number=3, io.confluent.docker.git.id=b2ad6a9, io.confluent.docker.git.repo=confluentinc/kafka-rest-images}, containers=-1)
13:50:30.330 [main] DEBUG org.testcontainers.images.LocalImagesCache - repoTags is null, skipping image: Image(created=1569960008, id=sha256:41dec74177bf028d8d50c6d02102ff024ab3d476a77ca50e5cbc9548d5054290, parentId=, repoTags=null, repoDigests=[174550113169.dkr.ecr.ap-southeast-2.amazonaws.com/software-platforms/airnz-kms-amazoncorretto-jre@sha256:0d15bd00a178832883f5a921aafd986aaf8166f508b0f5d7e67f19574971018e], size=234323837, virtualSize=234323837, sharedSize=-1, labels=null, containers=-1)
13:50:30.330 [main] DEBUG org.testcontainers.images.AbstractImagePullPolicy - Using locally available and not pulling image: localstack/localstack:0.12.7
13:50:30.331 [main] INFO  🐳 [localstack/localstack:0.12.7] - HOSTNAME_EXTERNAL environment variable set to localhost (to match host-routable address for container)
13:50:30.331 [main] INFO  🐳 [localstack/localstack:0.12.7] - Creating container for image: localstack/localstack:0.12.7
13:50:30.331 [main] DEBUG org.testcontainers.utility.RegistryAuthLocator - Looking up auth config for image: localstack/localstack:0.12.7 at registry: index.docker.io
13:50:30.332 [main] DEBUG org.testcontainers.utility.RegistryAuthLocator - No matching Auth Configs - falling back to defaultAuthConfig [null]
13:50:30.332 [main] DEBUG org.testcontainers.dockerclient.AuthDelegatingDockerClientConfig - Effective auth config [null]
13:50:30.337 [main] DEBUG org.testcontainers.utility.PrefixingImageNameSubstitutor - No prefix is configured
13:50:30.337 [main] DEBUG org.testcontainers.utility.ImageNameSubstitutor - Did not find a substitute image for alpine:3.5 (using image substitutor: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor'))
13:50:30.337 [main] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: alpine:3.5
13:50:30.341 [main] DEBUG org.testcontainers.utility.RegistryAuthLocator - Looking up auth config for image: alpine:3.5 at registry: index.docker.io
13:50:30.341 [main] DEBUG org.testcontainers.utility.RegistryAuthLocator - No matching Auth Configs - falling back to defaultAuthConfig [null]
13:50:30.341 [main] DEBUG org.testcontainers.dockerclient.AuthDelegatingDockerClientConfig - Effective auth config [null]
13:50:30.344 [main] DEBUG org.testcontainers.utility.MountableFile - Copying classpath resource(s) from jar:file:/C:/Users/CostiJ/.gradle/caches/modules-2/files-2.1/org.testcontainers/testcontainers/1.15.2/355ed4a824a9f54b5d95030f292b0e1ef15d70e8/testcontainers-1.15.2.jar!/org/testcontainers/utility/ResourceReaper.class to C:\Users\CostiJ\AppData\Local\Temp\1\.testcontainers-tmp-11805735807733847244 to permit Docker to bind
13:50:30.344 [main] DEBUG org.testcontainers.utility.MountableFile - Copying resource org/testcontainers/utility/ResourceReaper.class from JAR file C:\Users\CostiJ\.gradle\caches\modules-2\files-2.1\org.testcontainers\testcontainers\1.15.2\355ed4a824a9f54b5d95030f292b0e1ef15d70e8\testcontainers-1.15.2.jar
13:50:30.351 [main] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.core.command.CreateContainerCmdImpl@15e0fe05[name=<null>,hostName=<null>,domainName=<null>,user=<null>,attachStdin=<null>,attachStdout=<null>,attachStderr=<null>,portSpecs=<null>,tty=<null>,stdinOpen=<null>,stdInOnce=<null>,env=<null>,cmd=<null>,healthcheck=<null>,argsEscaped=<null>,entrypoint=<null>,image=alpine:3.5,volumes=com.github.dockerjava.api.model.Volumes@1128620c,workingDir=<null>,macAddress=<null>,onBuild=<null>,networkDisabled=<null>,exposedPorts=com.github.dockerjava.api.model.ExposedPorts@6bf13698,stopSignal=<null>,stopTimeout=<null>,hostConfig=HostConfig(binds=[C:\Users\CostiJ\AppData\Local\Temp\1\.testcontainers-tmp-11805735807733847244:/dummy:ro], blkioWeight=null, blkioWeightDevice=null, blkioDeviceReadBps=null, blkioDeviceWriteBps=null, blkioDeviceReadIOps=null, blkioDeviceWriteIOps=null, memorySwappiness=null, nanoCPUs=null, capAdd=null, capDrop=null, containerIDFile=null, cpuPeriod=null, cpuRealtimePeriod=null, cpuRealtimeRuntime=null, cpuShares=null, cpuQuota=null, cpusetCpus=null, cpusetMems=null, devices=null, deviceCgroupRules=null, deviceRequests=null, diskQuota=null, dns=null, dnsOptions=null, dnsSearch=null, extraHosts=null, groupAdd=null, ipcMode=null, cgroup=null, links=[], logConfig=LogConfig(type=null, config=null), lxcConf=null, memory=null, memorySwap=null, memoryReservation=null, kernelMemory=null, networkMode=null, oomKillDisable=null, init=null, autoRemove=null, oomScoreAdj=null, portBindings=null, privileged=null, publishAllPorts=null, readonlyRootfs=null, restartPolicy=null, ulimits=null, cpuCount=null, cpuPercent=null, ioMaximumIOps=null, ioMaximumBandwidth=null, volumesFrom=null, mounts=null, pidMode=null, isolation=null, securityOpts=null, storageOpt=null, cgroupParent=null, volumeDriver=null, shmSize=null, pidsLimit=null, runtime=null, tmpFs=null, utSMode=null, usernsMode=null, sysctls=null, consoleSize=null),labels={org.testcontainers=true, org.testcontainers.sessionId=91a69dd2-3cc0-4d5d-845e-6189eddfc22f},shell=<null>,networkingConfig=<null>,ipv4Address=<null>,ipv6Address=<null>,aliases=<null>,authConfig=<null>]
13:50:30.453 [main] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: e41bfdb30479f041bd65f4518ad880a375be40b4b7dc8e046651a92086bdb12d
13:53:25.052 [main] DEBUG org.testcontainers.DockerClientFactory - Failure while checking for mountable file support
com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"error while creating mount source path '/host_mnt/c/Users/CostiJ/AppData/Local/Temp/1/.testcontainers-tmp-11805735807733847244': mkdir /host_mnt/c: file exists"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
	at org.testcontainers.DockerClientFactory.runInsideDocker(DockerClientFactory.java:361)
	at org.testcontainers.DockerClientFactory.runInsideDocker(DockerClientFactory.java:347)
	at org.testcontainers.DockerClientFactory.checkMountableFile(DockerClientFactory.java:309)
	at org.testcontainers.DockerClientFactory.isFileMountingSupported(DockerClientFactory.java:84)
	at org.testcontainers.containers.GenericContainer.applyConfiguration(GenericContainer.java:750)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:359)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.start(TestcontainersExtension.java:242)
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.access$200(TestcontainersExtension.java:229)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$null$1(TestcontainersExtension.java:59)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$getOrComputeIfAbsent$4(ExtensionValuesStore.java:86)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.get(ExtensionValuesStore.java:205)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$StoredValue.evaluate(ExtensionValuesStore.java:182)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$StoredValue.access$100(ExtensionValuesStore.java:171)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.getOrComputeIfAbsent(ExtensionValuesStore.java:89)
	at org.junit.jupiter.engine.execution.NamespaceAwareStore.getOrComputeIfAbsent(NamespaceAwareStore.java:53)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$beforeAll$2(TestcontainersExtension.java:59)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.beforeAll(TestcontainersExtension.java:59)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
        ⚠︎ Unable to mount a file from test host into a running container. This may be a misconfiguration or limitation of your Docker environment. Some features might not work.
13:53:25.058 [main] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: org.testcontainers.shaded.com.github.dockerjava.core.command.CreateContainerCmdImpl@1816e24a[name=<null>,hostName=<null>,domainName=<null>,user=<null>,attachStdin=<null>,attachStdout=<null>,attachStderr=<null>,portSpecs=<null>,tty=<null>,stdinOpen=<null>,stdInOnce=<null>,env={HOSTNAME_EXTERNAL=localhost,SERVICES=s3},cmd={},healthcheck=<null>,argsEscaped=<null>,entrypoint=<null>,image=localstack/localstack:0.12.7,volumes=com.github.dockerjava.api.model.Volumes@6940f685,workingDir=<null>,macAddress=<null>,onBuild=<null>,networkDisabled=<null>,exposedPorts=com.github.dockerjava.api.model.ExposedPorts@47b179d7,stopSignal=<null>,stopTimeout=<null>,hostConfig=HostConfig(binds=[//var/run/docker.sock:/var/run/docker.sock:rw], blkioWeight=null, blkioWeightDevice=null, blkioDeviceReadBps=null, blkioDeviceWriteBps=null, blkioDeviceReadIOps=null, blkioDeviceWriteIOps=null, memorySwappiness=null, nanoCPUs=null, capAdd=null, capDrop=null, containerIDFile=null, cpuPeriod=null, cpuRealtimePeriod=null, cpuRealtimeRuntime=null, cpuShares=null, cpuQuota=null, cpusetCpus=null, cpusetMems=null, devices=null, deviceCgroupRules=null, deviceRequests=null, diskQuota=null, dns=null, dnsOptions=null, dnsSearch=null, extraHosts=[], groupAdd=null, ipcMode=null, cgroup=null, links=[], logConfig=LogConfig(type=null, config=null), lxcConf=null, memory=null, memorySwap=null, memoryReservation=null, kernelMemory=null, networkMode=null, oomKillDisable=null, init=null, autoRemove=null, oomScoreAdj=null, portBindings={}, privileged=null, publishAllPorts=true, readonlyRootfs=null, restartPolicy=null, ulimits=null, cpuCount=null, cpuPercent=null, ioMaximumIOps=null, ioMaximumBandwidth=null, volumesFrom=[], mounts=null, pidMode=null, isolation=null, securityOpts=null, storageOpt=null, cgroupParent=null, volumeDriver=null, shmSize=null, pidsLimit=null, runtime=null, tmpFs=null, utSMode=null, usernsMode=null, sysctls=null, consoleSize=null),labels={org.testcontainers=true, org.testcontainers.sessionId=91a69dd2-3cc0-4d5d-845e-6189eddfc22f},shell=<null>,networkingConfig=<null>,ipv4Address=<null>,ipv6Address=<null>,aliases=<null>,authConfig=<null>]
13:53:25.175 [main] INFO  🐳 [localstack/localstack:0.12.7] - Starting container with ID: f0f21b939b1af37b9eeb77a6bba955f4312f0da0a4ef95e7a28aaf97f051ab09
```
looks like the issue is: `error while creating mount source path '/host_mnt/c/Users/CostiJ/AppData/Local/Temp/1/.testcontainers-tmp-11805735807733847244': mkdir /host_mnt/c: file exists`, not sure what the root cause but I'll continue investigating.

**Comment by joel-costigliola** [comment]
Found the issue, it was due to docker not being able to access a shared drive :(
I solved the issue by installing a newer docker version and to get it to access my C drive, I was not able to share the drive my my older version due to some admin rights restrictions (joy of being a dev in a corporate environment).

**Comment by bsideup** [comment]
@joel-costigliola interesting! Thanks for sharing your investigation and I am happy to you got it solved 👍 

Also... thanks for your kind feedback :)
