### ISSUE TITLE
 Set DOCKER_HOST through testcontainers.properties

### ISSUE THREAD

**Issue by jizhuozhi** [testcontainers/testcontainers-java#3887]
For some reasons, I cannot set the environment variables on the CI machine. Can I set DOCKER_HOST through testcontainers.properties to access the Docker server?

It seems only support environment variables but not properties files 
[https://www.testcontainers.org/features/configuration/#customizing-docker-host-detection](https://www.testcontainers.org/features/configuration/#customizing-docker-host-detection)

**Comment by jizhuozhi** [comment]
Properties as follow in my classpath are not woring
```properties
# testcontainers.properties
DOCKER_HOST=tcp://X.X.X.X:2375
docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy
# docker-java.properties
DOCKER_HOST=tcp://X.X.X.X:2375
```

**Comment by jizhuozhi** [comment]
Today I pushed my code to repository and then the Jenkis was running. I got the exception as below.

```Console
2021-03-21 19:15:53.996  WARN 12056 --- [           main] o.t.u.TestcontainersConfiguration        : Attempted to read Testcontainers configuration file at file:/root/.testcontainers.properties but the file was not found. Exception message: FileNotFoundException: /root/.testcontainers.properties (No such file or directory)
2021-03-21 19:15:54.010  INFO 12056 --- [           main] .t.d.DockerMachineClientProviderStrategy : docker-machine executable was not found on PATH ([/usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/local/jeci-pts, /usr/local/jvm/jdk1.8.0_151/bin, /usr/local/jvm/jdk1.8.0_151/jre/bin, /usr/local/maven/apache-maven-3.5.4/bin, /usr/local/jeci-pts/jeci-pts])
2021-03-21 19:15:54.052 ERROR 12056 --- [           main] o.t.d.DockerClientProviderStrategy       : Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
2021-03-21 19:15:54.052 ERROR 12056 --- [           main] o.t.d.DockerClientProviderStrategy       :     UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (Could not find unix domain socket). Root cause NoSuchFileException (/var/run/docker.sock)
2021-03-21 19:15:54.053 ERROR 12056 --- [           main] o.t.d.DockerClientProviderStrategy       : As no valid configuration was found, execution cannot continue
2021-03-21 19:15:55.053 ERROR 12056 --- [           main] c.z.h.p.HikariPool                       : HikariPool-1 - Exception during pool initialization.

java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:215) ~[testcontainers-1.15.2.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_151]
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:207) ~[testcontainers-1.15.2.jar:?]
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:136) ~[testcontainers-1.15.2.jar:?]
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:178) ~[testcontainers-1.15.2.jar:?]
	at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14) ~[testcontainers-1.15.2.jar:?]
	at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12) ~[testcontainers-1.15.2.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:310) ~[testcontainers-1.15.2.jar:?]
	at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:118) ~[jdbc-1.15.2.jar:?]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121) ~[HikariCP-3.4.2.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354) ~[HikariCP-3.4.2.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) ~[HikariCP-3.4.2.jar:?]
```

It seems like reading ~/.testcontainers.properties directly but not reading classpath:testcontainers.properties, does any method to resolve this problem ?

**Comment by jizhuozhi** [comment]
I have read the relevant code. In this line testcontainers only read userProperties, but missed classpathProperties
https://github.com/testcontainers/testcontainers-java/blob/8965712f239ae3c449cec579264af5e79265f314/core/src/main/java/org/testcontainers/utility/TestcontainersConfiguration.java#L171
It should use the following line instead
```Java
    public String getDockerClientStrategyClassName() {
        return getEnvVarOrProperty("docker.client.strategy", null);
    }
```

**Comment by jizhuozhi** [comment]
@rnorth Hey, I'm trying to fix this problem to read DOCKER_HOST from classpath, but there seems to be a test case 'shouldNotReadDockerClientStrategyClasspathProperties' to avoid this, what's the historical factor?

**Comment by swift0303** [comment]
Hi, 
I met the same issue with yours.
Did you resolve it finally?
Due the CI machine, my code only can use the classpath way. 

`0:11:25  02:11:24.777 [main] INFO org.testcontainers.utility.ImageNameSubstitutor - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
10:11:25  02:11:24.785 [main] DEBUG org.testcontainers.utility.PrefixingImageNameSubstitutor - No prefix is configured
10:11:25  02:11:24.786 [main] DEBUG org.testcontainers.utility.ImageNameSubstitutor - Did not find a substitute image for docker.elastic.co/elasticsearch/elasticsearch:7.9.2 (using image substitutor: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor'))
10:11:25  02:11:24.803 [main] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - $XDG_RUNTIME_DIR is not set.
10:11:25  02:11:24.803 [main] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - '/root/.docker/run' does not exist.
10:11:25  02:11:24.835 [main] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - '/run/user/0' does not exist.
10:11:25  02:11:24.836 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - Trying out strategy: UnixSocketClientProviderStrategy
10:11:25  02:11:24.837 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (Could not find unix domain socket). Root cause NoSuchFileException (/var/run/docker.sock)
10:11:25  02:11:24.839 [main] INFO org.testcontainers.dockerclient.DockerMachineClientProviderStrategy - docker-machine executable was not found on PATH ([/opt/java/openjdk/bin, /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /opt/apache-maven/bin])
10:11:25  02:11:24.840 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
10:11:25  02:11:24.840 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy -     UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (Could not find unix domain socket). Root cause NoSuchFileException (/var/run/docker.sock)
10:11:25  02:11:24.840 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - As no valid configuration was found, execution cannot continue`

**Comment by jizhuozhi** [comment]
> Hi, I met the same issue with yours. Did you resolve it finally? Due the CI machine, my code only can use the classpath way.

Using `maven-surefire-plugin`

```xml
<plugin>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <environmentVariables>
            <DOCKER_HOST>${docker.host}</DOCKER_HOST>
        </environmentVariables>
    </configuration>
</plugin>
```

**Comment by swift0303** [comment]
Hi @jizhuozhi ,

if we use the maven-surefire-plugin, testcontainers.properties is still needed? 
Could you share the content? Thanks in advance!

**Comment by jizhuozhi** [comment]
There is no need to use any properties, just write any thing in the
maven-surefire-plugin as the issues ahead of this.

swift0303 ***@***.***>于2022年5月13日 周五11:13写道：

**Comment by swift0303** [comment]
Hi @jizhuozhi ,
Thanks a lot! I got it!
Now  i met the other issue.
