### ISSUE TITLE
Unable to run testcontainers with remote DOCKER_HOST due to invalid volume

### ISSUE THREAD

**Issue by crauterb** [testcontainers/testcontainers-java#3918]
Heyho,

I have searched through the issues here but not found any of them matching my problem, so pleas bear with me if I did open a duplicate.

My problem is the following: I am unable to run my test using testcontainers in my Jenkins-Pipeline using a remote DOCKER_HOST.

# Setup

My setup is the following:
I have a machine running a Jenkins Server and a Docker Daemon. The Jenkins should run the tests from my repo in which I have a Jenkinsfile.

Now, to avoid security leaks, I have set up a Rootless DinD Image. Jenkins now executes a pipeline within a "Docker Agent", that is configured to have said DinD-Image configured as its DOCKER_HOST.
I am now able to run my pipeline an build Docker Images from my code using `docker build` normally (with disabled testing).

However, when I want to run my tests using testcontainers, the whole thing crashes.

# Logs

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.5.RELEASE)

2021-03-22 11:17:44.614  WARN 112 --- [ers-lifecycle-0] o.t.utility.TestcontainersConfiguration  : Attempted to read Testcontainers configuration file at file:/root/.testcontainers.properties but the file was not found. Exception message: FileNotFoundException: /root/.testcontainers.properties (No such file or directory)
2021-03-22 11:17:44.618  INFO 112 --- [ers-lifecycle-0] o.t.utility.ImageNameSubstitutor         : Image name substitution will be performed by: DefaultImageNameSubstitutor (ConfigurationFileImageNameSubstitutor)
2021-03-22 11:17:44.646  INFO 112 --- [ers-lifecycle-1] .t.d.DockerMachineClientProviderStrategy : docker-machine executable was not found on PATH ([/usr/local/openjdk-14/bin, /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin])
2021-03-22 11:17:45.235  INFO 112 --- [ers-lifecycle-1] o.t.d.DockerClientProviderStrategy       : Found Docker environment with Environment variables, system properties and defaults. Resolved dockerHost=tcp://jenkinsdind:2376
2021-03-22 11:17:45.243  INFO 112 --- [ers-lifecycle-1] org.testcontainers.DockerClientFactory   : Docker host IP address is jenkinsdind
2021-03-22 11:17:45.270  INFO 112 --- [ers-lifecycle-1] org.testcontainers.DockerClientFactory   : Connected to docker: 
  Server Version: 19.03.13
  API Version: 1.40
  Operating System: Alpine Linux v3.12 (containerized)
  Total Memory: 773757 MB
2021-03-22 11:17:45.344  INFO 112 --- [ers-lifecycle-1] o.t.utility.RegistryAuthLocator          : Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: testcontainers/ryuk:0.3.0, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory)
2021-03-22 11:17:45.539 ERROR 112 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.util.concurrent.CompletionException: org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:327) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:308) ~[testcontainers-1.15.0.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) ~[na:na]
	... 4 common frames omitted
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=MY_NEXUS_REPO/MY_PSQL_IMAGE:1.0, imagePullPolicy=DefaultPullPolicy())
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1278) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:612) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:317) ~[testcontainers-1.15.0.jar:na]
	... 6 common frames omitted
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"invalid volume specification: 'tcp://jenkinsdind:2376:/var/run/docker.sock:rw'"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:125) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:33) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.shaded.com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:595) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:91) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:203) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.LazyDockerClient.listImagesCmd(LazyDockerClient.java:12) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.images.LocalImagesCache.maybeInitCache(LocalImagesCache.java:68) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.images.LocalImagesCache.get(LocalImagesCache.java:32) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.images.AbstractImagePullPolicy.shouldPull(AbstractImagePullPolicy.java:18) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:66) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:27) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:17) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:39) ~[testcontainers-1.15.0.jar:na]
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1276) ~[testcontainers-1.15.0.jar:na]
	... 8 common frames omitted

```

# Additional Configuration

- Testcontainers version: 1.15.2
- `DOCKER_HOST` and `TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE` are both set to `tcp://jenkinsdind:2376` as described [in the documentation](https://www.testcontainers.org/features/configuration/)

# Questions

A couple of questions now arise on my side from reading the logs:

1. Ryuk is telling me `/root/.docker/config.json` does not exist - however there is such a file within the Jenkins-Agent. How can I configure testcontainers to pass this file on to ruyk?
2. Why does Ryuk need the configuration in the first place - During my Pipeline, I use `docker login` and pull the required images beforehand.
3. Why am I able to run typical docker commands such as `docker build` inside my agent but testcontainers fails to access the correct configuration? What setting am I missing?
4. The latest error in the stack trace reads: `Status 500: {"message":"invalid volume specification: 'tcp://jenkinsdind:2376:/var/run/docker.sock:rw'"}` - can testcontainers not use a DOCKER_HOST connection via `tcp` ?

Help is much appreciated :-)

**Comment by bsideup** [comment]
TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE should point to the Linux socket, not DOCKER_HOST.

See https://bsideup.github.io/posts/rootless_docker/ for more details.

**Comment by bsideup** [comment]
1. and 2. questions are kinda invalid - Ryuk needs the socket to talk to Docker and perform the cleanup and not for the image pulling :)
