### ISSUE TITLE
Cannot start testcontainer if wincred store is used

### ISSUE THREAD

**Issue by beihaifeiwu** [testcontainers/testcontainers-java#392]
```bash
java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:142)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at org.junit.runners.model.FrameworkField.get(FrameworkField.java:73)
	at org.junit.runners.model.TestClass.getAnnotatedFieldValues(TestClass.java:230)
	at org.junit.runners.ParentRunner.classRules(ParentRunner.java:255)
	at org.junit.runners.ParentRunner.withClassRules(ParentRunner.java:244)
	at org.junit.runners.ParentRunner.classBlock(ParentRunner.java:194)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:362)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:189)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.github.dockerjava.api.exception.DockerClientException: Failed to parse dockerCfgFile
	at com.github.dockerjava.core.DefaultDockerClientConfig.effectiveAuthConfig(DefaultDockerClientConfig.java:268)
	at com.github.dockerjava.core.DockerClientImpl.pullImageCmd(DockerClientImpl.java:215)
	at org.testcontainers.dockerclient.AuditLoggingDockerClient.pullImageCmd(AuditLoggingDockerClient.java:22)
	at org.testcontainers.DockerClientFactory.checkAndPullImage(DockerClientFactory.java:202)
	at org.testcontainers.DockerClientFactory.runInsideDocker(DockerClientFactory.java:222)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:117)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:110)
	at org.testcontainers.containers.FixedHostPortGenericContainer.<init>(FixedHostPortGenericContainer.java:16)
	at com.palmaplus.euphoria.data.ElasticsearchRepositoryTest.<clinit>(ElasticsearchRepositoryTest.java:38)
	... 18 more
Caused by: java.io.IOException: The Auth Config file is empty
	at com.github.dockerjava.core.AuthConfigFile.loadConfig(AuthConfigFile.java:141)
	at com.github.dockerjava.core.DefaultDockerClientConfig.effectiveAuthConfig(DefaultDockerClientConfig.java:266)
	... 26 more
```

**Comment by wlsc** [comment]
I had same issue but not with the Test Containers library but the Docker itself. Reinstalled it (with deleting .docker folder) and it helped.

**Comment by kiview** [comment]
The error message sounds like a problem with your `config.json` file (which resides inside the `.docker/` registry, so @wlsc solution makes sense).

**Comment by beihaifeiwu** [comment]
Hi @kiview @wlsc , thinks for your reply , I have tried delete .docker folder and reinstall, but the error still exists. Now I cannot run any test due to this problem :( .

**Comment by kiview** [comment]
Are you trying to use a private image? Did you do a docker login on the host before?

**Comment by beihaifeiwu** [comment]
No, I just use the image from the docker hub.  Yes I have login on the host before, but that did not help either.

**Comment by kiview** [comment]
What's the content of your `config.json` file? Does it exist?

**Comment by beihaifeiwu** [comment]
Yes, it exists!

```json
{"credsStore":"wincred","auths":{"https://index.docker.io/v1/":{}}}
```

**Comment by kiview** [comment]
Oh I see, you are on windows? It might be a problem docker-java and a recent Docker for Windows version. I'll try to test it on windows once I have the time.

**Comment by beihaifeiwu** [comment]
Yes, my system is Windows 10, thanks for you attention

**Comment by bsideup** [comment]
Please also try https://github.com/testcontainers/testcontainers-java/pull/393 with updated docker-java (with Jitpack)

**Comment by beihaifeiwu** [comment]
@bsideup , It didn't work either :( .

**Comment by kiview** [comment]
@jeacott1 Which image were you testing? Do you have log output from the preflight checks, did they succeed?

**Comment by jeacott1** [comment]
@kiview initially the testcontainers-java-module-elasticsearch, and now the postgres module. haven't had any issues since removing the config file. and I just tried it, the postgres module at least still works now I've restored the file.
fwiw - I cant recall the order of things but at some point I had to accept a security permission dialog accepting docker be allowed access to the local drive.

**Comment by kiview** [comment]
@jeacott1 Thanks for all your feedback (spread over different issues :wink:), I'll try to confirm, that this has to do with the `wincred` credStore in Docker for Windows.

**Comment by rnorth** [comment]
We added support for credential helpers recently, with Windows support in [1.9.0](https://github.com/testcontainers/testcontainers-java/releases/tag/1.9.0).

As such, this should work now! Please feel free to reopen if there are other issues with this feature.
