### ISSUE TITLE
JDBC URL matches jdbc:tc: prefix but the database or tag name could not be identified

### ISSUE THREAD

**Issue by yerzhant** [testcontainers/testcontainers-java#3931]
When I'm using a private image as per https://www.testcontainers.org/features/image_name_substitution/#manual-substitution
like this `jdbc:tc:domain.com/my-image:1.0.0:///testdb` I'm getting the string parsing error:
```
Caused by: java.lang.IllegalArgumentException: JDBC URL matches jdbc:tc: prefix but the database or tag name could not be identified
	at org.testcontainers.jdbc.ConnectionUrl.parseUrl(ConnectionUrl.java:97)
	at org.testcontainers.jdbc.ConnectionUrl.newInstance(ConnectionUrl.java:67)
	at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:73)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	... 108 more
```

**Comment by bsideup** [comment]
the part after `tc:` isn't the image name, but the database id. Database aliases will help (see #4), but today you an use the image substitution feature to achieve what you need:
https://www.testcontainers.org/features/image_name_substitution/

**Comment by yerzhant** [comment]
As per https://www.testcontainers.org/modules/databases/jdbc/ it **is**.
From the docs: `jdbc:tc:postgresql:9.6.8:///databasename`

**Comment by tunovic** [comment]
Why does the `hub.image.name.prefix` not work in this case and I need to implement my own image substitutor? Can this be implemented that alias is using `hub.image.name.prefix` too?
