### ISSUE TITLE
NoSuchMethodError: com.fasterxml.jackson.annotation.JsonFormat$Value.empty

### ISSUE THREAD

**Issue by drazzib** [testcontainers/testcontainers-java#3937]
With latest testcontainers **1.15.2** I'm always getting the following error
```
2021-03-27 23:26:38,411  INFO  [testcontainers.dockerclient.DockerClientProviderStrategy] [main] Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy from ~/.testcontainers.properties, will try it first

java.lang.NoSuchMethodError: com.fasterxml.jackson.annotation.JsonFormat$Value.empty()Lcom/fasterxml/jackson/annotation/JsonFormat$Value;

	at org.testcontainers.shaded.com.fasterxml.jackson.databind.cfg.MapperConfig.<clinit>(MapperConfig.java:49)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:558)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:474)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultObjectMapperHolder.<init>(DockerClientConfig.java:51)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultObjectMapperHolder.<clinit>(DockerClientConfig.java:49)
	at org.testcontainers.shaded.com.github.dockerjava.core.DockerClientConfig.getObjectMapper(DockerClientConfig.java:44)
	at org.testcontainers.dockerclient.AuthDelegatingDockerClientConfig.getObjectMapper(AuthDelegatingDockerClientConfig.java:23)
	at org.testcontainers.shaded.com.github.dockerjava.core.DockerClientImpl.withHttpClient(DockerClientImpl.java:218)
	at org.testcontainers.shaded.com.github.dockerjava.core.DockerClientImpl.getInstance(DockerClientImpl.java:201)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getClientForConfig(DockerClientProviderStrategy.java:245)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getDockerClient(DockerClientProviderStrategy.java:40)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$6(DockerClientProviderStrategy.java:144)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:269)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:303)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:536)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:206)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:136)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:178)
	at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
	at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:310)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1029)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
```

From what I can see, shaded `org.testcontainers.shaded.com.fasterxml.jackson.databind.cfg.MapperConfig` still contains a reference to unshaded `com.fasterxml.jackson.annotation.JsonFormat.Value`

**Comment by bsideup** [comment]
@drazzib `JsonFormat$Value.empty()` is there since 2.7, and Testcontainers depends on Jackson 2.8.8, meaning that something in your project forces Jackson to some super old version. Please check your project.

**Comment by bsideup** [comment]
FYI there is nothing wrong with `org.testcontainers.shaded.com.fasterxml.jackson.databind.cfg.MapperConfig` referring `com.fasterxml.jackson.annotation.JsonFormat.Value`, as these are two different dependencies (`jackson-databind` and `jackson-annotations`).
