### ISSUE TITLE
java.lang.ClassCircularityError

### ISSUE THREAD

**Issue by CatCodeMe** [testcontainers/testcontainers-java#3997]
when I run s simple test-case , I get this error.  It works before some days.

java.lang.ClassCircularityError: javax/crypto/BadPaddingException

	at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:216)
	at java.security.Signature$Delegate.engineVerify(Signature.java:1394)
	at java.security.Signature.verify(Signature.java:771)
	at sun.security.x509.X509CertImpl.verify(X509CertImpl.java:452)
	at sun.security.x509.X509CertImpl.verify(X509CertImpl.java:391)
	at javax.crypto.JarVerifier.testSignatures(JarVerifier.java:783)
	at javax.crypto.JarVerifier.access$400(JarVerifier.java:37)
	at javax.crypto.JarVerifier$1.run(JarVerifier.java:230)
	at javax.crypto.JarVerifier$1.run(JarVerifier.java:195)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.crypto.JarVerifier.<clinit>(JarVerifier.java:194)
	at javax.crypto.JceSecurity.loadPolicies(JceSecurity.java:378)
	at javax.crypto.JceSecurity.setupJurisdictionPolicies(JceSecurity.java:323)
	at javax.crypto.JceSecurity.access$000(JceSecurity.java:50)
	at javax.crypto.JceSecurity$1.run(JceSecurity.java:85)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.crypto.JceSecurity.<clinit>(JceSecurity.java:82)
	at javax.crypto.Cipher.getInstance(Cipher.java:518)
	at sun.security.ssl.JsseJce.getCipher(JsseJce.java:189)
	at sun.security.ssl.SSLCipher.isTransformationAvailable(SSLCipher.java:483)
	at sun.security.ssl.SSLCipher.<init>(SSLCipher.java:472)
	at sun.security.ssl.SSLCipher.<clinit>(SSLCipher.java:81)
	at sun.security.ssl.CipherSuite.<clinit>(CipherSuite.java:67)
	at sun.security.ssl.SSLContextImpl.getApplicableSupportedCipherSuites(SSLContextImpl.java:345)
	at sun.security.ssl.SSLContextImpl.access$100(SSLContextImpl.java:46)
	at sun.security.ssl.SSLContextImpl$AbstractTLSContext.<clinit>(SSLContextImpl.java:577)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.security.Provider$Service.getImplClass(Provider.java:1728)
	at java.security.Provider$Service.newInstance(Provider.java:1686)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
	at org.testcontainers.shaded.okhttp3.internal.platform.Platform.getSSLContext(Platform.java:272)
	at org.testcontainers.shaded.okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
	at org.testcontainers.shaded.okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
	at org.testcontainers.shaded.okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
	at org.testcontainers.shaded.com.github.dockerjava.okhttp.OkDockerHttpClient.<init>(OkDockerHttpClient.java:154)
	at org.testcontainers.shaded.com.github.dockerjava.okhttp.OkDockerHttpClient.<init>(OkDockerHttpClient.java:32)
	at org.testcontainers.shaded.com.github.dockerjava.okhttp.OkDockerHttpClient$Builder.build(OkDockerHttpClient.java:75)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getClientForConfig(DockerClientProviderStrategy.java:228)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getDockerClient(DockerClientProviderStrategy.java:40)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$6(DockerClientProviderStrategy.java:144)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:302)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:469)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:206)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:136)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:178)
	at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
	at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:310)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1029)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

**Comment by CatCodeMe** [comment]
I use the default redis test-case from testcontainers.org

**Comment by CatCodeMe** [comment]
when I set system-env to “httpclient5”,  it works!
![image](https://user-images.githubusercontent.com/11496772/114542433-81152a80-9c8a-11eb-8a9f-8e5016f5cd56.png)
