### ISSUE TITLE
couchbase : image name required not compatible anymore with testcontainers

### ISSUE THREAD

**Issue by zbendhiba** [testcontainers/testcontainers-java#3999]
The docker image name in the code is not compatible anymore with the new docker tags.
Test container is expecting _couchbase/server_

On the other hands, in docker hub: the names of tags are now like that :  _couchbase:enterprise-6.6.1_ or _couchbase:community-6.6.0_ or _couchbase:6.6.1_

I'm having this error now if I'm using couchbase testcontainers with community tag couchbase/community-6.6.0 for instance :

```
java.lang.IllegalStateException: Failed to verify that image 'couchbase/community-6.6.0' is a compatible substitute for 'couchbase/server'. This generally means that you are trying to use an image that Testcontainers has not been designed to use. If this is deliberate, and if you are confident that the image is compatible, you should declare compatibility in code using the `asCompatibleSubstituteFor` method. For example:
   DockerImageName myImage = DockerImageName.parse("couchbase/community-6.6.0").asCompatibleSubstituteFor("couchbase/server");
and then use `myImage` instead.
	at org.testcontainers.utility.DockerImageName.assertCompatibleWith(DockerImageName.java:248)
	at org.testcontainers.couchbase.CouchbaseContainer.<init>(CouchbaseContainer.java:116)

```

An the old tag I was using couchbase/server-6.6.0 has been renamed and is not available anymore, and my integration tests are now failing.

**Comment by bsideup** [comment]
Hi @zbendhiba,

It looks like the Couchbase team released an "official" image: https://hub.docker.com/_/couchbase

For now, you can just follow what exception message says and pass it like this:
```java
new CouchbaseContainer(
    DockerImageName.parse("couchbase/community-6.6.0").asCompatibleSubstituteFor("couchbase/server")
)
```

**Comment by zbendhiba** [comment]
@bsideup thanks for the workaround tip !

**Comment by daschl** [comment]
I  think this should be resolved with the latest releases and versions, right? Can this be closed @zbendhiba ?
