### ISSUE TITLE
"Can not connect to Ryuk at localhost" on Fedora

### ISSUE THREAD

**Issue by akulik512** [testcontainers/testcontainers-java#4014]
I want to publish an issue with a connection to Ryuk and the solution which we found in Testcontainers Slack chat that this information will be possible to find.

When running my test, I get the following:
```
21:22:12.834 [testcontainers-ryuk] WARN org.testcontainers.utility.ResourceReaper - Can not connect to Ryuk at localhost:32776
java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.testcontainers.utility.ResourceReaper.lambda$null$1(ResourceReaper.java:163)
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
	at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:159)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
You may have seen a similar log in this issue: #3166 . Whereas a solution, it was suggested to use a newly released version 1.15.0-rc2 (#3159). But it didn't work for me because I've already used the 1.15.3 version and what is more important it was a specific on MacOs only problem.

OS: Fedora 33
Docker version: 19.03.13

For Fedora (and probably on other Linux distros) user, it can be fixed if add the following line to the `.testcontainers.properties`
```
ryuk.container.privileged = true
```
The `.testcontainers.properties` file should be located (or already exist) by this way: `/home/myuser/.testcontainers.properties`.

You can find more information about `.testcontainers.properties` file at this link: https://www.testcontainers.org/features/configuration/

**Comment by akulik512** [comment]
Since I answered my own question, I think that this issue can be closed. Not sure about labels for this issue but if necessary they can be added (I don't know how to do it).
