### ISSUE TITLE
 Could not find a valid Docker environment. Please see logs and check configuration

### ISSUE THREAD

**Issue by mikebell90** [testcontainers/testcontainers-java#4034]
Note: This is not a dupe of any ticket I could find.

1. I was at TestContainers 1.12.5, which worked but had both buildkti and rate limiting issues.
2. I upgrade to 1.15.3. I'm on a mac, with buildkit: false, gFuse unchecked. (hence those tips aint useful)\
3. I'm on Engine 20.10.5, overall release 3.3.1

When I run my testcontainer, I get  an error

`Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:215)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:207)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:136)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:178)
	at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
	at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:310)
	at com.opentable.redis.EmbeddedRedisConfiguration.embeddedRedis(EmbeddedRedisConfiguration.java:40)
	at com.opentable.redis.EmbeddedRedisConfiguration$$EnhancerBySpringCGLIB$$357f9c1e.CGLIB$embeddedRedis$0(<generated>)
	at com.opentable.redis.EmbeddedRedisConfiguration$$EnhancerBySpringCGLIB$$357f9c1e$$FastClassBySpringCGLIB$$dc3bce59.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.opentable.redis.EmbeddedRedisConfiguration$$EnhancerBySpringCGLIB$$357f9c1e.embeddedRedis(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 48 common frames omitted
`

<img width="1005" alt="Screen Shot 2021-04-26 at 2 27 16 PM" src="https://user-images.githubusercontent.com/780301/116153178-c29ad200-a69b-11eb-8233-6ec92a5fd28d.png">
<img width="846" alt="Screen Shot 2021-04-26 at 2 26 58 PM" src="https://user-images.githubusercontent.com/780301/116153182-c4649580-a69b-11eb-80e8-bc89eae92834.png">

**Comment by mikebell90** [comment]
Ah it was a dupe after all! The JNA wasn't updated to 5.8.0

**Comment by vshinde3574** [comment]
@mikebell90  Can you please elaborate the solution? I am facing the same issue for Testcontainers.

**Comment by mikebell90** [comment]
Jna jar wasn’t new enough
