### ISSUE TITLE
Execution gets stuck on DomainSocket#read() while creating container in DinD

### ISSUE THREAD

**Issue by harshSE** [testcontainers/testcontainers-java#4037]
I am using multiple parallel [docker:20.10.6-dind](https://hub.docker.com/_/docker) containers in a physical machine to run test cases in parallel.

Each container created by testcontainers during test execution in DinD container is local to that container only. 

When we run test cases with only a single DinD container. Test cases execute without any problem. But when we run test cases on multiple DinD containers it stuck on `DomainSocket#read()`. 

I have also check that containers are in created state and we are not able to delete that. so only option available for us is to restart DinD the container .

```
CONTAINER ID     IMAGE         COMMAND                      STATUS     NAMES
068ccef802bd      alpine:3.5     "sh -c 'ip route|awk…"      Created     exciting_brown
ad76819e8b86     alpine:3.5     "sh -c 'ip route|awk…"      Created     amazing_morse
1c5d11575513      alpine:3.5     "sh -c 'ip route|awk…"      Created     quirky_jennings
````

### Testcontainer Version
`1.15.3`

### Docker run command to run DinD container
`docker run --detach  --privileged gradle-docker:1.4.1-dind`

### Environment Variable in DinD container

- TESTCONTAINERS_TRANSPORT_TYPE=httpclient5

- TESTCONTAINERS_REUSE_ENABLE=true

Attaching thread dump and logs test container.

```
INFO  | 2021-04-27 19:48:28 IST| 9b14bf680111 | [main] org.testcontainers.dockerclient.DockerClientProviderStrategy (DockerClientProviderStrategy.java:136) - Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first | {}
INFO  | 2021-04-27 19:48:28 IST| cd578f6fac85 | [main] org.testcontainers.dockerclient.DockerClientProviderStrategy (DockerClientProviderStrategy.java:136) - Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first | {}
INFO  | 2021-04-27 19:48:28 IST| d4bb14f8e58d | [main] org.testcontainers.dockerclient.DockerClientProviderStrategy (DockerClientProviderStrategy.java:136) - Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first | {}
INFO  | 2021-04-27 19:48:28 IST| 2803dd6ee2fb | [main] org.testcontainers.dockerclient.DockerClientProviderStrategy (DockerClientProviderStrategy.java:136) - Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first | {}
INFO  | 2021-04-27 19:48:28 IST| 1f00865cf4d0 | [main] org.testcontainers.dockerclient.DockerClientProviderStrategy (DockerClientProviderStrategy.java:136) - Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first | {}
INFO  | 2021-04-27 19:48:28 IST| a2fa85a99927 | [main] org.testcontainers.dockerclient.DockerClientProviderStrategy (DockerClientProviderStrategy.java:136) - Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first | {}
INFO  | 2021-04-27 19:48:33 IST| cd578f6fac85 | [main] org.testcontainers.dockerclient.DockerClientProviderStrategy (DockerClientProviderStrategy.java:158) - Found Docker environment with local Unix socket (unix:///var/run/docker.sock) | {}
INFO  | 2021-04-27 19:48:33 IST| d4bb14f8e58d | [main] org.testcontainers.dockerclient.DockerClientProviderStrategy (DockerClientProviderStrategy.java:158) - Found Docker environment with local Unix socket (unix:///var/run/docker.sock) | {}
INFO  | 2021-04-27 19:48:33 IST| 2803dd6ee2fb | [main] org.testcontainers.dockerclient.DockerClientProviderStrategy (DockerClientProviderStrategy.java:158) - Found Docker environment with local Unix socket (unix:///var/run/docker.sock) | {}
INFO  | 2021-04-27 19:48:33 IST| 2803dd6ee2fb | [main] org.testcontainers.utility.ImageNameSubstitutor (ImageNameSubstitutor.java:50) - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor') | {}
INFO  | 2021-04-27 19:48:33 IST| 9b14bf680111 | [main] org.testcontainers.dockerclient.DockerClientProviderStrategy (DockerClientProviderStrategy.java:158) - Found Docker environment with local Unix socket (unix:///var/run/docker.sock) | {}
INFO  | 2021-04-27 19:48:33 IST| 9b14bf680111 | [main] org.testcontainers.utility.ImageNameSubstitutor (ImageNameSubstitutor.java:50) - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor') | {}
INFO  | 2021-04-27 19:48:33 IST| cd578f6fac85 | [main] org.testcontainers.utility.ImageNameSubstitutor (ImageNameSubstitutor.java:50) - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor') | {}
INFO  | 2021-04-27 19:48:33 IST| cd578f6fac85 | [main] org.testcontainers.utility.RegistryAuthLocator (RegistryAuthLocator.java:148) - Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: alpine:3.5, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory) | {}
INFO  | 2021-04-27 19:48:33 IST| 1f00865cf4d0 | [main] org.testcontainers.dockerclient.DockerClientProviderStrategy (DockerClientProviderStrategy.java:158) - Found Docker environment with local Unix socket (unix:///var/run/docker.sock) | {}
INFO  | 2021-04-27 19:48:33 IST| d4bb14f8e58d | [main] org.testcontainers.utility.ImageNameSubstitutor (ImageNameSubstitutor.java:50) - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor') | {}
INFO  | 2021-04-27 19:48:33 IST| d4bb14f8e58d | [main] org.testcontainers.utility.RegistryAuthLocator (RegistryAuthLocator.java:148) - Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: alpine:3.5, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory) | {}
INFO  | 2021-04-27 19:48:33 IST| 2803dd6ee2fb | [main] org.testcontainers.utility.RegistryAuthLocator (RegistryAuthLocator.java:148) - Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: alpine:3.5, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory) | {}
INFO  | 2021-04-27 19:48:33 IST| 9b14bf680111 | [main] org.testcontainers.utility.RegistryAuthLocator (RegistryAuthLocator.java:148) - Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: alpine:3.5, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory) | {}
INFO  | 2021-04-27 19:48:33 IST| 1f00865cf4d0 | [main] org.testcontainers.utility.ImageNameSubstitutor (ImageNameSubstitutor.java:50) - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor') | {}
INFO  | 2021-04-27 19:48:33 IST| 1f00865cf4d0 | [main] org.testcontainers.utility.RegistryAuthLocator (RegistryAuthLocator.java:148) - Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: alpine:3.5, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory) | {}
INFO  | 2021-04-27 19:48:33 IST| a2fa85a99927 | [main] org.testcontainers.dockerclient.DockerClientProviderStrategy (DockerClientProviderStrategy.java:158) - Found Docker environment with local Unix socket (unix:///var/run/docker.sock) | {}
INFO  | 2021-04-27 19:48:33 IST| a2fa85a99927 | [main] org.testcontainers.utility.ImageNameSubstitutor (ImageNameSubstitutor.java:50) - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor') | {}
INFO  | 2021-04-27 19:48:33 IST| a2fa85a99927 | [main] org.testcontainers.utility.RegistryAuthLocator (RegistryAuthLocator.java:148) - Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: alpine:3.5, configFile: /root/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /root/.docker/config.json (No such file or directory) | {}
```

[ThreadDump.txt](https://github.com/testcontainers/testcontainers-java/files/6389987/ThreadDump.txt)

```
"main" #1 prio=5 os_prio=0 tid=0x00007fa628017000 nid=0x4f0e runnable [0x00007fa62c220000]
       java.lang.Thread.State: RUNNABLE
        at com.github.dockerjava.transport.DomainSocket.read(Native Method)
        at com.github.dockerjava.transport.DomainSocket.read(DomainSocket.java:79)
        at com.github.dockerjava.transport.DomainSocket.access$200(DomainSocket.java:35)
        at com.github.dockerjava.transport.DomainSocket$DomainSocketInputStream.read(DomainSocket.java:162)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:149)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:241)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:53)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:187)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:175)
        at com.github.dockerjava.zerodep.HijackingHttpRequestExecutor.execute(HijackingHttpRequestExecutor.java:50)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:596)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:215)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:107)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:181)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:172)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
        at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
        at com.github.dockerjava.zerodep.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:161)
        at com.github.dockerjava.zerodep.ZerodepDockerHttpClient.execute(ZerodepDockerHttpClient.java:8)
        at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13)
        at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
        at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
        at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43)
        at org.testcontainers.DockerClientFactory.runInsideDocker(DockerClientFactory.java:361)
        at org.testcontainers.DockerClientFactory.runInsideDocker(DockerClientFactory.java:347)
        at org.testcontainers.dockerclient.DockerClientConfigUtils.getDefaultGateway(DockerClientConfigUtils.java:20)
        - locked <0x00000000fd702678> (a java.util.concurrent.atomic.AtomicReference)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$resolveDockerHostIpAddress$9(DockerClientProviderStrategy.java:287)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy$$Lambda$234/1233191588.get(Unknown Source)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.resolveDockerHostIpAddress(DockerClientProviderStrategy.java:286)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.getDockerHostIpAddress(DockerClientProviderStrategy.java:257)
        - locked <0x00000000e0013310> (a org.testcontainers.dockerclient.UnixSocketClientProviderStrategy)
        at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:180)
        - locked <0x00000000e0013478> (a [Ljava.lang.Object;)
        at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
        at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:310)
```

**Comment by bsideup** [comment]
Hi @harshSE,

> I have also check that containers are in created state and we are not able to delete that.

This sounds like a problem with Docker and not Testcontainers. Testcontainers waits for the container to start (see `StartContainerCmdExec.execute` in the stacktrace) but it doesn't, and it continues waiting.

Consider reporting to Docker, as it looks like a race condition with Docker (probably due to the usage of `dind`) and there isn't anything we could do about it on our side.
