### ISSUE TITLE
Testcontainers build fails - MySQL, DB2, ... impacted by removal of TLS<1.2 in `adopt@1.11.0-11` 

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#4058]
It seems that some of our tests are now failing on CI, and I've correlated this to `adopt@1.11.0-11` JDK. Note that this is _not_ a problem when using `adopt@1.11.0-10`, so it seems that a deprecation might be triggering this

```
Caused by:
                javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
                    at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:170)
                    at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:98)
                    at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:221)
                    at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:433)
                    at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:411)
                    at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:317)
                    at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:188)
                    at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:97)
                    at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:331)
                    ... 19 more
```

To reproduce, change JDK versions as above and run:
```
./gradlew clean mysql:test --tests org.testcontainers.junit.mysql.SimpleMySQLTest --no-build-cache
```

**Comment by rnorth** [comment]
Almost certainly due to this: https://bugs.openjdk.java.net/browse/JDK-8202343

**Comment by bsideup** [comment]
FYI https://github.com/actions/virtual-environments/issues/3325

**Comment by rnorth** [comment]
Reopening, as I've found the same problem with DB2.

**Comment by rnorth** [comment]
Looks like DB2 is going to be a pain, as out of the box it will need extra configuration operations to turn on TLS1.2:
https://www.ibm.com/docs/en/db2/11.5?topic=parameters-ssl-versions-supported-ssl-versions-server
> The default value for SSL_VERSIONS is null. If you set the parameter to null or TLSv1, the parameter enables support for TLS version 1.0 (RFC2246) and TLS version 1.1 (RFC4346). **TLS version 1.2 is not enabled by default.**
