### ISSUE TITLE
Shading org.apache.commons.io

### ISSUE THREAD

**Issue by mumukiller** [testcontainers/testcontainers-java#421]
I'm using org.testcontainers.postgresql version 1.4.2 and docker for windows

Getting this error:
Caused by: java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
	at org.testcontainers.DockerClientFactory.checkExposedPort(DockerClientFactory.java:190)
	at org.testcontainers.DockerClientFactory.lambda$client$1(DockerClientFactory.java:129)
	at org.testcontainers.DockerClientFactory.runInsideDocker(DockerClientFactory.java:230)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:118)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:116)
	at org.testcontainers.containers.JdbcDatabaseContainer.<init>(JdbcDatabaseContainer.java:35)
	at org.testcontainers.containers.PostgreSQLContainer.<init>(PostgreSQLContainer.java:25)
	at org.testcontainers.containers.PostgreSQLContainer.<init>(PostgreSQLContainer.java:21)

I checked dependencies using  mvn dependency:tree and found this:
+- commons-fileupload:commons-fileupload:jar:1.3.3:compile
     \- commons-io:commons-io:jar:2.2:compile

Probably it helps.

PS Used exclusions as workaround, but anyway it's better to report :)

**Comment by grexe** [comment]
had the same issue but in my case was able to solve it by using latest stable apache.commons-io 2.5 in my project, as testcontainers 1.4.2 core uses the same.

**Comment by glebsts** [comment]
+1 , added org.mock-server:mockserver-client-java:3.10.7 and it exploded with same things. @rnorth @bsideup can it be shaded pls?

**Comment by bsideup** [comment]
@glebsts @grexe @mumukiller 

ACK :)

**Comment by glebsts** [comment]
Sad story, mockserver-client-java is already 3.11 and has some changes regarding callback handling.

**Comment by glebsts** [comment]
just a note about my workarounds:
`dependencies {
testCompile ('org.testcontainers:testcontainers:1.4.3') {
        exclude group: 'org.apache.commons', module: 'commons-io'
    }
testCompile ('org.mock-server:mockserver-netty:3.11') {
        exclude group: 'org.apache.commons', module: 'commons-io'
    }
}
configurations.all {
    resolutionStrategy {
        force 'commons-io:commons-io:2.5'
    }
}
`
mb will help smbd
