### ISSUE TITLE
NullPointerException on BitbucketPipelines

### ISSUE THREAD

**Issue by heliomartins** [testcontainers/testcontainers-java#4215]
Hello 👋 ,

I was looking for some assistance here, please. 
I've been trying to run TestContainers in Bitbucket Pipelines but so far I didn't succeed. I've also followed this page https://www.testcontainers.org/supported_docker_environment/continuous_integration/bitbucket_pipelines/ to ensure that the configuration was properly setup. 

All the tests I've written working fine locally, however, when I push my changes, I get the following exception:

```java
java.lang.NullPointerException
        at org.testcontainers.utility.CommandLine.getSystemPath(CommandLine.java:77)
        at org.testcontainers.utility.CommandLine.executableExists(CommandLine.java:65)
        at org.testcontainers.utility.DockerMachineClient.isInstalled(DockerMachineClient.java:52)
        at org.testcontainers.dockerclient.DockerMachineClientProviderStrategy.isApplicable(DockerMachineClientProviderStrategy.java:56)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
        at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
        at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
        at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:723)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:548)
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:206)
        at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:136)
        at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:178)
        at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
        at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:310)
        at com.atlassian.buildeng.artifactory.test.usecase.validator.BambooValidatorNewTest.setup(BambooValidatorNewTest.kt:28)
```

My understanding is that the environment variable PATH is not being recognized and it is throwing NullPointer.
```java
    @NotNull
    public static String[] getSystemPath() {
        return System.getenv("PATH").split(Pattern.quote(File.pathSeparator));
    }
```
        
I'm running my application on `adoptopenjdk/openjdk11:slim` and I've checked that indeed it has `$PATH` set.

Below are some of the snippets I used to configure my application:

Dependency added in `build.gradle.kts`
`testImplementation("org.testcontainers", "spock", "1.15.3")`

```Kotlin
/**
 * This class is used as a workaround for https://github.com/testcontainers/testcontainers-java/issues/318.
 */
class KGenericContainer(imageName: String) : GenericContainer<KGenericContainer>(imageName)
```

```Kotlin
object RedisTestContainer {
    val redis: KGenericContainer = KGenericContainer("redis:6.2.4-alpine").withExposedPorts(6379)
}
```

Using Koin to create RedisClient and inject in my DI module.
```Kotlin
single { TokenatorRedisClient(RedisClient.create("redis://${RedisTestContainer.redis.host}:${RedisTestContainer.redis.firstMappedPort}/")) }
```

```Kotlin
class BambooValidatorNewTest : Specification() {
    @BeforeEach
    fun setup() {
        stopKoin()
        RedisTestContainer.redis.start() // It is here that triggers the exception.
        startKoin { modules(testModule) }
    }

    @AfterEach
    fun tearDown() {
        RedisTestContainer.redis.stop()
    }
```

BitbucketPipelines Step
```yaml
    - step:
        name: Build and Test
        image: adoptopenjdk/openjdk11:slim
        size: 2x
        services:
          - docker
        script:
          - export TESTCONTAINERS_RYUK_DISABLED=true
          - ./gradlew build
```

When the tests are executed in Bitbucket Pipelines, I have `RedisTestContainer.redis.start()` as the trigger to the exception.

Apologies if this is a silly problem, but any help would be greatly appreciated.

Thanks in advance.

**Comment by shmish111** [comment]
@heliomartins why did you close this issue? We are getting the same issue and are pretty flummoxed by it

**Comment by kiview** [comment]
@shmish111 Can you add an `echo $PATH` to your pipeline? 
Also, it is one thing of having the `PATH` set in the container, but another of how Bitbucket Pipelines executes the different `script` steps.

**Comment by shmish111** [comment]
Interestingly I can get this to fail in some environments and not others however since I can get it to fail from my local machine as well as google cloud build, I know that the PATH is correct (on the host)

**Comment by kiview** [comment]
What do you have to do to make it fail on your local machine and what is the OS of your local machine?
In addition, the content of the `$PATH` might help in debugging this.

**Comment by shmish111** [comment]
ok so weird:
OK, once we disabled caching, it failed on google cloud build (running in a linux container), failed on OSX (M1), failed on an aarch64 linux VM but passed on a native linux x86 machine.

Even more weird though:

I was on testcontainers 0.16.0 (things failed)
I upgraded to 0.16.2 (things passed)
I downgraded to 0.16.0 (things passed again!)

I did this with gradle clean and --no-build-cache so I have no idea how that's possible.

I'm just testing in cloud build now.

**Comment by kiview** [comment]
I assume you are talking about `1.16.2`?
Also, please make sure to use the latest version. 

And if this is about Gradle caches, I don't think this is related to Testcontainers, this code works for many users and many environments.

**Comment by shmish111** [comment]
sorry yes 1.16.2. My point with the caches was that I made sure it wasn't using any cache

**Comment by shmish111** [comment]
TBH since it seems to be working then I'm happy, this seems like it would be something very difficult to diagnose and 1.16.2 seems to work with no issues. Thanks for your help.
