### ISSUE TITLE
getting abstract method error when working with Mongo test container

### ISSUE THREAD

**Issue by shikharkhanna** [testcontainers/testcontainers-java#4218]
getting below error when trying to start a mongo test container,pls help

java.lang.AbstractMethodError: Method org/testcontainers/shaded/com/github/dockerjava/core/command/CreateContainerCmdImpl.getPlatform()Ljava/lang/String; is abstract

	at org.testcontainers.shaded.com.github.dockerjava.core.command.CreateContainerCmdImpl.getPlatform(CreateContainerCmdImpl.java)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:664)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:690)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3681)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3081)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.encode(DefaultInvocationBuilder.java:292)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:121)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:33)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:595)
	at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:107)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:205)
	at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
	at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:310)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1029)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)

**Comment by bsideup** [comment]
@shikharkhanna there was a breaking change in docker-java-api `3.2.{9,10}` that is fixed in just released `3.2.11`:
https://github.com/docker-java/docker-java/pull/1661

You can either use docker-java-api `3.2.8` or `3.2.11` to make it work. Next release of Testcontainers will depend on `3.2.11`, so the faulty `3.2.{9,10}` release of docker-java would also work fine with it.

Closing this issue as it is docker-java's issue, not Testcontainers'.

**Comment by shikharkhanna** [comment]
Ok thanks

Shikhar Khanna
Api Tribe
TATA Consultancy Services
***@***.******@***.***>
***@***.***
M: +44 7378777878


From: Sergei Egorov ***@***.***>
Date: Tuesday, 29 June 2021 at 11:06
To: testcontainers/testcontainers-java ***@***.***>
Cc: Shikhar Khanna ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [testcontainers/testcontainers-java] getting abstract method error when working with Mongo test container (#4218)

@shikharkhanna<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshikharkhanna&data=04%7C01%7CShikhar.Khanna%40marks-and-spencer.com%7C0345d00bc41041df4a8708d93ae5821f%7Cbd5c671373994b31be7978f2d078e543%7C1%7C0%7C637605579670657598%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=c5GTQjIIRPzKCl4SpZ9et9ENiVNqp76CE9hW9GrFXh4%3D&reserved=0> there was a breaking change in docker-java-api 3.2.{9,10} that is fixed in just released 3.2.11:
docker-java/docker-java#1661<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdocker-java%2Fdocker-java%2Fpull%2F1661&data=04%7C01%7CShikhar.Khanna%40marks-and-spencer.com%7C0345d00bc41041df4a8708d93ae5821f%7Cbd5c671373994b31be7978f2d078e543%7C1%7C0%7C637605579670667552%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=p%2FpaWrQQsRvGhcvsPLl4JmTqwHMK90AgAT%2FYMgUm02Y%3D&reserved=0>

You can either use docker-java-api 3.2.8 or 3.2.11 to make it work. Next release of Testcontainers will depend on 3.2.11, so the faulty 3.2.{9,10} release of docker-java would also work fine with it.

Closing this issue as it is docker-java's issue, not Testcontainers'.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftestcontainers%2Ftestcontainers-java%2Fissues%2F4218%23issuecomment-870459473&data=04%7C01%7CShikhar.Khanna%40marks-and-spencer.com%7C0345d00bc41041df4a8708d93ae5821f%7Cbd5c671373994b31be7978f2d078e543%7C1%7C0%7C637605579670667552%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2FA9hmZ%2BAeXbeWG4K4%2BMMfwju5rJPDe%2F7eJ69Jwy07BY%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAING5U7L54NUHMY4GGSJNDLTVGLIXANCNFSM47OG2XBQ&data=04%7C01%7CShikhar.Khanna%40marks-and-spencer.com%7C0345d00bc41041df4a8708d93ae5821f%7Cbd5c671373994b31be7978f2d078e543%7C1%7C0%7C637605579670677514%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QGFJa6Yb01Bl6%2FNFUHKiEBSM51qp2YyRC7riBPoPWdk%3D&reserved=0>.


Marks and Spencer
________________________________
Unless otherwise stated:
Marks and Spencer plc
Registered Office:
Waterside House
35 North Wharf Road
London
W2 1NW

Registered No. 214436 in England and Wales.

www.marksandspencer.com

Please note that electronic mail may be monitored.

This e-mail is confidential. If you received it by mistake, please let us know and then delete it from your system; you should not copy, disclose, or distribute its contents to anyone nor act in reliance on it, as this is prohibited and may be unlawful.

Facebook<https://www.Facebook.com/marksandspencer/>     Twitter<https://www.Twitter.com/marksandspencer/>       Linkedin<https://www.linkedin.com/company/marks-and-spencer>    Pinterest<https://www.Pinterest.com/marksandspencer/>   Youtube<https://www.youtube.com/user/marksandspencertv?sub_confirmation=1>      Instagram<https://www.instagram.com/marksandspencer/>
