### ISSUE TITLE
Exception when recording session

### ISSUE THREAD

**Issue by Poeschl** [testcontainers/testcontainers-java#427]
It tried out your example on the docs and if I start the test with any other VncRecordingMode then ``SKIP`` I get a exception that the recording file could not be moved. (Exception at end of post.)

During the test I see the ``.tmp-volume-1501669893324`` file getting generated. (And its a file not a folder if that is relevant)

System is a Windows OS with Docker Toolbox.

```
Could not move recording file from .tmp-volume-1501669893324\screen.flv to \tmp\recording-20170802-123141.flv
java.lang.RuntimeException: Could not move recording file from .tmp-volume-1501669893324\screen.flv to \tmp\recording-20170802-123141.flv
	at org.testcontainers.containers.VncRecordingSidekickContainer.stopAndRetainRecording(VncRecordingSidekickContainer.java:83)
	at org.testcontainers.containers.BrowserWebDriverContainer.stopAndRetainRecording(BrowserWebDriverContainer.java:221)
	at org.testcontainers.containers.BrowserWebDriverContainer.failed(BrowserWebDriverContainer.java:190)

...

Caused by: java.nio.file.NoSuchFileException: .tmp-volume-1501669893324\screen.flv -> \tmp\recording-20170802-123141.flv
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:387)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1395)
	at org.testcontainers.containers.VncRecordingSidekickContainer.stopAndRetainRecording(VncRecordingSidekickContainer.java:81)
	... 42 more
```

**Comment by akozhin** [comment]
Get this error on Windows 10 with native docker

**Comment by kiview** [comment]
I think this is somewhat expected, since there is no `/tmp` directory on Windows. I wonder if #445 and #423  might help in this case.

**Comment by kiview** [comment]
This error does not seem to happen with Docker for Windows anymore (on current master).
@Poeschl can you try with current master and Docker Toolbox please?

**Comment by Poeschl** [comment]
I will test it on monday, thanks for still replying

**Comment by Poeschl** [comment]
It works now with updated docker and master ;)
