### ISSUE TITLE
hub.image.name.prefix does not play for jdbc:tc settings

### ISSUE THREAD

**Issue by vsevolodk** [testcontainers/testcontainers-java#4276]
I use version
```
<dependency>
    <groupId>org.testcontainers</groupId>
    <artifactId>postgresql</artifactId>
    <version>1.15.0-rc2</version>
    <scope>test</scope>
</dependency>
```
with  ```jdbc:tc:postgresql:12:///databasename?TC_DAEMON=true```
and ```testcontainers.properties``` with
```
hub.image.name.prefix=docker-proxy.myhost/
```

And I get error
```
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=postgres:12, imagePullPolicy=DefaultPullPolicy())
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1282) ~[testcontainers-1.15.0-rc2.jar:na]
	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:616) ~[testcontainers-1.15.0-rc2.jar:na]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:321) ~[testcontainers-1.15.0-rc2.jar:na]
	... 95 common frames omitted
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.15.0-rc2.jar:na]
```

**Comment by bsideup** [comment]
Hi @vsevolodk,

Have you tried the latest release (1.15.3)?

**Comment by vsevolodk** [comment]
Thank you :) It works on (1.15.3)
