### ISSUE TITLE
AWS SES - Using SMTP

### ISSUE THREAD

**Issue by whgibbo** [testcontainers/testcontainers-java#4300]
Hi,
Trying to use SES using SMTP Java Mail..  But getting a response -1 error..

Have configured the Test as follows:
```java
LocalStackContainer LOCALSTACK = new LocalStackContainer(localstackImage)
            .withServices(LocalStackContainer.Service.SES)
            .withEnv("SMTP_USER", SMTP_USER)
            .withEnv("SMTP_PASSWORD", SMTP_PASSWORD)
            .withEnv("SMTP_EMAIL", FROM);
```
Added the environment variables as mentioned on [LocalStack documentation](https://localstack.cloud/docs/getting-started/configuration/#smtp_host--smtp_user--smtp_pass--smtp_email) but have omitted as using local

Endpoints are coming back as expected..  Also tested with the **AmazonSimpleEmailService** to verify it is working.

```java
PROVIDER = new AWSStaticCredentialsProvider(new BasicAWSCredentials(LOCALSTACK.getAccessKey(), LOCALSTACK.getSecretKey())

AmazonSimpleEmailService client = AmazonSimpleEmailServiceClientBuilder.standard()
                .withCredentials(PROVIDER)
                .withEndpointConfiguration(LOCALSTACK.getEndpointConfiguration(LocalStackContainer.Service.SES))
                .build();

String sourceEmail = FROM;

VerifyEmailIdentityRequest verifyRequest = new VerifyEmailIdentityRequest().withEmailAddress(sourceEmail);
VerifyEmailIdentityResult verifyResponse = client.verifyEmailIdentity(verifyRequest);

SendEmailRequest request = new SendEmailRequest()
                .withSource(sourceEmail)
                .withSourceArn("").withReturnPathArn("")
                .withReturnPath("")
                .withDestination(
                        new Destination().withToAddresses("recipient1@example.com", "recipient2@example.com").withCcAddresses("recipient3@example.com")
                                .withBccAddresses(new ArrayList()))
                .withMessage(
                        new com.amazonaws.services.simpleemail.model.Message()
                                .withSubject(new Content().withData("Test email").withCharset("UTF-8"))
                                .withBody(
                                        new Body()
                                                .withText(new Content().withData("This is the message body in text format.").withCharset("UTF-8"))
                                                )
                );

try {
    SendEmailResult result = client.sendEmail(request);
    System.out.println(result.getMessageId());
}
catch (Exception ex) {
    System.out.println(ex.getMessage());
}
```
Which returns a message ID.. :)

Now when I send with with Java Mail:
```java
Session session = Session.getDefaultInstance(mailProperties.getProperties());

Properties props = System.getProperties();
props.put("mail.transport.protocol", "smtp");
// sesPort is obtained from the LOCALSTACK.getEndpointConfiguration(LocalStackContainer.Service.SES).getServiceEndpoint()
props.put("mail.smtp.port", sesPort); 
props.put("mail.smtp.starttls.enable", false);
props.put("mail.smtp.auth", false);

// Send the message.
try (Transport transport = session.getTransport()) {
    MimeMessage msg = new MimeMessage(session);
    msg.setFrom(new InternetAddress(FROM));
    msg.setRecipient(Message.RecipientType.TO, new InternetAddress("wayne_gibson@mcafee.com"));
    msg.setSubject("SUBJECT");
    msg.setContent("BODY", "text/html");

    System.out.println("Connecting");

    // Connect to Amazon SES using the SMTP username and password you specified above.
    transport.connect("127.0.0.1", sesPort, SMTP_USER, SMTP_PASSWORD);

    System.out.println("Sending Email");
    transport.sendMessage(msg, msg.getAllRecipients());
}
catch (Exception ex) {
    System.out.println("The email was not sent.");
    System.out.println("Error message: " + ex.getMessage());
}
```
It returns with the following error when **transport.connect** is invoked.
```
javax.mail.MessagingException: Could not connect to SMTP host: 127.0.0.1, port: 32956, response: -1
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2197)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:740)
	at javax.mail.Service.connect(Service.java:366)
```

Any thoughts, wasn't sure if this is a testcontainers issue or localstack

**Comment by eddumelendez** [comment]
Look at [this example](https://github.com/ddossot/aws-sdk-java/blob/252778cd085482f339f31a2dd22fea7bc46a1008/src/samples/AmazonSimpleEmailService/AWSJavaMailSample.java#L47). I'll close it but if you find any issue, feel free to re-open.
