### ISSUE TITLE
Can not connect to Ryuk at localhost:49160 since fedora 34

### ISSUE THREAD

**Issue by Stefan538871** [testcontainers/testcontainers-java#4305]
Since upgrading to Fedora 34, testcontainers cant connect to ryuk anymore

```
2021-07-27 09:04:28.620  INFO 24831 --- [nPool-worker-19] o.t.d.DockerClientProviderStrategy       : Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2021-07-27 09:04:29.107  INFO 24831 --- [nPool-worker-19] o.t.d.DockerClientProviderStrategy       : Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
2021-07-27 09:04:29.109  INFO 24831 --- [nPool-worker-19] org.testcontainers.DockerClientFactory   : Docker host IP address is localhost
2021-07-27 09:04:29.133  INFO 24831 --- [nPool-worker-19] org.testcontainers.DockerClientFactory   : Connected to docker: 
  Server Version: 20.10.7
  API Version: 1.41
  Operating System: Fedora 34 (Workstation Edition)
  Total Memory: 31746 MB
2021-07-27 09:04:29.136  INFO 24831 --- [nPool-worker-19] o.t.utility.ImageNameSubstitutor         : Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2021-07-27 09:04:34.656  WARN 24831 --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Can not connect to Ryuk at localhost:49161

java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.testcontainers.utility.ResourceReaper.lambda$null$1(ResourceReaper.java:189)
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
	at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:185)
	at java.base/java.lang.Thread.run(Thread.java:829)

2021-07-27 09:04:39.912  WARN 24831 --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Can not connect to Ryuk at localhost:49161

java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.testcontainers.utility.ResourceReaper.lambda$null$1(ResourceReaper.java:189)
	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
	at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:185)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
Normally i dont use a testcontainers.properties file but i also tried to 
start the tests with 
```
ryuk.container.privileged = true
ryuk.container.timeout = 120
```
Same result though.
Does anyone know if something specific is changed in f34, which i need to change for testcontainers?

My docker version
```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:57:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:55:04 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.8
  GitCommit:        7eba5930496d9bbe375fdf71603e610ad737d2b2
 runc:
  Version:          1.0.0
  GitCommit:        v1.0.0-0-g84113ee
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Thx in advance

**Comment by kiview** [comment]
Hey @Stefan538871,

Fedora is known to regularly change details with regards to Docker behavior on OS upgrades, even more so since they started pushing towards Podman.

I assume you use the most recent Testcontainers version (1.16.0)? 

While absolutely not recommended as a permanent fix, can you please temporarily [disable Ryuk](https://www.testcontainers.org/features/configuration/#disabling-ryuk), to check if other containers work as expected?

**Comment by Stefan538871** [comment]
You are right, I use 1.16.0,

I upgraded from f33 to f34

Is there a recommended way to install docker on fedora? like the this one https://docs.docker.com/engine/install/fedora/ or  should i install moby something like this https://gist.github.com/sandys/a79749d82ad43e5a782c2b7e3c5139d2

**Comment by kiview** [comment]
I assume the second link is based on the fact, that at release time, Docker packages are generally not available for a new Fedora release (they come a couple of months later). Therefore, I would suggest using the Docker package, but lack experience with the recent Fedora version.

Please note the manual steps in the Gist, this might very well be related to the issue.

**Comment by kucharzyk** [comment]
I can confirm the same issue with Fedora 34.
I've tried both moby-engine from Fedora repo and docker ce (stable) - neighter works.

I had to disable ryuk.

**Comment by kiview** [comment]
Can you please try running Ryuk by hand, so we can see what happens there?
E.g. like this:
```
# run ryuk
docker run -v /var/run/docker.sock:/var/run/docker.sock -p 8080:8080 testcontainers/ryuk:0.3.1

# try connecting
nc -zv localhost 8080
```

**Comment by Stefan538871** [comment]
> I assume the second link is based on the fact, that at release time, Docker packages are generally not available for a new Fedora release (they come a couple of months later). Therefore, I would suggest using the Docker package, but lack experience with the recent Fedora version.
> 
> Please note the manual steps in the Gist, this might very well be related to the issue.
So for the gist 
removing "systemd.unified_cgroup_hierarchy=0" leads to docker non functional (maybe this works with moby)

```
➜  ~ docker run -v /var/run/docker.sock:/var/run/docker.sock -p 8080:8080 testcontainers/ryuk:0.3.1
2021/07/27 14:12:47 Pinging Docker...
2021/07/27 14:12:47 Docker daemon is available!
2021/07/27 14:12:47 Starting on port 8080...
2021/07/27 14:12:47 Started!
```
leads to an timeout
```
➜  ~ nc -zv localhost 8080

Ncat: Version 7.80 ( https://nmap.org/ncat )
Ncat: Connection to ::1 failed: Connection refused.
Ncat: Trying next address...
Ncat: TIMEOUT.
```

**Comment by kiview** [comment]
This sounds very much like a `firewalld` issue (and therefore general Docker+Fedora issue, non-related to Testcontainers). Can you please check that you can connect to an `httpd` container? 

Also, note the corresponding `firewalld` config from the gist:
```
sudo firewall-cmd --zone=docker --change-interface=docker0
```

**Comment by pioorg** [comment]
Hi!
I've ran the check suggested by @kiview using a) another Linux distro and b) an older Fedora and in both cases ryuk worked just as expected.
@kucharzyk, could please take a look at https://www.reddit.com/r/Fedora/comments/onui0l/docker_not_working_after_latest_update/h5wahmd and check if it wasn't caused by the latest Fedora update? There are some reports that "dnf downgrade fixed the problem like a charm", so maybe it's worth trying:
`sudo dnf downgrade containerd.io`

**Comment by kucharzyk** [comment]
I've tried fresh Fedora 34 installation (fully updated).

How I've installed docker:
```sudo dnf remove docker*
sudo dnf install moby-engine 
sudo systemctl start docker
sudo systemctl enable docker
sudo groupadd docker
sudo usermod -aG docker $USER
```

And after restart:

```docker run -v /var/run/docker.sock:/var/run/docker.sock -p 8080:8080 testcontainers/ryuk:0.3.1
2021/07/27 22:03:16 Pinging Docker...
2021/07/27 22:03:16 Docker daemon is available!
2021/07/27 22:03:16 Starting on port 8080...
2021/07/27 22:03:16 Started!
```

```
nc -zv localhost 8080
Ncat: Version 7.80 ( https://nmap.org/ncat )
Ncat: Connected to ::1:8080.
Ncat: 0 bytes sent, 0 bytes received in 0.01 seconds.
```

Testcontainers works like a charm

```
2021-07-28 00:01:11,518 INFO  [🐳 .2]] (build-34) Creating container for image: postgres:13.2
2021-07-28 00:01:11,553 INFO  [🐳 .2]] (build-34) Starting container with ID: cadeacf19dcf35a520541dfc96bcc7c4381fea50f2cf86ac6922d2c2cc51296e
2021-07-28 00:01:11,843 INFO  [🐳 .2]] (build-34) Container postgres:13.2 is starting: cadeacf19dcf35a520541dfc96bcc7c4381fea50f2cf86ac6922d2c2cc51296e
2021-07-28 00:01:13,616 INFO  [🐳 .2]] (build-34) Container postgres:13.2 started in PT26.885426S
```

It could be issue related to updating from Fedora 33 (or messed configuration)

**Comment by kiview** [comment]
Thanks a lot for trying this out @kucharzyk  and confirming that Testcontainers works if the Docker installation itself is clean on Fedora 34. Indeed, from reading different Reddit posts I got the feeling, that certain Docker-related settings in the system get messed up on system update (in this case I still suspect `firewalld`), but they get _repaired_ on downgrade or re-installation.

Another potential culprit with Fedora is `cgroups`. But it seems just having a clean installation with the up-to-date packages from the official Fedora repo provide working without fiddling with configs, so that is very good to know!
