### ISSUE TITLE
Unable to find docker environment after updating from 1.15.3 to 1.16.0

### ISSUE THREAD

**Issue by swerky** [testcontainers/testcontainers-java#4317]
Hi,
I tried to update testcontainer from version 1.15.3 to 1.16.0 and my tests crashed with the following error:

```console
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
```

This is my test:
```java
@Testcontainers
public class testContainer {
  @Test
    public void containerWithInitScriptShouldWork() {
      Jdbi jdbi = Jdbi.create("jdbc:tc:postgis:13-3.1:///testWIthData?TC_INITSCRIPT=sql/init_sql.sql")
          .installPlugin(new PostgresPlugin())
          .installPlugin(new Jackson2Plugin());
  
      List<Map<String, Object>> values = jdbi.withHandle(handle ->
          handle.createQuery("select ID, LAST_NAME, FIRST_NAME from users")
              .mapToMap().list());
      assertEquals(1, values.size());
      Map<String, Object> data = values.get(0);
      assertEquals(1, data.get("id"));
      assertEquals("Doe", data.get("last_name"));
      assertEquals("John", data.get("first_name"));
    }
}
 ```
 
 I tried on macOS and Linux but neither worked (same for Github actions).
 
 Application:
 - Java 11
 - Quarkus
 - maven

**Comment by bsideup** [comment]
Hi @swerky,

Could you please share the logs?

**Comment by swerky** [comment]
May I ask where should I found them. I spend a few minutes trying without any success.

**Comment by swerky** [comment]
Here is the stacktrace:
```console
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration

	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:215)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:207)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:135)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:177)
	at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
	at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:314)
	at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:118)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.jdbi.v3.core.Jdbi.lambda$create$0(Jdbi.java:114)
	at org.jdbi.v3.core.Jdbi.open(Jdbi.java:303)
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:340)
	at com.baremaps.ipmap.testContainer.containerWithInitScriptShouldWork(testContainer.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```

**Comment by kiview** [comment]
This is only the stacktrace, not the logs. Please configure your logging as [per documentation](https://www.testcontainers.org/supported_docker_environment/logging_config/).

**Comment by swerky** [comment]
```
 org.testcontainers.dockerclient.DockerClientProviderStrategy - Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
15:44:57.479 [main] INFO  org.testcontainers.dockerclient.DockerMachineClientProviderStrategy - docker-machine executable was not found on PATH ([/home/user/.npm-global/bin, /usr/local/lib/nodejs/node--linux-x64/bin, /home/user/.cargo/bin, /home/user/.local/bin, /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /usr/local/games, /snap/bin])
15:44:57.517 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
15:44:57.518 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy -     UnixSocketClientProviderStrategy: failed with exception RuntimeException (java.lang.NoClassDefFoundError: com/github/dockerjava/api/model/DockerObject). Root cause ClassNotFoundException (com.github.dockerjava.api.model.DockerObject)
15:44:57.518 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy -     UnixSocketClientProviderStrategy: failed with exception RuntimeException (java.lang.NoClassDefFoundError: com/github/dockerjava/api/model/DockerObject). Root cause NoClassDefFoundError (com/github/dockerjava/api/model/DockerObject)
15:44:57.519 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - As no valid configuration was found, execution cannot continue
```

**Comment by kiview** [comment]
Can you please also share your `pom.xml` ?

**Comment by bsideup** [comment]
> java.lang.NoClassDefFoundError: com/github/dockerjava/api/model/DockerObject). Root cause ClassNotFoundException (com.github.dockerjava.api.model.DockerObject)

here is the problem :) Something in your project forces an old version of `docker-java` :)

**Comment by swerky** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>myproject</artifactId>
  <version>1.0-SNAPSHOT</version>
  <properties>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <version.baremaps-osm>0.5.10</version.baremaps-osm>
    <version.compiler-plugin>3.8.1</version.compiler-plugin>
    <version.failsafe-plugin>3.0.0-M5</version.failsafe-plugin>
    <version.jdbi3>3.21.0</version.jdbi3>
    <version.jts>1.18.1</version.jts>
    <version.junit>5.7.2</version.junit>
    <version.lucene>8.9.0</version.lucene>
    <version.lucene-spatial>8.4.1</version.lucene-spatial>
    <version.maven-assembly-plugin>3.3.0</version.maven-assembly-plugin>
    <version.quarkus>2.0.3.Final</version.quarkus>
    <version.quarkus-platform>2.0.3.Final</version.quarkus-platform>
    <version.quarkus-plugin>2.1.0.Final</version.quarkus-plugin>
    <version.surefire-plugin>3.0.0-M5</version.surefire-plugin>
    <version.testcontainers>1.16.0</version.testcontainers>
    <version.jacoco>0.8.7</version.jacoco>
    <version.google-jib>3.0.0</version.google-jib>
    <sonar.host.url>https://sonarcloud.io</sonar.host.url>
    <sonar.organization>baremaps</sonar.organization>
    <sonar.projectKey>baremaps_ipmap</sonar.projectKey>
    <sonar.moduleKey>${project.groupId}:${project.artifactId}</sonar.moduleKey>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.jdbi</groupId>
        <artifactId>jdbi3-bom</artifactId>
        <version>${version.jdbi3}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-bom</artifactId>
        <version>${version.quarkus-platform}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-picocli</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-qute</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-agroal</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-postgresql</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-container-image-jib</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jboss.logmanager</groupId>
      <artifactId>log4j2-jboss-logmanager</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jdbi</groupId>
      <artifactId>jdbi3-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jdbi</groupId>
      <artifactId>jdbi3-jackson2</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jdbi</groupId>
      <artifactId>jdbi3-sqlobject</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jdbi</groupId>
      <artifactId>jdbi3-postgres</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.lucene</groupId>
      <artifactId>lucene-core</artifactId>
      <version>${version.lucene}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.lucene</groupId>
      <artifactId>lucene-queryparser</artifactId>
      <version>${version.lucene}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.lucene</groupId>
      <artifactId>lucene-spatial</artifactId>
      <version>${version.lucene-spatial}</version>
    </dependency>
    <dependency>
      <groupId>org.locationtech.jts</groupId>
      <artifactId>jts-core</artifactId>
      <version>${version.jts}</version>
    </dependency>
    <dependency>
      <groupId>com.baremaps</groupId>
      <artifactId>baremaps-osm</artifactId>
      <version>${version.baremaps-osm}</version>
    </dependency>
    <dependency>
      <groupId>com.baremaps</groupId>
      <artifactId>baremaps-osm-lmdb</artifactId>
      <version>${version.baremaps-osm}</version>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>${version.junit}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.vintage</groupId>
      <artifactId>junit-vintage-engine</artifactId>
      <version>${version.junit}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>${version.junit}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>testcontainers</artifactId>
      <version>${version.testcontainers}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>${version.testcontainers}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.testcontainers</groupId>
      <artifactId>postgresql</artifactId>
      <version>${version.testcontainers}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${version.compiler-plugin}</version>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${version.surefire-plugin}</version>
        <configuration>
          <excludedGroups>accuracy</excludedGroups>
          <systemPropertyVariables>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>${maven.home}</maven.home>
          </systemPropertyVariables>
        </configuration>
      </plugin>
      <plugin>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${version.quarkus-plugin}</version>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>${version.failsafe-plugin}</version>
      </plugin>
      <plugin>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>${version.maven-assembly-plugin}</version>
      </plugin>
      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>jib-maven-plugin</artifactId>
        <version>${version.google-jib}</version>
        <configuration>
          <container>
            <mainClass>com.baremaps.ipmap.IPMap</mainClass>
          </container>
          <from>
            <image>adoptopenjdk/openjdk11:alpine</image>
          </from>
          <to>
            <image>ipmap-app</image>
            <tags>v${project.version}</tags>
          </to>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>${version.jacoco}</version>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>report</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>accuracy</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>${version.surefire-plugin}</version>
            <configuration>
              <excludedGroups>none</excludedGroups>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
```
If I do a `mvn dependency:tree` the only occurence I found for docker-java is in testcontainer:

```
[INFO] +- org.testcontainers:testcontainers:jar:1.16.0:test
[INFO] |  +- org.rnorth.duct-tape:duct-tape:jar:1.0.8:test
[INFO] |  +- com.github.docker-java:docker-java-api:jar:3.2.8:test
[INFO] |  \- com.github.docker-java:docker-java-transport-zerodep:jar:3.2.8:test
[INFO] |     +- com.github.docker-java:docker-java-transport:jar:3.2.8:test
```

**Comment by bsideup** [comment]
I have no idea why, but Quarkus' BOM forces `docker-java-api` version to `3.2.8`:
https://repo1.maven.org/maven2/io/quarkus/quarkus-bom/2.0.3.Final/quarkus-bom-2.0.3.Final.pom

This will break your project. Consider reporting to the Quarkus team and temporary forcing `docker-java-api` and `docker-java-transport-zerodep` to the version that Testcontainers defines (`3.2.11` as per https://mvnrepository.com/artifact/org.testcontainers/testcontainers/1.16.0).

/cc @Ladicek  who added the enforcement in https://github.com/quarkusio/quarkus/commit/11f2e68f8c0ac6627b1b0c87e5b675a6dee857f2

**Comment by Ladicek** [comment]
I was _hoping_ that people updating Testcontainers in Quarkus would notice the comment and update docker-java too. Oh well :-/

**Comment by swerky** [comment]
Thank you very much for your help!

Have a good weekend.

**Comment by bsideup** [comment]
@Ladicek thanks for jumping in! It seems that the problem arises when someone updates TC in their project while staying on an old Quarkus that haven't updated docker-java yet.

We would highly recommend removing the version management for docker-java, as it looks like (judging by the reports that we're getting after releasing 1.16.0) it became a major issue for many of your users (indirectly) 👍

**Comment by Ladicek** [comment]
Actually no. You specify a dependency on Testcontainers 1.16.0, so it's your responsibility to manage the docker-java dependency. Quarkus still manages Testcontainers version to 1.15.3 and hence the corresponding docker-java 3.2.8.

@bsideup I have to disagree. If Quarkus has to manage Testcontainers version (which I don't know, but it's how it is), then it also has to manage docker-java version -- otherwise people have issues as well (different issues :-) ).

**Comment by bsideup** [comment]
@Ladicek Testcontainers depends on `3.2.11` as per https://mvnrepository.com/artifact/org.testcontainers/testcontainers/1.16.0 🤷‍♂️

**Comment by Ladicek** [comment]
@bsideup Testcontainers 1.16.0 depends on docker-java 3.2.11. Testcontainers 1.15.3 depends on docker-java 3.2.8.

In the Quarkus BOM, they are in sync. In this issue, they are out of sync, because @swerky overrode the Testcontainers version (to 1.16.0), but didn't override the docker-java version (to 3.2.11).

This is a general problem of aligning transitive dependencies. I spent countless hours on aligning dependencies (on some other product), so I totally feel your pain, but I'm not aware of a better solution -- not with Maven at least. Either you stick with what Quarkus gives you, or you're on your own. (Granted, the Quarkus BOM might be seen by some as way too large, but that's because Quarkus is not a library, it's a platform. That's off-topic here, though.)

**Comment by Ladicek** [comment]
Ah one general recommendation for Maven, though. If you add the Maven Enforcer plugin and enable dependency convergence check, that helps a lot. Something like this:

```xml
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-enforcer-plugin</artifactId>
          <version>${version.maven-enforcer-plugin}</version>
          <executions>
            <execution>
              <id>enforce-dependencies</id>
              <goals>
                <goal>enforce</goal>
              </goals>
              <configuration>
                <rules>
                  <dependencyConvergence />
                </rules>
              </configuration>
            </execution>
          </executions>
        </plugin>
```

**Comment by famod** [comment]
FWIW, we are trying to get 1.16.0 into Quarkus (with aligned `docker-java`) but we are facing some puzzling failures in tests using mariadb, mysql and mssql and SHARED network: https://github.com/quarkusio/quarkus/pull/18873

**Comment by famod** [comment]
@bsideup You might want to consider unpinning this, given that Quarkus has been managing a matching `docker-java` version in its BOM for a while now.
