### ISSUE TITLE
Solr container doesn't work with cloud (cluster) Solr client

### ISSUE THREAD

**Issue by acsbendi** [testcontainers/testcontainers-java#4389]
It is not possible to use the Solr container with the cloud Solr client (`CloudSolrClient`, this client can be used for accessing Solr clusters), because the following exception is thrown when trying to send any request:
```
Tried fetching cluster state using the node names we knew of, i.e. [localhost:8983_solr]. However, succeeded in obtaining the cluster state from none of them.If you think your Solr cluster is up and is accessible, you could try re-creating a new CloudSolrClient using working solrUrl(s) or zkHost(s).
java.lang.RuntimeException: Tried fetching cluster state using the node names we knew of, i.e. [localhost:8983_solr]. However, succeeded in obtaining the cluster state from none of them.If you think your Solr cluster is up and is accessible, you could try re-creating a new CloudSolrClient using working solrUrl(s) or zkHost(s).
	at org.apache.solr.client.solrj.impl.BaseHttpClusterStateProvider.getState(BaseHttpClusterStateProvider.java:105)
	at org.apache.solr.client.solrj.impl.BaseCloudSolrClient.resolveAliases(BaseCloudSolrClient.java:1182)
	at org.apache.solr.client.solrj.impl.BaseCloudSolrClient.requestWithRetryOnStaleState(BaseCloudSolrClient.java:894)
	at org.apache.solr.client.solrj.impl.BaseCloudSolrClient.request(BaseCloudSolrClient.java:866)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:214)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:106)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:71)
	at com.example.SolrQueryTest.setUp(SolrQueryTest.java:37)
...
```

You can see this exception by changing [this line](https://github.com/testcontainers/testcontainers-java/blob/99b91b89b6ee3f8f0e9545e86d9f0744b301db30/examples/solr-container/src/test/java/com/example/SolrQueryTest.java#L33) to 
        `solrClient = new CloudSolrClient.Builder(Collections.singletonList("http://" + solrContainer.getContainerIpAddress() + ":" + solrContainer.getSolrPort() + "/solr")).build();`

The underlying issue is that the cluster will report 8983 as the port used by Solr, but the container uses a different host port, so `localhost:8983` will not be available to the client.

**Comment by kiview** [comment]
We traditionally had similar challenges in `KafkaContainer` due to ZooKepper.  In the latest iteration, those were solved by updating the advertised connection _after_ the container has started and the mapped port is known:
https://github.com/testcontainers/testcontainers-java/blob/4df9b900e79e4a3033ef0975abacf9064a0e7353/modules/kafka/src/main/java/org/testcontainers/containers/KafkaContainer.java#L109-L119

I lack the knowledge of Solr to understand if such an approach would be feasible here as well.

The other alternative is starting Solr with the connection URLs as part of the `configure()` callback.
