### ISSUE TITLE
Exec not supported by LXC on CircleCi

### ISSUE THREAD

**Issue by monowai** [testcontainers/testcontainers-java#442]
I'm not sure if this is a TestContainers issue or CircleCI. I'm running docker stage tests using CircleCI and the following error occurs during startup using `v1.4.2`.  It works fine with `v1.1.7`

```
Unsupported: Exec is not supported by the lxc driver
com.github.dockerjava.api.exception.InternalServerErrorException: Unsupported: Exec is not supported by the lxc driver

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:109)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at org.testcontainers.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
...
...
	at java.lang.Thread.run(Thread.java:745)

        ✔ Docker environment has more than 2GB free
        ✔ File should be mountable
        ✔ Exposed port is accessible
2017-08-15 14:19:41.350 ERROR ${sys:PID} --- [java-netty-1-11] .a.ResultCallbackTemplate : Error during callback
```

I found this reference, but I don't think it's a solution when using TC. https://circleci.com/docs/1.0/docker/#docker-exec

**Comment by rnorth** [comment]
I think we'll soon need to revisit this - we explicitly throw an exception because CircleCI's docker implementation didn't support exec (being lxc-based). The workaround you linked to is probably a bit too fiddly.

It seems that Circle CI 2.0 (in beta now) will support exec, so it may be that we can start to relax this check. Once 2.0 is GA I'd imagine we might move swiftly towards only supporting that.

**Comment by monowai** [comment]
This is no longer an issue in CircleCI 2.0 with 1.4.2 👍
