### ISSUE TITLE
NullPointerException in execInContainer for long running commands

### ISSUE THREAD

**Issue by bgranvea** [testcontainers/testcontainers-java#4453]
Test case:
```
    @Test
    public void testExecInContainer() throws InterruptedException, IOException {
        try (GenericContainer<?> c = new GenericContainer<>(DockerImageName.parse("redis:3.0.2"))) {
            c.start();
            Container.ExecResult r = c.execInContainer("/bin/bash", "-c", "sleep 600");
        }
    }
```

After 3 minutes, I've got this exception:

```
java.lang.NullPointerException
	at org.testcontainers.containers.ExecInContainerPattern.execInContainer(ExecInContainerPattern.java:85)
	at org.testcontainers.containers.ContainerState.execInContainer(ContainerState.java:235)
	at org.testcontainers.containers.ContainerState.execInContainer(ContainerState.java:226)
```

Note: I'm using DOCKER_HOST to execute on a Linux machine.

My real problem is: how do I execute a command which runs a long time? there seems to be an underlying socket timeout in docker-java, is it possible to increase this timeout?

**Comment by silh** [comment]
Looks like the relevant part is in `org.testcontainers.dockerclient.DockerClientProviderStrategy#getClientForConfig`.
By default `com.github.dockerjava.httpclient5.ZerodepDockerHttpClient` will be created and it uses `org.apache.hc.client5.http.config.RequestConfig` which has defualt timeout:
```
    private static final Timeout DEFAULT_CONNECTION_REQUEST_TIMEOUT = Timeout.ofMinutes(3);
    private static final Timeout DEFAULT_CONNECT_TIMEOUT = Timeout.ofMinutes(3);
    private static final TimeValue DEFAULT_CONN_KEEP_ALIVE = TimeValue.ofMinutes(3);
```

And as neither `connectionTimeout` nor `responseTimeout` are called there doesn't seem to be a way to set custom timeout.

**Comment by bgranvea** [comment]
there are already variables for custom configuration: https://www.testcontainers.org/features/configuration/#customizing-docker-host-detection

so it seems possible to add connect and request timeout settings that would be transmitted to `TransportConfig `and then `ZerodepDockerHttpClient`.

**Comment by silh** [comment]
You can also probably define your own implementation `org.testcontainers.dockerclient.DockerClientProviderStrategy` and specify env variable `TESTCONTAINERS_DOCKER_CLIENT_STRATEGY=com.silh.testcontainers.example.CustomStrategy` or specify `docker.client.strategy` in your `~/.testcontainers.properties`.

Gist example - https://gist.github.com/silh/3b119a318eec9018dc4a13c2405eabd4

**Comment by bsideup** [comment]
FYI I think the underlying problem is in docker-java, see https://github.com/docker-java/docker-java/pull/1702

we will release a new version of it soon, and next Testcontainers release will have it updated.

**Comment by silh** [comment]
Just in case, on macOS the problem was not reproduced (no DOCKER_HOST).

**Comment by silh** [comment]
But shouldn't the NullPointerException be fixed?
I guess it happens when timeout is reached and we try to get return code and it is Integer(null) which is cast to plain int.

**Comment by bsideup** [comment]
@silh this should be fixed, yes 👍

**Comment by bgranvea** [comment]
I didn't know the `TESTCONTAINERS_DOCKER_CLIENT_STRATEGY `/ `docker.client.strategy` possibility, nice! In the meantime I found another workaround by wrapping my command with a background script that regularly sends something on stdout but that's ugly.

Anyway, thanks for your help, I'm looking forward for the new version.

**Comment by silh** [comment]
@bsideup it seems that we don't get timeout exception because it is intentionally ignored here - https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/output/FrameConsumerResultCallback.java#L82

Although with the recent socket fix it should work fine.

As there is no way in current docker API to get output of detached command execution we can only wait for an exitcode to be present, but then we will lose output.

What do you think?
