### ISSUE TITLE
Selenium Timeout with "no such element"

### ISSUE THREAD

**Issue by baztian** [testcontainers/testcontainers-java#447]
I can't get any selenium test to work. I've tried https://github.com/testcontainers/testcontainers-java-examples/tree/master/selenium-container without success. The spring boot example works though.

    [INFO] Scanning for projects...
    [INFO]                                                                         
    [INFO] ------------------------------------------------------------------------
    [INFO] Building selenium-container NOVERSION
    [INFO] ------------------------------------------------------------------------
    [INFO] 
    [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ selenium-container ---
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] skip non existing resourceDirectory /home/me/Sources/testcontainers-java-examples/selenium-container/src/main/resources
    [INFO] 
    [INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ selenium-container ---
    [INFO] No sources to compile
    [INFO] 
    [INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ selenium-container ---
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] Copying 1 resource
    [INFO] 
    [INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ selenium-container ---
    [INFO] Nothing to compile - all classes are up to date
    [INFO] 
    [INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ selenium-container ---
    [INFO] Surefire report directory: /home/me/Sources/testcontainers-java-examples/selenium-container/target/surefire-reports
    
    -------------------------------------------------------
     T E S T S
    -------------------------------------------------------
    Running SeleniumContainerTest
    14:28:37.583 [main] INFO  org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy - Found docker client settings from environment
    14:28:37.594 [main] INFO  org.testcontainers.dockerclient.DockerClientProviderStrategy - Found Docker environment with Environment variables, system properties and defaults. Resolved: 
        dockerHost=unix:///var/run/docker.sock
        apiVersion='{UNKNOWN_VERSION}'
        registryUrl='https://index.docker.io/v1/'
        registryUsername='me'
        registryPassword='null'
        registryEmail='null'
        dockerConfig='DefaultDockerClientConfig[dockerHost=unix:///var/run/docker.sock,registryUsername=me,registryPassword=<null>,registryEmail=<null>,registryUrl=https://index.docker.io/v1/,dockerConfig=/home/me/.docker,sslConfig=<null>,apiVersion={UNKNOWN_VERSION}]'
    
    14:28:37.598 [main] INFO  org.testcontainers.DockerClientFactory - Docker host IP address is localhost
    14:28:37.708 [main] INFO  org.testcontainers.DockerClientFactory - Connected to docker: 
      Server Version: 17.06.1-ce
      API Version: 1.30
      Operating System: Linux Mint 18.2
      Total Memory: 7981 MB
            [37;1mℹ︎ Checking the system... [m
            [32m✔ Docker version is newer than 1.6.0 [m
            [32m✔ Docker environment has more than 2GB free [m
            [32m✔ File should be mountable [m
            [32m✔ Exposed port is accessible [m
    14:28:38.898 [main] INFO  org.testcontainers.containers.SeleniumUtils - Selenium API version 2.45.0 detected on classpath
    14:28:38.906 [main] INFO  🐳 [selenium/standalone-chrome-debug:2.45.0] - Creating container for image: selenium/standalone-chrome-debug:2.45.0
    14:28:39.006 [main] INFO  🐳 [selenium/standalone-chrome-debug:2.45.0] - Starting container with ID: f666a26c2ec0a549619d507a7bca83213948c603051ca71b385ea9a15fcaba47
    14:28:39.464 [main] INFO  🐳 [selenium/standalone-chrome-debug:2.45.0] - Container selenium/standalone-chrome-debug:2.45.0 is starting: f666a26c2ec0a549619d507a7bca83213948c603051ca71b385ea9a15fcaba47
    14:28:39.784 [main] INFO  🐳 [selenium/standalone-chrome-debug:2.45.0] - Container selenium/standalone-chrome-debug:2.45.0 started
    14:28:39.787 [main] INFO  🐳 [richnorth/vnc-recorder:latest] - Creating container for image: richnorth/vnc-recorder:latest
    14:28:39.900 [main] INFO  🐳 [richnorth/vnc-recorder:latest] - Starting container with ID: dc338b9dffd0aa7cec5fc7d454eddc2c112c8b166e00aa248e50609b9bb0737c
    14:28:40.338 [main] INFO  🐳 [richnorth/vnc-recorder:latest] - Container richnorth/vnc-recorder:latest is starting: dc338b9dffd0aa7cec5fc7d454eddc2c112c8b166e00aa248e50609b9bb0737c
    14:28:40.635 [main] ERROR 🐳 [richnorth/vnc-recorder:latest] - Could not start container
    java.lang.IllegalStateException: Container did not start correctly.
    	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:231) [testcontainers--1.4.2-g1a04781-2.jar:na]
    	at org.testcontainers.containers.GenericContainer.lambda$start$0(GenericContainer.java:184) [testcontainers--1.4.2-g1a04781-2.jar:na]
    	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76) ~[duct-tape-1.0.6.jar:na]
    	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:182) [testcontainers--1.4.2-g1a04781-2.jar:na]
    	at org.testcontainers.containers.BrowserWebDriverContainer.containerIsStarted(BrowserWebDriverContainer.java:162) ~[selenium--1.4.2-g1a04781-2.jar:na]
    	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:238) [testcontainers--1.4.2-g1a04781-2.jar:na]
    	at org.testcontainers.containers.GenericContainer.lambda$start$0(GenericContainer.java:184) [testcontainers--1.4.2-g1a04781-2.jar:na]
    	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76) ~[duct-tape-1.0.6.jar:na]
    	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:182) [testcontainers--1.4.2-g1a04781-2.jar:na]
    	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:544) [testcontainers--1.4.2-g1a04781-2.jar:na]
    	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29) ~[testcontainers--1.4.2-g1a04781-2.jar:na]
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20) ~[junit-4.12.jar:4.12]
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) ~[junit-4.12.jar:4.12]
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) ~[junit-4.12.jar:4.12]
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) ~[junit-4.12.jar:4.12]
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) ~[junit-4.12.jar:4.12]
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) ~[junit-4.12.jar:4.12]
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) ~[junit-4.12.jar:4.12]
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) ~[junit-4.12.jar:4.12]
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) ~[junit-4.12.jar:4.12]
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) ~[junit-4.12.jar:4.12]
    	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252) ~[na:na]
    	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) ~[na:na]
    	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) ~[na:na]
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
    	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
    	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) ~[surefire-api-2.12.4.jar:2.12.4]
    	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) ~[surefire-booter-2.12.4.jar:2.12.4]
    	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) ~[surefire-booter-2.12.4.jar:2.12.4]
    	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) ~[surefire-booter-2.12.4.jar:2.12.4]
    	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) ~[surefire-booter-2.12.4.jar:2.12.4]
    14:28:40.642 [main] ERROR 🐳 [richnorth/vnc-recorder:latest] - Container log output (if any) will follow:
    14:28:40.677 [dockerjava-netty-1-2] INFO  🐳 [richnorth/vnc-recorder:latest] - STDERR: start recording
    14:28:40.681 [dockerjava-netty-1-2] INFO  🐳 [richnorth/vnc-recorder:latest] - STDERR: Socket error: [Errno 111] Connection refused
    14:28:40.687 [dockerjava-netty-1-2] INFO  🐳 [richnorth/vnc-recorder:latest] - STDERR: stop recording
    14:28:40.701 [main] INFO  🐳 [richnorth/vnc-recorder:latest] - Creating container for image: richnorth/vnc-recorder:latest
    14:28:40.790 [main] INFO  🐳 [richnorth/vnc-recorder:latest] - Starting container with ID: b6adf4c34d31c02400e6ff77aee2740a8c17fb018146de1fc3b7cfb44c1ac00b
    14:28:41.295 [main] INFO  🐳 [richnorth/vnc-recorder:latest] - Container richnorth/vnc-recorder:latest is starting: b6adf4c34d31c02400e6ff77aee2740a8c17fb018146de1fc3b7cfb44c1ac00b
    14:28:41.637 [main] INFO  🐳 [richnorth/vnc-recorder:latest] - Container richnorth/vnc-recorder:latest started
    14:30:03.282 [main] INFO  org.testcontainers.containers.BrowserWebDriverContainer - Screen recordings for test simplePlainSeleniumTest(SeleniumContainerTest) will be stored at: target/recording-20170821-143003.flv
    Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 87.741 sec <<< FAILURE!
    simplePlainSeleniumTest(SeleniumContainerTest)  Time elapsed: 85.825 sec  <<< ERROR!
    org.openqa.selenium.NoSuchElementException: no such element
      (Session info: chrome=43.0.2357.65)
      (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 4.10.0-32-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 32 milliseconds
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
    System info: host: 'f666a26c2ec0', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.10.0-32-generic', java.version: '1.7.0_79'
    *** Element info: {Using=name, value=search}
    Session ID: 28539c34bb7535f174dbf9a4a4f72987
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.s97JaI}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=43.0.2357.65, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
    Command duration or timeout: 117 milliseconds
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
    System info: host: 'melinux', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.10.0-32-generic', java.version: '1.8.0_144'
    Driver info: org.openqa.selenium.remote.RemoteWebDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/tmp/.com.google.Chrome.s97JaI}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=43.0.2357.65, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, webdriver.remote.sessionid=55940a6b-030e-4141-ae17-ea53f8a326a8, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
    Session ID: 55940a6b-030e-4141-ae17-ea53f8a326a8
    *** Element info: {Using=name, value=search}
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
    	at org.openqa.selenium.remote.RemoteWebDriver.findElementByName(RemoteWebDriver.java:425)
    	at SeleniumContainerTest.simplePlainSeleniumTest(SeleniumContainerTest.java:28)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
    Caused by: org.openqa.selenium.NoSuchElementException: no such element
      (Session info: chrome=43.0.2357.65)
      (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 4.10.0-32-generic x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 32 milliseconds
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
    System info: host: 'f666a26c2ec0', ip: '172.17.0.2', os.name: 'Linux', os.arch: 'amd64', os.version: '4.10.0-32-generic', java.version: '1.7.0_79'
    *** Element info: {Using=name, value=search}
    Session ID: 28539c34bb7535f174dbf9a4a4f72987
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.s97JaI}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=43.0.2357.65, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
    System info: host: 'melinux', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.10.0-32-generic', java.version: '1.8.0_144'
    Driver info: driver.version: EventFiringWebDriver
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
    	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
    	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
    	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
    	at org.openqa.selenium.remote.RemoteWebDriver.findElementByName(RemoteWebDriver.java:425)
    	at org.openqa.selenium.By$ByName.findElement(By.java:299)
    	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:606)
    	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:101)
    	at com.sun.proxy.$Proxy1.findElement(Unknown Source)
    	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:184)
    	at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:47)
    	at org.openqa.selenium.remote.server.handler.FindElement.call(FindElement.java:1)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    	at org.openqa.selenium.remote.server.DefaultSession$1.run(DefaultSession.java:168)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    	at java.lang.Thread.run(Thread.java:745)
    
    
    Results :
    
    Tests in error: 
      simplePlainSeleniumTest(SeleniumContainerTest): no such element(..)
    
    Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
    
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 01:29 min
    [INFO] Finished at: 2017-08-21T14:30:05+02:00
    [INFO] Final Memory: 12M/217M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project selenium-container: There are test failures.
    [ERROR] 
    [ERROR] Please refer to /home/me/Sources/testcontainers-java-examples/selenium-container/target/surefire-reports for the individual test results.
    [ERROR] -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by kiview** [comment]
Example works for me.
Is it possible, because of your Docker daemons DNS configuration, that the selenium container has no internet connectivity? 

Please run something like
```
docker run --rm appropriate/curl -fsSL https://www.google.com/
```
to check internet connectivity.

**Comment by rnorth** [comment]
@baztian did @kiview's suggestion help at all? It'd be good to know so we know whether to keep this issue open.
Thanks

**Comment by kiview** [comment]
@baztian any news on this? I'll close this issue for now. I'll be happy to reopen if you can provide further feedback. Of course you can also always ask for help at [Stackoverflow](https://stackoverflow.com/questions/tagged/testcontainers) or in our Slack channel.
