### ISSUE TITLE
Flaky test: kafka-cluster example

### ISSUE THREAD

**Issue by rnorth** [testcontainers/testcontainers-java#4479]
Recently we've seen a handful of [failures of `KafkaContainerClusterTest`](https://github.com/testcontainers/testcontainers-java/runs/3688588553#step:6:819) in the examples project.

```
     [testcontainers-lifecycle-2] INFO 🐳 [confluentinc/cp-kafka:5.2.1] - Container confluentinc/cp-kafka:5.2.1 is starting: 890f39bf938aa9b76f382e3b03335d9f62bbea36de3ae50485f3690020070930
    [testcontainers-lifecycle-4] INFO 🐳 [confluentinc/cp-kafka:5.2.1] - Container confluentinc/cp-kafka:5.2.1 is starting: f2cbb443b2429b82f388f32c42cab9a1dcd9b66f55ac8c73cd0aae4106450fe7
    [testcontainers-lifecycle-1] INFO 🐳 [confluentinc/cp-kafka:5.2.1] - Container confluentinc/cp-kafka:5.2.1 is starting: 5450127240c95d444343455c1844793bdd2745a6fc87edaaed3a101fb69721bc
    [testcontainers-lifecycle-4] INFO 🐳 [confluentinc/cp-kafka:5.2.1] - Container confluentinc/cp-kafka:5.2.1 started in PT22.747S
    [testcontainers-lifecycle-2] INFO 🐳 [confluentinc/cp-kafka:5.2.1] - Container confluentinc/cp-kafka:5.2.1 started in PT24.35S
    [testcontainers-lifecycle-1] INFO 🐳 [confluentinc/cp-kafka:5.2.1] - Container confluentinc/cp-kafka:5.2.1 started in PT24.5S
    [testcontainers-lifecycle-2] ERROR 🐳 [confluentinc/cp-kafka:5.2.1] - Could not start container
    java.lang.IllegalStateException: 
    	at org.testcontainers.containers.KafkaContainer.containerIsStarted(KafkaContainer.java:121)
    	at org.testcontainers.containers.GenericContainer.containerIsStarted(GenericContainer.java:687)
    	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:503)
    	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:330)
    	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
    	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:328)
    	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:316)
    	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719)
    	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
    	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
    [testcontainers-lifecycle-4] ERROR 🐳 [confluentinc/cp-kafka:5.2.1] - Could not start container
    java.lang.IllegalStateException: 
    	at org.testcontainers.containers.KafkaContainer.containerIsStarted(KafkaContainer.java:121)
    	at org.testcontainers.containers.GenericContainer.containerIsStarted(GenericContainer.java:687)
    	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:503)
    	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:330)
    	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
    	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:328)
    	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:316)
    	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719)
    	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
    	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
    [testcontainers-lifecycle-2] ERROR 🐳 [confluentinc/cp-kafka:5.2.1] - Log output from the failed container:

    [testcontainers-lifecycle-1] ERROR 🐳 [confluentinc/cp-kafka:5.2.1] - Could not start container
    java.lang.IllegalStateException: 
    	at org.testcontainers.containers.KafkaContainer.containerIsStarted(KafkaContainer.java:121)
    	at org.testcontainers.containers.GenericContainer.containerIsStarted(GenericContainer.java:687)
    	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:503)
    	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:330)
    	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
    	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:328)
    	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:316)
    	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719)
    	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701)
    	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
    [testcontainers-lifecycle-4] ERROR 🐳 [confluentinc/cp-kafka:5.2.1] - Log output from the failed container:


com.example.kafkacluster.KafkaContainerClusterTest > testKafkaContainerCluster FAILED
    java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
        at com.example.kafkacluster.KafkaContainerCluster.start(KafkaContainerCluster.java:85)
        at com.example.kafkacluster.KafkaContainerClusterTest.testKafkaContainerCluster(KafkaContainerClusterTest.java:35)
```

**Comment by rnorth** [comment]
This continues to be an issue in CI - at least one occurrence today.

**Comment by rnorth** [comment]
This is failing with high regularity still. Will try and fix.

My current hypothesis is that the parallel startup of three kafka brokers is just too much, causing all three to get bogged down with contention. It may be more reliable to start them in series. I'll try and reproduce then try with a fix.

**Comment by rnorth** [comment]
Ah, looking at the stack trace in depth, it looks like the failure is actually happening in `KafkaContainer`'s `containerIsStarted` method, here:
```
        String brokerAdvertisedListener = brokerAdvertisedListener(containerInfo);
        ExecResult result = execInContainer(
            "kafka-configs",
            "--alter",
            "--bootstrap-server", brokerAdvertisedListener,
            "--entity-type", "brokers",
            "--entity-name", getEnvMap().get("KAFKA_BROKER_ID"),
            "--add-config",
            "advertised.listeners=[" + String.join(",", getBootstrapServers(), brokerAdvertisedListener) + "]"
        );
        if (result.getExitCode() != 0) {
            throw new IllegalStateException(result.getStderr());    <---
        }
```
