### ISSUE TITLE
random java.lang.NullPointerException: networkMode was not specified

### ISSUE THREAD

**Issue by hstaudacher** [testcontainers/testcontainers-java#4483]
In our ci builds we see random failures every other build saying a container can't be started. Our scenario is the following:

* We have a container running our application
* We have another container (BrowserWebDriverContainer) to run chrome
* We have specified a network for both
* The chrome container depends on the application container.

The code looks like this:

```java
private void createContainers() {
	Network network = Network.newNetwork();
	GenericContainer<?> applicationContainer = new ApplicationContainer();
	applicationContainer.withNetwork(network).withNetworkAliases("app").withExposedPorts(8080, 8443);

	BrowserWebDriverContainer<?> chrome = new BrowserWebDriverContainer<>(
			DockerImageName.parse("selenium/standalone-chrome-debug:3.141.59-20210713")
					.asCompatibleSubstituteFor("selenium/standalone-chrome-debug"));
	chrome.withNetwork(network).withRecordingMode(VncRecordingMode.SKIP, null).dependsOn(applicationContainer);
	
	chrome.start();
}
```

In this scenario, `ApplicationContainer extends GenericContainer<ApplicationContainer>`. The code works most of the time. As said, every now and then we see the following error which makes the test run fail. 

We are using testcontainers **1.15.3** right now.

```java
java.lang.RuntimeException: com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.NoHttpResponseException: localhost:2375 failed to respond
	at com.github.dockerjava.zerodep.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:165) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.ZerodepDockerHttpClient.execute(ZerodepDockerHttpClient.java:8) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228) ~[testcontainers-1.15.3.jar:?]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:124) ~[testcontainers-1.15.3.jar:?]
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateNetworkCmdExec.execute(CreateNetworkCmdExec.java:27) ~[testcontainers-1.15.3.jar:?]
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.CreateNetworkCmdExec.execute(CreateNetworkCmdExec.java:12) ~[testcontainers-1.15.3.jar:?]
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21) ~[testcontainers-1.15.3.jar:?]
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[testcontainers-1.15.3.jar:?]
	at org.testcontainers.containers.Network$NetworkImpl.create(Network.java:92) ~[testcontainers-1.15.3.jar:?]
	at org.testcontainers.containers.Network$NetworkImpl.getId(Network.java:63) ~[testcontainers-1.15.3.jar:?]
	at org.testcontainers.containers.GenericContainer.applyConfiguration(GenericContainer.java:813) ~[testcontainers-1.15.3.jar:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:359) ~[testcontainers-1.15.3.jar:?]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325) ~[testcontainers-1.15.3.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323) ~[testcontainers-1.15.3.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311) ~[testcontainers-1.15.3.jar:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) [?:1.8.0_281]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701) [?:1.8.0_281]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) [?:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_281]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
Caused by: com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.NoHttpResponseException: localhost:2375 failed to respond
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.DefaultHttpResponseParser.createConnectionClosedException(DefaultHttpResponseParser.java:87) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:243) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:53) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:187) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:175) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.HijackingHttpRequestExecutor.execute(HijackingHttpRequestExecutor.java:50) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:596) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:215) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:107) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:181) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:172) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	at com.github.dockerjava.zerodep.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:161) ~[docker-java-transport-zerodep-3.2.8.jar:?]
	... 21 more
ERROR our-image:latest] - Could not start container
java.lang.NullPointerException: networkMode was not specified
	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_281]
	at com.github.dockerjava.api.command.CreateContainerCmd.withNetworkMode(CreateContainerCmd.java:294) ~[docker-java-api-3.2.8.jar:?]
	at org.testcontainers.containers.GenericContainer.applyConfiguration(GenericContainer.java:813) ~[testcontainers-1.15.3.jar:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:359) ~[testcontainers-1.15.3.jar:?]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325) ~[testcontainers-1.15.3.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323) ~[testcontainers-1.15.3.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311) ~[testcontainers-1.15.3.jar:?]
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) [?:1.8.0_281]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701) [?:1.8.0_281]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) [?:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_281]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_281]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]
ERROR our-image:latest] - Could not start container
```

**Comment by kiview** [comment]
Thanks for reporting this issue @hstaudacher.

I have a couple of questions, that might help us in triaging this bug further:

- Could you ever reproduce this issue on your local machine?
- Can you reproduce the error in CI, if you omit the `BrowserWebDriverContainer` and just start your single `ApplicationContainer` directly?
- Can you reproduce the error in CI, if you use a `GenericContainer` (not your custom `ApplicationContainer`) with some simple image, e.g. Redis?
- How is your Docker set up in CI? From the logs, it looks as if the Docker daemon is not responding when Testcontainers tries to create the network. This might be from the load on the daemon in high congestion shared CI scenarios. We might look into making the network creation more resilient.

**Comment by hstaudacher** [comment]
* Could you ever reproduce this issue on your local machine?
-> No

* Can you reproduce the error in CI, if you omit the BrowserWebDriverContainer and just start your single ApplicationContainer directly?
-> No, we have several other builds that use the same "ApplicationContainer". The scenarios are similar e.g. with a JdbcContainer but we haven't seen the error in such cases.

* Can you reproduce the error in CI, if you use a GenericContainer (not your custom ApplicationContainer) with some simple image, e.g. Redis?
-> We haven't tried this because it only happens 1 out of 10 runs or so. 

* How is your Docker set up in CI? From the logs, it looks as if the Docker daemon is not responding when Testcontainers tries to create the network. This might be from the load on the daemon in high congestion shared CI scenarios. We might look into making the network creation more resilient.
-> Not sure what you mean with how is it setup, what is the informatiom you are looking for. High load is a good pointer. We are executing the described scenario a couple times in parallel with forked surefire test vms. We can observe the when the error happens it only happens on one forked vm. All others pass.

**Comment by kiview** [comment]
Regarding the Docker setup question:
Is there a Docker daemon installed on the same node that executes the build? Is it accessed of the default Unix socket (I see `localhost:2375` in the logs)? Is the same Docker daemon shared by multiple CI builds at the same time? Is the Docker daemon running on another server? Is the build running Docker-in-Docker, etc.

IMO we should be able to reproduce this scenario locally by running something like a load test of multiple Testcontainers processes trying to create containers with a new network.

**Comment by hstaudacher** [comment]
We are using aws spot fleet instances for our builds and use one instance per job at a time. So, the job itself has all the hardware for itself.

On jenkins we are building inside a docker container. The container has mounted the /var/run/docker.sock as a volume from the host.

**Comment by rnorth** [comment]
In theory, what's the upper bound on the number of networks that your test suite could be creating? e.g. assuming all your tests ran as concurrently as possible, how many networks roughly would that entail?

**Comment by hstaudacher** [comment]
We have one network per forked jvm because we are holding the containers as static variables. We have configured a fork count of 6. So, 6 networks I think.

**Comment by rnorth** [comment]
OK, that shouldn't be enough to exhaust the IP address space that Docker uses for networks, unless there's a particularly bad overlap between the [docker defaults](https://github.com/moby/moby/pull/29376) and your AWS VPC subnets.

I think we need to see why creation of the `Network` is failing, rather than the container that relies on the `Network`. Are any other exceptions logged before this?

**Comment by hstaudacher** [comment]
Sorry, no exceptions before. Also, the aws instances are killed after the job ran. So, every job starts with a fresh address space. I will check the AWS VPC subnets with our IT.

**Comment by kiview** [comment]
Besides understanding the root cause of this issue in the case of @hstaudacher, I think we also have a bug (or rather oversight) in our code path, that leads to Testcontainers not retrying the creation of the network was part of the container startup retry.

This is the code in question:
https://github.com/testcontainers/testcontainers-java/blob/2be4c2a927abbed84e2a6cfcea974f821bfe3628/core/src/main/java/org/testcontainers/containers/Network.java#L62

If network creation failed (for whatever reason), the `initialized` will be set and Testcontainers won't try the creation again as part of the container startup retry block.
