### ISSUE TITLE
Cannot connect to containers when using docker-in-docker

### ISSUE THREAD

**Issue by jameslamine** [testcontainers/testcontainers-java#4596]
I'm using docker-in-docker inside of kubernetes in jenkins. My containers appear to start up fine, but the host/port never becomes accessible and so testcontainers cannot connect to them.

Everything works fine when I run the tests locally using docker desktop, it's only on when running in jenkins using docker-in-docker that they fail.

The container ip address is `172.17.0.2` but it's trying to connect to `172.17.0.1` which is the gateway. Is that normal?

I've tested this on both testcontainers 1.16.0 and 1.16.1 and they both fail. This could be related to #4591, except my problem happens on 1.16.0 as well. This also might be related to #4591 although I am not using `TESTCONTAINERS_HOST_OVERRIDE`

Here is my test case where I start up an elasticsearch container, log the ipAddress and hostAddress, and then run `docker inspect` and log the results:
```
class ElasticsearchContainerTest {

    companion object {
        private val logger = KontextLogger.logger {}
        private const val ELASTICSEARCH_VERSION = "6.7.0"
        private val container = ElasticsearchContainer(
            DockerImageName.parse("{REDACTED CONTAINER MIRROR URL}/elasticsearch")
                .withTag(ELASTICSEARCH_VERSION)
                .asCompatibleSubstituteFor("docker.elastic.co/elasticsearch/elasticsearch")
        ).withLogConsumer(Slf4jLogConsumer(KontextLogger.logger {}))

        @BeforeAll
        @JvmStatic
        fun beforeAll() {
            container.start()
        }

        @AfterAll
        @JvmStatic
        fun afterAll() {
            logger.error("Container IP address: ${container.containerIpAddress}")
            logger.error("Container  url: ${container.httpHostAddress}")

            val dockerInspect = container.dockerClient.inspectContainerCmd(container.containerId).exec()
            val mapper = ObjectMapper().disable(SerializationFeature.FAIL_ON_EMPTY_BEANS)
            val jsonOutput = mapper.writerWithDefaultPrettyPrinter().writeValueAsString(dockerInspect)
            logger.error("docker inspect elasticsearch: $jsonOutput")

            container.stop()
        }
    }

    @Test
    fun `check that container is running`() {
        Assert.assertTrue("Container is not running", container.isRunning)
    }
}
```

The test fails due to `Timed out waiting for URL to be accessible (http://172.17.0.1:49154/ should return HTTP 200`:
```
:integrationTest > 0 tests completed> :integrationTest > Executing test com.example.test.Elasticsea
 ElasticsearchContainerTest > initializationError FAILED
     org.testcontainers.containers.ContainerLaunchException: Container startup failed
         at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)
         at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
         at com.example.test.ElasticsearchContainerTest$Companion.beforeAll(ElasticsearchContainerTest.kt:28)
         at com.example.test.ElasticsearchContainerTest.beforeAll(ElasticsearchContainerTest.kt)
 
         Caused by:
         org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
             at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
             at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)
             ... 3 more
 
             Caused by:
             org.testcontainers.containers.ContainerLaunchException: Could not create/start container
                 at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:525)
                 at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)
                 at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
                 ... 4 more
 
                 Caused by:
                 org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://172.17.0.1:49154/ should return HTTP 200)
                     at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:264)
                     at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:51)
                     at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:929)
                     at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:468)
                     ... 6 more
```

Here is the output of `docker inspect`:
```
{
 "Args" : [ "eswrapper" ],
 "Config" : {
   "healthcheck" : null,
   "AttachStderr" : false,
   "AttachStdin" : false,
   "AttachStdout" : false,
   "Cmd" : [ "eswrapper" ],
   "Domainname" : "",
   "Entrypoint" : [ "/usr/local/bin/docker-entrypoint.sh" ],
   "Env" : [ "discovery.type=single-node", "PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "ELASTIC_CONTAINER=true", "JAVA_HOME=/opt/jdk-12" ],
   "ExposedPorts" : {
     "9200/tcp" : { },
     "9300/tcp" : { }
   },
   "Hostname" : "8d8c72fac5a9",
   "Image" : "{REDACTED CONTAINER MIRROR URL}/open-source-mirror/dockerhub/elasticsearch:6.7.0",
   "Labels" : {
     "license" : "Elastic License",
     "org.label-schema.build-date" : "20190305",
     "org.label-schema.license" : "GPLv2",
     "org.label-schema.name" : "elasticsearch",
     "org.label-schema.schema-version" : "1.0",
     "org.label-schema.url" : "https://www.elastic.co/products/elasticsearch",
     "org.label-schema.vcs-url" : "https://github.com/elastic/elasticsearch",
     "org.label-schema.vendor" : "Elastic",
     "org.label-schema.version" : "6.7.0",
     "org.testcontainers" : "true",
     "org.testcontainers.sessionId" : "671d3a01-4780-4f87-af21-ac568bafdc6f"
   },
   "MacAddress" : null,
   "NetworkDisabled" : null,
   "OnBuild" : null,
   "OpenStdin" : false,
   "PortSpecs" : null,
   "StdinOnce" : false,
   "Tty" : false,
   "User" : "",
   "Volumes" : null,
   "WorkingDir" : "/usr/share/elasticsearch",
   "Healthcheck" : null
 },
 "Created" : "2021-10-20T20:26:52.934006535Z",
 "Driver" : "overlay2",
 "ExecDriver" : null,
 "HostConfig" : {
   "Binds" : [ ],
   "BlkioWeight" : 0,
   "BlkioWeightDevice" : null,
   "BlkioDeviceReadBps" : null,
   "BlkioDeviceWriteBps" : null,
   "BlkioDeviceReadIOps" : null,
   "BlkioDeviceWriteIOps" : null,
   "MemorySwappiness" : null,
   "NanoCpus" : 0,
   "CapAdd" : null,
   "CapDrop" : null,
   "ContainerIDFile" : "",
   "CpuPeriod" : 0,
   "CpuRealtimePeriod" : 0,
   "CpuRealtimeRuntime" : 0,
   "CpuShares" : 0,
   "CpuQuota" : 0,
   "CpusetCpus" : "",
   "CpusetMems" : "",
   "Devices" : null,
   "DeviceCgroupRules" : null,
   "DeviceRequests" : null,
   "DiskQuota" : null,
   "Dns" : null,
   "DnsOptions" : null,
   "DnsSearch" : null,
   "ExtraHosts" : [ ],
   "GroupAdd" : null,
   "IpcMode" : "shareable",
   "Cgroup" : "",
   "Links" : null,
   "LogConfig" : {
     "Type" : "json-file",
     "Config" : { }
   },
   "LxcConf" : null,
   "Memory" : 0,
   "MemorySwap" : 0,
   "MemoryReservation" : 0,
   "KernelMemory" : 0,
   "NetworkMode" : "default",
   "OomKillDisable" : false,
   "Init" : null,
   "AutoRemove" : false,
   "OomScoreAdj" : 0,
   "PortBindings" : {
     "9200/tcp" : [ {
       "HostIp" : "",
       "HostPort" : ""
     } ],
     "9300/tcp" : [ {
       "HostIp" : "",
       "HostPort" : ""
     } ]
   },
   "Privileged" : false,
   "PublishAllPorts" : false,
   "ReadonlyRootfs" : false,
   "RestartPolicy" : {
     "MaximumRetryCount" : 0,
     "Name" : ""
   },
   "Ulimits" : null,
   "CpuCount" : 0,
   "CpuPercent" : 0,
   "IOMaximumIOps" : 0,
   "IOMaximumBandwidth" : 0,
   "VolumesFrom" : [ ],
   "Mounts" : null,
   "PidMode" : "",
   "Isolation" : null,
   "SecurityOpt" : null,
   "StorageOpt" : null,
   "CgroupParent" : "",
   "VolumeDriver" : "",
   "ShmSize" : 67108864,
   "PidsLimit" : null,
   "Runtime" : "runc",
   "Tmpfs" : null,
   "UTSMode" : "",
   "UsernsMode" : "",
   "Sysctls" : null,
   "ConsoleSize" : [ 0, 0 ]
 },
 "HostnamePath" : "/home/rootless/.local/share/docker/containers/8d8c72fac5a93471e0407a085e0b79236542b0ec01fc1f5d8c74024aa80b3457/hostname",
 "HostsPath" : "/home/rootless/.local/share/docker/containers/8d8c72fac5a93471e0407a085e0b79236542b0ec01fc1f5d8c74024aa80b3457/hosts",
 "LogPath" : "/home/rootless/.local/share/docker/containers/8d8c72fac5a93471e0407a085e0b79236542b0ec01fc1f5d8c74024aa80b3457/8d8c72fac5a93471e0407a085e0b79236542b0ec01fc1f5d8c74024aa80b3457-json.log",
 "Id" : "8d8c72fac5a93471e0407a085e0b79236542b0ec01fc1f5d8c74024aa80b3457",
 "SizeRootFs" : null,
 "Image" : "sha256:02982be5777dea7bbf9573e1993c936b8add775d303bafd638924cf9635e8c38",
 "MountLabel" : "",
 "Name" : "/focused_roentgen",
 "RestartCount" : 0,
 "NetworkSettings" : {
   "Bridge" : "",
   "SandboxID" : "786b67295fe24a75cd4edcf66b69383e72e2972f80bf6b6a801f9c020d14bf27",
   "HairpinMode" : false,
   "LinkLocalIPv6Address" : "",
   "LinkLocalIPv6PrefixLen" : 0,
   "Ports" : {
     "9200/tcp" : [ {
       "HostIp" : "0.0.0.0",
       "HostPort" : "49154"
     }, {
       "HostIp" : "::",
       "HostPort" : "49154"
     } ],
     "9300/tcp" : [ {
       "HostIp" : "0.0.0.0",
       "HostPort" : "49153"
     }, {
       "HostIp" : "::",
       "HostPort" : "49153"
     } ]
   },
   "SandboxKey" : "/run/user/1000/docker/netns/786b67295fe2",
   "SecondaryIPAddresses" : null,
   "SecondaryIPv6Addresses" : null,
   "EndpointID" : "d2a62c1fbd8241342d7f782109a54fa9caf8fbe1a9d07408aaefa695abd82d87",
   "Gateway" : "172.17.0.1",
   "PortMapping" : null,
   "GlobalIPv6Address" : "",
   "GlobalIPv6PrefixLen" : 0,
   "IPAddress" : "172.17.0.2",
   "IPPrefixLen" : 16,
   "IPv6Gateway" : "",
   "MacAddress" : "02:42:ac:11:00:02",
   "Networks" : {
     "bridge" : {
       "IPAMConfig" : null,
       "Links" : null,
       "Aliases" : null,
       "NetworkID" : "aaeb65fa1c11b6e4e4350d4b68b34d38796f2170d26073bdb0282fe14f4dc6a6",
       "EndpointID" : "d2a62c1fbd8241342d7f782109a54fa9caf8fbe1a9d07408aaefa695abd82d87",
       "Gateway" : "172.17.0.1",
       "IPAddress" : "172.17.0.2",
       "IPPrefixLen" : 16,
       "IPv6Gateway" : "",
       "GlobalIPv6Address" : "",
       "GlobalIPv6PrefixLen" : 0,
       "MacAddress" : "02:42:ac:11:00:02"
     }
   }
 },
 "Path" : "/usr/local/bin/docker-entrypoint.sh",
 "ProcessLabel" : "",
 "ResolvConfPath" : "/home/rootless/.local/share/docker/containers/8d8c72fac5a93471e0407a085e0b79236542b0ec01fc1f5d8c74024aa80b3457/resolv.conf",
 "ExecIDs" : null,
 "State" : {
   "oomkilled" : false,
   "pidLong" : 873,
   "exitCodeLong" : 0,
   "Status" : "running",
   "Running" : true,
   "Paused" : false,
   "Restarting" : false,
   "OOMKilled" : false,
   "Dead" : false,
   "Pid" : 873,
   "ExitCode" : 0,
   "Error" : "",
   "StartedAt" : "2021-10-20T20:26:53.468541843Z",
   "FinishedAt" : "0001-01-01T00:00:00Z",
   "Health" : null
 },
 "Volumes" : null,
 "VolumesRW" : null,
 "Node" : null,
 "Mounts" : [ ],
 "GraphDriver" : {
   "Name" : "overlay2",
   "Data" : {
     "RootDir" : null,
     "DeviceId" : null,
     "DeviceName" : null,
     "DeviceSize" : null,
     "dir" : null
   }
 },
 "Platform" : "linux",
 "Path" : "/usr/local/bin/docker-entrypoint.sh",
 "Args" : [ "eswrapper" ],
 "ProcessLabel" : "",
 "Mounts" : [ ],
 "Platform" : "linux",
 "Config" : {
   "Hostname" : "8d8c72fac5a9",
   "Domainname" : "",
   "User" : "",
   "AttachStdin" : false,
   "AttachStdout" : false,
   "AttachStderr" : false,
   "ExposedPorts" : {
     "9200/tcp" : { },
     "9300/tcp" : { }
   },
   "Tty" : false,
   "OpenStdin" : false,
   "StdinOnce" : false,
   "Env" : [ "discovery.type=single-node", "PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "ELASTIC_CONTAINER=true", "JAVA_HOME=/opt/jdk-12" ],
   "Cmd" : [ "eswrapper" ],
   "Image" : "{REDACTED CONAINER MIRROR URL}/open-source-mirror/dockerhub/elasticsearch:6.7.0",
   "Volumes" : null,
   "WorkingDir" : "/usr/share/elasticsearch",
   "Entrypoint" : [ "/usr/local/bin/docker-entrypoint.sh" ],
   "OnBuild" : null,
   "Labels" : {
     "license" : "Elastic License",
     "org.label-schema.build-date" : "20190305",
     "org.label-schema.license" : "GPLv2",
     "org.label-schema.name" : "elasticsearch",
     "org.label-schema.schema-version" : "1.0",
     "org.label-schema.url" : "https://www.elastic.co/products/elasticsearch",
     "org.label-schema.vcs-url" : "https://github.com/elastic/elasticsearch",
     "org.label-schema.vendor" : "Elastic",
     "org.label-schema.version" : "6.7.0",
     "org.testcontainers" : "true",
     "org.testcontainers.sessionId" : "671d3a01-4780-4f87-af21-ac568bafdc6f"
   }
 },
 "Driver" : "overlay2",
 "AppArmorProfile" : "",
 "HostsPath" : "/home/rootless/.local/share/docker/containers/8d8c72fac5a93471e0407a085e0b79236542b0ec01fc1f5d8c74024aa80b3457/hosts",
 "HostnamePath" : "/home/rootless/.local/share/docker/containers/8d8c72fac5a93471e0407a085e0b79236542b0ec01fc1f5d8c74024aa80b3457/hostname",
 "GraphDriver" : {
   "Data" : {
     "LowerDir" : "/home/rootless/.local/share/docker/overlay2/b90bba9ed9340bb782431671713047f5ef740d51818a6e82ae64d9246d8215a5-init/diff:/home/rootless/.local/share/docker/overlay2/1e71332ad2a429a4d06d157b6c4e2c4401da2b44b640d412557feb3c39452010/diff:/home/rootless/.local/share/docker/overlay2/1302968f5de6c81580eadb218555c0bc49bd3af7c766e77cbdb0ea9f02371d2a/diff:/home/rootless/.local/share/docker/overlay2/3b2b6c22a55172df81ac6af6f439aa3ec1cfe0576269d9fab8c25772e49a65ca/diff:/home/rootless/.local/share/docker/overlay2/42a8e273145d92d47a2c6827fa4d276800e98189da117ca69b25808ce1013edc/diff:/home/rootless/.local/share/docker/overlay2/be84a76283d29eac19bb5e262a4b26578218877d2302cea775fc57c29e195fb0/diff:/home/rootless/.local/share/docker/overlay2/05a94b779ac49607562a956de5a274e5cd000747ef966e612f156ba3f5018cb3/diff:/home/rootless/.local/share/docker/overlay2/57967e2c3b2027a4b67e5d97544d36b11573228ae195fb1cb0799b0ca954c669/diff",
     "MergedDir" : "/home/rootless/.local/share/docker/overlay2/b90bba9ed9340bb782431671713047f5ef740d51818a6e82ae64d9246d8215a5/merged",
     "UpperDir" : "/home/rootless/.local/share/docker/overlay2/b90bba9ed9340bb782431671713047f5ef740d51818a6e82ae64d9246d8215a5/diff",
     "WorkDir" : "/home/rootless/.local/share/docker/overlay2/b90bba9ed9340bb782431671713047f5ef740d51818a6e82ae64d9246d8215a5/work"
   },
   "Name" : "overlay2"
 },
 "Image" : "sha256:02982be5777dea7bbf9573e1993c936b8add775d303bafd638924cf9635e8c38",
 "Created" : "2021-10-20T20:26:52.934006535Z",
 "Name" : "/focused_roentgen",
 "RestartCount" : 0,
 "NetworkSettings" : {
   "Bridge" : "",
   "SandboxID" : "786b67295fe24a75cd4edcf66b69383e72e2972f80bf6b6a801f9c020d14bf27",
   "HairpinMode" : false,
   "LinkLocalIPv6Address" : "",
   "LinkLocalIPv6PrefixLen" : 0,
   "Ports" : {
     "9200/tcp" : [ {
       "HostIp" : "0.0.0.0",
       "HostPort" : "49154"
     }, {
       "HostIp" : "::",
       "HostPort" : "49154"
     } ],
     "9300/tcp" : [ {
       "HostIp" : "0.0.0.0",
       "HostPort" : "49153"
     }, {
       "HostIp" : "::",
       "HostPort" : "49153"
     } ]
   },
   "SandboxKey" : "/run/user/1000/docker/netns/786b67295fe2",
   "SecondaryIPAddresses" : null,
   "SecondaryIPv6Addresses" : null,
   "EndpointID" : "d2a62c1fbd8241342d7f782109a54fa9caf8fbe1a9d07408aaefa695abd82d87",
   "Gateway" : "172.17.0.1",
   "GlobalIPv6Address" : "",
   "GlobalIPv6PrefixLen" : 0,
   "IPAddress" : "172.17.0.2",
   "IPPrefixLen" : 16,
   "IPv6Gateway" : "",
   "MacAddress" : "02:42:ac:11:00:02",
   "Networks" : {
     "bridge" : {
       "IPAMConfig" : null,
       "Links" : null,
       "Aliases" : null,
       "NetworkID" : "aaeb65fa1c11b6e4e4350d4b68b34d38796f2170d26073bdb0282fe14f4dc6a6",
       "EndpointID" : "d2a62c1fbd8241342d7f782109a54fa9caf8fbe1a9d07408aaefa695abd82d87",
       "Gateway" : "172.17.0.1",
       "IPAddress" : "172.17.0.2",
       "IPPrefixLen" : 16,
       "IPv6Gateway" : "",
       "GlobalIPv6Address" : "",
       "GlobalIPv6PrefixLen" : 0,
       "MacAddress" : "02:42:ac:11:00:02",
       "DriverOpts" : null
     }
   }
 },
 "MountLabel" : "",
 "State" : {
   "Status" : "running",
   "Running" : true,
   "Paused" : false,
   "Restarting" : false,
   "OOMKilled" : false,
   "Dead" : false,
   "Pid" : 873,
   "ExitCode" : 0,
   "Error" : "",
   "StartedAt" : "2021-10-20T20:26:53.468541843Z",
   "FinishedAt" : "0001-01-01T00:00:00Z"
 },
 "ResolvConfPath" : "/home/rootless/.local/share/docker/containers/8d8c72fac5a93471e0407a085e0b79236542b0ec01fc1f5d8c74024aa80b3457/resolv.conf",
 "ExecIDs" : null,
 "HostConfig" : {
   "Binds" : [ ],
   "ContainerIDFile" : "",
   "LogConfig" : {
     "Type" : "json-file",
     "Config" : { }
   },
   "NetworkMode" : "default",
   "PortBindings" : {
     "9200/tcp" : [ {
       "HostIp" : "",
       "HostPort" : ""
     } ],
     "9300/tcp" : [ {
       "HostIp" : "",
       "HostPort" : ""
     } ]
   },
   "RestartPolicy" : {
     "Name" : "",
     "MaximumRetryCount" : 0
   },
   "AutoRemove" : false,
   "VolumeDriver" : "",
   "VolumesFrom" : [ ],
   "CapAdd" : null,
   "CapDrop" : null,
   "CgroupnsMode" : "host",
   "Dns" : null,
   "DnsOptions" : null,
   "DnsSearch" : null,
   "ExtraHosts" : [ ],
   "GroupAdd" : null,
   "IpcMode" : "shareable",
   "Cgroup" : "",
   "Links" : null,
   "OomScoreAdj" : 0,
   "PidMode" : "",
   "Privileged" : false,
   "PublishAllPorts" : false,
   "ReadonlyRootfs" : false,
   "SecurityOpt" : null,
   "UTSMode" : "",
   "UsernsMode" : "",
   "ShmSize" : 67108864,
   "Runtime" : "runc",
   "ConsoleSize" : [ 0, 0 ],
   "Isolation" : "",
   "CpuShares" : 0,
   "Memory" : 0,
   "NanoCpus" : 0,
   "CgroupParent" : "",
   "BlkioWeight" : 0,
   "BlkioWeightDevice" : null,
   "BlkioDeviceReadBps" : null,
   "BlkioDeviceWriteBps" : null,
   "BlkioDeviceReadIOps" : null,
   "BlkioDeviceWriteIOps" : null,
   "CpuPeriod" : 0,
   "CpuQuota" : 0,
   "CpuRealtimePeriod" : 0,
   "CpuRealtimeRuntime" : 0,
   "CpusetCpus" : "",
   "CpusetMems" : "",
   "Devices" : null,
   "DeviceCgroupRules" : null,
   "DeviceRequests" : null,
   "KernelMemory" : 0,
   "KernelMemoryTCP" : 0,
   "MemoryReservation" : 0,
   "MemorySwap" : 0,
   "MemorySwappiness" : null,
   "OomKillDisable" : false,
   "PidsLimit" : null,
   "Ulimits" : null,
   "CpuCount" : 0,
   "CpuPercent" : 0,
   "IOMaximumIOps" : 0,
   "IOMaximumBandwidth" : 0,
   "MaskedPaths" : [ "/proc/asound", "/proc/acpi", "/proc/kcore", "/proc/keys", "/proc/latency_stats", "/proc/timer_list", "/proc/timer_stats", "/proc/sched_debug", "/proc/scsi", "/sys/firmware" ],
   "ReadonlyPaths" : [ "/proc/bus", "/proc/fs", "/proc/irq", "/proc/sys", "/proc/sysrq-trigger" ]
 },
 "Id" : "8d8c72fac5a93471e0407a085e0b79236542b0ec01fc1f5d8c74024aa80b3457",
 "LogPath" : "/home/rootless/.local/share/docker/containers/8d8c72fac5a93471e0407a085e0b79236542b0ec01fc1f5d8c74024aa80b3457/8d8c72fac5a93471e0407a085e0b79236542b0ec01fc1f5d8c74024aa80b3457-json.log"
}
```

When I run a similar test for postgres, it passes but that's only because the postgres testcontainer uses a log watching wait strategy and doesn't try to connect to the exposed port. If I try to actually connect to the postgres container it fails as well.

My kubernetes podspec is like this:
```
    podSpec:
      spec:
        containers:
        - name: main
          image: <redacted, but my image is based on debian>
          command:
            - cat
          tty: true
          volumeMounts:
            - mountPath: /var/run
              name: docker-socket
          env:
            - name: TESTCONTAINERS_RYUK_DISABLED
              value: true
        - name: dind-daemon
          image: docker:20.10.9-dind-rootless
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
          volumeMounts:
            - name: docker-socket
              mountPath: /run/user/1000
        volumes:
          - name: docker-socket
            emptyDir: {}
```

**Comment by jameslamine** [comment]
Setting `TESTCONTAINERS_HOST_OVERRIDE` to `localhost` fixed the issue. So it's not automatically detecting that correctly. The fix worked with testcontainers `1.16.1`. I didn't test it with `1.16.0`.

**Comment by kiview** [comment]
Can you please set your Testcontainers logs to DEBUG level (see here https://www.testcontainers.org/supported_docker_environment/logging_config/) and provide all the logs of the test run?

If you would be able to create some kind of local reproducer, this would also be helpful, but I get that this might be challenging or nearly impossible.

**Comment by bsideup** [comment]
> The container ip address is 172.17.0.2 but it's trying to connect to 172.17.0.1 which is the gateway. Is that normal?

this is normal, as we are not connecting to container's IP, but Docker Gateway on which all ports are exposed

> This could be related to #4594, except my problem happens on 1.16.0 as well. This also might be related to #4591 although I am not using TESTCONTAINERS_HOST_OVERRIDE

I think these issues are unrelated. What happening is:
1. You start your tests in a pod with Docker as a sidecar container I would assume
2. Testcontainers' [detects that it runs in a container](https://github.com/testcontainers/testcontainers-java/blob/31e55619a36f89afe27234b94e0250417dc5ff8f/core/src/main/java/org/testcontainers/dockerclient/DockerClientProviderStrategy.java#L310). This usually means that `localhost` won't work, and the gateway IP should be used instead
3. The gateway IP is `172.17.0.1` but your pod cannot see it, as you have multiple layers of containerization

Setting `TESTCONTAINERS_HOST_OVERRIDE` to `localhost` works because containers in k8s pods share the same network namespace. Unfortunately, there isn't much we can do in this scenario, as the setup is custom. But that's exactly why we introduced `TESTCONTAINERS_HOST_OVERRIDE` - to be able to override the detection in the most advanced environments.

I hope this explanation helps understanding what's going on better 👍

**Comment by jameslamine** [comment]
I can confirm that this shows up in the logs:
```
 INFO  org.testcontainers.dockerclient.DockerClientProviderStrategy - Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
INFO  org.testcontainers.DockerClientFactory - Docker host IP address is 172.17.0.1
```
