### ISSUE TITLE
testcontainers 1.16.2 and selenium 4.0.0 throws NPE

### ISSUE THREAD

**Issue by SiKing** [testcontainers/testcontainers-java#4674]
Just trying this out for first time today.

Have the most trivial test, using information from here https://www.testcontainers.org/modules/webdriver_containers/

This is what I see in my console:

```
12:57:25.879-0800 [main] [INFO] DockerClientProviderStrategy - Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
12:57:26.746-0800 [main] [INFO] DockerClientProviderStrategy - Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
12:57:26.747-0800 [main] [INFO] DockerClientFactory - Docker host IP address is localhost
12:57:26.794-0800 [main] [INFO] DockerClientFactory - Connected to docker: 
  Server Version: 20.10.10
  API Version: 1.41
  Operating System: Linux Mint 19.3
  Total Memory: 15662 MB
12:57:26.798-0800 [main] [INFO] ImageNameSubstitutor - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
12:57:26.935-0800 [main] [INFO] RegistryAuthLocator - Credential helper/store (docker-credential-secretservice) does not have credentials for index.docker.io
12:57:27.864-0800 [main] [INFO] DockerClientFactory - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
12:57:27.864-0800 [main] [INFO] DockerClientFactory - Checking the system...
12:57:27.865-0800 [main] [INFO] DockerClientFactory - ✔︎ Docker server version should be at least 1.6.0
12:57:28.003-0800 [main] [INFO] DockerClientFactory - ✔︎ Docker environment should have more than 2GB free disk space
12:57:28.008-0800 [main] [INFO] SeleniumUtils - Selenium API version 4.0.0 detected on classpath
```

This is the stacktrace that I get:
```
java.lang.NullPointerException
	at org.testcontainers.containers.BrowserWebDriverContainer.retainRecordingIfNeeded(BrowserWebDriverContainer.java:346)
	at org.testcontainers.containers.BrowserWebDriverContainer.afterTest(BrowserWebDriverContainer.java:307)
	at org.testcontainers.containers.GenericContainer.failed(GenericContainer.java:1081)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:34)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

This happens at the `@Rule`, it does not even get to my test code!

**Comment by SiKing** [comment]
Not sure if this is related to #4593. But the errors reported there are different.

**Comment by kiview** [comment]
While it might be related, it does not look like the same issue, because of the location of the exception (after test execution). Can you share your test code? 

Exception occurs here:
https://github.dev/testcontainers/testcontainers-java/blob/440179d3fe372ff076426b8d1ac9ad614f6eefce/modules/selenium/src/main/java/org/testcontainers/containers/BrowserWebDriverContainer.java#L346

**Comment by SiKing** [comment]
```java
package tests;

import org.junit.Rule;
import org.junit.Test;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testcontainers.containers.BrowserWebDriverContainer;

public class ContainersIT {

    private static final Logger log = LoggerFactory.getLogger(ContainersIT.class);

    @Rule
    public BrowserWebDriverContainer<?> chrome = new BrowserWebDriverContainer<>()
	    .withCapabilities(new ChromeOptions());

    @Test
    public void test() {

	RemoteWebDriver driver = chrome.getWebDriver();

	driver.get("http://www.google.com");
	log.info("Trying: " + driver.getCurrentUrl());
    }
}
```

**Comment by tobiasstadler** [comment]
Is there any other error in the logs? I suspect that the browser container wasn't able to start.

**Comment by SiKing** [comment]
Above is the entirety of the logs produced.

**Comment by tobiasstadler** [comment]
IMHO the problem is, that the image `selenium/standalone-chrome-debug`, which is the default chrome image used by testcontainers, does not exist for Selenium 4. The vnc stuff is now included In the normal image.

Can you please test `new DockerImageName.parse("selenium/standalone-chrome:4.0.0")`

**Comment by SiKing** [comment]
This gives me: `DockerImageName.parse cannot be resolved to a type`.

**Comment by tobiasstadler** [comment]
Sorry, my fault. `new BrowserWebDriverContainer<>(DockerImageName.parse("selenium/standalone-chrome:4.0.0"))` is correct.

**Comment by SiKing** [comment]
So that "works". As in: it gets me to #4593.
ty
