### ISSUE TITLE
Failing to run testcontainers with selenide using Testng @BeforeMehtod and @AfterMethod

### ISSUE THREAD

**Issue by sergsol** [testcontainers/testcontainers-java#4697]
I am running tests using Gradle Testng selenide and now I want tests to run inside a container. From what I found I only should use .start() and .stop() I am using @BeforeMehtod and @AfterMethod code below. But can't make it run. Getting this error: com.github.dockerjava.api.exception.BadRequestException: Status 400:{"message":"Duplicate mount point: /dev/shm"}

```
@Listeners({ ScreenShooter.class })
public class BaseTest {
    protected ProjectConfig config = ConfigFactory.create(ProjectConfig.class, System.getProperties());
    protected String environment = config.environment();
    protected String VIDEO = config.VIDEO();
    protected String GAME = config.GAME();
    protected String login = config.login();
    protected String password = config.password();
    public static BrowserWebDriverContainer chrome =
            new BrowserWebDriverContainer()
                    .withCapabilities(DesiredCapabilities.chrome())
                    .withRecordingMode(BrowserWebDriverContainer.VncRecordingMode.RECORD_ALL, new File("./target/"));


    @BeforeMethod
    public void setUp(){
        Configuration.baseUrl = config.baseUrl();
        Configuration.timeout = 30000;
        ProjectConfig config = ConfigFactory.create(ProjectConfig.class, System.getProperties());
        SelenideLogger.addListener("AllureSelenide", new AllureSelenide().screenshots(true).savePageSource(false));
        chrome.start();
        RemoteWebDriver driver = chrome.getWebDriver();
        WebDriverRunner.setWebDriver(driver);
    }

    @AfterMethod()
    public void clean(){
        chrome.stop();
    }
    
}


    at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:315)
    at test.base.BaseTest.setUp(BaseTest.java:45)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
    at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
    at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
    at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
    at org.testng.TestRunner.privateRun(TestRunner.java:648)
    at org.testng.TestRunner.run(TestRunner.java:505)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
    at org.testng.SuiteRunner.run(SuiteRunner.java:364)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
    at org.testng.TestNG.runSuites(TestNG.java:1049)
    at org.testng.TestNG.run(TestNG.java:1017)
    at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:141)
    at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:90)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
    at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
    at com.sun.proxy.$Proxy2.stop(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
    at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
    at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
    at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
    at java.base/java.lang.Thread.run(Thread.java:834)
24597 [Test worker] INFO 🐳 [selenium/standalone-chrome-debug:3.141.59] - Creating container for image: selenium/standalone-chrome-debug:3.141.59
24630 [Test worker] ERROR 🐳 [selenium/standalone-chrome-debug:3.141.59] - Could not start container
com.github.dockerjava.api.exception.BadRequestException: Status 400: {"message":"Duplicate mount point: /dev/shm"}
```

**Comment by kiview** [comment]
Hi @sergsol, 

the error you are getting `Duplicate mount point: /dev/shm"` comes from Docker. It means you already have a container on your system, that is using this mount point. Try to clean up old containers from your system.

**Comment by sergsol** [comment]
Hi @kiview thanks for taking a look, but there are no containers on my system, I cleaned all. And other,  if I run all code usung @BeforeTest or @BeforeClass all works, i don't want to go into details why I am using  @Before-AfterMethod there are couple reasons.
Check screenshot

<img width="1606" alt="Docker" src="https://user-images.githubusercontent.com/17390660/143412668-ccca33fd-0753-477c-827a-268940671e0b.png">
.

**Comment by tobiasstadler** [comment]
Does using `new BrowserWebDriverContainer().withSharedMemorySize(..);` work?

**Comment by sergsol** [comment]
@tobiasstadler I am sorry but can you show me how that should look like in my case? :
```
 public static BrowserWebDriverContainer chrome =
            new BrowserWebDriverContainer()
                    .withCapabilities(DesiredCapabilities.chrome())
                    .withRecordingMode(BrowserWebDriverContainer.VncRecordingMode.RECORD_ALL, new File("./target/"));
```

**Comment by tobiasstadler** [comment]
e.g.
```
public static BrowserWebDriverContainer chrome =
            new BrowserWebDriverContainer()
                    .withSharedMemorySize(2147483648)
                    .withCapabilities(DesiredCapabilities.chrome())
                    .withRecordingMode(BrowserWebDriverContainer.VncRecordingMode.RECORD_ALL, new File("./target/"));
```

**Comment by sergsol** [comment]
@tobiasstadler unfortunately that doesn't work 
<img width="1582" alt="container" src="https://user-images.githubusercontent.com/17390660/143464044-03409eea-78fc-42e6-8b13-ec175488937f.png">

**Comment by tobiasstadler** [comment]
What about:
```
public static BrowserWebDriverContainer chrome =
            (BrowserWebDriverContainer) new BrowserWebDriverContainer()
                    .withCapabilities(DesiredCapabilities.chrome())
                    .withRecordingMode(BrowserWebDriverContainer.VncRecordingMode.RECORD_ALL, new File("./target/"))
                    .withSharedMemorySize(2147483648L);
```

**Comment by sergsol** [comment]
@tobiasstadler it works! Can you explain what was the issue?

**Comment by kiview** [comment]
The other variant did not work because of the typing. Using `withSharedMemorySize(2147483648L)` fixes your perceived issue, because if it is set, it won't mount through `/dev/shm`. Your code will have ended with multiple containers at the same time, bind mounting to `/dev/shm`.

**Comment by sergsol** [comment]
@kiview thanks for the explanation!
@tobiasstadler thanks for helping!
