### ISSUE TITLE
Error in test execution

### ISSUE THREAD

**Issue by vtroliveira** [testcontainers/testcontainers-java#472]
I'm trying to execute the test containers inside an web application deployed on glassfish
My test call is 

> public Result run(Test test) {
        this.test = test;
        logger.info("Running test {}", test.getTestName());
        JUnitCore runner = new JUnitCore();
        Result result = runner.run(TestBrowser.class);
        logger.info("{} run complete", test.getTestName());
        logger.info("It was successfull test? {}", result.wasSuccessful());
        return result;
    }

When I run this I got the exception above
`Informações:   java.lang.RuntimeException: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableSet.toImmutableSet()Ljava/util/stream/Collector;
	at org.rnorth.ducttape.timeouts.Timeouts.callFuture(Timeouts.java:57)
	at org.rnorth.ducttape.timeouts.Timeouts.getWithTimeout(Timeouts.java:32)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:38)
	at org.testcontainers.containers.BrowserWebDriverContainer.containerIsStarted(BrowserWebDriverContainer.java:166)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:238)
	at org.testcontainers.containers.GenericContainer.lambda$start$0(GenericContainer.java:184)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:182)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:544)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)`

In maven test scope it works perfectly, but this test works before on glassfish. Can anyone help me?

**Comment by rnorth** [comment]
I think this is a dependency version conflict - probably two versions of Guava conflicting. Please could you try checking whether Maven is overriding any deps at build time (`mvn dependency:analyze`, I think)?

**Comment by bsideup** [comment]
@rnorth aren't we shade Guava?

**Comment by iNikem** [comment]
I have similar/same issue:

```
    2018-02-20 22:01:49.692  INFO   --- [    Test worker] o.t.containers.SeleniumUtils             : Selenium API version 3.8.1 detected on classpath
    2018-02-20 22:01:49.859  INFO   --- [    Test worker] ?.8.1]                                   : Pulling docker image: selenium/standalone-chrome-debug:3.8.1. Please be patient; this may take some time but only needs to be done once.
    2018-02-20 22:03:41.870  INFO   --- [    Test worker] ?.8.1]                                   : Creating container for image: selenium/standalone-chrome-debug:3.8.1
    2018-02-20 22:03:41.999  INFO   --- [    Test worker] ?.8.1]                                   : Starting container with ID: 7f1a5028e94d82f1303aa65ce041966711408c55e9fdc692fda5e3841a00a250
    2018-02-20 22:03:42.425  INFO   --- [    Test worker] ?.8.1]                                   : Container selenium/standalone-chrome-debug:3.8.1 is starting: 7f1a5028e94d82f1303aa65ce041966711408c55e9fdc692fda5e3841a00a250
    2018-02-20 22:03:42.851  INFO   --- [    Test worker] ?.8.1]                                   : Container selenium/standalone-chrome-debug:3.8.1 started
    2018-02-20 22:03:42.854  INFO   --- [    Test worker] 🐳 [richnorth/vnc-recorder:latest]       : Creating container for image: richnorth/vnc-recorder:latest
    2018-02-20 22:03:44.142  INFO   --- [    Test worker] 🐳 [richnorth/vnc-recorder:latest]       : Starting container with ID: 7d1bf316ce10e35f1dffcd6e3483e5246bd5223a04e7de85499e8ae0652a1242
    2018-02-20 22:03:44.594  INFO   --- [    Test worker] 🐳 [richnorth/vnc-recorder:latest]       : Container richnorth/vnc-recorder:latest is starting: 7d1bf316ce10e35f1dffcd6e3483e5246bd5223a04e7de85499e8ae0652a1242
    2018-02-20 22:03:44.602  INFO   --- [    Test worker] 🐳 [richnorth/vnc-recorder:latest]       : Container richnorth/vnc-recorder:latest started
    2018-02-20 22:03:44.967 ERROR   --- [    Test worker] ?.8.1]                                   : Could not start container

    java.lang.RuntimeException: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableSortedSet.toImmutableSortedSet(Ljava/util/Comparator;)Ljava/util/stream/Collector;
        at org.rnorth.ducttape.timeouts.Timeouts.callFuture(Timeouts.java:57)
        at org.rnorth.ducttape.timeouts.Timeouts.getWithTimeout(Timeouts.java:32)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:38)
        at org.testcontainers.containers.BrowserWebDriverContainer.containerIsStarted(BrowserWebDriverContainer.java:166)
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:246)
        at org.testcontainers.containers.GenericContainer.lambda$start$0(GenericContainer.java:194)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:192)
        at eu.plumbr.dashboard.BaseTest.<clinit>(BaseTest.groovy:68)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
        at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:380)
        at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:293)
        at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:115)
        at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:200)
        at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:120)
        at org.testng.TestRunner.initMethods(TestRunner.java:409)
        at org.testng.TestRunner.init(TestRunner.java:235)
        at org.testng.TestRunner.init(TestRunner.java:205)
        at org.testng.TestRunner.<init>(TestRunner.java:153)
        at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:536)
        at org.testng.SuiteRunner.init(SuiteRunner.java:159)
        at org.testng.SuiteRunner.<init>(SuiteRunner.java:113)
        at org.testng.TestNG.createSuiteRunner(TestNG.java:1299)
        at org.testng.TestNG.createSuiteRunners(TestNG.java:1286)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
        at org.testng.TestNG.run(TestNG.java:1057)
        at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:129)
        at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:88)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy1.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:119)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableSortedSet.toImmutableSortedSet(Ljava/util/Comparator;)Ljava/util/stream/Collector;
        at org.openqa.selenium.remote.NewSessionPayload.lambda$validate$4(NewSessionPayload.java:199)
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.openqa.selenium.remote.NewSessionPayload.validate(NewSessionPayload.java:215)
        at org.openqa.selenium.remote.NewSessionPayload.<init>(NewSessionPayload.java:163)
        at org.openqa.selenium.remote.NewSessionPayload.create(NewSessionPayload.java:114)
        at org.openqa.selenium.remote.NewSessionPayload.create(NewSessionPayload.java:107)
        at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:67)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:219)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:142)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
        at org.testcontainers.containers.BrowserWebDriverContainer.lambda$null$0(BrowserWebDriverContainer.java:169)
        at org.rnorth.ducttape.unreliables.Unreliables.lambda$retryUntilSuccess$0(Unreliables.java:41)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 common frames omitted
```

Any hints, @bsideup @rnorth ?

**Comment by iNikem** [comment]
Ou, disregard my comment. I myself had wrong guava dependency :)

**Comment by bsideup** [comment]
@iNikem Actually, we should shade Guava in @rnorth's ducttape library to avoid that in future :)

**Comment by iNikem** [comment]
But here the problem lies not in your code, but in Selenium's, not? It calls guava code and I had too old version of that.
