### ISSUE TITLE
Missing standalone-chrome-debug manifest for selenium 4.0 and 4.1

### ISSUE THREAD

**Issue by Nicklas2751** [testcontainers/testcontainers-java#4769]
I'm using selenium 4.1 and because of #4593 with testcontainers 1.16.0

When I start a test with it I get the following error:

```
2021-12-07 13:20:12,001 docker-java-stream--726727059-19 ERROR ResultCallbackTemplate:52 - Error during callback
  com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"manifest for selenium/standalone-chrome-debug:4.1.0 not found: manifest unknown: manifest unknown"}

	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:241) ~[testcontainers-1.16.0.jar:?]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269) ~[testcontainers-1.16.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
 2021-12-07 13:20:12,052 main-1 INFO  TestCase:50 - Browser start
```

The class `BrowserWebDriverContainer` sets `selenium/standalone-chrome-debug` as default image to use for chrome. The latest tag for this image is `3.141.59` and not `4.1.0`. The image `selenium/standalone-chrome` has the new tag `4.1.0`. For me it looks like selenium has stopped creating a `selenium/standalone-chrome-debug` image since 4.0.

My workaround is to set `selenium/standalone-chrome` as custom image name via the `BrowserWebDriverContainer` constructor.

As a fix I would suggest to change the default image for chrome from `selenium/standalone-chrome-debug`  to `selenium/standalone-chrome`.

**Comment by tobiasstadler** [comment]
See #4686

**Comment by eddumelendez** [comment]
The latest versions of Testcontainers for Java support multiple images.

https://github.com/testcontainers/testcontainers-java/blob/main/modules/selenium/src/main/java/org/testcontainers/containers/BrowserWebDriverContainer.java#L52-L60

**Comment by eddumelendez** [comment]
AS mentioned previously this was done, and it is already available.
