### ISSUE TITLE
Cannot run mariadb docker by testcontainer at M1 Apple Silicon

### ISSUE THREAD

**Issue by mingyu-lee** [testcontainers/testcontainers-java#4778]
## Problem
- Test Container cannot start mariadb docker container after changed my laptop apple intel mac to apple silicon m1 pro

## What I tried
- add platform argument using withCreateContainerCmdModifier() and value is "linux/amd64"

### Gradle test
```
17:24:51.941 [DEBUG] [TestEventLogger]         Caused by:
17:24:51.941 [DEBUG] [TestEventLogger]         org.testcontainers.containers.ContainerLaunchException: Container startup failed
17:24:51.941 [DEBUG] [TestEventLogger]             at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
17:24:51.941 [DEBUG] [TestEventLogger]             at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:315)
17:24:51.941 [DEBUG] [TestEventLogger]             at com.nail.crm.api.v2.common.AbstractTestContainer.<clinit>(AbstractTestContainer.java:32)
17:24:51.941 [DEBUG] [TestEventLogger]             ... 88 more
17:24:51.941 [DEBUG] [TestEventLogger] 
17:24:51.941 [DEBUG] [TestEventLogger]             Caused by:
17:24:51.941 [DEBUG] [TestEventLogger]             org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
17:24:51.941 [DEBUG] [TestEventLogger]                 at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
17:24:51.941 [DEBUG] [TestEventLogger]                 at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:327)
17:24:51.941 [DEBUG] [TestEventLogger]                 ... 90 more
17:24:51.941 [DEBUG] [TestEventLogger] 
17:24:51.941 [DEBUG] [TestEventLogger]                 Caused by:
17:24:51.941 [DEBUG] [TestEventLogger]                 org.testcontainers.containers.ContainerLaunchException: Could not create/start container
17:24:51.941 [DEBUG] [TestEventLogger]                     at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:523)
17:24:51.941 [DEBUG] [TestEventLogger]                     at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:329)
17:24:51.942 [DEBUG] [TestEventLogger]                     at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
17:24:51.942 [DEBUG] [TestEventLogger]                     ... 91 more
17:24:51.942 [DEBUG] [TestEventLogger] 
17:24:51.942 [DEBUG] [TestEventLogger]                     Caused by:
17:24:51.942 [DEBUG] [TestEventLogger]                     java.lang.IllegalStateException: Container exited with code 2
17:24:51.942 [DEBUG] [TestEventLogger]                         at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:495)
17:24:51.942 [DEBUG] [TestEventLogger]                         ... 93 more
```
### Docker logs
```
docker logs --details d1ea13d67ab3a04afa268bda03b69b278954726ababd4c32211e3bbcc90ab186
 runtime: failed to create new OS thread (have 2 already; errno=22)
 fatal error: newosproc

 runtime stack:
 runtime.throw(0x4cb21f, 0x9)
 	/usr/local/go/src/runtime/panic.go:566 +0x95
 runtime.newosproc(0xc42002a000, 0xc420039fc0)
 	/usr/local/go/src/runtime/os_linux.go:160 +0x194
 runtime.newm(0x4d6db8, 0x0)
 	/usr/local/go/src/runtime/proc.go:1572 +0x132
 runtime.main.func1()
 	/usr/local/go/src/runtime/proc.go:126 +0x36
 runtime.systemstack(0x53ae00)
 	/usr/local/go/src/runtime/asm_amd64.s:298 +0x79
 runtime.mstart()
 	/usr/local/go/src/runtime/proc.go:1079

 goroutine 1 [running]:
 runtime.systemstack_switch()
 	/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc420024768 sp=0xc420024760
 runtime.main()
 	/usr/local/go/src/runtime/proc.go:127 +0x6c fp=0xc4200247c0 sp=0xc420024768
 runtime.goexit()
 	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200247c8 sp=0xc4200247c0
```

### Environment
JDK: openjdk 1.8
Testcontainer Version: 1.16.0
Testcontainer Mariadb module version: 1.16.0
Framework: Spring Boot 2.2.1
Teset framework: Junit 5, testcontainer-junit 1.16.0

### Configuration code for TestContainer

- BaseMvcIntegrationTest.java
```
@Testcontainers
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(initializers = BaseMvcIntegrationTest.TestContainerInitializer.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
public abstract class BaseMvcIntegrationTest extends AbstractTestContainer {
   // omitted
}
```

- AbstractTestContainer.java
```
public class AbstractTestContainer {
    public static JdbcDatabaseContainer<?> container;

    static {
        final String IMAGE_NAME = "mariadb:10.2.14";
        container = new MariaDBContainer<>(IMAGE_NAME)
            .withDatabaseName("testdb")
            .withUsername("testuser")
            .withPassword("1q2w3e4r")
            .withUrlParam("characterEncoding", StandardCharsets.UTF_8.name())
            .withCommand("mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci")
            .withCreateContainerCmdModifier(cmd -> cmd.withPlatform("linux/amd64")) // just add at M1
        ;
        container.start();
    }

    public static class TestContainerInitializer implements
        ApplicationContextInitializer<ConfigurableApplicationContext> {

        @Override
        public void initialize(ConfigurableApplicationContext applicationContext) {

            TestPropertySourceUtils.addInlinedPropertiesToEnvironment(
                applicationContext,
                "spring.datasource.jdbc-url=" + container.getJdbcUrl(),
                "spring.datasource.username=" + container.getUsername(),
                "spring.datasource.password=" + container.getPassword(),
                "spring.datasource.driver-class-name=" + container.getDriverClassName()
            );
        }
    }
}
```

Is it possible mariadb moudle working on Apple Silicon?

Anyone help please

BR

**Comment by kiview** [comment]
I am not a Mac user, so can't comment on those specifics, but do you have a Docker CLI command for MariaDB, that works on your M1 Mac? Because I don't think this is a Testcontainers issue.

**Comment by rnorth** [comment]
The error in the docker logs:
```
 runtime: failed to create new OS thread (have 2 already; errno=22)
 fatal error: newosproc
```
looks like a fairly typical QEMU error - i.e. Docker trying to emulate x86_64 on arm64, and failing for MariaDB.

I can only really suggest:
* Upgrade Docker for Mac, because the QEMU emulation is improving all the time
* Find (or create) a multi-platform MariaDB image which is built for arm64, and use that for your `IMAGE_NAME`

As we can't really do anything about this from a Testcontainers perspective, I'll close.

**Comment by mingyu-lee** [comment]
Thanks for reply and give suggestions. I solved it by changed mariadb docker image version from 10.2.14 to 10..2.16 which supporting arm architecture.
