### ISSUE TITLE
Pull from private repository not working when using secretservice as Credentials store

### ISSUE THREAD

**Issue by MeneDev** [testcontainers/testcontainers-java#483]
When using secretservice as Credentials store I am able to pull from my private repository. Using this setup testcontainers fails to pull with error 

**Reproduce**

1. Download [secretservice](https://github.com/docker/docker-credential-helpers/releases/download/v0.6.0/docker-credential-secretservice-v0.6.0-amd64.tar.gz) credentials store, unpack and put in $PATH
1. `docker logout <repo>`
1. stop docker service: `service docker stop`
1. Set credentials store to secretservice (see first `config.json` below)
1. start docker service: `service docker start`
1. `docker login <repo>` (results in second `config.json` below)

Then:
docker pull <image>
works, whereas using the same <image> from testcontainers will fail with exception below

**Expected behavior**

Testcontainers should be able to fetch when the docker client is able to fetch.

**`config.json` for using secretservice**

    {
            "credsStore": "secretservice"
    }

**`config.json` after docker login with secretservice**

    {
        "auths": {
                "docker.repository.corp.gdaag.de": {}
        },
        "HttpHeaders": {
                    "User-Agent": "Docker-Client/17.10.0-ce (linux)"
            },
        "credsStore": "secretservice"
    }

**Resulting Exception**

    org.testcontainers.containers.ContainerFetchException: Can't get Docker image name from org.testcontainers.images.RemoteDockerImage@4b3a45f1
    
        at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:772)
        at org.testcontainers.containers.GenericContainer.setDockerImageName(GenericContainer.java:760)
        at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:160)
        at de.gdata.emd.SomeSpec.$spock_initializeSharedFields(SomeSpec.groovy:30)
    Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get <url>: denied: access forbidden"}
    
        at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:109)
        at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
        at org.testcontainers.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at org.testcontainers.shaded.io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
        at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at org.testcontainers.shaded.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
        at org.testcontainers.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at org.testcontainers.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at org.testcontainers.shaded.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at org.testcontainers.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at org.testcontainers.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at org.testcontainers.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:997)
        at org.testcontainers.shaded.io.netty.channel.epoll.EpollDomainSocketChannel$EpollDomainUnsafe.epollInReady(EpollDomainSocketChannel.java:138)
        at org.testcontainers.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:401)
        at org.testcontainers.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
        at org.testcontainers.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at org.testcontainers.shaded.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)

**Comment by kiview** [comment]
Do you now if using docker-java library directly works as expected?

**Comment by kiview** [comment]
@MeneDev Did you ever try this again with a recent Testcontainers version? Since we are delegating this to Docker tools now, it should just work ideally.
