### ISSUE TITLE
Please place a file at the root of the classpath named container-license-acceptance.txt  ERROR

### ISSUE THREAD

**Issue by barryrhutchison** [testcontainers/testcontainers-java#4936]
Hello, we are having a problem building our application due to an error we think testcontainers is complaining about.

Error:

Caused by: java.lang.IllegalStateException: The image mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-20.04 requires you to accept a license agreement. Please place a file at the root of the classpath named container-license-acceptance.txt, e.g. at src/test/resources/con
tainer-license-acceptance.txt. This file should contain the line:
mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-20.04
at org.testcontainers.utility.LicenseAcceptance.assertLicenseAccepted(LicenseAcceptance.java:30)
at org.testcontainers.containers.MSSQLServerContainer.configure(MSSQLServerContainer.java:71)
at io.quarkus.devservices.mssql.deployment.MSSQLDevServicesProcessor$1$1.configure(MSSQLDevServicesProcessor.java:38)
at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:316)
... 14 more

It states that we must put the .txt file in the classpath.  We have it in the resources folder for each module that uses test containers but this error continues to show.  Only some developers are having this problem, not everyone.  

Do you have any suggestions for a fix for this ?  Thank you

**Comment by kiview** [comment]
This seems to be an inconsistency with regards to the development environment of your individual devs and what is added to the classpath. It does not seem like a Testcontainers issue.

Are you using Maven or Gradle?

**Comment by barryrhutchison** [comment]
> This seems to be an inconsistency with regards to the development environment of your individual devs and what is added to the classpath. It does not seem like a Testcontainers issue.
> 
> Are you using Maven or Gradle?

We are using Maven, issue is happening on a windows machine.  It most likely is an environment issue just wondered if this had  been seen before since its testcontainer specific and its preventing people from building the app.

**Comment by kiview** [comment]
Is the dev on the windows machine executing the build from the command line, or from an IDE that does not delegate to Maven?

**Comment by barryrhutchison** [comment]
> Is the dev on the windows machine executing the build from the command line, or from an IDE that does not delegate to Maven?

Directly in their command line they are executing the maven build

**Comment by kiview** [comment]
Can you confirm the file is present on their machine, has correct file encoding and correct line endings?

**Comment by barryrhutchison** [comment]
Problem resolved, it was an incorrect application property that caused this error.  Thanks for your input @kiview.

**Comment by kiview** [comment]
Thanks for letting me know, closing the issue.
