### ISSUE TITLE
TestContainers fails to detect successful container run and exit when a container is short-lived

### ISSUE THREAD

**Issue by mcekovic** [testcontainers/testcontainers-java#4957]
TestContainers fails to detect successful container run and exit when a container is short-lived.
This happens when a container starts and exits before TestCointainers first check if container is started. For example, official Docker `hello-world` image fails on simple TestContainers test:

```
@Testcontainers
class HelloWorldTestContainersTest {

	@Container
	public GenericContainer<?> container = new GenericContainer<>("hello-world");

	@Test
	void containerIsStarted() {
		assertNotNull(container.getContainerId());
	}
}

```

It can be seen that `hello-world` image container has started successfully and exited, but TestCotainers fails in detecting it:

```

[main] ERROR 🐳 [hello-world:latest] - Log output from the failed container:

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/



org.testcontainers.containers.ContainerLaunchException: Container startup failed

	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.start(TestcontainersExtension.java:242)
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.access$200(TestcontainersExtension.java:229)
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$null$4(TestcontainersExtension.java:82)

...

Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)
	... 88 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:525)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 89 more
Caused by: org.rnorth.ducttape.TimeoutException: Timeout waiting for result with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:54)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilTrue(Unreliables.java:100)
	at org.testcontainers.containers.startupcheck.StartupCheckStrategy.waitUntilStartupSuccessful(StartupCheckStrategy.java:35)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:460)
	... 91 more
Caused by: java.lang.RuntimeException: Not ready yet
	at org.rnorth.ducttape.unreliables.Unreliables.lambda$retryUntilTrue$1(Unreliables.java:102)
	at org.rnorth.ducttape.unreliables.Unreliables.lambda$retryUntilSuccess$0(Unreliables.java:43)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mcekovic** [comment]
Did some debugging. Seems that `org.testcontainers.containers.wait.internal.InternalCommandPortListeningCheck` fails with all 3 strategies in a container running in Rancher Desktop. Here are the outputs of all 3 strategies to detect internal listening port executed inside a redis container running in Rancher Desktop:

```
root@ca5ce0536c0f:/data# grep -i ':0*18eb' /proc/net/tcp*
root@ca5ce0536c0f:/data# nc -vz -w 1 localhost 6379
bash: nc: command not found
root@ca5ce0536c0f:/data# /bin/bash -c '</dev/tcp/localhost/6379'
/bin/bash: connect: Cannot assign requested address
/bin/bash: line 1: /dev/tcp/localhost/6379: Cannot assign requested address
```

**Comment by jennyowen** [comment]
I had this problem bad! The solution is to use the "One Shot" startup strategy, documented here: 
https://www.testcontainers.org/features/startup_and_waits/#one-shot-startup-strategy-example
https://www.javadoc.io/doc/org.testcontainers/testcontainers/latest/org/testcontainers/containers/startupcheck/OneShotStartupCheckStrategy.html

like:
`container.setStartupCheckStrategy( new OneShotStartupCheckStrategy() )`

**Comment by bsideup** [comment]
As @jennyowen shared, `OneShotStartupCheckStrategy` is indeed what should be used for one-off containers. The default expects containers to be running after they start (as this is the majority of containers started with Testcontainers), and that alternative strategy allows making it "one-off" friendly.
