### ISSUE TITLE
Can not connect to Ryuk at 172.17.0.1:49153: Connect timed out

### ISSUE THREAD

**Issue by thomasneuteboom** [testcontainers/testcontainers-java#5027]
I'm trying to run a Docker container that spins up a test container through `docker-compose` and `Gradle`. Everything works fine in CircleCI, but it does not work on my VPS (latest Digital Ocean Docker image). CircleCI and the VPS both use the same versions: 

```
Docker 20.10.12
Docker Compose 1.29.2
Ubuntu 20.04
Testcontainers 1.2.1
Gradle 7.3
```

**In Docker-compose.yml:**
```
console_gradle:
  image: openjdk:17-jdk
  working_dir: /app/backend/console
  volumes:
    - ./app/backend:/app/backend
    - /var/run/docker.sock:/var/run/docker.sock
  entrypoint: [ './gradlew' ]
```

**Running docker-compose:**
```
docker-compose run console_gradle installDist
```

**Running in build.gradle.kts:**
```
...
> Task :core:startTestDatabase
Timed out waiting for Ryuk container to start. Ryuk's logs:
2022/02/05 21:36:35 Pinging Docker...
2022/02/05 21:36:35 Docker daemon is available!
2022/02/05 21:36:35 Starting on port 8080...
2022/02/05 21:36:35 Started!
...
```

**The error:**
```
...
Can not connect to Ryuk at 172.17.0.1:49153
java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at org.testcontainers.utility.ResourceReaper.lambda$null$3(ResourceReaper.java:194)
        at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
        at org.testcontainers.utility.ResourceReaper.lambda$start$4(ResourceReaper.java:190)
        at java.base/java.lang.Thread.run(Thread.java:833)
Can not connect to Ryuk at 172.17.0.1:49153
java.net.SocketTimeoutException: Connect timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at org.testcontainers.utility.ResourceReaper.lambda$null$3(ResourceReaper.java:194)
        at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
        at org.testcontainers.utility.ResourceReaper.lambda$start$4(ResourceReaper.java:190)
        at java.base/java.lang.Thread.run(Thread.java:833)
...
```

**What I've tried on the VPS:**
```
 docker run -d -v /var/run/docker.sock:/var/run/docker.sock -p 8080:8080 testcontainers/ryuk:0.3.1
```
**Which does succeed:**
```
nc -zv localhost 8080
Connection to localhost 8080 port [tcp/http-alt] succeeded!
```

Anyone else experiencing this issue? Or does someone know a solution?

Thanks in advance! :)

**Comment by thomasneuteboom** [comment]
Ah, it works with ufw disabled. How would anyone use testcontainers with ufw enabled?

**Comment by kiview** [comment]
There might be some specific ufw default rules that get applied that break something here. TBH, this is the first time I hear about such problems on Ubuntu. I am aware of similar problems on Fedora/RHEL/CentOS with regards to `firewalld`, which needs to be configured along these lines:
```
firewall-cmd --zone=docker --change-interface=docker0
```

This is even more curious, given that manually running Ryuk works for you. 

Can you please try to run your tests without using Docker-Compose? I think the culprit is the firewall between container-ryukContainer and not between host-ryukContainer.
