### ISSUE TITLE
Getting a DockerComposeContainer up and running

### ISSUE THREAD

**Issue by andez2000** [testcontainers/testcontainers-java#5042]
I am trying to get mosquitto up and running in docker.  Everything has worked fine in a normal docker-compose.yml.  However, I am struggling with the test containers setup for my testing.

```
services:
  mosquitto-anonymous:
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto/config/anonymous/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data/anonymous:/mosquitto/data:rwo
      - ./mosquitto/log/mosquitto-anonymous.log:/mosquitto/log/mosquitto.log:rwo
```

I have tried a few incarnations of the following code.  I am getting the following exception when `environment.start()` is called:
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed

	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
	at org.testcontainers.containers.DockerComposeContainer.startAmbassadorContainers(DockerComposeContainer.java:330)
	at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:178)
	at com.acme.mqtt.ConnectToMqttBrokerAsAnonymous.connects_to_broker_and_sends_a_message_to_a_topic(ConnectToMqttBrokerAsAnonymous.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:125)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:132)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:124)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:74)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:104)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:62)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:43)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:35)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:202)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:198)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:69)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)
	... 69 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:525)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 70 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Aborting attempt to link to container ot82rwbswk8a_mosquitto-anonymous_1 as it is not running
	at org.testcontainers.containers.GenericContainer.applyConfiguration(GenericContainer.java:815)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:365)
	... 72 more
```

```
@ClassRule
    public static DockerComposeContainer<?> environment =
            new DockerComposeContainer<>(new File("src/test/resources/docker-compose-test.yml"))
                    .withExposedService("mosquitto-anonymous", 1890)
                    .withLocalCompose(true)
//                    .waitingFor("mosquitto-anonymous", Wait.forLogMessage("mosquitto version 2.0.14 running", 1))

   @Test
    public void connects_to_broker_and_sends_a_message_to_a_topic() throws MqttException, URISyntaxException {
        environment.start();

        //        environment.waitingFor("mosquitto-anonymous_1", Wait.forLogMessage("started", 1));
        //        String serviceHost = environment.getServiceHost("mosquitto-anonymous", 1890);
        //        Integer servicePort = environment.getServicePort("mosquitto-anonymous", 1890);

        MqttClientEndPoint mqttClientEndPoint = new MqttClientEndPoint(URI.create("tcp://127.0.0.1:1890"), "anonymousClient1");


        mqttClientEndPoint.connect();

        mqttClientEndPoint.publish("test topic", "some message");
    }
```

The examples I have seen do not explicitly call environment start (https://www.testcontainers.org/modules/docker_compose/).

If I put a breakpoint on the line GenericContainer.doStart() exception handler, I do see my container running:

![image](https://user-images.githubusercontent.com/16876524/153634657-db588b84-47f0-4adc-bedc-6e2e0701f009.png)

And mosquitto actually logs to the log file:

```
2022-02-11 16:55:27: mosquitto version 2.0.14 starting
2022-02-11 16:55:27: Config loaded from /mosquitto/config/mosquitto.conf.
2022-02-11 16:55:27: Opening ipv4 listen socket on port 1890.
2022-02-11 16:55:27: Opening ipv6 listen socket on port 1890.
2022-02-11 16:55:27: mosquitto version 2.0.14 running
```

Noticably the port bindings are missing in my container:

![image](https://user-images.githubusercontent.com/16876524/153634945-2992e655-d51d-4b60-bc0b-e0b51819accc.png)

Is there something wrong with my code setup and docker compose?

**Comment by andez2000** [comment]
@kiview  Thanks for the info.
I managed to get the logging setup.  I have attached it from the last run.

In the meantime, I will have a look at GenericContainer implementation a little bit more.  I did have a go of this and have experienced similar issues.  I will also look at putting together a project from the template.

[docker-testcontaines-logfile.txt](https://github.com/testcontainers/testcontainers-java/files/8053147/docker-testcontaines-logfile.txt)

**Comment by andez2000** [comment]
I now have a working test environment up and running with a GenericContainer.

This repo was pretty much what was required.
https://github.com/krizsan/mqtt-example

However, there would appear to be something odd about `.waitingFor(Wait.forLogMessage(".*mosquitto.*", 1))` and the logging to a file in the mosquitto.config - `log_dest file /mosquitto/log/mosquitto.log`.  But this is a battle for another day.
