### ISSUE TITLE
Unable to run test containers with M1 Mac and IDEA

### ISSUE THREAD

**Issue by q147258134** [testcontainers/testcontainers-java#5049]
```
 % docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:46:56 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.5.0 (74594)
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:07 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
Disabled: Use gRPC FUSE for file sharing
```
main 2022-02-16 17:32:51,577 INFO  (ImageNameSubstitutor.java:50) - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
main 2022-02-16 17:32:51,608 INFO  (DockerClientProviderStrategy.java:249) - Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
main 2022-02-16 17:32:52,123 INFO  (DockerMachineClientProviderStrategy.java:58) - docker-machine executable was not found on PATH ([/opt/homebrew/bin, /opt/homebrew/sbin, /usr/local/bin, /usr/bin, /bin, /usr/sbin, /sbin, /Users/mowancheng/apache-maven-3.5.4/bin])
main 2022-02-16 17:32:52,123 ERROR (DockerClientProviderStrategy.java:149) - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
main 2022-02-16 17:32:52,124 ERROR (DockerClientProviderStrategy.java:151) -     UnixSocketClientProviderStrategy: failed with exception RuntimeException (java.lang.UnsatisfiedLinkError: /private/var/folders/1w/976rw41s3xg5w__qyr9ng0r40000gp/T/jna-1664259479/jna1699989073320620441.tmp: dlopen(/private/var/folders/1w/976rw41s3xg5w__qyr9ng0r40000gp/T/jna-1664259479/jna1699989073320620441.tmp, 0x0001): tried: '/private/var/folders/1w/976rw41s3xg5w__qyr9ng0r40000gp/T/jna-1664259479/jna1699989073320620441.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/jna1699989073320620441.tmp' (no such file)). Root cause UnsatisfiedLinkError (/private/var/folders/1w/976rw41s3xg5w__qyr9ng0r40000gp/T/jna-1664259479/jna1699989073320620441.tmp: dlopen(/private/var/folders/1w/976rw41s3xg5w__qyr9ng0r40000gp/T/jna-1664259479/jna1699989073320620441.tmp, 0x0001): tried: '/private/var/folders/1w/976rw41s3xg5w__qyr9ng0r40000gp/T/jna-1664259479/jna1699989073320620441.tmp' (fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e')), '/usr/lib/jna1699989073320620441.tmp' (no such file))
main 2022-02-16 17:32:52,124 ERROR (DockerClientProviderStrategy.java:153) - As no valid configuration was found, execution cannot continue
Exception in thread "main" org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=elasticsearch:5.6.3, imagePullPolicy=DefaultPullPolicy())
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1326)
	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:643)
	at org.testcontainers.elasticsearch.ElasticsearchContainer.<init>(ElasticsearchContainer.java:73)
	at com.sankuai.amon.base.MoneyBillBaseUnitTest.main(MoneyBillBaseUnitTest.java:290)
Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$4(DockerClientProviderStrategy.java:156)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:148)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:146)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:188)
	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:101)
	at com.github.dockerjava.api.DockerClientDelegate.listImagesCmd(DockerClientDelegate.java:167)
	at org.testcontainers.images.LocalImagesCache.maybeInitCache(LocalImagesCache.java:68)
	at org.testcontainers.images.LocalImagesCache.get(LocalImagesCache.java:32)
	at org.testcontainers.images.AbstractImagePullPolicy.shouldPull(AbstractImagePullPolicy.java:18)
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:67)
	at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:28)
	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:17)
	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:39)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1324)
	... 3 more
```
Using test containers in a Maven build
```
<dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>1.16.3</version>
            <scope>test</scope>
</dependency>
<dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.10.0</version>
            <scope>test</scope>
</dependency>
```

**Comment by futurechan** [comment]
Same issue!

**Comment by afganhalbana** [comment]
in my case it's due to the elastic search version that i use has jna as transitive dependency that not supported the m1, so all i need to exclude it in my build.gradle.

> implementation ("org.elasticsearch:elasticsearch:7.10.1") {
>         exclude group: "org.elasticsearch", module: "jna"
>     }
