### ISSUE TITLE
Confusing error messages when Docker machine initialization fails

### ISSUE THREAD

**Issue by ldcasillas-progreso** [testcontainers/testcontainers-java#52]
When attempting to use testcontainers in OS X, I get the following exception.  Note the cause right at the bottom, which has the message "Could not find a suitable docker instance - is DOCKER_HOST defined and pointing to a running Docker daemon?":

    java.lang.IllegalStateException: Failed to prepare Docker client
    	at org.testcontainers.DockerClientFactory.<init>(DockerClientFactory.java:49)
    	at org.testcontainers.DockerClientFactory.instance(DockerClientFactory.java:60)
    	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:72)
    	at org.testcontainers.containers.JdbcDatabaseContainer.<init>(JdbcDatabaseContainer.java:27)
    	at org.testcontainers.containers.PostgreSQLContainer.<init>(PostgreSQLContainer.java:17)
    	at org.testcontainers.containers.PostgreSQLContainerProvider.newInstance(PostgreSQLContainerProvider.java:14)
    	at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:111)
    	at com.mchange.v2.c3p0.DriverManagerDataSource.getConnection(DriverManagerDataSource.java:161)
    	at com.progressfin.dataplatform.DataPlatformETLTest.runInitializationScripts(DataPlatformETLTest.java:121)
    	at com.progressfin.dataplatform.DataPlatformETLTest.<init>(DataPlatformETLTest.java:79)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:29)
    	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21)
    	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
    	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
    	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
    	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:88)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:56)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:64)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:50)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:106)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:744)
    Caused by: java.lang.IllegalStateException: Could not find a suitable docker instance - is DOCKER_HOST defined and pointing to a running Docker daemon?
    	at org.testcontainers.DockerClientFactory.determineConfiguration(DockerClientFactory.java:145)
    	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:72)
    	at org.testcontainers.DockerClientFactory.<init>(DockerClientFactory.java:44)
    	... 45 more

The problem is that this exception's descriptive message has, in my case, nothing to do with the actual cause of the failure.  The logs before the point this exception was thrown show this:

    [Test worker] INFO org.testcontainers.DockerClientFactory - Checking environment for docker settings
    [Test worker] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request to {s}->https://localhost:2376: https protocol is not supported
    [Test worker] INFO org.apache.http.impl.execchain.RetryExec - Retrying request to {s}->https://localhost:2376
    [Test worker] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request to {s}->https://localhost:2376: https protocol is not supported
    [Test worker] INFO org.apache.http.impl.execchain.RetryExec - Retrying request to {s}->https://localhost:2376
    [Test worker] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request to {s}->https://localhost:2376: https protocol is not supported
    [Test worker] INFO org.apache.http.impl.execchain.RetryExec - Retrying request to {s}->https://localhost:2376
    [Test worker] INFO org.testcontainers.DockerClientFactory - Could not initialize docker settings using environment variables: org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported
    [Test worker] INFO org.testcontainers.DockerClientFactory - Checking for presence of docker-machine
    [Test worker] INFO org.testcontainers.DockerClientFactory - Could not initialize docker settings using docker machine: docker-machine must be installed for use on OS X

That last message is apparently the real cause of the failure, but it's being reported as an info-level log message, one which several of my unit test reporting tools don't even report on.

**Comment by ldcasillas-progreso** [comment]
I should note that I have docker-machine installed.  In at least one instance, the cause of the error seems to be that IntelliJ is not including `/usr/local/bin` in the `PATH`.  So a much more useful failure mode would be something like this:

    Could not find docker-machine executable; PATH = [/usr/bin, /bin/]

**Comment by rnorth** [comment]
Luca,
Thank you for trying testcontainers out, and thanks raising this. I'd agree that these logs are confusing and need to be improved.

DockerClientFactory tries a couple of ways of accesing docker (via environment vars, then falling back to docker-machine) but at the moment I think it's too generic about the final (fatal) failure reporting. It should clearly state what's been tried and failed in the exception message. (Being in a 'caused by' is probably not all that great for clarity either).

I'll try and take a look at this in the next few days and prioritise for the next release, as I think not much work could make a worthwhile improvement.

Thanks!
Richard

**Comment by rnorth** [comment]
Your PATH reporting suggestion looks like a very good thing to do as well - nice and clear!

**Comment by rnorth** [comment]
I have a proposed improvement in a branch. 

Log output in a case of failure is something like:
```
21:00:21.746 [main] INFO  org.testcontainers.dockerclient.DockerConfigurationStrategy - Looking for Docker environment. Trying Environment variables, system properties and defaults: DockerClientConfig{uri=https://localhost:2376, version='null', username='root', password='null', email='null', serverAddress='https://index.docker.io/v1/', dockerCfgPath='/root/.dockercfg', sslConfig='LocalDirectorySSLConfig{dockerCertPath=/root/.docker}'}
21:00:24.377 [main] INFO  org.testcontainers.dockerclient.DockerConfigurationStrategy - Looking for Docker environment. Trying docker-machine
21:00:24.433 [main] ERROR org.testcontainers.dockerclient.DockerConfigurationStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
21:00:24.435 [main] ERROR org.testcontainers.dockerclient.DockerConfigurationStrategy -     Environment variables, system properties and defaults: DockerClientConfig{uri=https://localhost:2376, version='null', username='root', password='null', email='null', serverAddress='https://index.docker.io/v1/', dockerCfgPath='/root/.dockercfg', sslConfig='LocalDirectorySSLConfig{dockerCertPath=/root/.docker}'}: failed with exception message: ping failed
21:00:24.437 [main] ERROR org.testcontainers.dockerclient.DockerConfigurationStrategy -     docker-machine: failed with exception message: docker-machine executable was not found on PATH ([/usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /usr/games, /usr/local/games])
21:00:24.442 [main] ERROR org.testcontainers.dockerclient.DockerConfigurationStrategy - As no valid configuration was found, execution cannot continue
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.4 sec <<< FAILURE!
```

If, however, environment-based settings fail but docker-machine succeeds, the logs are a slightly more succinct:
```
20:36:05.439 [main] INFO  org.testcontainers.dockerclient.DockerConfigurationStrategy - Looking for Docker environment. Trying Environment variables, system properties and defaults: DockerClientConfig{uri=foobar, version='null', username='rnorth', password='null', email='null', serverAddress='https://index.docker.io/v1/', dockerCfgPath='/Users/rnorth/.dockercfg', sslConfig='LocalDirectorySSLConfig{dockerCertPath=/Users/rnorth/.docker}'}
20:36:40.615 [main] INFO  org.testcontainers.dockerclient.DockerConfigurationStrategy - Looking for Docker environment. Trying docker-machine
20:36:42.344 [main] DEBUG org.testcontainers.utility.CommandLine - Executing shell command: `docker-machine ls -q`
20:36:45.269 [main] INFO  org.testcontainers.dockerclient.DockerConfigurationStrategy - Found docker-machine, and will use machine named dev
20:36:45.275 [main] DEBUG org.testcontainers.utility.CommandLine - Executing shell command: `docker-machine status dev`
20:36:45.824 [main] DEBUG org.testcontainers.utility.CommandLine - Executing shell command: `docker-machine ip dev`
20:36:46.834 [main] INFO  org.testcontainers.dockerclient.DockerConfigurationStrategy - Docker daemon IP address for docker machine dev is 192.168.99.100
```

I'd appreciate feedback on any ways this could be made better!

**Comment by zxkane** [comment]
I'm trying to use library to do integration test of my project.

The error message really confused me. Currently I'm using `docker-machine` on mac osx which was installed by `docker toolkit`.

I also met the error message,

> Could not find a suitable docker instance - is DOCKER_HOST defined and pointing to a running Docker daemon?

After debugging the source of `testcontainers` a bit, the original error was caused by the `docker-machine` was not in PATH. Then looks like the configuration of docker, this lib was trying to access the `https://<ip of docker machine>:2736`, then I got the error of certification.

>22:32:51.811 [main] INFO  o.testcontainers.DockerClientFactory - Docker daemon IP address for docker machine default is 192.168.99.100
>22:32:51.814 [main] INFO  o.testcontainers.DockerClientFactory - Could not initialize docker settings using docker machine: Error in SSL Configuration

Could you add the prerequisites of docker's configuration in documentation or how to configure the test suites to use this library?

**Comment by rnorth** [comment]
@zxkane thanks for pointing that out. It seems like the library is having trouble picking up the right configuration settings for docker-machine. I've tried to make it work with docker-machine out of the box, so this is a bit odd. I assume you haven't made any unusual tweaks to your docker-machine configuration?

Please could you help me track this down by giving me the output of:

- `docker-machine -v`
- `docker version` (when you're using docker from the command line)
- `docker-machine env default`

These might yield some clues...

**Comment by zxkane** [comment]
I don't think I made tweaks on docker-machine.

Below is output of above commands,

> ➜  testcontainers-java-examples git:(master) docker-machine -v
> docker-machine version 0.5.2 ( 0456b9f )
> ➜  testcontainers-java-examples git:(master) docker version
> Client:
>  Version:      1.9.1
>  API version:  1.21
>  Go version:   go1.4.3
>  Git commit:   a34a1d5
>  Built:        Fri Nov 20 17:56:04 UTC 2015
>  OS/Arch:      darwin/amd64
> 
> Server:
>  Version:      1.9.1
>  API version:  1.21
>  Go version:   go1.4.3
>  Git commit:   a34a1d5
>  Built:        Fri Nov 20 17:56:04 UTC 2015
>  OS/Arch:      linux/amd64
> ➜  testcontainers-java-examples git:(master) docker-machine env default
> export DOCKER_TLS_VERIFY="1"
> export DOCKER_HOST="tcp://192.168.99.100:2376"
> export DOCKER_CERT_PATH="/Users/kane/.docker/machine/machines/default"
> export DOCKER_MACHINE_NAME="default"
> # Run this command to configure your shell: 
> # eval "$(docker-machine env default)"

A bit difference of running the test, I used IDE(eclipse 4.5) to run the test case.

**Comment by rnorth** [comment]
Thanks - that output looks correct, so this is a bit strange. I'll try and
release a milestone version (1.0.0.M1) this weekend which should address
the original issue described in this ticket and may (hopefully) address
what you're seeing to. It should at least provide a bit more debugging
information to help track it down.

Sorry you've been having trouble with this - I hope the update will help.

**Comment by rnorth** [comment]
Hi @ldcasillas-progreso, @zxkane 
I released a new version last night, which I hope goes some way towards improving the usefulness of the logging and documentation around docker daemon discovery. Please let me know if you have a chance to try again, and if things look better for you now.
Many thanks
Richard
