### ISSUE TITLE
'withNetworkMode()' method is not working for BrowserWebDriverContainer 

### ISSUE THREAD

**Issue by agafox** [testcontainers/testcontainers-java#533]
Hello,
Starting version 1.5.1 'withNetworkMode()' method is not working for BrowserWebDriverContainer.
Here is the gist with failing test:
https://gist.github.com/agafox/64d674032c699a4e7f1c70a9d7a48317

**Comment by agafox** [comment]
Here is the source of issue:

**Comment by bsideup** [comment]
Hi @agafox,

Thanks for reporting! Yes, it is an issue indeed. 

May I ask you about your `withNetworkMode` usecase btw?

**Comment by agafox** [comment]
Sure @bsideup. I'm using DockerComposeContainer with BrowserWebDriverContainer and looking for the way to land them on the same docker network.

**Comment by bsideup** [comment]
Hi @agafox,

I see. I'll fix it soon-ish, for now you can use a workaround:
```java
browser.withNetwork(
    new Network() {

        @Override
        public Statement apply(Statement base, Description description) {
            return base;
        }

        @Override
        public String getId() {
            return "host";
        }
    }
)
```

**Comment by agafox** [comment]
Awesome @bsideup,

**Comment by everflux** [comment]
Unfortunately the workaround does not work. The error message states:


```
com.github.dockerjava.api.exception.BadRequestException: {"message":"network-scoped alias is supported only for containers in user defined networks"}
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:99)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
```

**Comment by hhuangpen** [comment]
I wonder if it is fixed by now. I am trying to run this in pods for the ci pipeline. Since I am running testcontainer in dind, the BrowserWebDriverContainer needs to use host network driver so that I can at least access nodeport or clusterIp.

**Comment by kiview** [comment]
We did not touch this code yet.
