### ISSUE TITLE
Podman with Docker-compose not working

### ISSUE THREAD

**Issue by ssrikanthc** [testcontainers/testcontainers-java#5351]
Trying to get testcontainers work with Podman and Docker-compose in Fedora 35 OS to run tests on a custom Kafka cluster. Tried the following approaches but all of them are failing:

1st Approach:
@Container
private static final DockerComposeContainer kafka = new DockerComposeContainer(
	new File("src/test/resources/compose-test.yml")).withOptions("--compatibility")
	.withExposedService(KAFKA_SERVICE, KAFKA_PORT,
			Wait.forListeningPort().withStartupTimeout(Duration.ofSeconds(360)))
	.withLocalCompose(true);

This approach throws the below error "Link is not supported"
![image](https://user-images.githubusercontent.com/22582795/167110168-f82f11a8-7c9c-4dd0-916e-42ec29c2742e.png)

Seemingly related to the deprecated addLink method below:
![image](https://user-images.githubusercontent.com/22582795/167109213-e646b63a-eb00-444b-93b2-36b459e51207.png)

2nd Approach:
@Container
private static final DockerComposeContainer kafka = new DockerComposeContainer(
	new File("src/test/resources/compose-test.yml")).withOptions("--compatibility")
	.waitingFor(KAFKA_SERVICE, Wait.defaultWaitStrategy().withStartupTimeout(Duration.ofSeconds(360)))
	.withLocalCompose(true);

This approach simply throws a null pointer error:
![image](https://user-images.githubusercontent.com/22582795/167110734-7d1667c1-cd9a-48b3-9d45-c0b724197c8f.png)

3rd Approach:
@Container
	private static final DockerComposeContainer kafka = new DockerComposeContainer(
			new File("src/test/resources/compose-test.yml")).withOptions("--compatibility")
			.waitingFor(KAFKA_SERVICE, Wait.defaultWaitStrategy().withStartupTimeout(Duration.ofSeconds(360)));

This approach throws the below error:
![image](https://user-images.githubusercontent.com/22582795/167111361-5aff74e9-2b44-427c-b1dc-25312aa4c0d5.png)
![image](https://user-images.githubusercontent.com/22582795/167111477-5e9337aa-267a-4517-a085-6c54850c2792.png)
But, the file in the error has Read/Write/Execute permissions for all users.

**Comment by kiview** [comment]
Would you expect that Podman works together with Docker Compose outside of Testcontainers? Can you give a CLI example of how Podman can work with Docker Compose?

**Comment by ssrikanthc** [comment]
@kiview, thanks for your response. I am using the below CLI commands to make Podman work with Docker-compose
sudo systemctl enable podman.socket
sudo systemctl start podman.socket
sudo systemctl status podman.socket

##or##

systemctl --user enable podman.socket
systemctl --user start podman.socket
systemctl --user status podman.socket
export DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock

Reference:
https://fedoramagazine.org/use-docker-compose-with-podman-to-orchestrate-containers-on-fedora/
https://www.redhat.com/sysadmin/podman-docker-compose

**Comment by bjconlan** [comment]
I'm seeing better behaviour than this on podman 4.3.1 (rootless).

To note im using [docker-compose](https://github.com/docker/compose/releases/tag/v2.12.2) against podman (not sure if testcontainers invoke against this executable or in isolation).

But im seeing issue surrounding socat initialisation: 

> `11:38:09.386 [main] INFO  🐳 [docker-compose] - Docker Compose has finished running
11:38:09.530 [main] INFO  🐳 [alpine/socat:1.7.4.3-r0] - Creating container for image: alpine/socat:1.7.4.3-r0
11:38:09.741 [main] ERROR 🐳 [alpine/socat:1.7.4.3-r0] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Aborting attempt to link to container 2t1bdw4yyjmb_formio.mock_1 as it is not running`

It looks like there is already an [issue for this problem](https://github.com/testcontainers/testcontainers-java/issues/2981). But i suspect it also might be due to the slirp networking functionality.

**Comment by chenlin2001** [comment]
Hi, Is there an update on this issue? We are facing similar problems after moving from docker desktop to podman.
Using DockerComposeContainer with testcontainers version 1.17.6 we get the following error:
`[10] Failed to execute script docker-compose
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
PermissionError: [Errno 13] Permission denied`
Upgrading to version 1.19.0 using DockerComposecontainer fails on out of heap memory as described in: https://github.com/testcontainers/testcontainers-java/issues/7239
Tried using ComposeContainer with version 1.19.0 and localmode in order to avoid the heap issues and facing the issue of Link is not supported.

Podman compose without testcontainers work on that docker-compose.yaml

**Comment by jfrantzius** [comment]
Hi @chenlin2001 , I'm not sure I had the same error, but concerning Permission denied errors you might want to have a look at https://gist.github.com/jfrantzius/0996e224cbe81d885553ece6f8abf99a#status-500-lsetxattr-varrundockersock-operation-not-permitted

**Comment by ben-gineer** [comment]
We're still seeing this with latest TestContainers (1.20.4), local docker-compose, and `ComposeContainer` (for v2 support). Tried with and without `withExposedServices`.

Be great to know how people are managing this?

**Comment by MajerMartin** [comment]
We were using Testcontainers for Scala, which obviously shares the same issue. We have tried every suggested option on GitHub but unfortunately had to get rid of Testcontainers in the end. However we were not using any advanced features of Testcontainers, so we could easily switch to manual startup and teardown using `docker compose` commands.

```scala
override def beforeAll(): Unit = {
  system.log.info("Starting services...")
  "docker compose up -d".!
}

override def afterAll(): Unit = {
  system.log.info("Shutting down actor system...")
  Await.result(system.terminate(), DefaultTimeout)

  system.log.info("Stopping services...")
  "docker compose down".!
 }
```

**Comment by alersrt** [comment]
Any updates with deprecated `link is not supported`? Now I'm using random port mapping in compose and retrieve mapped port via `docker compose -p xxx port xxx xxx` but it has some limitations.

**Comment by frankjkelly** [comment]
Also seeing this after the switchover to podman.

I tried the instructions here to no avail
https://podman-desktop.io/tutorial/testcontainers-with-podman

Running podman in`--rootful` state

**Comment by frankjkelly** [comment]
FYI I tried switching to Orbstack and ALSO seeing this.
Also using `ComposeContainer` and `withLocalCompose(true)`.

NOTE: We can use Podman and OrbStack fine with Golang Test containers and docker compose based tests so can't really blame this on the docker service provider software.

**Comment by frankjkelly** [comment]
FYI a suggestion from @eddumelendez [here in slack](https://testcontainers.slack.com/archives/C04RM836XUP/p1750168568637179?thread_ts=1750167532.127389&cid=C04RM836XUP) 

```
Docker compose in java use linked containers, which it has been deprecated in Docker but AFAIK Podman 
doesn't use it and that's why it fails. I guess is similar for Orbstack
```

**Comment by ben-gineer** [comment]
I see the related issue is still open: https://github.com/testcontainers/testcontainers-java/issues/465

It talks about using networks instead of linked containers. Would love to see how this could be modified for Podman support. Right now, this issue is a deal-breaker for switching to Podman - and perhaps this is deliberate now Docker owns Testcontainers!

**Comment by frankjkelly** [comment]
What's odd is we can use Docker Compose tests in Golang no problem with Podman and Orbstack. Java Testcontainers seems to be the only exception.

**Comment by kiview** [comment]
@frankjkelly That's because tc-go directly uses Compose as a dependency in code, while tc-java relies on running the Compose binary in a container.
