### ISSUE TITLE
Potential issues when pulling Elasticsearch image

### ISSUE THREAD

**Issue by swift0303** [testcontainers/testcontainers-java#5362]
Hi everyone,
Could you help me here? My code can not load the testcontainer properties under the src/test/rescourse in CI docker maven enviroment.

But I can run it in local by  Windows: C:/Users/myuser/.testcontainers.properties.

As we know, we can config our parameters follow below three ways.
1. Environment variables
2. .testcontainers.properties in user's home folder. Example locations:
   Linux: /home/myuser/.testcontainers.properties
  Windows: C:/Users/myuser/.testcontainers.properties
  macOS: /Users/myuser/.testcontainers.properties
3. testcontainers.properties on the classpath.

Because the CI machine, so I config it on the classpath (src/test/resources/*)
![image](https://user-images.githubusercontent.com/23657657/168038738-92f22db4-9cca-419a-a577-0e171dde8f2b.png)

`public class ElasticInitializer
		implements ApplicationContextInitializer<ConfigurableApplicationContext> {
	@ClassRule
	public static ElasticsearchContainer container = new ElasticsearchContainer();

	/**
	 * @param applicationContext
	 */
	@Override
	public void initialize(ConfigurableApplicationContext applicationContext) {
		container.start();
		TestPropertyValues.of("elasticsearch.host=" + container.getHost(),
						"elasticsearch.port=" + container.getMappedPort(9200))
				.applyTo(applicationContext);
	}
}

@Testcontainers
@SpringBootTest
@ActiveProfiles(profiles = {"test"})
@ContextConfiguration(initializers = {ElasticInitializer.class})
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class PMBServiceImplTest {
}`
 

`16:48:42  08:48:42.863 [main] DEBUG org.springframework.test.context.support.AbstractDirtiesContextTestExecutionListener - Before test class: context [DefaultTestContext@49872d67 testClass = PMWHServiceImplTest, testInstance = [null], testMethod = [null], testException = [null], mergedContextConfiguration = [WebMergedContextConfiguration@56303b57 testClass = PMWHServiceImplTest, locations = '{}', classes = '{class com....MetaApplication}', contextInitializerClasses = '[class .....impl.ElasticInitializer]', activeProfiles = '{test}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@338fc1d8, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@55cb6996, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@dc7df28, org.springframework.boot.test.autoconfigure.actuate.metrics.MetricsExportContextCustomizerFactory$DisableMetricExportContextCustomizer@60f00693, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@7eecb5b8, org.springframework.boot.test.context.SpringBootTestArgs@1, org.springframework.boot.test.context.SpringBootTestWebEnvironment@448ff1a8], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map['org.springframework.test.context.web.ServletTestExecutionListener.activateListener' -> true]], class annotated with @DirtiesContext [false] with mode [null].
16:48:42  08:48:42.925 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/root/.testcontainers.properties
16:48:42  08:48:42.940 [main] WARN org.testcontainers.utility.TestcontainersConfiguration - Attempted to read Testcontainers configuration file at file:/root/.testcontainers.properties but the file was not found. Exception message: FileNotFoundException: /root/.testcontainers.properties (No such file or directory)
16:48:42  08:48:42.944 [main] INFO org.testcontainers.utility.ImageNameSubstitutor - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
16:48:43  08:48:42.952 [main] DEBUG org.testcontainers.utility.PrefixingImageNameSubstitutor - No prefix is configured
16:48:43  08:48:42.952 [main] DEBUG org.testcontainers.utility.ImageNameSubstitutor - Did not find a substitute image for docker.elastic.co/elasticsearch/elasticsearch:7.9.2 (using image substitutor: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor'))
16:48:43  08:48:42.969 [main] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - $XDG_RUNTIME_DIR is not set.
16:48:43  08:48:42.969 [main] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - '/root/.docker/run' does not exist.
16:48:43  08:48:42.999 [main] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - '/run/user/0' does not exist.
16:48:43  08:48:42.999 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - Trying out strategy: UnixSocketClientProviderStrategy
16:48:43  08:48:43.001 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (Could not find unix domain socket). Root cause NoSuchFileException (/var/run/docker.sock)
16:48:43  08:48:43.003 [main] INFO org.testcontainers.dockerclient.DockerMachineClientProviderStrategy - docker-machine executable was not found on PATH ([/opt/java/openjdk/bin, /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /opt/apache-maven/bin])
16:48:43  08:48:43.003 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
16:48:43  08:48:43.003 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy -     UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (Could not find unix domain socket). Root cause NoSuchFileException (/var/run/docker.sock)
16:48:43  08:48:43.004 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - As no valid configuration was found, execution cannot continue
16:48:43  08:48:43.004 [main] DEBUG org.testcontainers.utility.PrefixingImageNameSubstitutor - No prefix is configured
16:48:43  08:48:43.004 [main] DEBUG org.testcontainers.utility.ImageNameSubstitutor - Did not find a substitute image for docker.elastic.co/elasticsearch/elasticsearch:7.9.2 (using image substitutor: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor'))
16:48:43  08:48:43.007 [main] ERROR org.springframework.test.context.TestContextManager - Caught exception while allowing TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener@4b45dcb8] to prepare test instance [.......dao.impl.PMWHServiceImplTest@3d08f3f5]
16:48:43  java.lang.IllegalStateException: Failed to load ApplicationContext`

**Comment by eddumelendez** [comment]
Hi @swift0303 

According to the [docs](https://github.com/testcontainers/testcontainers-java/blob/17407eff6ef3343ee0c2d52e9306d40708909c43/core/src/main/java/org/testcontainers/utility/TestcontainersConfiguration.java#L31-L43)

- A file in the user's home directory named `.testcontainers.properties`
- A file in the classpath named `testcontainers.properties`
- Environment variables

I see the file at `src/test/resources` is `.testcontainers.properties` instead of just `testcontainers.properties`

**Comment by swift0303** [comment]
Hi @eddumelendez ,
Thanks for your help!
Now I has change it use testcontainers.properties.
It still shows   "**Could not find a valid Docker environment** ". 

testcontainers.properties
`docker.client.strategy=org.testcontainers.dockerclient.UnixSocketClientProviderStrategy
docker.host=tcp://127.0.0.1:2375`

`10:45:45  02:45:45.320 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/home/jenkins/workspace/service-gerrit-verify/service/target/test-classes/testcontainers.properties
10:45:45  02:45:45.321 [main] INFO org.testcontainers.utility.ImageNameSubstitutor - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
10:45:45  02:45:45.332 [main] DEBUG org.testcontainers.utility.PrefixingImageNameSubstitutor - No prefix is configured
10:45:45  02:45:45.332 [main] DEBUG org.testcontainers.utility.ImageNameSubstitutor - Did not find a substitute image for docker.elastic.co/elasticsearch/elasticsearch:7.9.2 (using image substitutor: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor'))
10:45:45  02:45:45.349 [main] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - $XDG_RUNTIME_DIR is not set.
10:45:45  02:45:45.349 [main] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - '/root/.docker/run' does not exist.
10:45:45  02:45:45.383 [main] DEBUG org.testcontainers.dockerclient.RootlessDockerClientProviderStrategy - '/run/user/0' does not exist.
10:45:45  02:45:45.383 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - Trying out strategy: UnixSocketClientProviderStrategy
10:45:45  02:45:45.385 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (Could not find unix domain socket). Root cause NoSuchFileException (/var/run/docker.sock)
10:45:45  02:45:45.387 [main] INFO org.testcontainers.dockerclient.DockerMachineClientProviderStrategy - docker-machine executable was not found on PATH ([/opt/java/openjdk/bin, /usr/local/sbin, /usr/local/bin, /usr/sbin, /usr/bin, /sbin, /bin, /opt/apache-maven/bin])
10:45:45  02:45:45.387 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
10:45:45  02:45:45.387 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy -     UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (Could not find unix domain socket). Root cause NoSuchFileException (/var/run/docker.sock)
10:45:45  02:45:45.387 [main] ERROR org.testcontainers.dockerclient.DockerClientProviderStrategy - As no valid configuration was found, execution cannot continue`

**Comment by kiview** [comment]
@swift0303 
Can you please make sure the following simple example project works in all of your environments?
https://github.com/testcontainers/testcontainers-java-repro

**Comment by swift0303** [comment]
> which tc version are you using? running `docker pull docker.elastic.co/elasticsearch/elasticsearch:7.9.2` works for you?

Hi @eddumelendez,
My tc version is 1.16.3. 

Besides, Actually I set the elasticsearch version with 7.12.1 in pom.xml. But the log show it tried to search 7.9.2.

`15:50:44  07:50:43.418 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/root/.testcontainers.properties
15:50:44  07:50:43.432 [main] WARN org.testcontainers.utility.TestcontainersConfiguration - Attempted to read Testcontainers configuration file at file:/root/.testcontainers.properties but the file was not found. Exception message: FileNotFoundException: /root/.testcontainers.properties (No such file or directory)
15:50:44  07:50:43.435 [main] INFO org.testcontainers.utility.ImageNameSubstitutor - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
15:50:44  07:50:43.448 [main] DEBUG org.testcontainers.utility.PrefixingImageNameSubstitutor - No prefix is configured
15:50:44  07:50:43.448 [main] DEBUG org.testcontainers.utility.ImageNameSubstitutor - Did not find a substitute image for docker.elastic.co/elasticsearch/elasticsearch:7.9.2 (using image substitutor: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor'))
15:50:44  07:50:43.468 [main] INFO org.testcontainers.dockerclient.DockerClientProviderStrategy - Loaded org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
15:50:44  07:50:43.470 [main] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - Trying out strategy: EnvironmentAndSystemPropertyClientProviderStrategy
15:50:44  07:50:43.841 [ducttape-0] DEBUG org.testcontainers.dockerclient.DockerClientProviderStrategy - Pinging docker daemon...
15:50:44  07:50:43.882 [ducttape-0] DEBUG org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: 
15:50:44  07:50:43.903 [ducttape-0] DEBUG com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.InternalHttpClient - ex-00000001: preparing request execution
15:50:44  07:50:43.909 [ducttape-0] DEBUG com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.protocol.RequestAddCookies - Cookie spec selected: strict
15:50:44  07:50:43.914 [ducttape-0] DEBUG com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.protocol.RequestAuthCache - Auth cache not set in the context
15:50:44  07:50:43.914 [ducttape-0] DEBUG com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ProtocolExec - ex-00000001: target auth state: UNCHALLENGED
15:50:44  07:50:43.915 [ducttape-0] DEBUG com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ProtocolExec - ex-00000001: proxy auth state: UNCHALLENGED
15:50:44  07:50:43.915 [ducttape-0] DEBUG com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.ConnectExec - ex-00000001: acquiring connection with route {}->http://127.0.0.1:2375/`

**Comment by eddumelendez** [comment]
@swift0303 please, you can check [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) how to properly format the code

If you are calling `ElasticsearchContainer()` then the default tag used is `7.9.2` as you can see [here](https://github.com/testcontainers/testcontainers-java/blob/master/modules/elasticsearch/src/main/java/org/testcontainers/elasticsearch/ElasticsearchContainer.java#L57)

**Comment by swift0303** [comment]
Hi @eddumelendez ,
Sure, I checked my code. 
1. If I use the default constructor, it will use the 7.9.2 . But it will load the image from https://registry-1.docker.io/v2/ .  The error likes this.
`10:58:46  02:58:46.476 [docker-java-stream--1007472360] ERROR com.github.dockerjava.api.async.ResultCallbackTemplate - Error during callback
10:58:46  com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}`
2. If I change it to use the internal image name, it shows the other error.
`10:53:01  Caused by: java.lang.IllegalStateException: Failed to verify that image 'registry1-docker-io.repo.lab.pl.alcatel-lucent.com/elasticsearch:latest' is a compatible substitute for 'docker.elastic.co/elasticsearch/elasticsearch'. This generally means that you are trying to use an image that Testcontainers has not been designed to use. If this is deliberate, and if you are confident that the image is compatible, you should declare compatibility in code using the `asCompatibleSubstituteFor` method. For example:
10:53:01     DockerImageName myImage = DockerImageName.parse("registry1-docker-io.repo.lab.pl.alcatel-lucent.com/elasticsearch:latest").asCompatibleSubstituteFor("docker.elastic.co/elasticsearch/elasticsearch");
10:53:01  and then use `myImage` instead.
10:53:01  	at org.testcontainers.utility.DockerImageName.assertCompatibleWith(DockerImageName.java:248)
10:53:01  	at org.testcontainers.elasticsearch.ElasticsearchContainer.<init>(ElasticsearchContainer.java:67)
10:53:01  	at org.testcontainers.elasticsearch.ElasticsearchContainer.<init>(ElasticsearchContainer.java:57)
10:53:01  	at **.db.dao.impl.ElasticInitializer.<clinit>(ElasticInitializer.java:12)
10:53:01  	... 82 common frames omitted`

Below is my initial code.


ElasticInitializer.java
`public class ElasticInitializer
		implements ApplicationContextInitializer<ConfigurableApplicationContext> {
	@ClassRule
	// public static ElasticsearchContainer container = new ElasticsearchContainer();
public static ElasticsearchContainer container = new ElasticsearchContainer("internal.repo.com: elasticsearch:latest");

	/**
	 * @param applicationContext
	 */
	@Override
	public void initialize(ConfigurableApplicationContext applicationContext) {
		container.start();
		TestPropertyValues.of("elasticsearch.host=" + container.getHost(),
						"elasticsearch.port=" + container.getMappedPort(9200))
				.applyTo(applicationContext);
	}
}`

*Test.java
`@Testcontainers
@SpringBootTest
@ActiveProfiles(profiles = {"test"})
@ContextConfiguration(initializers = {ElasticInitializer.class})
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class **ServiceImplTest {...}`

**Comment by eddumelendez** [comment]
For the second case you should use something like this

```
private static DockerImageName IMAGE = DockerImageName.parse("internal.repo.com.com/elasticsearch:latest")
            .asCompatibleSubstituteFor("docker.elastic.co/elasticsearch/elasticsearch");
```

as mentioned by the exception message you just shared

**Comment by kiview** [comment]
I don't think `repo.*.net/elasticsearch:7.8.0` is supposed to be the name of the image you want to use. Also please note, that Elasticsearch does not publish images with `latest` tag, as per [their documentation](https://hub.docker.com/_/elasticsearch):

> Note: Pulling an images requires using a specific version number tag. The latest tag is not supported.

As said before, please ensure the following basic Testcontainers example is working on your machine, so we have an easier time triaging your issue:
https://github.com/testcontainers/testcontainers-java-repro

**Comment by eddumelendez** [comment]
@swift0303 any news on this? Please join our [slack](https://slack.testcontainers.org/) channel and continue the conversation right there

**Comment by eddumelendez** [comment]
Closing this because of lack of activity. @swift0303 feel free to reopen it with more info or join slack channel.
