### ISSUE TITLE
Mapped port polling on container startup causes race conditions with containers that terminate on startup

### ISSUE THREAD

**Issue by davidmc24** [testcontainers/testcontainers-java#5385]
It appears that https://github.com/testcontainers/testcontainers-java/pull/4263 introduced some flakiness in a subset of our tests.  In particular, we have a few tests that test failure conditions for a container.  In those tests, we either override `waitUntilContainerStarted` to check for a special log message or use a `OneShotStartupCheckStrategy` to detect when the desired state has been achieved.  However, after upgrading to a version of TestContainers that includes the PR above (in this case, from 1.15.3 to 1.17.1), we started occasionally getting failures like this:

```
...
Caused by: org.testcontainers.shaded.org.awaitility.core.ConditionTimeoutException: Lambda expression in org.testcontainers.containers.GenericContainer: expected the predicate to return <true> but it returned <false> for input of ...
	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)
	at org.testcontainers.shaded.org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:691)
	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:708)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:450)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:340)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:338)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:326)
...
```

My belief is that, when it fails, the container terminates in between polling attempts, causing the `until` block to never succeed. 
 My expectation would be that the block to detect mapped ports should not throw an exception in this case.

**Comment by vsuharnikov** [comment]
I had a bug with the same error. But in my case docker didn't bind container ports even I wrote `.withExposedPorts`. The cause was in a custom `withHostConfig` in `withCreateContainerCmdModifier`. The issue has gone when I deleted the custom host config.
