### ISSUE TITLE
With v1.17.2 NoClassDefFoundError org/testcontainers/shaded/org/apache/commons/lang/StringUtils

### ISSUE THREAD

**Issue by sytolk** [testcontainers/testcontainers-java#5396]
With some test it's have NoClassDefFoundError only with v1.17.2 If I downgrade to 1.16.3 test works.

```
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.lang.NoClassDefFoundError: org/testcontainers/shaded/org/apache/commons/lang/StringUtils
org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.lang.NoClassDefFoundError: org/testcontainers/shaded/org/apache/commons/lang/StringUtils
	at app//org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:309)
	at app//org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
	at app//org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
	at app//org.springframework.test.context.transaction.TransactionContext.startTransaction(TransactionContext.java:103)
	at app//org.springframework.test.context.transaction.TransactionalTestExecutionListener.beforeTestMethod(TransactionalTestExecutionListener.java:231)
	at app//org.springframework.test.context.TestContextManager.beforeTestMethod(TestContextManager.java:293)
	at app//org.springframework.test.context.junit.jupiter.SpringExtension.beforeEach(SpringExtension.java:174)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeEachCallbacks$2(TestMethodTestDescriptor.java:163)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeMethodsOrCallbacksUntilExceptionOccurs$6(TestMethodTestDescriptor.java:199)
	at app//org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:199)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachCallbacks(TestMethodTestDescriptor.java:162)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:129)
	at app//org.junit.jupiter.engine.descriptor.TestMethodTest
```

**Comment by bsideup** [comment]
@https://github.com/sytolk please make sure that all your Testcontainers dependencies are using 1.17.2 or higher. The easiest way to do it is to use the BOM:
```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>testcontainers-bom</artifactId>
            <version>1.17.2</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

**Comment by sytolk** [comment]
yes all testcontainers use the same version maybe the problem is with zonky
```Gradle
testImplementation("org.testcontainers:mssqlserver:${testcontainersVersion}")
    testImplementation("org.testcontainers:mysql:${testcontainersVersion}")
    testImplementation("org.testcontainers:postgresql:${testcontainersVersion}")
    testImplementation("org.testcontainers:junit-jupiter:${testcontainersVersion}")

    testImplementation("io.zonky.test:embedded-database-spring-test:2.1.1")
    testImplementation("io.zonky.test:embedded-postgres:1.3.1")
```

**Comment by kiview** [comment]
Zonky seems to use old Testcontainers dependencies:
https://github.com/zonkyio/embedded-database-spring-test/blob/master/build.gradle#L219

**Comment by sytolk** [comment]
https://github.com/zonkyio/embedded-database-spring-test/issues/196
