### ISSUE TITLE
Cannot use Clickhouse's grpc  for mac Apple silicon

### ISSUE THREAD

**Issue by SusurHe** [testcontainers/testcontainers-java#5483]
when i use the docker image of new version clickhouse, i can't use grpc; 
I think it's because testcontainers pulled the arm64 docker image for me by default, but clickhouse does not support grpc on arm64 (https://github.com/ClickHouse/ClickHouse/pull/36754);

how can i option platform with "linux/amd64" when i use testcontainers to pull docker image;

**if it can't do it, is it better to have a 'platform' configuration?**

```
18:12:46.179 DEBUG xenon.clickhouse.grpc.GrpcNodeClient: Execute ClickHouse SQL [5d3e6020-0d0f-4298-bd78-85c856445961]:
SELECT 1

- clickhouse command runner *** FAILED *** (2 seconds, 857 milliseconds)
  xenon.relocated.io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
  at xenon.relocated.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
  at xenon.relocated.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
  at xenon.relocated.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
  at xenon.protocol.grpc.ClickHouseGrpc$ClickHouseBlockingStub.executeQuery(ClickHouseGrpc.java:316)
  at xenon.clickhouse.grpc.GrpcNodeClient.executeQuery(GrpcNodeClient.scala:172)
  at xenon.clickhouse.grpc.GrpcNodeClient.syncQuery(GrpcNodeClient.scala:155)
  at xenon.clickhouse.grpc.GrpcNodeClient.syncQueryAndCheck(GrpcNodeClient.scala:163)
  at xenon.clickhouse.grpc.GrpcNodeClient.syncQueryAndCheckOutputJSONEachRow(GrpcNodeClient.scala:97)
  at xenon.clickhouse.ClickHouseCatalog.initialize(ClickHouseCatalog.scala:68)
  at org.apache.spark.sql.connector.catalog.Catalogs$.load(Catalogs.scala:60)
  ...

```

Thanks;

**Comment by eddumelendez** [comment]
Hi @SusurHe, there is no arm image provided by clickhouse as you can see [here](https://hub.docker.com/r/yandex/clickhouse-server/tags?page=1), so the amd64 image is the one downloaded. The issue as you just point is that clickhouse image is not able to run on arm. There are other similar issues with other container images.

**Comment by SusurHe** [comment]
i need to use the new version of clickhouse image (clickhouse/clickhouse), it has arm image, but it does not support grpc
