### ISSUE TITLE
org.testcontainers.shaded.com.fasterxml.jackson.databind.JsonMappingException

### ISSUE THREAD

**Issue by maciekc** [testcontainers/testcontainers-java#5496]
Java 11
Testcontainers 1.17.2

I get the following exception running Testcontainers using Gitlab CI pipelines
```
Exception in thread "Thread-4" java.lang.RuntimeException: org.testcontainers.shaded.com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.EmptyInputStream@290d6094; line: 1, column: 0]
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:128)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.PruneCmdExec.execute(PruneCmdExec.java:33)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.PruneCmdExec.execute(PruneCmdExec.java:13)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.PruneCmdImpl.exec(PruneCmdImpl.java:100)
	at org.testcontainers.utility.JVMHookResourceReaper.prune(JVMHookResourceReaper.java:53)
	at org.testcontainers.utility.JVMHookResourceReaper.lambda$performCleanup$2(JVMHookResourceReaper.java:27)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testcontainers.utility.JVMHookResourceReaper.performCleanup(JVMHookResourceReaper.java:27)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.testcontainers.shaded.com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.EmptyInputStream@290d6094; line: 1, column: 0]
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3838)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2915)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:125)
	... 10 more
```
This error occurs only with Gitlab (with Kubernetes), not on localhost.
Gitlab config
```
check:
  <<: *gradle_job
  stage: test
  tags: [k8s]
  # Kubedock service is required for Testcontainers: it's the bridge between DinD and K8S
  services:
    - name: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/joyrex2001/kubedock:0.8.2
      alias: docker
      command: ["server", "start", "--reverse-proxy"]
  variables:
    # Instruct Testcontainers to use the daemon of DinD.
    DOCKER_HOST: "tcp://docker:2475"
    # Configure Testcontainers
    TESTCONTAINERS_CHECKS_DISABLE: "true"
    # kubedock has own container cleaning https://www.testcontainers.org/features/configuration/#disabling-ryuk
    TESTCONTAINERS_RYUK_DISABLED: "true"
```

**Comment by bsideup** [comment]
> ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/joyrex2001/kubedock:0.8.2

I see that you are using `kubedock`. Please report your issue to them, as it seems to be a bug there (this cannot be reproduced with "normal" Docker).

**Comment by wuservices** [comment]
@maciekc Did you ever find any solution? I just started using `kubedock` and noticed this too, but didn't see any related issues posted there yet. Maybe `kubedock` doesn't like being asked to delete the volumes. Since it cleans up anyways and this error happens on JVM shutdown, it's more of an annoyance and everything (that matters) appears to work despite the error.
