### ISSUE TITLE
I have new versions for the jersey client in my project due to other dependency

### ISSUE THREAD

**Issue by paul8620** [testcontainers/testcontainers-java#55]
This are my unsatisfied list of dependecies
 
         
         
         
         
         
            
               
               
            
            
               
               
            
            
               
               
            
            
               
               
            
            
               
               
            
            
               
               
            
         
      

After excluding this i have 
`15:31:15.126 WARN  [o.t.DockerClientFactory] Encountered and ignored error while checking disk space 
javax.ws.rs.ProcessingException: com.fasterxml.jackson.databind.ObjectWriter.getJsonFactory()Lcom/fasterxml/jackson/core/JsonFactory;
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:264) ~[jersey-client-2.22.1.jar:na]
        at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:700) ~[jersey-client-2.22.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.22.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.22.1.jar:na]
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[jersey-common-2.22.1.jar:na]
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444) ~[jersey-common-2.22.1.jar:na]
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:696) ~[jersey-client-2.22.1.jar:na]
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448) ~[jersey-client-2.22.1.jar:na]
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349) ~[jersey-client-2.22.1.jar:na]
        at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:32) ~[docker-java-2.1.1.jar:na]
        at com.github.dockerjava.jaxrs.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:14) ~[docker-java-2.1.1.jar:na]
        at com.github.dockerjava.jaxrs.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:24) ~[docker-java-2.1.1.jar:na]
        at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33) ~[docker-java-2.1.1.jar:na]
        at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:143) ~[docker-java-2.1.1.jar:na]
        at org.testcontainers.DockerClientFactory.checkDiskSpace(DockerClientFactory.java:193) [testcontainers-0.9.9.jar:na]
        at org.testcontainers.DockerClientFactory.checkDiskSpaceAndHandleExceptions(DockerClientFactory.java:173) [testcontainers-0.9.9.jar:na]
        at org.testcontainers.DockerClientFactory.<init>(DockerClientFactory.java:47) [testcontainers-0.9.9.jar:na]
        at org.testcontainers.DockerClientFactory.instance(DockerClientFactory.java:60) [testcontainers-0.9.9.jar:na]
        at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:72) [testcontainers-0.9.9.jar:na]
        at com.videoplaza.forecast.common.DockerSteps.aDockerComposeContainerConfiguration(DockerSteps.java:22) [test-classes/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
        at cucumber.runtime.Utils$1.call(Utils.java:37) [cucumber-core-1.2.4.jar:na]
        at cucumber.runtime.Timeout.timeout(Timeout.java:13) [cucumber-core-1.2.4.jar:na]
        at cucumber.runtime.Utils.invoke(Utils.java:31) [cucumber-core-1.2.4.jar:na]
        at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:38) [cucumber-java-1.2.4.jar:na]
        at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:37) [cucumber-core-1.2.4.jar:na]
        at cucumber.runtime.Runtime.runStep(Runtime.java:299) [cucumber-core-1.2.4.jar:na]
        at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44) [cucumber-core-1.2.4.jar:na]
        at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39) [cucumber-core-1.2.4.jar:na]
        at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44) [cucumber-core-1.2.4.jar:na]
        at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91) [cucumber-junit-1.2.4.jar:na]
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63) [cucumber-junit-1.2.4.jar:na]
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18) [cucumber-junit-1.2.4.jar:na]
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70) [cucumber-junit-1.2.4.jar:na]
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:97) [rmtest-cucumber-2.0.7.jar:na]
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:42) [rmtest-cucumber-2.0.7.jar:na]
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
        at cucumber.api.junit.Cucumber.run(Cucumber.java:102) [rmtest-cucumber-2.0.7.jar:na]
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283) [surefire-junit4-2.18.1.jar:2.18.1]
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173) [surefire-junit4-2.18.1.jar:2.18.1]
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.18.1.jar:2.18.1]
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128) [surefire-junit4-2.18.1.jar:2.18.1]
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203) [surefire-booter-2.18.1.jar:2.18.1]
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155) [surefire-booter-2.18.1.jar:2.18.1]
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.18.1.jar:2.18.1]
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ObjectWriter.getJsonFactory()Lcom/fasterxml/jackson/core/JsonFactory;
        at com.fasterxml.jackson.jaxrs.json.annotation.EndpointConfig.initWriter(EndpointConfig.java:159) ~[jackson-jaxrs-json-provider-2.1.2.jar:2.1.2]
        at com.fasterxml.jackson.jaxrs.json.annotation.EndpointConfig.forWriting(EndpointConfig.java:63) ~[jackson-jaxrs-json-provider-2.1.2.jar:2.1.2]
        at com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider.writeTo(JacksonJsonProvider.java:531) ~[jackson-jaxrs-json-provider-2.1.2.jar:2.1.2]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265) ~[jersey-common-2.22.1.jar:na]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250) ~[jersey-common-2.22.1.jar:na]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162) ~[jersey-common-2.22.1.jar:na]
        at com.github.dockerjava.jaxrs.filter.LoggingFilter.aroundWriteTo(LoggingFilter.java:301) ~[docker-java-2.1.1.jar:na]
        at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162) ~[jersey-common-2.22.1.jar:na]
        at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130) ~[jersey-common-2.22.1.jar:na]
        at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:502) ~[jersey-client-2.22.1.jar:na]
        at com.github.dockerjava.jaxrs.connector.ApacheConnector$2.writeTo(ApacheConnector.java:578) ~[docker-java-2.1.1.jar:na]
        at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:123) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:158) ~[httpcore-4.4.3.jar:4.4.3]
        at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:237) ~[httpcore-4.4.3.jar:4.4.3]
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:122) ~[httpcore-4.4.3.jar:4.4.3]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71) ~[httpclient-4.5.1.jar:4.5.1]
        at com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:443) ~[docker-java-2.1.1.jar:na]
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255) ~[jersey-client-2.22.1.jar:na]
        ... 58 common frames omitted
`

**Comment by rnorth** [comment]
Hi Paul
Sorry for my slow response. I hope this kind of issue should be fixed in the pending 1.0.0 release - this is the same as #35, which I've just reopened.
Thanks
Richard

**Comment by rnorth** [comment]
Hi @paul8620 
I released a new version last night, which I hope fixes this kind of issue. Please let me know if you have a chance to retry and if this makes things better for you.
Thanks

Richard

**Comment by paul8620** [comment]
@rnorth thanks a lot
