### ISSUE TITLE
Cannot pull from private repo

### ISSUE THREAD

**Issue by iNikem** [testcontainers/testcontainers-java#567]
I use an image from private repository: `new FixedHostPortGenericContainer('plumbr-dockerv2-local.jfrog.io/kafka:latest')`. And it fails:

```
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image name from org.testcontainers.images.RemoteDockerImage@24ce9f81
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:856)
	at org.testcontainers.containers.GenericContainer.setDockerImageName(GenericContainer.java:844)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:170)
	at org.testcontainers.containers.FixedHostPortGenericContainer.<init>(FixedHostPortGenericContainer.java:16)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at eu.plumbr.archive.archivist.kafka.KafkaArchivistIntegrationTest.<clinit>(KafkaArchivistIntegrationTest.groovy:34)
	... 37 more
Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"unauthorized: The client does not have permission for manifest"}

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:109)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at org.testcontainers.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.testcontainers.shaded.io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.testcontainers.shaded.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at org.testcontainers.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at org.testcontainers.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at org.testcontainers.shaded.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.testcontainers.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.testcontainers.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at org.testcontainers.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at org.testcontainers.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at org.testcontainers.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at org.testcontainers.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at org.testcontainers.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at org.testcontainers.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at org.testcontainers.shaded.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 more
```

**Comment by iNikem** [comment]
With new 1.6.0 release

**Comment by iNikem** [comment]
Same problem with 1.5.1

**Comment by kiview** [comment]
Is this happening on OSX?

**Comment by iNikem** [comment]
Yes, OS X El Capitan, 10.11.6

**Comment by rnorth** [comment]
@iNikem without revealing any secrets, please could you share the rough content of your `~/docker/config.json` file? I'm curious as to which `credsStore` implementation you have active.

FWIW I've not had any trouble with the AWS ECR registry at work, and I think my work machine has the `osxkeychain` set as its `credsStore` type.

**Comment by iNikem** [comment]
Here it is.
```
{
  "auths" : {
    "https://plumbr-dockerv2-local.jfrog.io" : {

    },
    "plumbr-dockerv2-local.jfrog.io" : {

    }
  },
  "HttpHeaders" : {
    "User-Agent" : "Docker-Client/17.12.0-ce (darwin)"
  },
  "credsStore" : "osxkeychain"
}
```

I think it did work. Will try to investigate what broke :)

**Comment by rnorth** [comment]
Hi @iNikem, did you get to the bottom of this?

**Comment by iNikem** [comment]
Nope. Have not found any workarounds (apart from doing `docker pull` by hand prior the test) nor any actual root causes.

**Comment by rnorth** [comment]
We released support for docker credential helpers/store in [1.8.1](https://github.com/testcontainers/testcontainers-java/releases/tag/1.8.1)! 🎉

Please could you give this a try @iNikem?
