### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nikolashermann** [testcontainers/testcontainers-java#5768]
### Module

MongoDB

### Testcontainers version

1.17.3

### Using the latest Testcontainers version?

Yes

### Host OS

linux

### Host Arch

amd64

### Docker version

```shell
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        20.10.12-0ubuntu2~20.04.1
 Built:             Wed Apr  6 02:14:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.2
  Git commit:       20.10.12-0ubuntu2~20.04.1
  Built:            Thu Feb 10 15:03:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu1~20.04.4
  GitCommit:        
 runc:
  Version:          1.1.0-0ubuntu1~20.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### What happened?

The official mongodb 6.0 docker image was released yesterday: https://hub.docker.com/_/mongo
The image can not be used with testcontainers, as there is mongo-executable within the PATH anymore: 
```
➜  ~ docker run mongo:6.0 mongo
/usr/local/bin/docker-entrypoint.sh: line 421: exec: mongo: not found
```
Testcontainers startup fails accordingly.

### Relevant log output

```shell
09:23:11.511 [testcontainers-lifecycle-0] ERROR org.testcontainers.containers.MongoDBContainer - An error occurred: OCI runtime exec failed: exec failed: unable to start container process: exec: "mongo": executable file not found in $PATH: unknown

09:23:11.511 [testcontainers-lifecycle-0] ERROR 🐳 [mongo:6.0] - Could not start container
org.testcontainers.containers.MongoDBContainer$ReplicaSetInitializationException: An error occurred: OCI runtime exec failed: exec failed: unable to start container process: exec: "mongo": executable file not found in $PATH: unknown

	at org.testcontainers.containers.MongoDBContainer.checkMongoNodeExitCode(MongoDBContainer.java:97)
	at org.testcontainers.containers.MongoDBContainer.initReplicaSet(MongoDBContainer.java:132)
	at org.testcontainers.containers.MongoDBContainer.containerIsStarted(MongoDBContainer.java:86)
	at org.testcontainers.containers.GenericContainer.containerIsStarted(GenericContainer.java:701)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:521)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by eddumelendez** [comment]
Thanks for raising the issue! This is not an issue in the image. See the [releases notes
](https://www.mongodb.com/docs/manual/release-notes/6.0-compatibility/#legacy-mongo-shell-removed) about MongoDB 6

It is not offered as you can see in the image below.

<img width="246" alt="Screen Shot 2022-08-25 at 9 25 45" src="https://user-images.githubusercontent.com/1810547/186706904-10c8be49-2333-4814-a825-6249bf2450c5.png">

We need to update the `MongoDBContainer` to use `mongosh` when image version is 6.0+

**Comment by bernermic** [comment]
related with [https://github.com/docker-library/mongo/issues/558](https://github.com/docker-library/mongo/issues/558)

**Comment by josebarroszeiss** [comment]
the above comment helps nobody
just tell me " use mongosh" it doesnt solve the problem, please next time try to add some example, there is no usable example how to make mongosh run togeter with testcontainers now, not even chatgpt knows how to do it

**Comment by kiview** [comment]
@josebarroszeiss This was already implemented as part of https://github.com/testcontainers/testcontainers-java/pull/5771. What is your actual issue at hand?
