### ISSUE TITLE
[Bug]: Localstack container does not start on Jenkins 

### ISSUE THREAD

**Issue by tiefenauer** [testcontainers/testcontainers-java#5869]
### Module

LocalStack

### Testcontainers version

1.17.3

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

X86

### Docker version

```shell
20.10.16
```

### What happened?

I am using Testcontainers' [Localstack Module](https://www.testcontainers.org/modules/localstack/) for advanced integration testing with Spring Boot, replacing the AmazonS3 client with the one from Localstack. I have set up my integration test roughly as follows (only relevant parts):

```kotlin
// FurnitureDetailsControllerIT.kt

@Testcontainers
@SpringBootTest
@ExtendWith(SpringExtension::class)
@AutoConfigureMockMvc
@DirtiesContext
class FurnitureDetailsControllerIT {

  @Autowired
  private val amazonS3: AmazonS3? = null

  
  companion object {
    @Container
    var localStack: LocalStackContainer =
      LocalStackContainer(DockerImageName.parse("localstack/localstack:latest")).withServices(LocalStackContainer.Service.S3)

    @JvmStatic
    @DynamicPropertySource
    fun properties(registry: DynamicPropertyRegistry) {
      registry.add("cloud.aws.s3.endpoint") { localStack.getEndpointOverride(LocalStackContainer.Service.S3) }
      registry.add("cloud.aws.credentials.access-key") { localStack.accessKey }
      registry.add("cloud.aws.credentials.secret-key") { localStack.secretKey }
    }
  }
(...)
}
```

Everything runs fine when running the integration test locally (from my IDE or command line using Maven), meaning I can see the localstack container spinning up in the logs:

```
13:54:16.360 [main] INFO 🐳 [remote-docker.artifactory.mycompany.com/localstack/localstack:0.13.0] - Container remote-docker.artifactory.mycompany.com/localstack/localstack:0.13.0 started in PT4.6099665S

```

However, when running on Jenkins, the build fails because of an error message.

```

2022-09-28 14:27:19.971  INFO 1185 --- [           main] ?.a.s.com/localstack/localstack:latest]  : Container remote-docker.artifactory.mycompany.com/localstack/localstack:latest is starting: ec383bda85f2636c3bef3f6b3938ac169636e4542244e3067b5184b6b03a6e35

2022-09-28 14:28:20.612 ERROR 1185 --- [           main] ?.a.s.com/localstack/localstack:latest]  : Could not start container

org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Ready\.
```

I guess it has to do with the temporary directory needed by Localstack. When running on my Windows machine I have to manually click on "Share It" before the test resumes:

[![Docker Desktop notification for file sharing (Windows)][1]][1]

I suppose since the test is failing on Jenkins (because I cannot click on "Share It" there) starting the container will eventually time out and the test will fail.

I read that you can configure the directory using the `TMPDIR` environment variable as described in https://docs.localstack.cloud/localstack/configuration/. But using that variable is deprecated. What is the best way to set the temp directory to Jenkins working directory without having to explicitly conset to sharing that directory?

Note: I am already using Testcontainers' [MongoBD module](https://www.testcontainers.org/modules/databases/mongodb/) successfully, which starts a dockerized MongoDB instance. That works flawlessly, so I am not sure if it's an issue with Testcontainers or Localstack.

  [1]: https://i.stack.imgur.com/O4Akk.png

### Additional Information

I have already tried playing around with various environment variables (for example to disable persistence or change the data directory) but nothing worked

**Comment by kiview** [comment]
Thanks for the detailed issue report @tiefenauer.

I don't think it is directly related to the Docker Desktop popup you shared, since this is something specific to Docker Desktop on Windows and I would assume your Jenkins is not running on Windows (you shared above that this is a Linux host). How is Docker installed and available on Jenkins? 

Our `LocalStackContainer` mounts the Docker socket, I could imagine this might be an issue on your Jenkins setup. I have to check with the other module maintainers why this is necessary (I am not very experienced with LocalStack).
https://github.com/testcontainers/testcontainers-java/blob/a9c2e9e148097f4996dc7a96f85fced1ee857ddc/modules/localstack/src/main/java/org/testcontainers/containers/localstack/LocalStackContainer.java#L97

For further debugging, I would suggest you try to start the LocalStack container directly using Docker in your Jenkins job and check if it comes up successfully:
```
docker run -v /var/run/docker.sock:/var/run/docker.sock localstack/localstack:latest
```

**Comment by tiefenauer** [comment]
We use Jenkins in a docker-in-docker (DIND) setup, so the agent running the build is a docker container itself. Unfortunately I don't have access to the Jenkins instance itself, so I cannot try out the docker command you provided.

**Comment by kiview** [comment]
I assume your setup will fail for the line I've linked above. The `LocalStackContainer` won't be available to mount the Docker socket. There is currently no easy way to disable this mount, besides copying the `LocalStackContainer` class into your own code and patching out the line. You can give it a try. 

I need to check in with @eddumelendez why mounting the Docker socket is necessary, maybe we can make it optional in the `LocalStackContainer` implementation.

**Comment by tiefenauer** [comment]
I just copied `LocalStackContainer.java` to my codebase and commented out line 97 (from above comment).
Still the same result:
```
2022-09-29 16:09:20.129  INFO 1287 --- [ream--609944143] ?.a.s.com/testcontainers/ryuk:0.3.3]     : Pull complete. 3 layers, pulled in 2s (downloaded 5 MB at 2 MB/s)

2022-09-29 16:09:20.133  INFO 1287 --- [           main] ?.a.s.com/testcontainers/ryuk:0.3.3]     : Creating container for image: remote-docker.artifactory.mycompany.com/testcontainers/ryuk:0.3.3

2022-09-29 16:09:20.236  INFO 1287 --- [           main] ?.a.s.com/testcontainers/ryuk:0.3.3]     : Container remote-docker.artifactory.mycompany.com/testcontainers/ryuk:0.3.3 is starting: fcf85be7ab6b40f67864d99ad16a8bbb8f6f5adc19061019a5de83c17bb496ee

2022-09-29 16:09:20.661  INFO 1287 --- [           main] ?.a.s.com/testcontainers/ryuk:0.3.3]     : Container remote-docker.artifactory.mycompany.com/testcontainers/ryuk:0.3.3 started in PT4.725721649S

2022-09-29 16:09:21.132  INFO 1287 --- [           main] ?.a.s.com/localstack/localstack:latest]  : Container remote-docker.artifactory.mycompany.com/localstack/localstack:latest is starting: 4d6d878d5a4275a71acd9077ae25d513aedf0d17aba55e0e62cf834f3bdbb77a

2022-09-29 16:10:21.579 ERROR 1287 --- [           main] ?.a.s.com/localstack/localstack:latest]  : Could not start container



org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Ready\.
```

**Comment by eddumelendez** [comment]
@tiefenauer I found a [thread](https://localstack-community.slack.com/archives/CLRFWBFC3/p1626913427026400) related to localstack and dind setup in the localstack's slack. If there is a way to reproduce the issue will be helpful for localstack team and for us.

**Comment by tiefenauer** [comment]
@eddumelendez : Unfortunately, I can't open the link to the slack thread since I'm not a member of this community (can I become one?). Unfortunately, I don't have insight into our company's Jenkins setup. It is a master node spinning up worker DIND agents as needed using Kubernetes. 
Also investigating the log output did not give me any hints other than Localstack timing out. I'm posting it here for completeness:

```
2022-10-04 09:44:07.431 ERROR 1326 --- [           main] ?.a.s.com/localstack/localstack:latest]  : Could not start container

org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Ready\.
'
	at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:49) ~[testcontainers-1.17.2.jar:na]
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:51) ~[testcontainers-1.17.2.jar:na]
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:926) ~[testcontainers-1.17.2.jar:na]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:480) ~[testcontainers-1.17.2.jar:na]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:340) ~[testcontainers-1.17.2.jar:na]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar:na]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:338) ~[testcontainers-1.17.2.jar:na]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:326) ~[testcontainers-1.17.2.jar:na]
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.start(TestcontainersExtension.java:242) ~[junit-jupiter-1.17.2.jar:na]
	at org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.access$200(TestcontainersExtension.java:229) ~[junit-jupiter-1.17.2.jar:na]
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$null$1(TestcontainersExtension.java:59) ~[junit-jupiter-1.17.2.jar:na]
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$getOrComputeIfAbsent$4(ExtensionValuesStore.java:86) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.computeValue(ExtensionValuesStore.java:223) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.get(ExtensionValuesStore.java:211) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$StoredValue.evaluate(ExtensionValuesStore.java:191) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$StoredValue.access$100(ExtensionValuesStore.java:171) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.getOrComputeIfAbsent(ExtensionValuesStore.java:89) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.execution.NamespaceAwareStore.getOrComputeIfAbsent(NamespaceAwareStore.java:53) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$beforeAll$2(TestcontainersExtension.java:59) ~[junit-jupiter-1.17.2.jar:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.testcontainers.junit.jupiter.TestcontainersExtension.beforeAll(TestcontainersExtension.java:59) ~[junit-jupiter-1.17.2.jar:na]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$10(ClassBasedTestDescriptor.java:381) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:381) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:205) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:80) ~[junit-jupiter-engine-5.8.2.jar:5.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54) ~[junit-platform-engine-1.8.2.jar:1.8.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128) ~[junit-platform-launcher-1.3.1.jar:1.3.1]
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150) ~[surefire-junit-platform-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124) ~[surefire-junit-platform-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384) ~[surefire-booter-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345) ~[surefire-booter-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126) ~[surefire-booter-2.22.2.jar:2.22.2]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418) ~[surefire-booter-2.22.2.jar:2.22.2]

2022-10-04 09:44:07.453 ERROR 1326 --- [           main] ?.a.s.com/localstack/localstack:latest]  : Log output from the failed container:
Waiting for all LocalStack services to be ready
2022-10-04 07:43:07,834 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-10-04 07:43:07,836 INFO supervisord started with pid 16
2022-10-04 07:43:08,840 INFO spawned: 'infra' with pid 21
2022-10-04 07:43:09,841 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Waiting for all LocalStack services to be ready
SERVICES variable is ignored if EAGER_SERVICE_LOADING=0.

LocalStack version: 1.1.1.dev
LocalStack Docker container id: bf9754b98b8a
LocalStack build date: 2022-10-03
LocalStack build git hash: 4b8318ee

Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready
Waiting for all LocalStack services to be ready

2022-10-04 09:44:07.461  INFO 1326 --- [           main] o.s.t.c.support.AbstractContextLoader    : Could not detect default resource locations for test class [com.swisscom.designa.controller.files.FurnitureDetailsControllerIT]: no resource found for suffixes {-context.xml, Context.groovy}.
2022-10-04 09:44:07.461  INFO 1326 --- [           main] t.c.s.AnnotationConfigContextLoaderUtils : Could not detect default configuration classes for test class [com.swisscom.designa.controller.files.FurnitureDetailsControllerIT]: FurnitureDetailsControllerIT does not declare any static, non-private, non-final, nested classes annotated with @Configuration.
2022-10-04 09:44:07.559  INFO 1326 --- [           main] .b.t.c.SpringBootTestContextBootstrapper : Found @SpringBootConfiguration com.swisscom.designa.DesignaBackendApplication for test class com.swisscom.designa.controller.files.FurnitureDetailsControllerIT
2022-10-04 09:44:07.562  INFO 1326 --- [           main] .b.t.c.SpringBootTestContextBootstrapper : Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener, org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.event.ApplicationEventsTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener, org.springframework.test.context.event.EventPublishingTestExecutionListener, com.ninjasquad.springmockk.MockkTestExecutionListener, com.ninjasquad.springmockk.ClearMocksTestExecutionListener, org.springframework.security.test.context.support.WithSecurityContextTestExecutionListener, org.springframework.security.test.context.support.ReactorContextTestExecutionListener]
2022-10-04 09:44:07.563  INFO 1326 --- [           main] .b.t.c.SpringBootTestContextBootstrapper : Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@202199e, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@5864a44f, org.springframework.test.context.event.ApplicationEventsTestExecutionListener@4c8ad35b, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@33b7c027, com.ninjasquad.springmockk.MockkTestExecutionListener@216bf126, org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@5cd07f98, org.springframework.test.context.support.DirtiesContextTestExecutionListener@465a6f52, org.springframework.test.context.transaction.TransactionalTestExecutionListener@4be13946, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener@35fd03dd, org.springframework.test.context.event.EventPublishingTestExecutionListener@6a0e9645, org.springframework.security.test.context.support.WithSecurityContextTestExecutionListener@7f3b54a9, org.springframework.security.test.context.support.ReactorContextTestExecutionListener@3dd26901, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@60ec668d, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@7ece786b, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@5b75f507, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@75410509, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@761acd22, org.springframework.boot.test.autoconfigure.webservices.client.MockWebServiceServerTestExecutionListener@7b1aeeaa, com.ninjasquad.springmockk.ClearMocksTestExecutionListener@f33f103]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 270.269 s <<< FAILURE! - in com.swisscom.designa.controller.files.FurnitureDetailsControllerIT
[ERROR] com.swisscom.designa.controller.files.FurnitureDetailsControllerIT  Time elapsed: 270.236 s  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
Caused by: org.testcontainers.containers.ContainerLaunchException: 
Timed out waiting for log output matching '.*Ready\.
'
```

**Comment by kiview** [comment]
@tiefenauer Check [here](https://localstack.cloud/contact/) for joining the LocalStack Slack.

**Comment by tiefenauer** [comment]
Turns out it was an issue with the company proxy after all. For some reason, LocalStack needs to download dependencies at runtime:

From https://docs.localstack.cloud/localstack/configuration/:

> OUTBOUND_HTTP_PROXY: HTTP Proxy used for downloads of runtime dependencies and connections outside LocalStack itself

Since our Jenkins is behind a corporate proxy, I had to set the following environment variables: `SKIP_SSL_CERT_DOWNLOAD`, `OUTBOUND_HTTP_PROXY`, `OUTBOUND_HTTPS_PROXY`. On top of that I had to hardcode the version to `1.1.0` instead of using the `latest` tag.

So my code now looks like this:

```kotlin
    LocalStackContainer(DockerImageName.parse("localstack/localstack:1.1.0"))
      .withServices(LocalStackContainer.Service.S3)
      .withEnv("SKIP_SSL_CERT_DOWNLOAD", "true")
      .withEnv("OUTBOUND_HTTP_PROXY", "http://{proxy}:{port}")
      .withEnv("OUTBOUND_HTTPS_PROXY", "http://{proxy}:{port}")
      .apply { start() }
```

**Comment by kiview** [comment]
Thanks for letting us know @tiefenauer and glad you could resolve it 👍

**Comment by tiefenauer** [comment]
Thanks for your help. The issue is closed but it would still be interesting why it works with `1.1.0`, but not when using the `latest` tag...

**Comment by kiview** [comment]
`latest` does not give you any control over which image is used. So `latest` might refer to an older version in this case, that was pulled the first time you used `latest`.

**Comment by eddumelendez** [comment]
Can you let the LocalStack team know about this, please?

**Comment by cstmgl** [comment]
> Can you let the LocalStack team know about this, please?
I created a bug but honestly I'm not sure if I'm able to provide all the necessary details.
https://github.com/localstack/localstack/issues/7929
