### ISSUE TITLE
[Bug]: Test container is not compatible with docker compose version 2

### ISSUE THREAD

**Issue by ArnauG** [testcontainers/testcontainers-java#6081]
### Module

Core

### Testcontainers version

1.17.5

### Using the latest Testcontainers version?

Yes

### Host OS

MAC

### Host Arch

x86

### Docker version

```shell
Client:
 Cloud integration: v1.0.29
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:20:35 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.13.0 (89412)
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974
  Built:            Tue Oct 18 18:18:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

Docker compose v2, compose the containers name with dash instead of underscore (ex seygypsegnd1-postgres-1 instead of seygypsegnd1_postgres_1). Due to this testcontainers is not capable to find the containers.

Thanks in advance!

### Relevant log output

```shell
Stack trace:

Caused by: org.testcontainers.containers.ContainerLaunchException: Aborting attempt to link to container seygypsegnd1_postgres_1 as it is not running
	at app//org.testcontainers.containers.GenericContainer.applyConfiguration(GenericContainer.java:828)
	at app//org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:378)
```

**Comment by eddumelendez** [comment]
Closing because there is already an issue related to support for compose v2 https://github.com/testcontainers/testcontainers-java/issues/4565

There is also a [PR](https://github.com/testcontainers/testcontainers-java/pull/5608) you can follow.
