### ISSUE TITLE
[Bug]: shade jackson-annotations

### ISSUE THREAD

**Issue by shawjef3** [testcontainers/testcontainers-java#6161]
### Module

Core

### Testcontainers version

1.17.5

### Using the latest Testcontainers version?

Yes

### Host OS

Linux, MacOS

### Host Arch

x86-64

### Docker version

```shell
Client:
 Cloud integration: v1.0.28
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.11.1 (84025)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:05:12 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.18
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       e42327a
  Built:            Thu Sep  8 23:12:21 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

We have a project that is stuck on Jackson 2.6.7. Testcontainers shades some of jackson but not jackson-annotations, which is binary incompatible with our version. If jackson-annotations was also shaded, we could use testcontainers.

### Relevant log output

```shell
java.lang.NoSuchMethodError: 'com.fasterxml.jackson.annotation.JsonFormat$Value com.fasterxml.jackson.annotation.JsonFormat$Value.empty()'
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.cfg.MapperConfig.<clinit>(MapperConfig.java:49)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:558)
	at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:474)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultObjectMapperHolder.<init>(DockerClientConfig.java:68)
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultObjectMapperHolder.<clinit>(DockerClientConfig.java:66)
	at org.testcontainers.shaded.com.github.dockerjava.core.DockerClientConfig.getDefaultObjectMapper(DockerClientConfig.java:36)
	at org.testcontainers.shaded.com.github.dockerjava.core.DockerClientConfig.getObjectMapper(DockerClientConfig.java:61)
	at org.testcontainers.shaded.com.github.dockerjava.core.DockerClientConfigDelegate.getObjectMapper(DockerClientConfigDelegate.java:55)
	at org.testcontainers.shaded.com.github.dockerjava.core.DockerClientImpl.withHttpClient(DockerClientImpl.java:228)
	at org.testcontainers.shaded.com.github.dockerjava.core.DockerClientImpl.getInstance(DockerClientImpl.java:211)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getClientForConfig(DockerClientProviderStrategy.java:392)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getDockerClient(DockerClientProviderStrategy.java:64)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.tryOutStrategy(DockerClientProviderStrategy.java:272)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$5(DockerClientProviderStrategy.java:245)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:246)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:135)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:171)
	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:89)
	at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:108)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:321)
...
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:212)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:135)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:171)
	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:89)
	at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:108)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:321)
```

**Comment by shawjef3** [comment]
never mind.
