### ISSUE TITLE
Test not able to start MS SQL Server

### ISSUE THREAD

**Issue by Vipin-Sharma** [testcontainers/testcontainers-java#6404]
### Module

MSSQLServer

### Testcontainers version

1.17.6

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

x86

### Docker version

```shell
This is output requested:

Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Seems logs print different output, here is docker version from application test logs:
DEBUG org.testcontainers.DockerClientFactory - Docker version: {Components=[{Name=Engine, Version=20.10.12, Details={ApiVersion=1.41, Arch=amd64, BuildTime=2022-02-10T15:03:35.000000000+00:00, Experimental=false, GitCommit=20.10.12-0ubuntu2~20.04.1, GoVersion=go1.16.2, KernelVersion=5.13.0-1031-azure, MinAPIVersion=1.12, Os=linux}}, {Name=containerd, Version=1.5.9-0ubuntu1~20.04.6, Details={GitCommit=}}, {Name=runc, Version=1.1.0-0ubuntu1~20.04.1, Details={GitCommit=}}, {Name=docker-init, Version=0.19.0, Details={GitCommit=}}], KernelVersion=5.13.0-1031-azure, ApiVersion=1.41, Platform={Name=}, GitCommit=20.10.12-0ubuntu2~20.04.1, Os=linux, Version=20.10.12, MinAPIVersion=1.12, Arch=amd64, GoVersion=go1.16.2, BuildTime=2022-02-10T15:03:35.000000000+00:00}
```

### What happened?

Tests using TestContainers library are failing with SQL Server related errors, same code was working few months back during Oct 2022. That time I used version 1.17.5

### Relevant log output

Here are some of the errors from logs:

Below is error towards end of the tests, surprisingly it shows SQL Server SQL Server 2019 but I am using server:2022-latest, which can be seen in first line of log as well. Also why it shows "The evaluation period has expired." I was expecting it to use MSSQL_PID=Developer which is default option.

```
2023-01-09T12:42:44.8172543Z 12:42:44.816 [ForkJoinPool-1-worker-2] ERROR 🐳 [mcr.microsoft.com/mssql/server:2022-latest] - Log output from the failed container:
2023-01-09T12:42:44.8173373Z SQL Server 2019 will run as non-root by default.
2023-01-09T12:42:44.8173810Z This container is running as user mssql.
2023-01-09T12:42:44.8174289Z To learn more visit https://go.microsoft.com/fwlink/?linkid=2099216.
2023-01-09T12:42:44.8174754Z Error: The evaluation period has expired.
2023-01-09T12:42:44.8175212Z /opt/mssql/bin/sqlservr: PAL initialization failed. Error: 104
```

### Additional Information

2 more exception that can be important here

First Exception:

```
2023-01-09T12:38:43.6567384Z 12:38:43.643 [docker-java-stream-140947385] DEBUG com.github.dockerjava.zerodep.ApacheDockerHttpClientImpl$ApacheResponse - Failed to close the response
2023-01-09T12:38:43.6568073Z java.nio.channels.ClosedChannelException: null
2023-01-09T12:38:43.6568677Z 	at java.base/sun.nio.ch.SocketChannelImpl.ensureOpenAndConnected(SocketChannelImpl.java:215)
2023-01-09T12:38:43.6569345Z 	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:403)
2023-01-09T12:38:43.6570110Z 	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:59)
2023-01-09T12:38:43.6570733Z 	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)
2023-01-09T12:38:43.6571362Z 	at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)
2023-01-09T12:38:43.6572155Z 	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.io.LoggingInputStream.read(LoggingInputStream.java:81)
2023-01-09T12:38:43.6573184Z 	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:149)
2023-01-09T12:38:43.6574204Z 	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
2023-01-09T12:38:43.6575252Z 	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:261)
2023-01-09T12:38:43.6576253Z 	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:222)
2023-01-09T12:38:43.6577202Z 	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:147)
2023-01-09T12:38:43.6578114Z 	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.ChunkedInputStream.close(ChunkedInputStream.java:314)
2023-01-09T12:38:43.6578999Z 	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.io.Closer.close(Closer.java:48)
2023-01-09T12:38:43.6579835Z 	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.impl.io.IncomingHttpEntity.close(IncomingHttpEntity.java:111)
2023-01-09T12:38:43.6580842Z 	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.io.entity.HttpEntityWrapper.close(HttpEntityWrapper.java:120)
2023-01-09T12:38:43.6581669Z 	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.io.Closer.close(Closer.java:48)
2023-01-09T12:38:43.6582545Z 	at com.github.dockerjava.zerodep.shaded.org.apache.hc.core5.http.message.BasicClassicHttpResponse.close(BasicClassicHttpResponse.java:93)
2023-01-09T12:38:43.6583588Z 	at com.github.dockerjava.zerodep.shaded.org.apache.hc.client5.http.impl.classic.CloseableHttpResponse.close(CloseableHttpResponse.java:200)
2023-01-09T12:38:43.6584518Z 	at com.github.dockerjava.zerodep.ApacheDockerHttpClientImpl$ApacheResponse.close(ApacheDockerHttpClientImpl.java:256)
2023-01-09T12:38:43.6585530Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:277)
2023-01-09T12:38:43.6586302Z 	at java.base/java.lang.Thread.run(Thread.java:833)
```

Second Exception:
```
2023-01-09T12:39:15.1153252Z Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host localhost, port 49280 has failed. Error: "Connection refused. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".
2023-01-09T12:39:15.1154445Z 	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:237)
2023-01-09T12:39:15.1155270Z 	at com.microsoft.sqlserver.jdbc.SQLServerException.ConvertConnectExceptionToSQLServerException(SQLServerException.java:288)
2023-01-09T12:39:15.1156023Z 	at com.microsoft.sqlserver.jdbc.SocketFinder.findSocket(IOBuffer.java:2519)
2023-01-09T12:39:15.1156687Z 	at com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:777)
2023-01-09T12:39:15.1157349Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3300)
2023-01-09T12:39:15.1158186Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2950)
2023-01-09T12:39:15.1158919Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2790)
2023-01-09T12:39:15.1159643Z 	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1663)
2023-01-09T12:39:15.1160431Z 	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1064)
2023-01-09T12:39:15.1161152Z 	at
 org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:254)
2023-01-09T12:39:15.1161717Z 	... 62 common frames omitted
```

For sequence of events on these 2 exceptions attached log file TestContainers_Relavant_log.txt
[TestContainers_Relavant_log.txt](https://github.com/testcontainers/testcontainers-java/files/10391412/TestContainers_Relavant_log.txt)

If it helps, here is Abstract class that I am using for TestContainers setup.

```
package abc;

import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.MSSQLServerContainer;
import org.testcontainers.ext.ScriptUtils;
import org.testcontainers.jdbc.JdbcDatabaseDelegate;

public abstract class AbstractSQLServerBaseTest
{
  private static final MSSQLServerContainer msSqlServer = new MSSQLServerContainer("mcr.microsoft.com/mssql/server:2022-latest")
          .acceptLicense();
  static
  {
    msSqlServer.start();
    ScriptUtils.runInitScript(new JdbcDatabaseDelegate(msSqlServer, ""), "schema.sql");
    ScriptUtils.runInitScript(new JdbcDatabaseDelegate(msSqlServer, ""), "data.sql");
  }
  @DynamicPropertySource
  public static void overrideProps(DynamicPropertyRegistry registry)
  {
    System.out.println("Inside AbstractSQLServerBaseTest.overrideProps method ");
    registry.add("spring.datasource.url", () -> msSqlServer.getJdbcUrl() + ";databaseName=ABCD");
    registry.add("spring.datasource.username", msSqlServer::getUsername);
    registry.add("spring.datasource.password", msSqlServer::getPassword);
  }
}

```

**Comment by HofmeisterAn** [comment]
According to the logs, it looks like the container somehow terminates. I am not getting the mentioned error above for `MSSQL_PID=Developer`:

> /opt/mssql/bin/sqlservr: PAL initialization failed. Error: 104

Did you try to pull the image [again](https://stackoverflow.com/a/74526992/690017)?

**Comment by Vipin-Sharma** [comment]
> 

I am running test on a azure spot vm, I think it has to pull image every time it instantiates a new vm. And this test is failing consistently for last few months. 
I am not passing "MSSQL_PID=Developer" explicitly, I am expecting this is default. is there any way I can pass this?

**Comment by Vipin-Sharma** [comment]
My bad, it was not spot vm and after pulling the image my tests are successful. Thanks @HofmeisterAn !

**Comment by HofmeisterAn** [comment]
> I am running test on a azure spot vm, I think it has to pull image every time it instantiates a new vm. And this test is failing consistently for last few months.

It depends on the VM image (if it contains a cached version). You can set the [Image Pull Policy](https://www.testcontainers.org/features/advanced_options/#image-pull-policy) to always pull the image.

> I am not passing "MSSQL_PID=Developer" explicitly, I am expecting this is default. is there any way I can pass this?

Yes, `Developer` is the default vaule. You can override `MSSQL_PID` with `withEnv(String, String)` (it's just an environment variable).
