### ISSUE TITLE
[Bug]: Attempting to run MySQL 8 with MariaDB compatibile results in "RSA public key" error

### ISSUE THREAD

**Issue by tbeauvais-imagine** [testcontainers/testcontainers-java#6589]
### Module

MariaDB

### Testcontainers version

1.17.6

### Using the latest Testcontainers version?

Yes

### Host OS

macOS

### Host Arch

x86

### Docker version

```shell
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:41 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.2 (95914)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

Starting a MySQL 8 instance like this results in an error on `container.start()`.

```
        var image = DockerImageName.parse("mysql:8.0.27")
            .asCompatibleSubstituteFor("mariadb");

        container = new MariaDBContainer<>(image);
        container.addEnv("MYSQL_ALLOW_EMPTY_PASSWORD", "yes");
        container.addParameter("MYSQL_ALLOW_EMPTY_PASSWORD", "yes");
        container.start();
```

### Relevant log output

```shell
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
	at BaseJpaTest.<clinit>(BaseJpaTest.java:56)
	... 71 more
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
	... 73 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	... 74 more
Caused by: java.lang.IllegalStateException: Container is started, but cannot be accessed by (JDBC URL: jdbc:mariadb://localhost:52161/test), please check container logs
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:178)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:485)
	... 76 more
Caused by: java.sql.SQLException: Could not create new connection
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:263)
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:219)
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:159)
	... 77 more
Caused by: java.sql.SQLTransientConnectionException: Could not connect to address=(host=localhost)(port=52161)(type=master) : RSA public key is not available client side (option serverRsaPublicKeyFile not set)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:79)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:197)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1399)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
	at org.mariadb.jdbc.Driver.connect(Driver.java:89)
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:254)
	... 79 more
Caused by: java.sql.SQLException: RSA public key is not available client side (option serverRsaPublicKeyFile not set)
	at org.mariadb.jdbc.internal.com.send.authentication.CachingSha2PasswordPlugin.process(CachingSha2PasswordPlugin.java:189)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authenticationHandler(AbstractConnectProtocol.java:762)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:563)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1394)
	... 83 more
```

**Comment by eddumelendez** [comment]
`MYSQL_ALLOW_EMPTY_PASSWORD` will be set automatically if the `username` is `root` and `password` is empty or null.

https://github.com/testcontainers/testcontainers-java/blob/de1324ed2800eff4da326d0c23d281399d006bc0/modules/mariadb/src/main/java/org/testcontainers/containers/MariaDBContainer.java#L75-L80

As the [mysql image documentation](https://hub.docker.com/_/mysql) says:

> MYSQL_ALLOW_EMPTY_PASSWORD
This is an optional variable. Set to a non-empty value, like yes, to allow the container to be started with a blank password for the root user. NOTE: Setting this variable to yes is not recommended unless you really know what you are doing, since this will leave your MySQL instance completely unprotected, allowing anyone to gain complete superuser access.

**Comment by eddumelendez** [comment]
@tbeauvais-imagine did the last comment help you?

**Comment by tbeauvais-imagine** [comment]
Nope, it didn't. Though I was able to get around it eventually. 

Half of it had to do with improper documentation and the other half had to do with how we are setting up the properties for the Spring clients.

Assigning the properties directly on the container works.
```
var image = DockerImageName.parse("965331111166.dkr.ecr.us-west-2.amazonaws.com/mysql:8.0.27")
    .asCompatibleSubstituteFor("mariadb");

container = new MariaDBContainer<>(image)
    .withUrlParam("allowPublicKeyRetrieval", "true")
    .withUrlParam("useUnicode", "true")
    .withUrlParam("characterEncoding", "UTF-8");

container.start();
```

Then use the JDBC URL that is generated by the container (where we were building it improperly ourselves.
```
@DynamicPropertySource
static void mysqlProperties(DynamicPropertyRegistry registry) {
    var dsUsername = container.getUsername();
    var dsPassword = container.getPassword();

    registry.add("spring.datasource.url", () -> container.getJdbcUrl());
    registry.add("spring.datasource.username", () -> dsUsername);
    registry.add("spring.datasource.password", () -> dsPassword);
}    
```

Hopefully, this helps the next ones that have this problem.

Thanks for the response! :)
