### ISSUE TITLE
No value present

### ISSUE THREAD

**Issue by HeadHunter747** [testcontainers/testcontainers-java#666]
Hi,

in my test I want to create a GenericContainer with:

public static final GenericContainer c = new GenericContainer("nginx:1.13-alpine");

when i run mvn test I get the error 

`by: java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:102)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:119)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:142)`

Of course i have the import

`import org.testcontainers.containers.GenericContainer;`

Do you have an idea how to solve this issue?

I also had the error "cannot connect to ryuk". Now I run a moby-ryuk container, hope it solves the problem?!

Thank you

**Comment by bsideup** [comment]
Hi @HeadHunter747,

What version of Testcontainers are you using?

P.S. you don't have to start `moby-ryuk` yourself :)

**Comment by HeadHunter747** [comment]
HI,

im using version 1.7.1

Ok, so maybe there are two issues, but lets solve the "No value present"-error first :)

**Comment by bsideup** [comment]
@HeadHunter747 please send the logs via Gist or similar service :)

**Comment by bsideup** [comment]
@HeadHunter747 
oh wow! 
could you please try to downgrade to 1.7.0 and report if it helps? Could be a regression after docker-java update

**Comment by bsideup** [comment]
@HeadHunter747 Also, I see that you disabled the pre-flight checks. Could you please enable them back and try 1.7.1 again?

**Comment by HeadHunter747** [comment]
Same issue with 1.7.0

How can i enable the pre-flight checks back? Cant remember that i disabled them. Thank you

**Comment by bsideup** [comment]
@HeadHunter747 
See https://www.testcontainers.org/usage/properties.html and `checks.disable`

**Comment by bsideup** [comment]
@HeadHunter747 also, I see that you're not running Docker on your Linux machine, but somewhere else, right?

**Comment by HeadHunter747** [comment]
Yey, im running Docker version 18.03.0-ce, build 0520e24

**Comment by bsideup** [comment]
@HeadHunter747 but not on your machine, is that correct? Could you please describe your setup? Thanks!

**Comment by HeadHunter747** [comment]
I have docker running on my Linux machine. I have the error as describes. The above log is from maven thats running inside a docker container. I followed your instruction: https://www.testcontainers.org/usage/inside_docker.html

**Comment by bsideup** [comment]
@HeadHunter747 
I see `/mnt` as root folder. 
Usually it means that you didn't add `-v $PWD:$PWD -w $PWD` to `docker run`. 
Did you?

**Comment by HeadHunter747** [comment]
I updated my testcontainer.properties but have the same issue. 

Log: https://gist.github.com/HeadHunter747/0ef8527fd8a3fb1982c45fcd17b9b189

**Comment by HeadHunter747** [comment]
Yeah youre right! When i change it to `-v $PWD:$PWD -w $PWD` I have the issue again that it cant connect to Ryuk. See log. I always have to add "userns=host" 

https://gist.github.com/HeadHunter747/476ddbfeafcdfc5cd8994681d22ad5b3

**Comment by bsideup** [comment]
@HeadHunter747 the log is truncated, could you please send the first part, before it starts repeating `Connection refused` ?

**Comment by HeadHunter747** [comment]
Hi. Sorry for my late response. I think the problem is my system. I tried it in a linux VM and it works fine!
