### ISSUE TITLE
[Bug]: testcontainer-java 1.17.+ ClassNotFoundException from docker-java-api-3.2.8

### ISSUE THREAD

**Issue by vroyer** [testcontainers/testcontainers-java#6665]
### Module

Elasticsearch

### Testcontainers version

1.17.0+

### Using the latest Testcontainers version?

Yes

### Host OS

Mac

### Host Arch

Apple M2 Max

### Docker version

```shell
docker version 
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:41 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.2 (95914)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:43 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

Cannot build Apache/pulsar/pulsar-io/elastic-search because testcontainers 1.17.0+ references the class com/github/dockerjava/api/DockerClientDelegate which is not part of docker-java-api:3.2.8

(Apache Pulsar depends on testcontainers-java 1.15.3, but Apple M2 chip requires version 1.17.1+ according to #5266)

[ERROR] Tests run: 4, Failures: 2, Errors: 0, Skipped: 2, Time elapsed: 0.371 s <<< FAILURE! - in org.apache.pulsar.io.elasticsearch.ElasticSearchSinkRawDataTests
[ERROR] initBeforeClass(org.apache.pulsar.io.elasticsearch.ElasticSearchSinkRawDataTests)  Time elapsed: 0.324 s  <<< FAILURE!
java.lang.NoClassDefFoundError: com/github/dockerjava/api/DockerClientDelegate
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.testcontainers.DockerClientFactory.lazyClient(DockerClientFactory.java:101)
        at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:202)
        at org.testcontainers.elasticsearch.ElasticsearchContainer.<init>(ElasticsearchContainer.java:95)
        at org.testcontainers.elasticsearch.ElasticsearchContainer.<init>(ElasticsearchContainer.java:87)
        at org.apache.pulsar.io.elasticsearch.ElasticSearchTestBase.createElasticsearchContainer(ElasticSearchTestBase.java:31)
        at org.apache.pulsar.io.elasticsearch.ElasticSearchSinkRawDataTests.initBeforeClass(ElasticSearchSinkRawDataTests.java:65)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
        at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
        at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
        at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
        at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at org.testng.TestRunner.privateRun(TestRunner.java:764)
        at org.testng.TestRunner.run(TestRunner.java:585)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
        at org.testng.SuiteRunner.run(SuiteRunner.java:286)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
        at org.testng.TestNG.runSuites(TestNG.java:1069)
        at org.testng.TestNG.run(TestNG.java:1037)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.ClassNotFoundException: com.github.dockerjava.api.DockerClientDelegate
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 44 more

**Comment by eddumelendez** [comment]
I can see that Apache Pulsar is using Testcontainers 1.17.6 which is the latest https://github.com/apache/pulsar/blob/389792b1fc7a56647ccfc820e83ae08dfed037df/pom.xml#L247

I couldn't find any reference to 1.15.3

**Comment by eddumelendez** [comment]
Also, I am able to run test successfully in M1. Please, provide more info.

**Comment by vroyer** [comment]
Sorry, Apache pulsar has an explicit dependency to com.github.docker-java:3.2.8 causing my issue when building pulsar with testcontainer 1.17.6. Upgrading this dep to com.github.docker-java:3.3.0 solved this issue.
