### ISSUE TITLE
Startup time for RabbitMQ with testcontainers

### ISSUE THREAD

**Issue by sshogunn** [testcontainers/testcontainers-java#669]
Hello,

We use Spock Framework and TestContainers. In one of our integration tests we want to setup RabbitMQ with TestContainers, it works very well on local development environment with Windows 10. Whenever we try to run our tests on Jenkins we see that RabbitMQ is starting quite slow and the integration test fails:

```
org.springframework.jms.UncategorizedJmsException: Uncategorized exception occurred during JMS processing; nested exception is com.rabbitmq.jms.util.RMQJMSException: RabbitMQ connection was refused. RabbitMQ broker may not be available.
	at org.springframework.jms.support.JmsUtils.convertJmsAccessException(JmsUtils.java:317)
	at org.springframework.jms.support.JmsAccessor.convertJmsAccessException(JmsAccessor.java:185)
	at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:507)
	at org.springframework.jms.core.JmsTemplate.receiveSelected(JmsTemplate.java:753)
	at org.springframework.jms.core.JmsTemplate.receive(JmsTemplate.java:727)
	at org.springframework.jms.core.JmsTemplate.receiveAndConvert(JmsTemplate.java:835)
```

I've tried different types of WaitStrategy, none of them work. Do you have any ideas how we can make it working?

**Comment by bsideup** [comment]
Hi @sshogunn,

Please provide full logs.

Also, when you're running it on Jenkins, how do you start it?

**Comment by sshogunn** [comment]
[logs.txt](https://github.com/testcontainers/testcontainers-java/files/1965899/logs.txt)

And here an example from my tests:
```

@SpringBootTest(classes = Application.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("test")
@DirtiesContext
//Need this annotation for TestingContainers
@Testcontainers
@ContextConfiguration(initializers = Initializer.class)
class AbstractIntSpec extends Specification {
   ...

    def setupSpec() {
        Initializer.rabbitMqPort = rabbitMqContainer.getMappedPort(5672)
    }

    static class Initializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {
        static String postgresContainerUrl
        static Integer rabbitMqPort

        @Override
        void initialize(ConfigurableApplicationContext configurableApplicationContext) {
            TestPropertyValues.of("spring.datasource.url:$postgresContainerUrl",
                    "cloud.local.messaging.port=${rabbitMqPort}")
                    .applyTo(configurableApplicationContext)
        }
    }

    @Shared
    GenericContainer rabbitMqContainer = new GenericContainer("rabbitmq:3.7.4")
            .withExposedPorts(5672)
            .withEnv(["RABBITMQ_DEFAULT_USER": "root",
                      "RABBITMQ_DEFAULT_PASS": "toor"])
            .waitingFor(Wait.forListeningPort())
}
```

**Comment by bsideup** [comment]
@sshogunn the log is truncated, please send full log

Also, from your code I see that you forgot to use `rabbitMqContainer.containerIpAddress`. You should set `cloud.local.messaging.host` (or whatever the property is) because it might not be `localhost`

**Comment by sshogunn** [comment]
@bsideup  I found an example that reproduce the same issue - https://github.com/maciejwalkowiak/testcontainers-spring-rabbitmq-issue

**Comment by sshogunn** [comment]
We can close the issue, because the problem was in the wrong port and host :)
