### ISSUE TITLE
[Bug]: Could not find a valid Docker environment.

### ISSUE THREAD

**Issue by devcken-seven** [testcontainers/testcontainers-java#6774]
### Module

Core

### Testcontainers version

1.17.2

### Using the latest Testcontainers version?

No

### Host OS

Linux(CentOS, Ubuntu), macOS(13.2.1(22D68)) 

### Host Arch

ARM

### Docker version

```shell
Client:
 Cloud integration: v1.0.29
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:20:35 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       20.10.21-0ubuntu1~20.04.1
  Built:            Thu Nov 17 20:19:30 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.12-0ubuntu1~20.04.1
  GitCommit:
 runc:
  Version:          1.1.4-0ubuntu1~20.04.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### What happened?

I'm using Testcontainers with a remote Docker engine, and my project is built on macOS or Jenkin. Sometimes, but not always, tests fail. Unfortunately, I can't intentionally reproduce the situation.

As a result of testing several hypotheses, I had doubts about the behavior of the `DockerClientProviderStrategy#test()` method. Below, I'll explain why I'm suspecting that behavior.

First, if you look at the log, you can see that the `DockerClientProviderStrategy#getFirstValidStrategy()` method is outputting a stacktrace, and that the exception message is being output within that method.

Within the `getFirstValidStrategy(...)` method, we will execute the `tryOutStrategy(..)` method for valid strategies, and within that method, we will execute the `test()` method for each strategy. As you know, the `test()` method determines the test method according to the Docker host schema, performs the test according to the test method, and returns the result as a Boolean value. For reference, in my environment the schema is tcp.

Anyway, the point of the `test()` method is to create an instance of `InetSocketAddress` and actually `connect` it to the Docker host. By the way, I think there's a little bit tricky something in some of these parts. It's a timeout setting. In that method, connection timeout is 200ms.

I know that it's enough for socket connection, generally. As I said, I'm using a remote Docker host. And I run my tests with Testcontainers that is enabled reuse option. Because of this, tests are performed in parallel and the Docker host could receive numerous connection requests from Testcontainers simultaneously.

I wrote the following test code to prove this hypothesis:
```
class DockerConnectionTest {
    private val address = InetSocketAddress("...", 2375)

    @Test
    fun test() {
        Unreliables.retryUntilTrue(1000, TimeUnit.SECONDS) {
            // Thread.sleep(50)
            try {
                connect()
            } catch (e: Exception) {
                println("failed!!!!")
                println(e.message)
            }

            false
        }
    }

    fun connect() {
        val socketFactory = SocketFactory.getDefault()
        val socketProvider = Callable { socketFactory.createSocket() }

        socketProvider.call().use { socket ->
            socket.connect(address, 200)
        }
    }
}
```

Of course, this test also has its drawbacks, because concurrency or parallelism is ignored. However, I don't think testing with Testcontainers (although the reuse option is enabled) poses huge concurrency and parallelism problems. So I thought this was enough, and I experimented, and in reality, the connection often fails in my environment.

So, after adjusting the connection timeout, I tested again. 300 failures, 400 failures, but less, and almost no failures at 500.

How about making the connection timeout adjustable for testing? Here is my suggestion. Depending on the environment, 200 or 300 may be insufficient values.

### Relevant log output

```shell
Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$6(DockerClientProviderStrategy.java:242)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:234)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:135)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:176)
	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:90)
	at com.github.dockerjava.api.DockerClientDelegate.listContainersCmd(DockerClientDelegate.java:188)
```

**Comment by eddumelendez** [comment]
Sorry for the late reply. Can you provide more info, please? Are you using Docker Desktop for Linux? If so, which version? I would recommend to test Testcontainers for Java 1.18.2 which has some improvements related to auto-detection for `docker.sock`

**Comment by eddumelendez** [comment]
Closing due to inactivity. @devcken-seven feel free to reopen the issue. I'd suggest to upgrade to version 1.18.3.
