### ISSUE TITLE
Can't run image without internet connection/server issues

### ISSUE THREAD

**Issue by 4ntoine** [testcontainers/testcontainers-java#691]
I've pulled mysql image:
```
$docker image ls
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
mysql               5.6.40              5f5ccdc8aedc        10 days ago         256MB
```

but i can't run the tests if not having internet connection or having some server issues:

```
12:23:19.934 [main] INFO  UnixSocketClientProviderStrategy - Accessing docker with local Unix socket
12:23:19.938 [main] INFO  DockerClientProviderStrategy - Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
12:23:19.941 [main] INFO  DockerClientFactory - Docker host IP address is localhost
12:23:20.077 [main] INFO  DockerClientFactory - Connected to docker: 
  Server Version: 18.03.1-ce
  API Version: 1.37
  Operating System: Docker for Mac
  Total Memory: 1998 MB
        ℹ︎ Checking the system...
        ✔ Docker version is newer than 1.6.0
12:23:35.551 [dockerjava-netty-1-5] ERROR ResultCallbackTemplate - Error during callback
com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:109) [testcontainers-1.4.2.jar:na]
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:608) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.kqueue.KQueueDomainSocketChannel$KQueueDomainUnsafe.readReady(KQueueDomainSocketChannel.java:127) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:355) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:198) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:270) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [testcontainers-1.4.2.jar:na]
	at org.testcontainers.shaded.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138) [testcontainers-1.4.2.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
```

**Comment by 4ntoine** [comment]
any reason internet connection is required or any options to configure it not to use internet connection?

**Comment by 4ntoine** [comment]
using testcontainers 1.4.2:
```
<dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>mysql</artifactId>
            <version>1.4.2</version>
            <scope>test</scope>
        </dependency>
```

**Comment by 4ntoine** [comment]
having the same issue with `1.7.2`:
```
<dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>mysql</artifactId>
            <version>1.7.2</version>
            <scope>test</scope>
        </dependency>
```

**Comment by bsideup** [comment]
Hi @4ntoine,

Are you sure you're using the same image in your tests? `mysql:5.6.40`? Could you plz share your test setup?
Also, are you using JDBC-style containers or just do `new MySQLContainer()`?

**Comment by 4ntoine** [comment]
Yes, sure, here is the code:
```
@Before
    protected void setUp(Class... dbEntityClasses) throws Exception {
        // run docker image with MySql instance + database running
        mySqlContainer = new MySQLContainer("mysql:5.6.40");
        mySqlContainer.start();

        // override EMF settings
        Map dataSourceProperties = new HashMap();
        dataSourceProperties.put("javax.persistence.jdbc.url", mySqlContainer.getJdbcUrl());
        dataSourceProperties.put("javax.persistence.jdbc.driver", mySqlContainer.getDriverClassName());
        PersistenceFactory.getInstance().setProperties(dataSourceProperties);

        // get db connection
        entityManager = PersistenceFactory.getInstance().getEntityManager();
    }
```

**Comment by 4ntoine** [comment]
i've been waited a bit and just restarted the tests, now i having another problem (not sure if it's related or another one):
```
com.github.dockerjava.api.exception.DockerClientException: Could not pull image: Verifying Checksum

	at com.github.dockerjava.core.command.PullImageResultCallback.checkDockerClientPullSuccessful(PullImageResultCallback.java:96)
	at com.github.dockerjava.core.command.PullImageResultCallback.throwFirstError(PullImageResultCallback.java:111)
	at com.github.dockerjava.core.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:91)
	at com.github.dockerjava.core.command.PullImageResultCallback.awaitSuccess(PullImageResultCallback.java:124)
	at org.testcontainers.DockerClientFactory.checkAndPullImage(DockerClientFactory.java:186)
	at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:69)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:119)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:142)
	at org.testcontainers.containers.JdbcDatabaseContainer.<init>(JdbcDatabaseContainer.java:37)
	at org.testcontainers.containers.MySQLContainer.<init>(MySQLContainer.java:28)
```

**Comment by 4ntoine** [comment]
I did nothing, but now it works:
```
15:58:02.942 [main] INFO  UnixSocketClientProviderStrategy - Accessing docker with local Unix socket
15:58:02.942 [main] INFO  DockerClientProviderStrategy - Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
15:58:02.944 [main] INFO  DockerClientFactory - Docker host IP address is localhost
15:58:03.262 [main] INFO  DockerClientFactory - Connected to docker: 
  Server Version: 18.03.1-ce
  API Version: 1.37
  Operating System: Docker for Mac
  Total Memory: 1998 MB
15:58:04.328 [main] INFO  DockerClientFactory - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
        ✔ File should be mountable
15:58:04.522 [main] INFO  GenericContainer - Creating container for image: mysql:5.6.40
15:58:04.653 [main] INFO  GenericContainer - Starting container with ID: 819b412c230986b183c01de6762483e72f16b8e5bbb33d83232a52e4feea1367
15:58:05.016 [main] INFO  GenericContainer - Container mysql:5.6.40 is starting: 819b412c230986b183c01de6762483e72f16b8e5bbb33d83232a52e4feea1367
15:58:05.036 [main] INFO  JdbcDatabaseContainer - Waiting for database connection to become available at jdbc:mysql://localhost:32780/test using query 'SELECT 1'
15:58:14.338 [ducttape-0] INFO  JdbcDatabaseContainer - Obtained a connection to container (jdbc:mysql://localhost:32780/test)
15:58:14.339 [main] INFO  GenericContainer - Container mysql:5.6.40 started
```

**Comment by kiview** [comment]
Would it be possible, that the initial error was when pulling the `ryuk` image? (okay, first post was with tc 1.4, but AFAIK we were also using some aux container back then for pre-flight checks?)
