### ISSUE TITLE
[Bug]: testcontainers fails to recognize colima container runtime

### ISSUE THREAD

**Issue by olka** [testcontainers/testcontainers-java#7032]
### Module

Core

### Testcontainers version

1.17.6

### Using the latest Testcontainers version?

Yes

### Host OS

MacOS

### Host Arch

x86

### Docker version

```shell
docker version
Client: Docker Engine - Community
 Version:           23.0.6
 API version:       1.41 (downgraded from 1.42)
 Go version:        go1.20.4
 Git commit:        ef23cbc431
 Built:             Thu May  4 10:51:27 2023
 OS/Arch:           darwin/amd64
 Context:           colima

Server:
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974ae9e6c219862907efdd76ec2e77ec930b
  Built:            Wed Oct 19 02:58:31 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        5fd4c4d144137e991c4acebb2146ab1483a97925
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### What happened?

Using https://github.com/abiosoft/colima but receiving

```
java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:212)
        at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:150)
        at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:186)
        at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:104)
```

**Comment by eddumelendez** [comment]
Did you check the [docs](https://www.testcontainers.org/supported_docker_environment/#using-colima)?
