### ISSUE TITLE
[Bug]: gradle clean test fails

### ISSUE THREAD

**Issue by nagkumar** [testcontainers/testcontainers-java#7038]
### Module

Core

### Testcontainers version

latest on main

### Using the latest Testcontainers version?

Yes

### Host OS

windows

### Host Arch

x86

### Docker version

```shell
windows latest
```

### What happened?

root folder `gradle clean test ` cases are failing

### Relevant log output

```shell
> Task :cratedb:test

Gradle Test Executor 9 > org.testcontainers.jdbc.cratedb.CrateDBJDBCDriverTest > test[0 - jdbc:tc:cratedb:5.2.3://hostname/crate?user=crate&password=somepwd] STARTED

Gradle Test Executor 9 > org.testcontainers.jdbc.cratedb.CrateDBJDBCDriverTest > test[0 - jdbc:tc:cratedb:5.2.3://hostname/crate?user=crate&password=somepwd] FAILED
    com.zaxxer.hikari.pool.PoolInitializationException: Exception during pool initialization
        at com.zaxxer.hikari.pool.BaseHikariPool.initializeConnections(BaseHikariPool.java:550)
        at com.zaxxer.hikari.pool.BaseHikariPool.<init>(BaseHikariPool.java:172)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:60)
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:48)
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:80)
        at org.testcontainers.jdbc.AbstractJDBCDriverTest.getDataSource(AbstractJDBCDriverTest.java:223)
        at org.testcontainers.jdbc.AbstractJDBCDriverTest.test(AbstractJDBCDriverTest.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:108)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:60)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:52)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

        Caused by:
        org.testcontainers.containers.ContainerLaunchException: Container startup failed for image crate:5.2.3
            at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
            at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
            at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:134)
            at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
            at com.zaxxer.hikari.pool.BaseHikariPool.addConnection(BaseHikariPool.java:444)
            at com.zaxxer.hikari.pool.BaseHikariPool.initializeConnections(BaseHikariPool.java:548)
            ... 58 more

            Caused by:
            org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
                at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
                at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
                ... 63 more

                Caused by:
                org.testcontainers.containers.ContainerLaunchException: Could not create/start container
                    at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:553)
                    at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
                    at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
                    ... 64 more

                    Caused by:
                    java.lang.IllegalStateException: Wait strategy failed. Container exited with code 78
                        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:523)
                        ... 66 more

                        Caused by:
                        org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://localhost:56650/ should return HTTP [200])
                            at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:320)
                            at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
                            at org.testcontainers.cratedb.CrateDBContainer.waitUntilContainerStarted(CrateDBContainer.java:114)
                            at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:490)
                            ... 66 more

                            Caused by:
                            org.rnorth.ducttape.TimeoutException: Timeout waiting for result with exception
                                at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:54)
                                at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:252)
                                ... 69 more

                                Caused by:
                                java.lang.RuntimeException: java.net.ConnectException: Connection refused: connect
                                    at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$null$6(HttpWaitStrategy.java:312)
                                    at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
                                    at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$waitUntilReady$7(HttpWaitStrategy.java:257)
                                    at org.rnorth.ducttape.unreliables.Unreliables.lambda$retryUntilSuccess$0(Unreliables.java:43)
                                    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                    at java.lang.Thread.run(Thread.java:750)

                                    Caused by:
                                    java.net.ConnectException: Connection refused: connect
                                        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
                                        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:75)
                                        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
                                        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
                                        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
                                        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:162)
                                        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
                                        at java.net.Socket.connect(Socket.java:606)
                                        at java.net.Socket.connect(Socket.java:555)
                                        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
                                        at sun.net.www.http.HttpClient.openServer(HttpClient.java:499)
                                        at sun.net.www.http.HttpClient.openServer(HttpClient.java:594)
                                        at sun.net.www.http.HttpClient.<init>(HttpClient.java:278)
                                        at sun.net.www.http.HttpClient.New(HttpClient.java:375)
                                        at sun.net.www.http.HttpClient.New(HttpClient.java:393)
                                        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1240)
                                        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1167)
                                        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1061)
                                        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:995)
                                        at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$null$6(HttpWaitStrategy.java:274)
                                        ... 7 more

Gradle Test Executor 9 > org.testcontainers.junit.cratedb.SimpleCrateDBTest > testExplicitInitScript STARTED

Gradle Test Executor 9 > org.testcontainers.junit.cratedb.SimpleCrateDBTest > testExplicitInitScript FAILED
    org.testcontainers.containers.ContainerLaunchException: Container startup failed for image crate:5.2.5
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
        at org.testcontainers.junit.cratedb.SimpleCrateDBTest.testExplicitInitScript(SimpleCrateDBTest.java:53)

        Caused by:
        org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
            at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
            at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
            ... 2 more

            Caused by:
            org.testcontainers.containers.ContainerLaunchException: Could not create/start container
                at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:553)
                at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
                at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
                ... 3 more

                Caused by:
                java.lang.IllegalStateException: Wait strategy failed. Container exited with code 78
                    at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:523)
                    ... 5 more

                    Caused by:
                    org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://localhost:56683/ should return HTTP [200])
                        at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:320)
                        at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
                        at org.testcontainers.cratedb.CrateDBContainer.waitUntilContainerStarted(CrateDBContainer.java:114)
                        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:490)
                        ... 5 more

                        Caused by:
                        org.rnorth.ducttape.TimeoutException: Timeout waiting for result with exception
                            at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:54)
                            at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:252)
                            ... 8 more

                            Caused by:
                            java.lang.RuntimeException: java.net.ConnectException: Connection refused: connect
                                at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$null$6(HttpWaitStrategy.java:312)
                                at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
                                at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$waitUntilReady$7(HttpWaitStrategy.java:257)
                                at org.rnorth.ducttape.unreliables.Unreliables.lambda$retryUntilSuccess$0(Unreliables.java:43)
                                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                at java.lang.Thread.run(Thread.java:750)

                                Caused by:
                                java.net.ConnectException: Connection refused: connect
                                    at java.net.DualStackPlainSocketImpl.connect0(Native Method)
                                    at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:75)
                                    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
                                    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
                                    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
                                    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:162)
                                    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
                                    at java.net.Socket.connect(Socket.java:606)
                                    at java.net.Socket.connect(Socket.java:555)
                                    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
                                    at sun.net.www.http.HttpClient.openServer(HttpClient.java:499)
                                    at sun.net.www.http.HttpClient.openServer(HttpClient.java:594)
                                    at sun.net.www.http.HttpClient.<init>(HttpClient.java:278)
                                    at sun.net.www.http.HttpClient.New(HttpClient.java:375)
                                    at sun.net.www.http.HttpClient.New(HttpClient.java:393)
                                    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1240)
                                    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1167)
                                    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1061)
                                    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:995)
                                    at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$null$6(HttpWaitStrategy.java:274)
                                    ... 7 more

Gradle Test Executor 9 > org.testcontainers.junit.cratedb.SimpleCrateDBTest > testCommandOverride STARTED

Gradle Test Executor 9 > org.testcontainers.junit.cratedb.SimpleCrateDBTest > testCommandOverride FAILED
    org.testcontainers.containers.ContainerLaunchException: Container startup failed for image crate:5.2.5
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
        at org.testcontainers.junit.cratedb.SimpleCrateDBTest.testCommandOverride(SimpleCrateDBTest.java:39)

        Caused by:
        org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
            at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)
            at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)
            ... 2 more

            Caused by:
            org.testcontainers.containers.ContainerLaunchException: Could not create/start container
                at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:553)
                at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)
                at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
                ... 3 more

                Caused by:
                java.lang.IllegalStateException: Wait strategy failed. Container exited with code 78
                    at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:523)
                    ... 5 more

                    Caused by:
                    org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://localhost:56716/ should return HTTP [200])
                        at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:320)
                        at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
                        at org.testcontainers.cratedb.CrateDBContainer.waitUntilContainerStarted(CrateDBContainer.java:114)
                        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:490)
                        ... 5 more

                        Caused by:
                        org.rnorth.ducttape.TimeoutException: Timeout waiting for result with exception
                            at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:54)
                            at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:252)
                            ... 8 more

                            Caused by:
                            java.lang.RuntimeException: java.net.ConnectException: Connection refused: connect
                                at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$null$6(HttpWaitStrategy.java:312)
                                at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
                                at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$waitUntilReady$7(HttpWaitStrategy.java:257)
                                at org.rnorth.ducttape.unreliables.Unreliables.lambda$retryUntilSuccess$0(Unreliables.java:43)
                                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                                at java.lang.Thread.run(Thread.java:750)

                                Caused by:
                                java.net.ConnectException: Connection refused: connect
                                    at java.net.DualStackPlainSocketImpl.connect0(Native Method)
                                    at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:75)
                                    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:476)
                                    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:218)
                                    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:200)
                                    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:162)
                                    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:394)
                                    at java.net.Socket.connect(Socket.java:606)
                                    at java.net.Socket.connect(Socket.java:555)
                                    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
                                    at sun.net.www.http.HttpClient.openServer(HttpClient.java:499)
                                    at sun.net.www.http.HttpClient.openServer(HttpClient.java:594)
                                    at sun.net.www.http.HttpClient.<init>(HttpClient.java:278)
                                    at sun.net.www.http.HttpClient.New(HttpClient.java:375)
                                    at sun.net.www.http.HttpClient.New(HttpClient.java:393)
                                    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1240)
                                    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1167)
                                    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1061)
                                    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:995)
                                    at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.lambda$null$6(HttpWaitStrategy.java:274)
                                    ... 7 more

Gradle Test Executor 9 > org.testcontainers.junit.cratedb.SimpleCrateDBTest > testSimple STARTED
<===----------> 25% EXECUTING [3m 38s]
```

### Additional Information

<img width="904" alt="image" src="https://github.com/testcontainers/testcontainers-java/assets/332234/fcc9681f-1c33-43b8-b8ef-f462f2133c20">

CreateDB new example is failing.. as I think the issue is hostname in the JDBC URL

**Comment by eddumelendez** [comment]
This is weird but indeed is happening. Thanks for raising the issue. I say weird because when the module was contributed it was working. See details [here](https://github.com/testcontainers/testcontainers-java/actions/runs/4579878567/jobs/8088108257)

Also, looks like the image was not updated recently. See https://hub.docker.com/_/crate/tags?page=1&name=5.2.3

@matriv do you know what could happen?

From logs, I can identified this 

```
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144] by adding `vm.max_map_count = 262144` to `/etc/sysctl.conf` or invoking `sysctl -w vm.max_map_count=262144`
```

Adding container logs

```
May 13, 2023 7:39:06 PM org.apache.lucene.store.MemorySegmentIndexInputProvider <init>
INFO: Using MemorySegmentIndexInput with Java 19+
[2023-05-13T19:39:06,287][INFO ][o.e.e.NodeEnvironment    ] [Kronplatz] using [1] data paths, mounts [[/data (/dev/root)]], net usable_space [59.6gb], net total_space [64.9gb], types [ext4]
[2023-05-13T19:39:06,288][INFO ][o.e.e.NodeEnvironment    ] [Kronplatz] heap size [512mb], compressed ordinary object pointers [true]
[2023-05-13T19:39:06,312][INFO ][o.e.n.Node               ] [Kronplatz] node name [Kronplatz], node ID [LM1Ryq44SFG7QvC4gKk03Q], cluster name [crate]
[2023-05-13T19:39:06,321][INFO ][o.e.n.Node               ] [Kronplatz] version[5.2.3], pid[1], build[22edf87/2023-02-23T18:10:29Z], OS[Linux/5.10.137/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/19.0.2/19.0.2+7]
[2023-05-13T19:39:06,832][INFO ][o.e.p.PluginsService     ] [Kronplatz] no modules loaded
[2023-05-13T19:39:06,833][INFO ][o.e.p.PluginsService     ] [Kronplatz] loaded plugin [cr8-copy-s3]
[2023-05-13T19:39:06,833][INFO ][o.e.p.PluginsService     ] [Kronplatz] loaded plugin [crate-functions]
[2023-05-13T19:39:06,833][INFO ][o.e.p.PluginsService     ] [Kronplatz] loaded plugin [crate-jmx-monitoring]
[2023-05-13T19:39:06,833][INFO ][o.e.p.PluginsService     ] [Kronplatz] loaded plugin [crate-lang-js]
[2023-05-13T19:39:06,833][INFO ][o.e.p.PluginsService     ] [Kronplatz] loaded plugin [es-analysis-common]
[2023-05-13T19:39:06,834][INFO ][o.e.p.PluginsService     ] [Kronplatz] loaded plugin [es-analysis-phonetic]
[2023-05-13T19:39:06,834][INFO ][o.e.p.PluginsService     ] [Kronplatz] loaded plugin [es-repository-azure]
[2023-05-13T19:39:06,834][INFO ][o.e.p.PluginsService     ] [Kronplatz] loaded plugin [io.crate.plugin.SrvPlugin]
[2023-05-13T19:39:06,834][INFO ][o.e.p.PluginsService     ] [Kronplatz] loaded plugin [io.crate.udc.plugin.UDCPlugin]
[2023-05-13T19:39:06,834][INFO ][o.e.p.PluginsService     ] [Kronplatz] loaded plugin [org.elasticsearch.discovery.ec2.Ec2DiscoveryPlugin]
[2023-05-13T19:39:06,834][INFO ][o.e.p.PluginsService     ] [Kronplatz] loaded plugin [org.elasticsearch.plugin.repository.url.URLRepositoryPlugin]
[2023-05-13T19:39:06,834][INFO ][o.e.p.PluginsService     ] [Kronplatz] loaded plugin [org.elasticsearch.repositories.s3.S3RepositoryPlugin]
[2023-05-13T19:39:06,834][INFO ][o.e.p.PluginsService     ] [Kronplatz] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
[2023-05-13T19:39:07,484][INFO ][o.e.d.DiscoveryModule    ] [Kronplatz] using discovery type [zen] and seed hosts providers [settings]
[2023-05-13T19:39:08,190][INFO ][psql                     ] [Kronplatz] PSQL SSL support is disabled.
[2023-05-13T19:39:08,371][INFO ][i.c.n.c.PipelineRegistry ] [Kronplatz] HTTP SSL support is disabled.
[2023-05-13T19:39:08,394][WARN ][o.e.g.DanglingIndicesState] [Kronplatz] gateway.auto_import_dangling_indices is disabled, dangling indices will not be detected or imported
[2023-05-13T19:39:08,437][INFO ][o.e.n.Node               ] [Kronplatz] initialized
[2023-05-13T19:39:08,437][INFO ][o.e.n.Node               ] [Kronplatz] starting ...
[2023-05-13T19:39:08,485][INFO ][psql                     ] [Kronplatz] publish_address {172.18.0.3:5432}, bound_addresses {127.0.0.1:5432}, {172.18.0.3:5432}
[2023-05-13T19:39:08,491][INFO ][o.e.h.n.Netty4HttpServerTransport] [Kronplatz] publish_address {172.18.0.3:4200}, bound_addresses {127.0.0.1:4200}, {172.18.0.3:4200}
[2023-05-13T19:39:08,499][INFO ][o.e.t.TransportService   ] [Kronplatz] publish_address {172.18.0.3:4300}, bound_addresses {127.0.0.1:4300}, {172.18.0.3:4300}
[2023-05-13T19:39:08,598][INFO ][o.e.b.BootstrapChecks    ] [Kronplatz] bound or publishing to a non-loopback address, enforcing bootstrap checks
ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144] by adding `vm.max_map_count = 262144` to `/etc/sysctl.conf` or invoking `sysctl -w vm.max_map_count=262144`
[2023-05-13T19:39:08,603][INFO ][o.e.n.Node               ] [Kronplatz] stopping ...
[2023-05-13T19:39:08,609][INFO ][o.e.n.Node               ] [Kronplatz] stopped
[2023-05-13T19:39:08,609][INFO ][o.e.n.Node               ] [Kronplatz] closing ...
[2023-05-13T19:39:08,617][INFO ][o.e.n.Node               ] [Kronplatz] closed
```

**Comment by matriv** [comment]
Hi @eddumelendez thx for pinging.

This fails only on windows, right? I think I have an idea, will take a look within the next couple of days.

**Comment by eddumelendez** [comment]
I did a quick test in linux and it fails too

**Comment by matriv** [comment]
This bootstrap check should be called only if you don't set localhost as a bind address but an ip, then it guesses it's in "production" mode and calls the bootstrap checks.

**Comment by eddumelendez** [comment]
JFTR, it works fine in macos M1

**Comment by matriv** [comment]
Strange, for me it works:
```
└─(09:50:20 on main)──> ./gradlew cratedb:test                                                                                                                                                                   1 ↵ ──(Sun,May14)─┘
Configuration on demand is an incubating feature.

> Task :jdbc:compileJava
Note: /home/matriv/crate/testcontainers-java/modules/jdbc/src/main/java/org/testcontainers/containers/JdbcDatabaseContainer.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/matriv/crate/testcontainers-java/modules/jdbc/src/main/java/org/testcontainers/jdbc/ContainerDatabaseDriver.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :cratedb:test

Gradle Test Executor 3 > org.testcontainers.jdbc.cratedb.CrateDBJDBCDriverTest > test[0 - jdbc:tc:cratedb:5.2.3://hostname/crate?user=crate&password=somepwd] STARTED

Gradle Test Executor 3 > org.testcontainers.jdbc.cratedb.CrateDBJDBCDriverTest > test[0 - jdbc:tc:cratedb:5.2.3://hostname/crate?user=crate&password=somepwd] PASSED

Gradle Test Executor 3 > org.testcontainers.junit.cratedb.SimpleCrateDBTest > testExplicitInitScript STARTED

Gradle Test Executor 3 > org.testcontainers.junit.cratedb.SimpleCrateDBTest > testExplicitInitScript PASSED

Gradle Test Executor 3 > org.testcontainers.junit.cratedb.SimpleCrateDBTest > testCommandOverride STARTED

Gradle Test Executor 3 > org.testcontainers.junit.cratedb.SimpleCrateDBTest > testCommandOverride PASSED

Gradle Test Executor 3 > org.testcontainers.junit.cratedb.SimpleCrateDBTest > testSimple STARTED

Gradle Test Executor 3 > org.testcontainers.junit.cratedb.SimpleCrateDBTest > testSimple PASSED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 32s
23 actionable tasks: 16 executed, 7 up-to-date

A build scan was not published as you have not authenticated with server 'ge.testcontainers.org'.
For more information, please see https://gradle.com/help/gradle-authenticating-with-gradle-enterprise.
```

**Comment by matriv** [comment]
Could you please if: https://github.com/testcontainers/testcontainers-java/pull/7041 solves the issue?
