### ISSUE TITLE
[Bug]: YugabyteDBYSQLContainer doesn't work because of unrecognised command --background=false

### ISSUE THREAD

**Issue by lukaseder** [testcontainers/testcontainers-java#7056]
### Module

YugabyteDB

### Testcontainers version

1.18.1

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host Arch

x64

### Docker version

```shell
$ docker version
Client:
 Cloud integration: v1.0.29
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:08:16 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.14.1 (91661)
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 18:00:19 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.9
  GitCommit:        1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

I'm using testcontainers from JUnit with:

```java
    @ClassRule
    public static YugabyteDBYSQLContainer db = TC.yugabytedb();
```

And:

```java
    public static YugabyteDBYSQLContainer yugabytedb() {
        return yugabytedb("yugabytedb/yugabyte");
    }

    public static YugabyteDBYSQLContainer yugabytedb(String imageName) {
        return new YugabyteDBYSQLContainer(imageName)
            .withUsername("yugabyte")
            .withDatabaseName("yugabyte")
            .withPassword("yugabyte");
    }
```

This doesn't work, see the logs

### Relevant log output

```shell
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
16:26:15,260  INFO [ImageNameSubstitutor          ] - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
16:26:15,794  INFO [DockerClientProviderStrategy  ] - Loaded org.testcontainers.dockerclient.NpipeSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
16:26:16,493  INFO [DockerClientProviderStrategy  ] - Found Docker environment with local Npipe socket (npipe:////./pipe/docker_engine)
16:26:16,497  INFO [DockerClientFactory           ] - Docker host IP address is localhost
16:26:16,532  INFO [DockerClientFactory           ] - Connected to docker: 
  Server Version: 20.10.21
  API Version: 1.41
  Operating System: Docker Desktop
  Total Memory: 15976 MB
16:26:16,615 DEBUG [0                             ] - Starting container: testcontainers/ryuk:0.4.0
16:26:16,619 DEBUG [0                             ] - Trying to start container: testcontainers/ryuk:0.4.0 (attempt 1/1)
16:26:16,621 DEBUG [0                             ] - Starting container: testcontainers/ryuk:0.4.0
16:26:16,621  INFO [0                             ] - Creating container for image: testcontainers/ryuk:0.4.0
16:26:17,008  INFO [0                             ] - Container testcontainers/ryuk:0.4.0 is starting: ce8f053143ecc15e8c0d197130f060c4ade907ff90a52e3ff94b437172c7a6a9
16:26:17,481  INFO [0                             ] - Container testcontainers/ryuk:0.4.0 started in PT0.929614S
16:26:17,488  INFO [RyukResourceReaper            ] - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
16:26:17,489  INFO [DockerClientFactory           ] - Checking the system...
16:26:17,490  INFO [DockerClientFactory           ] - ✔︎ Docker server version should be at least 1.6.0
16:26:17,490 DEBUG [yugabytedb/yugabyte:latest    ] - yugabytedb/yugabyte:latest is not in image name cache, updating...
16:26:17,504 DEBUG [yugabytedb/yugabyte:latest    ] - Starting container: yugabytedb/yugabyte:latest
16:26:17,504 DEBUG [yugabytedb/yugabyte:latest    ] - Trying to start container: yugabytedb/yugabyte:latest (attempt 1/1)
16:26:17,505 DEBUG [yugabytedb/yugabyte:latest    ] - Starting container: yugabytedb/yugabyte:latest
16:26:17,505  INFO [yugabytedb/yugabyte:latest    ] - Creating container for image: yugabytedb/yugabyte:latest
16:26:17,567  INFO [yugabytedb/yugabyte:latest    ] - Container yugabytedb/yugabyte:latest is starting: d525a5d7940a1afc53195c1908a45d234c881733a3960d7da7a53f9bd85790c9
16:26:17,977  INFO [yugabytedb/yugabyte:latest    ] - Waiting for database connection to become available at jdbc:yugabytedb://localhost:60694/yugabyte using query 'SELECT 1'
16:26:18,005 DEBUG [yugabytedb/yugabyte:latest    ] - Trying to create JDBC connection using com.yugabyte.Driver to jdbc:yugabytedb://localhost:60694/yugabyte with properties: {password=yugabyte, user=yugabyte}
16:26:18,340 DEBUG [yugabytedb/yugabyte:latest    ] - Failure when trying test query
java.sql.SQLException: Could not create new connection
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:262) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:218) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:158) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:490) ~[testcontainers-1.18.1.jar:?]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344) ~[testcontainers-1.18.1.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) [duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334) [testcontainers-1.18.1.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322) [testcontainers-1.18.1.jar:?]
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1131) [testcontainers-1.18.1.jar:?]
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:28) [testcontainers-1.18.1.jar:?]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
Caused by: com.yugabyte.util.PSQLException: Connection to localhost:60694 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at com.yugabyte.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:316) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.jdbc.PgConnection.<init>(PgConnection.java:244) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.Driver.makeConnection(Driver.java:497) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.Driver.connect(Driver.java:287) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:253) ~[jdbc-1.18.1.jar:?]
	... 18 more
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at com.yugabyte.core.PGStream.createSocket(PGStream.java:241) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.core.PGStream.<init>(PGStream.java:98) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:102) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:230) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.jdbc.PgConnection.<init>(PgConnection.java:244) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.Driver.makeConnection(Driver.java:497) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.Driver.connect(Driver.java:287) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:253) ~[jdbc-1.18.1.jar:?]
	... 18 more
16:28:18,031 DEBUG [yugabytedb/yugabyte:latest    ] - Wait strategy threw an exception
java.lang.IllegalStateException: Container is started, but cannot be accessed by (JDBC URL: jdbc:yugabytedb://localhost:60694/yugabyte), please check container logs
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:176) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:490) ~[testcontainers-1.18.1.jar:?]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344) ~[testcontainers-1.18.1.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) [duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334) [testcontainers-1.18.1.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322) [testcontainers-1.18.1.jar:?]
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1131) [testcontainers-1.18.1.jar:?]
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:28) [testcontainers-1.18.1.jar:?]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
Caused by: java.sql.SQLException: Could not create new connection
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:262) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:218) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:158) ~[jdbc-1.18.1.jar:?]
	... 16 more
Caused by: com.yugabyte.util.PSQLException: Connection to localhost:60694 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at com.yugabyte.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:316) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.jdbc.PgConnection.<init>(PgConnection.java:244) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.Driver.makeConnection(Driver.java:497) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.Driver.connect(Driver.java:287) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:253) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:218) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:158) ~[jdbc-1.18.1.jar:?]
	... 16 more
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at com.yugabyte.core.PGStream.createSocket(PGStream.java:241) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.core.PGStream.<init>(PGStream.java:98) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:102) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:230) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.jdbc.PgConnection.<init>(PgConnection.java:244) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.Driver.makeConnection(Driver.java:497) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.Driver.connect(Driver.java:287) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:253) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:218) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:158) ~[jdbc-1.18.1.jar:?]
	... 16 more
16:28:18,038 ERROR [yugabytedb/yugabyte:latest    ] - Could not start container
java.lang.IllegalStateException: Wait strategy failed. Container exited with code 2
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:523) ~[testcontainers-1.18.1.jar:?]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344) ~[testcontainers-1.18.1.jar:?]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) [duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334) [testcontainers-1.18.1.jar:?]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322) [testcontainers-1.18.1.jar:?]
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1131) [testcontainers-1.18.1.jar:?]
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:28) [testcontainers-1.18.1.jar:?]
	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) [junit-4.13.2.jar:4.13.2]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413) [junit-4.13.2.jar:4.13.2]
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452) [.cp/:?]
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210) [.cp/:?]
Caused by: java.lang.IllegalStateException: Container is started, but cannot be accessed by (JDBC URL: jdbc:yugabytedb://localhost:60694/yugabyte), please check container logs
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:176) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:490) ~[testcontainers-1.18.1.jar:?]
	... 15 more
Caused by: java.sql.SQLException: Could not create new connection
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:262) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:218) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:158) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:490) ~[testcontainers-1.18.1.jar:?]
	... 15 more
Caused by: com.yugabyte.util.PSQLException: Connection to localhost:60694 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at com.yugabyte.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:316) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.jdbc.PgConnection.<init>(PgConnection.java:244) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.Driver.makeConnection(Driver.java:497) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.Driver.connect(Driver.java:287) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:253) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:218) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:158) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:490) ~[testcontainers-1.18.1.jar:?]
	... 15 more
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at com.yugabyte.core.PGStream.createSocket(PGStream.java:241) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.core.PGStream.<init>(PGStream.java:98) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:102) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:230) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.core.ConnectionFactory.openConnection(ConnectionFactory.java:51) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.jdbc.PgConnection.<init>(PgConnection.java:244) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.Driver.makeConnection(Driver.java:497) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at com.yugabyte.Driver.connect(Driver.java:287) ~[jdbc-yugabytedb-42.3.5-yb-3.jar:42.3.5-yb-3]
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:253) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.JdbcDatabaseContainer.createConnection(JdbcDatabaseContainer.java:218) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:158) ~[jdbc-1.18.1.jar:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:490) ~[testcontainers-1.18.1.jar:?]
	... 15 more
16:28:18,076 ERROR [yugabytedb/yugabyte:latest    ] - Log output from the failed container:
Usage: yugabyted [-h]
                 {start,stop,destroy,status,version,collect_logs,connect,demo}
                 ...

To start yugabyted, run 'yugabyted start'.

Commands:
  {start,stop,destroy,status,version,collect_logs,connect,demo}
    start               Start yugabyted.
    stop                Stop running yugabyted.
    destroy             Destroy yugabyted cluster and remove data.
    status              Print status of yugabyted.
    version             Version of yugabyted.
    collect_logs        Collect and package logs for troubleshooting.
    connect             Connect to an API through the CLI.
    demo                Load and interact with preset demo data.

Flags:
  -h, --help            show this help message and exit

Run 'yugabyted [command] -h' for help with specific commands.
Error: unrecognized arguments: --background=false.
```

key is this:

```
Error: unrecognized arguments: --background=false.
```

This means the workaround for now is:

```java
    public static YugabyteDBYSQLContainer yugabytedb(String imageName) {
        return new YugabyteDBYSQLContainer(imageName) {
            @Override
            public YugabyteDBYSQLContainer withCommand(String cmd) {
                return super.withCommand(cmd.replace(" --background=false", ""));
            };
        }
            .withUsername("yugabyte")
            .withDatabaseName("yugabyte")
            .withPassword("yugabyte");
    }
```

After this, I still cannot connect to it (which I'll investigate next week), but at least I'm getting a step further.

**Comment by eddumelendez** [comment]
Thanks for the report, @lukaseder ! I jus ran the whole test suite for [YugabyteDBYSQLContainer](https://github.com/testcontainers/testcontainers-java/blob/main/modules/yugabytedb/src/test/java/org/testcontainers/junit/yugabytedb/YugabyteDBYSQLTest.java) and couldn't replicate it 🤔

**Comment by lukaseder** [comment]
Thanks for your feedback, @eddumelendez: I can't reproduce it either with your test suite, nor on a different computer. I'll try again later this week, and will close in case it's some user error.

**Comment by lukaseder** [comment]
I didn't manage to reproduce this issue. May have been a local setup. Sorry for the noise.
