### ISSUE TITLE
richnorth/vnc-recorder: Could not start container and seg fault

### ISSUE THREAD

**Issue by kikogolk** [testcontainers/testcontainers-java#706]
Hi!

I am trying to use testcontainers in my project (1.7.2) and I am getting some issues related with the containers. Just to be sure it was not any issue related with my project, I downloaded your testcontainers-java-examples project and try to execute the selenium-container example, getting the same issue.

These are the logs I got:
```
18:52:30.663 [main] INFO  🐳 [richnorth/vnc-recorder:latest] - Container richnorth/vnc-recorder:latest is starting: ae1406ceff13e785e93f1cafb8f78d6a41ae95770bb39474c5dbefe43c9b2082
18:53:30.690 [main] ERROR 🐳 [richnorth/vnc-recorder:latest] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output
	at org.testcontainers.containers.VncRecordingContainer$1.waitUntilReady(VncRecordingContainer.java:91) ~[testcontainers--1.7.3-g0aeaec3-2.jar:na]
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:32) ~[testcontainers--1.7.3-g0aeaec3-2.jar:na]
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:531) [testcontainers--1.7.3-g0aeaec3-2.jar:na]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:258) [testcontainers--1.7.3-g0aeaec3-2.jar:na]
	at org.testcontainers.containers.GenericContainer.lambda$start$0(GenericContainer.java:209) [testcontainers--1.7.3-g0aeaec3-2.jar:na]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76) ~[duct-tape-1.0.7.jar:na]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:207) [testcontainers--1.7.3-g0aeaec3-2.jar:na]
	at org.testcontainers.containers.BrowserWebDriverContainer.containerIsStarted(BrowserWebDriverContainer.java:189) ~[selenium--SNAPSHOT.jar:na]
```

```
18:53:30.703 [main] ERROR 🐳 [richnorth/vnc-recorder:latest] - Container log output (if any) will follow:
18:53:30.708 [testcontainers-netty-1-1] INFO  🐳 [richnorth/vnc-recorder:latest] - STDERR: Segmentation fault (core dumped)
18:53:30.714 [main] ERROR 🐳 [selenium/standalone-chrome-debug:2.45.0] - Could not start container
```

I attached the complete maven logs if you need them:
[logs.txt](https://github.com/testcontainers/testcontainers-java/files/2019663/logs.txt)

Thanks a lot for your support,

**Comment by eddumelendez** [comment]
@kikogolk I think you should not have those issues with recent versions of Testcontainers. If so, can we close this one?
