### ISSUE TITLE
[Enhancement]: Access Chrome Dev Tools via SE_NODE_GRID_URL 

### ISSUE THREAD

**Issue by volosied** [testcontainers/testcontainers-java#7242]
### Module

Selenium

### Proposal

I would like to be able to access  Chrome Dev Tools easily  because I cannot while running on TestContainers.  The [selenium website]( https://www.selenium.dev/documentation/webdriver/bidirectional/chrome_devtools/   ) provides the following RemoteWebDriver example:

```
ChromeOptions chromeOptions = new ChromeOptions();
WebDriver driver = new RemoteWebDriver(new URL("<grid-url>"), chromeOptions);
driver = new Augmenter().augment(driver);

DevTools devTools = ((HasDevTools) driver).getDevTools();
devTools.createSession();
``` 

The issue is with the augment call.  It tries to connect via the image's internal address, and I get the following exception: 

```
[06/27/2023 22:37:42:000 EDT] 043 WebSocket$Listener             onError                        W Network is unreachable: /172.17.0.4:4444
java.net.ConnectException: Network is unreachable: /172.17.0.4:4444
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	at org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.channel.AbstractChannel$AnnotatedSocketException: Network is unreachable: /172.17.0.4:4444
Caused by: java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
```

The solution, from what I've been able to find, is to set up the SE_NODE_GRID_URL environment variable. However, this is where I'm stuck.  Testcontainers maps to a random port, so I can not just specify http://localhost:4444 (as indicated in issues like [here](https://groups.google.com/g/selenium-users/c/N0RN8jdQNk0) and [here](https://github.com/SeleniumHQ/docker-selenium/issues/1451))  without knowing which port 4444 is mapped to externally.

If I try running docker manually (ie. docker run -p 4444:444 -e SE_NODE_GRID_URL="http://localhost:4444" <container image>  as suggested in the linked issues ) and connect to this URL then the connection works fine.   It's just this port randomization that I can't work around.  

I appreciate any feedback or workarounds! Thanks!

**Comment by eddumelendez** [comment]
Hi @volosied, I've been thinking about it and I think I found something that will make it work

```
Network network = Network.newNetwork();

SocatContainer socatContainer = new SocatContainer()
        .withTarget(2000, "chrome", 4444)
        .withNetworkAliases("proxy")
        .withNetwork(network);
socatContainer.start();

BrowserWebDriverContainer<?> chrome = new BrowserWebDriverContainer<>()
        .withCapabilities(new ChromeOptions())
        .withEnv("SE_NODE_GRID_URL", String.format("http://%s:%d", socatContainer.getHost(), socatContainer.getMappedPort(2000)))
        .withNetworkAliases("chrome")
        .withNetwork(network)
```

Using `SocatContainer` you will make sure a random port is still used in your tests and that one can be set as `SE_NODE_GRID_URL` env var. I was able to create `devTools.createSession();` and get `devTools.getCdpSession()`.

Please, LMK if that helps.

**Comment by eddumelendez** [comment]
@volosied if the issue persist, feel free to reopen the issue.
