### ISSUE TITLE
[Bug]: shade jackson-annotations 

### ISSUE THREAD

**Issue by atais** [testcontainers/testcontainers-java#7399]
### Module

Core

### Testcontainers version

1.18.1

### Using the latest Testcontainers version?

No

### Host OS

Mac

### Host Arch

ARM

### Docker version

```shell
Docker version 24.0.2-rd, build e63f5fa
```

### What happened?

If I am not adding:

```
  <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>${jackson-annotations.testcontainers.version}</version>
  </dependency>
```

to my project, since I am using Spark, it uses version 2.6.7 or something like this, and the test failes.

Could we add `jackson-annotations` to shaded libs?

### Relevant log output

```shell
{code}
  Cause: java.lang.NoSuchMethodError: com.fasterxml.jackson.annotation.JsonFormat$Value.empty()Lcom/fasterxml/jackson/annotation/JsonFormat$Value;
  at org.testcontainers.shaded.com.fasterxml.jackson.databind.cfg.MapperConfig.<clinit>(MapperConfig.java:49)
  at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:558)
  at org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:474)
  at org.testcontainers.shaded.com.github.dockerjava.core.DefaultObjectMapperHolder.<init>(DockerClientConfig.java:68)
  at org.testcontainers.shaded.com.github.dockerjava.core.DefaultObjectMapperHolder.<clinit>(DockerClientConfig.java:66)
  at org.testcontainers.shaded.com.github.dockerjava.core.DockerClientConfig.getDefaultObjectMapper(DockerClientConfig.java:36)
  at org.testcontainers.shaded.com.github.dockerjava.core.DefaultDockerClientConfig$Builder.readDockerConfig(DefaultDockerClientConfig.java:470)
  at org.testcontainers.shaded.com.github.dockerjava.core.DefaultDockerClientConfig$Builder.build(DefaultDockerClientConfig.java:457)
  at org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy.<init>(EnvironmentAndSystemPropertyClientProviderStrategy.java:57)
  at org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy.<init>(EnvironmentAndSystemPropertyClientProviderStrategy.java:34)
{code}
```

### Additional Information

Use shading for the whole jackson lib?

Don't understand why https://github.com/testcontainers/testcontainers-java/issues/6161 was closed by the author

**Comment by eddumelendez** [comment]
Hi, that's not currently possible due to the `jackson-annotations` library is not only used with other shaded libraries but also with the `DockerClient` itself and perform operations.

```java
GenericContainer<?> redis = new GenericContainer<>("redis:7-alpine")
    .withExposedPorts(6379);
redis.start();
DockerClient dockerClient = redis.getDockerClient();
```
