### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by prasanna-marathe** [testcontainers/testcontainers-java#7430]
### Module

MongoDB

### Testcontainers version

1.18.3

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

PPC64LE(Power)

### Docker version

```shell
Issue occurs while building code only on Power architecture.
[root@p006vm33 ~]# docker --version
Docker version v24.0.2, build cb74dfc
[root@p006vm33 ~]#
```

### What happened?

JAVA Environment:
JAVA Version: JAVA17
JAVAC Version: JAVA17
JAVA_HOME=/usr/lib/jvm/java-17-openjdk-17.0.8.0.7-2.el8.ppc64le/

Trying to build mongodb module on IBM power platform using JAVA17. 
command used: 
```
gradle build -p modules/mongodb/
```

However getting below error

```
 What went wrong:
Execution failed for task ':mongodb:japicmp'.
> A failure occurred while executing me.champeau.gradle.japicmp.JApiCmpWorkAction
   > Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because "com.sun.xml.bind.v2.runtime.reflect.opt.Injector.defineClass" is null
  ``` 

### Relevant log output

```shell
[root@p006vm33 testcontainers-java]# ./gradlew build -p modules/mongodb/
Starting a Gradle Daemon (subsequent builds will be faster)
Configuration on demand is an incubating feature.
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :testcontainers:compileJava UP-TO-DATE
> Task :mongodb:compileJava UP-TO-DATE
> Task :mongodb:processResources UP-TO-DATE
> Task :mongodb:classes UP-TO-DATE
> Task :mongodb:jar UP-TO-DATE
> Task :mongodb:assemble UP-TO-DATE
> Task :mongodb:checkstyleMain UP-TO-DATE
> Task :mongodb:compileTestJava UP-TO-DATE
> Task :mongodb:processTestResources UP-TO-DATE
> Task :mongodb:testClasses UP-TO-DATE
> Task :mongodb:checkstyleTest UP-TO-DATE
> Task :mongodb:shadowJar UP-TO-DATE
> Task :mongodb:delombok UP-TO-DATE
> Task :mongodb:javadoc UP-TO-DATE
> Task :spotlessInternalRegisterDependencies UP-TO-DATE
> Task :mongodb:spotlessGroovyGradle UP-TO-DATE
> Task :mongodb:spotlessGroovyGradleCheck UP-TO-DATE
> Task :mongodb:spotlessJava UP-TO-DATE
> Task :mongodb:spotlessJavaCheck UP-TO-DATE
> Task :mongodb:spotlessCheck UP-TO-DATE
> Task :testcontainers:processResources UP-TO-DATE
> Task :testcontainers:classes UP-TO-DATE
> Task :testcontainers:jar UP-TO-DATE
> Task :testcontainers:shadowJar UP-TO-DATE

> Task :mongodb:japicmp FAILED
null
java.security.PrivilegedActionException: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:573)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.<clinit>(Injector.java:197)
        at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:81)
        at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:125)
        at com.sun.xml.bind.v2.runtime.reflect.Accessor$GetterSetterReflection.optimize(Accessor.java:402)
        at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.<init>(TransducedAccessor.java:235)
        at com.sun.xml.bind.v2.runtime.reflect.TransducedAccessor.get(TransducedAccessor.java:175)
        at com.sun.xml.bind.v2.runtime.property.AttributeProperty.<init>(AttributeProperty.java:91)
        at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:108)
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:181)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:514)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:331)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:139)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1156)
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:165)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:297)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:286)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:409)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
        at japicmp.output.xml.XmlOutputGenerator.createXmlDocumentAndSchema(XmlOutputGenerator.java:119)
        at japicmp.output.xml.XmlOutputGenerator.generate(XmlOutputGenerator.java:70)
        at me.champeau.gradle.japicmp.JApiCmpWorkerAction.generateOutput(JApiCmpWorkerAction.java:240)
        at me.champeau.gradle.japicmp.JApiCmpWorkerAction.run(JApiCmpWorkerAction.java:175)
        at me.champeau.gradle.japicmp.JApiCmpWorkAction.execute(JApiCmpWorkAction.java:9)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:54)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:48)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:48)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:49)
        at org.gradle.workers.internal.IsolatedClassloaderWorker.run(IsolatedClassloaderWorker.java:30)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:96)
        at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:65)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
        at java.base/java.lang.Class.getMethod(Class.java:2227)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:201)
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector$3.run(Injector.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        ... 54 more

> Task :mongodb:test
```

### Additional Information

This issue is also observed while compiling  other modules on Power platform

**Comment by eddumelendez** [comment]
Testcontainers for Java is built with Java 8.
