### ISSUE TITLE
Cannot use custom Dockerfiles with FixedHostPortGenericContainer

### ISSUE THREAD

**Issue by alexpdp7** [testcontainers/testcontainers-java#757]
It hides the `Future<String>` constructor, if I try:

```
ImageFromDockerfile dockerImage = new ImageFromDockerfile().withFileFromClasspath("Dockerfile", "Dockerfile");
try (FixedHostPortGenericContainer<?> container = new FixedHostPortGenericContainer<>(dockerImage.getDockerImageName())) {
```

I get:

```
Exception in thread "main" java.lang.NullPointerException
	at org.testcontainers.utility.DockerImageName.toString(DockerImageName.java:97)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at org.testcontainers.images.RemoteDockerImage.toString(RemoteDockerImage.java:25)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:841)
	at org.testcontainers.containers.GenericContainer.setDockerImageName(GenericContainer.java:829)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:185)
	at org.testcontainers.containers.FixedHostPortGenericContainer.<init>(FixedHostPortGenericContainer.java:16)
```

(on testcontainers 1.7.3)

**Comment by kiview** [comment]
The exception is to be expected, you can't `getDockerImageName()` before the image is built.
This feature is indeed missing.

Btw. I wonder what's your use case for `FixedHostPortGenericContainer` since we generally discourage its usage.

**Comment by alexpdp7** [comment]
Hi,

I'm perverting your library, I'm afraid. I'm writing a project which is a gRPC server and I need to use grpcwebproxy to expose it to browsers. So what I do in my dev environment is to use testcontainers to spin up the grpcwebproxy for convenience (when I start my gRPC server, the grpcwebproxy is started, etc.).

So I'm outside the intended use case of your library, but it's so daaamn convenient... I've pushed my image to Docker Hub so I can live without the feature.

Cheers,

Álex

**Comment by bsideup** [comment]
Hi Alex,

Just do image.get() ;)
It will build an image and return it's id which can be used as an argument
of the constructor.

**Comment by alexpdp7** [comment]
Hi @bsideup :

If you mean:

```
import org.testcontainers.containers.FixedHostPortGenericContainer;
import org.testcontainers.images.builder.ImageFromDockerfile;

public class Bug {
	public static void main(String[] args) throws Exception {
		ImageFromDockerfile dockerImage = new ImageFromDockerfile().withFileFromClasspath("Dockerfile", "Dockerfile");
		try (FixedHostPortGenericContainer<?> container = new FixedHostPortGenericContainer<>(dockerImage.get())) {
			
		}
	}
}
```

This fails with:

```
Jun 22, 2018 9:55:32 PM org.testcontainers.DockerClientFactory client
INFO: Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
        ℹ︎ Checking the system...
        ✔ Docker version should be at least 1.6.0
        ✔ Docker environment should have more than 2GB free disk space
        ✔ File should be mountable
Exception in thread "main" java.lang.NullPointerException
	at org.testcontainers.utility.DockerImageName.toString(DockerImageName.java:97)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at org.testcontainers.images.RemoteDockerImage.toString(RemoteDockerImage.java:25)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:841)
	at org.testcontainers.containers.GenericContainer.setDockerImageName(GenericContainer.java:829)
	at org.testcontainers.containers.GenericContainer.<init>(GenericContainer.java:185)
	at org.testcontainers.containers.FixedHostPortGenericContainer.<init>(FixedHostPortGenericContainer.java:16)
	at net.pdp7.imnei.server.Bug.main(Bug.java:9)
```

**Comment by bsideup** [comment]
@alexpdp7 could you please try Testcontainers 1.8.0?

**Comment by alexpdp7** [comment]
Oh, sorry, that works :(
