### ISSUE TITLE
[Bug]: A PostgreSQLContainer over an existing DB is never seen as starting

### ISSUE THREAD

**Issue by caluml** [testcontainers/testcontainers-java#7648]
### Module

PostgreSQL

### Testcontainers version

1.19.1

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

X86_64

### Docker version

```shell
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:17 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

When starting a Postgres container over an existing database*, the log output "database system is ready to accept connections" is output over STDERR, which doesn't seem to be seen by the LogMessageWaitStrategy (although I see
    .withStdOut(true)
    .withStdErr(true);
in the LogMessageWaitStrategy code.)

This means that the container is never seen as being ready.

* Yes, I need to do this - it's not a way of pre-populating a database before tests

### Relevant log output

```shell
2023-10-11T04:50:50.439+01:00 DEBUG 17362 --- [o-auto-1-exec-1] o.t.containers.output.WaitingConsumer    : STDOUT: PostgreSQL Database directory appears to contain a database; Skipping initialization
2023-10-11T04:50:50.470+01:00 DEBUG 17362 --- [o-auto-1-exec-1] o.t.containers.output.WaitingConsumer    : STDERR: 2023-10-11 03:50:50.469 UTC [1] LOG:  starting PostgreSQL 15.4 (Debian 15.4-2.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2023-10-11T04:50:50.471+01:00 DEBUG 17362 --- [o-auto-1-exec-1] o.t.containers.output.WaitingConsumer    : STDERR: 2023-10-11 03:50:50.470 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-10-11T04:50:50.471+01:00 DEBUG 17362 --- [o-auto-1-exec-1] o.t.containers.output.WaitingConsumer    : STDERR: 2023-10-11 03:50:50.469 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-10-11T04:50:50.481+01:00 DEBUG 17362 --- [o-auto-1-exec-1] o.t.containers.output.WaitingConsumer    : STDERR: 2023-10-11 03:50:50.478 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-10-11T04:50:50.492+01:00 DEBUG 17362 --- [o-auto-1-exec-1] o.t.containers.output.WaitingConsumer    : STDERR: 2023-10-11 03:50:50.488 UTC [29] LOG:  database system was interrupted; last known up at 2023-10-11 03:49:58 UTC
2023-10-11T04:50:50.731+01:00 DEBUG 17362 --- [o-auto-1-exec-1] o.t.containers.output.WaitingConsumer    : STDERR: 2023-10-11 03:50:50.731 UTC [29] LOG:  database system was not properly shut down; automatic recovery in progress
2023-10-11T04:50:50.742+01:00 DEBUG 17362 --- [o-auto-1-exec-1] o.t.containers.output.WaitingConsumer    : STDERR: 2023-10-11 03:50:50.736 UTC [29] LOG:  redo done at 0/1AFC2E8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
2023-10-11T04:50:50.742+01:00 DEBUG 17362 --- [o-auto-1-exec-1] o.t.containers.output.WaitingConsumer    : STDERR: 2023-10-11 03:50:50.736 UTC [29] LOG:  invalid record length at 0/1AFE2A0: wanted 24, got 0
2023-10-11T04:50:50.742+01:00 DEBUG 17362 --- [o-auto-1-exec-1] o.t.containers.output.WaitingConsumer    : STDERR: 2023-10-11 03:50:50.736 UTC [29] LOG:  redo starts at 0/1AFC2E8
2023-10-11T04:50:50.753+01:00 DEBUG 17362 --- [o-auto-1-exec-1] o.t.containers.output.WaitingConsumer    : STDERR: 2023-10-11 03:50:50.744 UTC [27] LOG:  checkpoint starting: end-of-recovery immediate wait
2023-10-11T04:50:50.772+01:00 DEBUG 17362 --- [o-auto-1-exec-1] o.t.containers.output.WaitingConsumer    : STDERR: 2023-10-11 03:50:50.772 UTC [27] LOG:  checkpoint complete: wrote 5 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.008 s, sync=0.007 s, total=0.032 s; sync files=4, longest=0.004 s, average=0.002 s; distance=8 kB, estimate=8 kB
2023-10-11T04:50:50.783+01:00 DEBUG 17362 --- [o-auto-1-exec-1] o.t.containers.output.WaitingConsumer    : STDERR: 2023-10-11 03:50:50.779 UTC [1] LOG:  database system is ready to accept connections
2023-10-11T04:51:50.523+01:00 DEBUG 17362 --- [o-auto-1-exec-1] o.t.s.c.g.d.core.command.AbstrDockerCmd  : Cmd: 84c9035b2c5831bb39afd5fbc64e613ceae8e1f6fcdebf02b36af06acb2f0e78,false
2023-10-11T04:51:50.523+01:00 DEBUG 17362 --- [o-auto-1-exec-1] o.t.s.c.g.d.c.e.InspectContainerCmdExec  : GET: DefaultWebTarget{path=[/containers/84c9035b2c5831bb39afd5fbc64e613ceae8e1f6fcdebf02b36af06acb2f0e78/json], queryParams={}}
2023-10-11T04:51:50.528+01:00 ERROR 17362 --- [o-auto-1-exec-1] tc.postgres:15-bookworm                  : Could not start container

org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*database system is ready to accept connections.*\s'
	at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47) ~[testcontainers-1.19.1.jar:1.19.1]
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52) ~[testcontainers-1.19.1.jar:1.19.1]
```

### Additional Information

To reproduce, run
```
	@Test
	public void reproduce() {
		PostgreSQLContainer container = new PostgreSQLContainer<>("postgres:15-bookworm")
			.withFileSystemBind("/tmp/github", "/var/lib/postgresql/data")
			.withCommand("postgres");
		container.start();
	}
```
twice.

**Comment by eddumelendez** [comment]
Please read the form before to fill it.

Closing as duplicated of https://github.com/testcontainers/testcontainers-java/issues/5359
