### ISSUE TITLE
[Bug]: Kafka fails to start when using new test containers library version

### ISSUE THREAD

**Issue by SofiaVynnytska12** [testcontainers/testcontainers-java#7656]
### Module

Kafka

### Testcontainers version

1.19.0

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host Arch

x64

### Docker version

```shell
Client:
 Cloud integration: v1.0.35+desktop.4
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:48 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.23.0 (120376)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

When configuring Kafka in test containers using library of version 1.18.0 and later, container fails to start in both zookeeper and kraft mode.

```
public static KafkaContainer kafka = new KafkaContainer(DockerImageName.parse("confluentinc/cp-kafka:7.5.1")).withKraft().withStartupAttempts(3);
kafka.start();
```

### Relevant log output

```shell
java.lang.NoSuchMethodError: 'org.testcontainers.images.builder.Transferable org.testcontainers.images.builder.Transferable.of(java.lang.String, int)'

	at org.testcontainers.containers.KafkaContainer.containerIsStarting(KafkaContainer.java:195)
	at org.testcontainers.containers.GenericContainer.containerIsStarting(GenericContainer.java:678)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:457)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
```

**Comment by eddumelendez** [comment]
can you try 1.19.1? If the issue persist please submit a project to reproduce the error

**Comment by eddumelendez** [comment]
I've had examples running since Testcontainers 1.18.0 without issues. See https://github.com/eddumelendez/testcontainers-samples/tree/main/spring-boot-kafka
