### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by xaviarias** [testcontainers/testcontainers-java#774]
Hi,

I have an issue starting a multi-container test with Test Containers 1.8.0 and Java gRPC 1.13.1.

The error appears when starting a gRPC server at port 11123. Before starting the image as a generic container, there are other generic containers I need to start, but no other is using gRPC or starting a process at this port.

If I run the failing container all alone or with Docker it starts without any problem, but if I start it after the other containers, Netty throws this exception:

```
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1358)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:1019)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

To start the gRPC  server I have tried using the Reuse Address option in Netty:

```java
    NettyServerBuilder.forPort(11123)
        .withChildOption(ChannelOption.SO_REUSEADDR, true)
        .addService(new MyService())
        .build()
```

Not completely sure but everything points that there is an issue with the TestContainers ports. Any ideas on what could it be? 

Thanks

**Comment by xaviarias** [comment]
Hi @rnorth, since then we are not using Tescontainers anymore for now, proceed as you need with this issue.
