### ISSUE TITLE
Broken Pipe when sending label to ryuk container

### ISSUE THREAD

**Issue by thorstenwitt** [testcontainers/testcontainers-java#780]
In some cases I get this error when trying to make java integration tests with mysql.
This only happens on our teamcity server with debian jessie. 

Teamcity calls the task `gradle test`

This is the output

`2018-07-11 17:43:54.346 DEBUG   --- [    Test worker] o.t.utility.TestcontainersConfiguration  : Testcontainers configuration overrides loaded from TestcontainersConfiguration(properties={docker.client.strategy=org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy, ryuk.container.timeout=90})
2018-07-11 17:43:54.380  INFO   --- [    Test worker] o.t.d.DockerClientProviderStrategy       : Loaded org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy from ~/.testcontainers.properties, will try it first
2018-07-11 17:43:54.412  INFO   --- [    Test worker] o.t.d.DockerClientProviderStrategy       : Will use 'netty' transport
2018-07-11 17:43:55.424  INFO   --- [    Test worker] tAndSystemPropertyClientProviderStrategy : Found docker client settings from environment
2018-07-11 17:43:55.452  INFO   --- [    Test worker] o.t.d.DockerClientProviderStrategy       : Found Docker environment with Environment variables, system properties and defaults. Resolved: 
    dockerHost=unix:///var/run/docker.sock
    apiVersion='{UNKNOWN_VERSION}'
    registryUrl='https://index.docker.io/v1/'
    registryUsername='teamcity'
    registryPassword='null'
    registryEmail='null'
    dockerConfig='DefaultDockerClientConfig[dockerHost=unix:///var/run/docker.sock,registryUsername=teamcity,registryPassword=<null>,registryEmail=<null>,registryUrl=https://index.docker.io/v1/,dockerConfigPath=/home/teamcity/.docker,sslConfig=<null>,apiVersion={UNKNOWN_VERSION},dockerConfig=<null>]'

2018-07-11 17:43:55.455  INFO   --- [    Test worker] org.testcontainers.DockerClientFactory   : Docker host IP address is localhost
2018-07-11 17:43:56.072  INFO   --- [    Test worker] org.testcontainers.DockerClientFactory   : Connected to docker: 
  Server Version: 18.03.1-ce
  API Version: 1.37
  Operating System: Debian GNU/Linux 8 (jessie)
  Total Memory: 15773 MB
2018-07-11 17:43:56.192 DEBUG   --- [    Test worker] o.testcontainers.utility.MountableFile   : Copying classpath resource(s) from jar:file:/home/teamcity/.gradle/caches/modules-2/files-2.1/org.testcontainers/testcontainers/1.8.0/bc413912f7044f9f12aa0782853aef0a067ee52a/testcontainers-1.8.0.jar!/org/testcontainers/utility/ResourceReaper.class to /tmp/.testcontainers-tmp-4999372261342671633 to permit Docker to bind
2018-07-11 17:43:56.193 DEBUG   --- [    Test worker] o.testcontainers.utility.MountableFile   : Copying resource org/testcontainers/utility/ResourceReaper.class from JAR file /home/teamcity/.gradle/caches/modules-2/files-2.1/org.testcontainers/testcontainers/1.8.0/bc413912f7044f9f12aa0782853aef0a067ee52a/testcontainers-1.8.0.jar
2018-07-11 17:44:08.056 TRACE   --- [    Test worker] org.testcontainers.utility.AuditLogger   : START action with image: null, containerId: 93ab21705ef235522090263413115e36ad5ed52f3bca2c74b2b49065cf04951e
2018-07-11 17:44:08.181 DEBUG   --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Sending 'label=org.testcontainers%3Dtrue&label=org.testcontainers.sessionId%3D4b81df97-9d4d-444d-be99-42b4c7f26904' to Ryuk
2018-07-11 17:44:08.182  WARN   --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Can not connect to Ryuk at localhost:32772

java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:132)
	at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:144)
	at java.lang.Thread.run(Thread.java:745)

2018-07-11 17:44:08.183 DEBUG   --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Sending 'label=org.testcontainers%3Dtrue&label=org.testcontainers.sessionId%3D4b81df97-9d4d-444d-be99-42b4c7f26904' to Ryuk
2018-07-11 17:44:08.184  WARN   --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Can not connect to Ryuk at localhost:32772

java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:132)
	at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:144)
	at java.lang.Thread.run(Thread.java:745)

2018-07-11 17:44:08.185 DEBUG   --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Sending 'label=org.testcontainers%3Dtrue&label=org.testcontainers.sessionId%3D4b81df97-9d4d-444d-be99-42b4c7f26904' to Ryuk
2018-07-11 17:44:08.185  WARN   --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Can not connect to Ryuk at localhost:32772

java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:132)
	at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:144)
	at java.lang.Thread.run(Thread.java:745)

2018-07-11 17:44:08.186 DEBUG   --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Sending 'label=org.testcontainers%3Dtrue&label=org.testcontainers.sessionId%3D4b81df97-9d4d-444d-be99-42b4c7f26904' to Ryuk
2018-07-11 17:44:08.187  WARN   --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Can not connect to Ryuk at localhost:32772

java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:132)
	at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:144)
	at java.lang.Thread.run(Thread.java:745)

2018-07-11 17:44:08.187 DEBUG   --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Sending 'label=org.testcontainers%3Dtrue&label=org.testcontainers.sessionId%3D4b81df97-9d4d-444d-be99-42b4c7f26904' to Ryuk
2018-07-11 17:44:08.188  WARN   --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Can not connect to Ryuk at localhost:32772

java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:132)
	at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:144)
	at java.lang.Thread.run(Thread.java:745)

2018-07-11 17:44:08.188 DEBUG   --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Sending 'label=org.testcontainers%3Dtrue&label=org.testcontainers.sessionId%3D4b81df97-9d4d-444d-be99-42b4c7f26904' to Ryuk
2018-07-11 17:44:08.189  WARN   --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Can not connect to Ryuk at localhost:32772

java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:132)
	at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:144)
	at java.lang.Thread.run(Thread.java:745)

2018-07-11 17:44:08.189 DEBUG   --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Sending 'label=org.testcontainers%3Dtrue&label=org.testcontainers.sessionId%3D4b81df97-9d4d-444d-be99-42b4c7f26904' to Ryuk
2018-07-11 17:44:08.189  WARN   --- [containers-ryuk] o.testcontainers.utility.ResourceReaper  : Can not connect to Ryuk at localhost:32772

java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:132)
	at org.testcontainers.utility.ResourceReaper.lambda$start$2(ResourceReaper.java:144)
	at java.lang.Thread.run(Thread.java:745)`

I have already increased the timeout in the container.properties: `ryuk.container.timeout=90`

**Comment by bsideup** [comment]
Hi @thorstenwitt! 

Does it happen with the previous version (1.8.0)?

**Comment by thorstenwitt** [comment]
Hi @bsideup 

yes we use 1.8.0.

**Comment by bsideup** [comment]
@thorstenwitt does it also happen if you add `checks.disable=true` to your `testcontainers.properties`? See there:
https://www.testcontainers.org/usage/properties.html

**Comment by thorstenwitt** [comment]
hi @bsideup ,

when `checks.disable=true` the issue does not happen

**Comment by thammerl** [comment]
Might be fixed by #843.

**Comment by kiview** [comment]
I'll close this for now, please inform us if the issue still persist.
