### ISSUE TITLE
[Bug]: Testcontainers 1.19.2 throws StackOverflowError

### ISSUE THREAD

**Issue by straurob** [testcontainers/testcontainers-java#7828]
### Module

Core

### Testcontainers version

1.19.2

### Using the latest Testcontainers version?

Yes

### Host OS

Fedora 39

### Host Arch

x64

### Docker version

```shell
lient: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:09:56 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:22 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

When running a Spring Boot integration test with the `@SpringBootTest` annotation, the test fails with the following exception. To be more precise, the test doesn't even get instantiated.

Unfortunately, I haven't been able yet to track down the issue. Maybe it is related to my test setup or another test dependency, but if I downgrade the Testcontainers version to 1.19.1, the test runs successfully.

```java
22:42:41.145 [main] INFO org.testcontainers.ext.ScriptUtils -- Executing database script from db/init.sql
Exception in thread "main" java.lang.StackOverflowError
	at java.base/java.lang.StringUTF16.checkIndex(StringUTF16.java:1624)
	at java.base/java.lang.StringUTF16.charAt(StringUTF16.java:1421)
	at java.base/java.lang.String.charAt(String.java:1515)
	at java.base/java.lang.Character.codePointAt(Character.java:8910)
	at java.base/java.util.regex.Pattern$CharProperty.match(Pattern.java:3927)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4734)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
	at java.base/java.util.regex.Pattern$Loop.match(Pattern.java:4898)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
	at java.base/java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4734)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
	at java.base/java.util.regex.Pattern$Loop.match(Pattern.java:4898)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
	at java.base/java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4734)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
	at java.base/java.util.regex.Pattern$Loop.match(Pattern.java:4898)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
	at java.base/java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4734)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
	at java.base/java.util.regex.Pattern$Loop.match(Pattern.java:4898)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
	at java.base/java.util.regex.Pattern$CharProperty.match(Pattern.java:3931)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4734)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4789)
	at java.base/java.util.regex.Pattern$Loop.match(Pattern.java:4898)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4820)
	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4698)
```

**Comment by eddumelendez** [comment]
Hi, this has been fixed via https://github.com/testcontainers/testcontainers-java/pull/7818
