### ISSUE TITLE
[Bug]: TC is failing to start the VNC container

### ISSUE THREAD

**Issue by vmassol** [testcontainers/testcontainers-java#8053]
### Module

Core

### Testcontainers version

1.19.3

### Using the latest Testcontainers version?

Yes

### Host OS

linux, max osx

### Host Arch

x86, arm

### Docker version

```shell
$ docker version
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.25.2 (129061)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```


### What happened?

The XWiki functional tests use TC and we capture screenshots and videos by starting the VNC container.  This used to work well and suddenly a few week(s) ago, it started failing to start the VNC container.

I don't know how to debug this. Any help is most welcome. Thanks!

### Relevant log output

```shell
01:35:03.700 [main] ERROR t.testcontainers/vnc-recorder:1.3.0 - Could not start container
java.lang.IllegalStateException: Wait strategy failed. Container exited with code 1
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:536)
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:357)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:347)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:333)
        at org.xwiki.test.docker.internal.junit5.DockerTestUtils.startContainerInternal(DockerTestUtils.java:218)
...
Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Connected.*'
        at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)
        at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
        at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:912)
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:503)
```

And in the TC logs, we see:

```
10:22:05.501 [main] DEBUG o.t.c.output.WaitingConsumer - STDERR: write_header: flv_version=1, audio=False, video=True
10:22:05.502 [main] DEBUG o.t.c.output.WaitingConsumer - END: 
10:22:05.502 [main] DEBUG o.t.c.output.WaitingConsumer - END: 
10:22:05.502 [main] DEBUG o.t.c.output.WaitingConsumer - STDERR: write_metadata: {'duration': 0.0, 'width': 0, 'framerate': 30, 'videocodecid': 3, 'height': 0}
10:22:05.502 [main] DEBUG o.t.c.output.WaitingConsumer - STDERR: flush
10:22:05.502 [main] DEBUG o.t.c.output.WaitingConsumer - STDERR: stop recording
10:22:05.502 [main] DEBUG o.t.c.output.WaitingConsumer - STDERR: Socket error: [Errno 111] Connection refused
10:22:05.502 [main] DEBUG o.t.c.output.WaitingConsumer - STDERR: start recording
10:22:05.502 [main] DEBUG o.t.c.output.WaitingConsumer - STDERR: write_metadata: {'duration': 0, 'width': 0, 'framerate': 30, 'videocodecid': 3, 'height': 0}
10:22:20.414 [main] DEBUG t.testcontainers/vnc-recorder:1.3.0 - Wait strategy threw an exception
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Connected.*'
        at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:47)
        at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52)
        at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:912)
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:503)
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:357)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:347)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:333)
        at org.xwiki.test.docker.internal.junit5.DockerTestUtils.startContainerInternal(DockerTestUtils.java:218)
```
```


### Additional Information

This is where we start the VNC container: https://github.com/xwiki/xwiki-platform/blob/0657206bd1175a6c4e7d11404d44e87445010841/xwiki-platform-core/xwiki-platform-test/xwiki-platform-test-docker/src/main/java/org/xwiki/test/docker/internal/junit5/XWikiDockerExtension.java#L225-L247

**Comment by omegagussan** [comment]
+1 here

**Comment by vmassol** [comment]
Seems the issue has been fixed as I don't reproduce the problem anymore with version 1.19.8.

**Comment by omegagussan** [comment]
Thats strange. Its exaclty:     
`testImplementation("org.testcontainers:testcontainers:1.19.8")
`
that Im using and Im getting the same logs you did:
`write_header: flv_version=1, audio=False, video=True
write_metadata: {'duration': 0, 'width': 0, 'framerate': 30, 'videocodecid': 3, 'height': 0}
start recording
Socket error: [Errno 111] Connection refused
stop recording
flush
write_metadata: {'duration': 0.0, 'width': 0, 'framerate': 30, 'videocodecid': 3, 'height': 0}
`
when creating a [selenium/standalone-chrome:4.18.1](app://dd/dashboard/images/local/sha256:aac002c2f7645da565b0aba78f8fdfa80d3473957570a950dbc2b0e460a8964f?tag=4.18.1&name=selenium%2Fstandalone-chrome)

**Comment by omegagussan** [comment]
[selenium/standalone-chrome:4.22.0](app://dd/dashboard/images/local/sha256:a0672e3f5bb07f535b09d923726c31e05127976609c2ee50ae3189efea82f220?tag=4.22.0&name=selenium%2Fstandalone-chrome) upgrade chrome and it worked. Sorry for the fuss
