### ISSUE TITLE
[Bug]: Starting elasticsearch container from spring boot 3.2 uber jar is broken because of nested url

### ISSUE THREAD

**Issue by amergey** [testcontainers/testcontainers-java#8111]
### Module

Core

### Testcontainers version

1.19.3

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host Arch

ARM

### Docker version

```shell
24.0.5
```

### What happened?

Starting elasticsearch container from spring boot uber jar is broken since spring boot 3.2 because of https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#nested-jar-support.

This is not related to elasticsearch itself but org.testcontainers.utility.MountableFile.extractClassPathResourceToTempLocation(String) is messing up the url and custom spring boot format should be supported 

The workaround given in spring boot doc is working, but this should MountableFile should probably be fixed

### Relevant log output

```shell
`Caused by: java.nio.file.NoSuchFileException: nested:/home/mybootapp-boot.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:?]
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148) ~[?:?]
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99) ~[?:?]
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851) ~[?:?]
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264) ~[?:?]
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709) ~[?:?]
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243) ~[?:?]
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172) ~[?:?]
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:347) ~[?:?]
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:318) ~[?:?]
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:257) ~[?:?]
	at org.testcontainers.utility.MountableFile.extractClassPathResourceToTempLocation(MountableFile.java:241) ~[testcontainers-1.19.3.jar!/:1.19.3]
	at org.testcontainers.utility.MountableFile.getResourcePath(MountableFile.java:219) ~[testcontainers-1.19.3.jar!/:1.19.3]
	at org.testcontainers.utility.MountableFile.resolvePath(MountableFile.java:187) ~[testcontainers-1.19.3.jar!/:1.19.3]
	at org.testcontainers.utility.MountableFile.getResolvedPath(MountableFile.java:58) ~[testcontainers-1.19.3.jar!/:1.19.3]
	at org.testcontainers.containers.ContainerState.copyFileToContainer(ContainerState.java:299) ~[testcontainers-1.19.3.jar!/:1.19.3]
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:444) ~[testcontainers-1.19.3.jar!/:1.19.3]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:357) ~[testcontainers-1.19.3.jar!/:1.19.3]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar!/:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:347) ~[testcontainers-1.19.3.jar!/:1.19.3]
`
```

**Comment by eddumelendez** [comment]
Hi, I have the following [example](https://github.com/eddumelendez/testcontainers-samples/tree/main/spring-boot-elasticsearch/src/test/java/com/example/springbootelasticsearch) and it is working fine. Can you share a project that reproduces the issue described, please?

**Comment by amergey** [comment]
Hi @eddumelendez your example works because it is a unit test. 
The issue occurs when the elasticsearch container is started from an uber jar packaged spring boot application. When the code is executed outside (in a dev workspace, or in a unit test) it is working fine because classpath resource url is not the new specific url introduced by spring. I can provide a jar file reproducing the issue, but the source code is pretty simple 
`@SpringBootApplication
public class SpringBootElasticsearchApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringBootElasticsearchApplication.class, args);
	}
        @Override
	public void run(String... args) throws Exception {
            ElasticsearchContainer elasticsearch = new ElasticsearchContainer(
			"docker.elastic.co/elasticsearch/elasticsearch:7.17.5");
            elasticsearch.start();
        }
}`

**Comment by eddumelendez** [comment]
Can you elaborate a little bit more about why are you packaging Testcontainers in the uber jar? Please, read more about Spring Boot Testcontainers support in [this blogpost](https://spring.io/blog/2023/06/23/improved-testcontainers-support-in-spring-boot-3-1/).

Giving the current support Spring Boot provides for Testcontainers. I don't think the use case is an expected one.
