### ISSUE TITLE
Tests reliably fail on my mac because image ID remains null in BuildImageResultCallback

### ISSUE THREAD

**Issue by sscarduzio** [testcontainers/testcontainers-java#841]
I can't run tests locally in ReadonlyREST. The test waits some time for the container to startup (way less than the 15 minutes I set up as a timeout), but then it throws:

```

org.testcontainers.containers.ContainerFetchException: Can't get Docker image: org.testcontainers.images.builder.ImageFromDockerfile@3da30852

	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:967)
	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:351)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:217)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:212)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:717)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not build image
	at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:76)
	at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:51)
	at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:141)
	at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:30)
	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:27)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:965)
	... 12 more

```

I have set a breakpoint right before the exception is thrown in `com.github.dockerjava.core.command.BuildImageResultCallback#getImageId` and noticed that the image id is actually well known in the `this$0.dockerImageName` at the time the exception is thrown. The field is just not picked up by the field "this.imageId" (bottom of the screenshot).

<img width="1355" alt="screen shot 2018-08-20 at 12 00 29" src="https://user-images.githubusercontent.com/1327189/44334393-acabcc80-a471-11e8-8350-5b99238e54dd.png">

I demonstrated this is the only issue by manually taking the image name from `this$0.dockerImageName` and injecting it inside `this.imageId`. And everything worked then.

How is it possible that the value does not get to `this.imageId`?

**Comment by bsideup** [comment]
Hi @sscarduzio,

Sorry for taking so long! Have you tried version 1.8.3?

**Comment by sscarduzio** [comment]
Hello Sergei, 1.8.3 fails even before that. 
In a with @ClassRule static container initialization like [this](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/integration-tests/src/test/java/tech/beshu/ror/integration/RorKbnAuthTests.java#L50), I get an not so informative exception. 

```
org.testcontainers.containers.ContainerFetchException: Can't get Docker image: org.testcontainers.images.builder.ImageFromDockerfile@7d151a

	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:841)
	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:311)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:197)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:638)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.io.UncheckedIOException: java.io.IOException: Pipe closed
	at org.testcontainers.utility.MountableFile.recursiveTar(MountableFile.java:324)
	at org.testcontainers.utility.MountableFile.transferTo(MountableFile.java:291)
	at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:135)
	at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:30)
	at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
	at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:27)
	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:839)
	... 11 more
	Suppressed: java.io.IOException: This archive contains unclosed entries.
		at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.finish(TarArchiveOutputStream.java:276)
		at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.close(TarArchiveOutputStream.java:293)
		at org.testcontainers.images.builder.ImageFromDockerfile.resolve(ImageFromDockerfile.java:138)
		... 15 more
Caused by: java.io.IOException: Pipe closed
	at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:260)
	at java.io.PipedInputStream.receive(PipedInputStream.java:226)
	at java.io.PipedOutputStream.write(PipedOutputStream.java:149)
	at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
	at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
	at java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:145)
	at org.apache.commons.compress.utils.CountingOutputStream.write(CountingOutputStream.java:48)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream$BufferAtATimeOutputChannel.write(FixedLengthBlockOutputStream.java:241)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.writeBlock(FixedLengthBlockOutputStream.java:92)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.maybeFlush(FixedLengthBlockOutputStream.java:86)
	at org.apache.commons.compress.utils.FixedLengthBlockOutputStream.write(FixedLengthBlockOutputStream.java:122)
	at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.write(TarArchiveOutputStream.java:439)
	at java.nio.file.Files.copy(Files.java:2909)
	at java.nio.file.Files.copy(Files.java:3069)
	at org.testcontainers.utility.MountableFile.recursiveTar(MountableFile.java:310)
	... 17 more
```

Step-by-step debugging though, I found the root exception (swallowed somewhere) is another:

```
java.lang.IllegalStateException: Mapped port can only be obtained after the container is started
	at org.testcontainers.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at org.testcontainers.containers.ContainerState.getMappedPort(ContainerState.java:88)
	at org.testcontainers.containers.GenericContainer.getLivenessCheckPort(GenericContainer.java:351)
	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:311)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:197)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:638)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
Tell me if you need more info.

**Comment by sscarduzio** [comment]
**UPDATE**: as of today at 10:04 PM UTC time, the master "SNAPSHOT" works in my IntelliJ Idea!

**Comment by bsideup** [comment]
@sscarduzio nice, thanks for testing! 👍 
We will cut an RC1 soon for the brave ones like you, I'll let you know :)

**Comment by kiview** [comment]
@sscarduzio I assume it also works with 1.9.1 for you? I'll close the issue for now.

**Comment by sscarduzio** [comment]
yes thank you, this worked. 
I'm back on having the snapshot dependency on the project's master branch. 👌
