### ISSUE TITLE
[Bug]: Can't connect to Ryuk possibly due to some strange docker network interaction.

### ISSUE THREAD

**Issue by FeatureSpitter** [testcontainers/testcontainers-java#8435]
### Module

Core

### Testcontainers version

1.19.7

### Using the latest Testcontainers version?

Yes

### Host OS

Ubuntu 23

### Host Arch

Linux servy 6.5.0-15-generic #15-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan  9 17:03:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Docker version

```shell
25.0.4 (but also with 24)
```

### What happened?

Testcontainer can't connect to Ryuk in a dind setup, although it can launch it just fine.

### Relevant log output

```shell
challengefw-1  | 2024-03-11T20:23:45.906179467Z 2024-03-11 20:23:45,905 INFO  [Thread-1] org.testcontainers.dockerclient.DockerClientProviderStrategy: Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
challengefw-1  | 2024-03-11T20:23:45.942779763Z 2024-03-11 20:23:45,942 INFO  [Thread-1] org.testcontainers.DockerClientFactory: Docker host IP address is 172.17.0.1
challengefw-1  | 2024-03-11T20:23:45.965782949Z 2024-03-11 20:23:45,965 INFO  [Thread-1] org.testcontainers.DockerClientFactory: Connected to docker: 
challengefw-1  | 2024-03-11T20:23:45.965799679Z   Server Version: 25.0.4
challengefw-1  | 2024-03-11T20:23:45.965803699Z   API Version: 1.44
challengefw-1  | 2024-03-11T20:23:45.965807239Z   Operating System: Ubuntu 23.10
challengefw-1  | 2024-03-11T20:23:45.965810559Z   Total Memory: 7926 MB
challengefw-1  | 2024-03-11T20:23:46.015444195Z 2024-03-11 20:23:46,011 INFO  [Thread-1] org.testcontainers.containers.GenericContainer: Creating container for image: testcontainers/ryuk:0.6.0
challengefw-1  | 2024-03-11T20:23:46.026387049Z 2024-03-11 20:23:46,026 INFO  [Thread-1] org.testcontainers.utility.RegistryAuthLocator: Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: testcontainers/ryuk:0.6.0, configFile: /root/.docker/config.json, configEnv: DOCKER_AUTH_CONFIG). Falling back to docker-java default behaviour. Exception message: Status 404: No config supplied. Checked in order: /root/.docker/config.json (file not found), DOCKER_AUTH_CONFIG (not set)
challengefw-1  | 2024-03-11T20:23:46.190044652Z 2024-03-11 20:23:46,188 INFO  [Thread-1] org.testcontainers.containers.GenericContainer: Container testcontainers/ryuk:0.6.0 is starting: d9d1b5dc3bfaf2a270c546101193b6b70e9aab882597c6aaf94d588d8c0401e9
challengefw-1  | 2024-03-11T20:23:46.512207708Z 2024-03-11 20:23:46,511 INFO  [Thread-1] org.testcontainers.containers.GenericContainer: Container testcontainers/ryuk:0.6.0 started in PT0.500383635S
challengefw-1  | 2024-03-11T20:23:51.522868411Z 2024-03-11 20:23:51,522 WARN  [testcontainers-ryuk] org.testcontainers.utility.RyukResourceReaper: Can not connect to Ryuk at 172.17.0.1:32780
challengefw-1  | 2024-03-11T20:23:51.522905250Z java.net.SocketTimeoutException: Connect timed out
challengefw-1  | 2024-03-11T20:23:51.522937791Z 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
challengefw-1  | 2024-03-11T20:23:51.522941881Z 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
challengefw-1  | 2024-03-11T20:23:51.522945271Z 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
challengefw-1  | 2024-03-11T20:23:51.522948551Z 	at java.base/java.net.Socket.connect(Unknown Source)
challengefw-1  | 2024-03-11T20:23:51.522951961Z 	at org.testcontainers.utility.RyukResourceReaper.lambda$null$1(RyukResourceReaper.java:105)
challengefw-1  | 2024-03-11T20:23:51.522955261Z 	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
challengefw-1  | 2024-03-11T20:23:51.522958611Z 	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$2(RyukResourceReaper.java:101)
challengefw-1  | 2024-03-11T20:23:51.522961981Z 	at java.base/java.lang.Thread.run(Unknown Source)
challengefw-1  | 2024-03-11T20:23:56.774333311Z 2024-03-11 20:23:56,773 WARN  [testcontainers-ryuk] org.testcontainers.utility.RyukResourceReaper: Can not connect to Ryuk at 172.17.0.1:32780
challengefw-1  | 2024-03-11T20:23:56.774370961Z java.net.SocketTimeoutException: Connect timed out
challengefw-1  | 2024-03-11T20:23:56.774375771Z 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
challengefw-1  | 2024-03-11T20:23:56.774401631Z 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
challengefw-1  | 2024-03-11T20:23:56.774405522Z 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
challengefw-1  | 2024-03-11T20:23:56.774408802Z 	at java.base/java.net.Socket.connect(Unknown Source)
challengefw-1  | 2024-03-11T20:23:56.774412122Z 	at org.testcontainers.utility.RyukResourceReaper.lambda$null$1(RyukResourceReaper.java:105)
challengefw-1  | 2024-03-11T20:23:56.774415602Z 	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
challengefw-1  | 2024-03-11T20:23:56.774419011Z 	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$2(RyukResourceReaper.java:101)
challengefw-1  | 2024-03-11T20:23:56.774422461Z 	at java.base/java.lang.Thread.run(Unknown Source)
challengefw-1  | 2024-03-11T20:24:02.029261464Z 2024-03-11 20:24:02,028 WARN  [testcontainers-ryuk] org.testcontainers.utility.RyukResourceReaper: Can not connect to Ryuk at 172.17.0.1:32780
challengefw-1  | 2024-03-11T20:24:02.029295014Z java.net.SocketTimeoutException: Connect timed out
challengefw-1  | 2024-03-11T20:24:02.029299115Z 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
challengefw-1  | 2024-03-11T20:24:02.029302944Z 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
challengefw-1  | 2024-03-11T20:24:02.029306374Z 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
challengefw-1  | 2024-03-11T20:24:02.029326054Z 	at java.base/java.net.Socket.connect(Unknown Source)
challengefw-1  | 2024-03-11T20:24:02.029329494Z 	at org.testcontainers.utility.RyukResourceReaper.lambda$null$1(RyukResourceReaper.java:105)
challengefw-1  | 2024-03-11T20:24:02.029332804Z 	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
challengefw-1  | 2024-03-11T20:24:02.029336164Z 	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$2(RyukResourceReaper.java:101)
challengefw-1  | 2024-03-11T20:24:02.029339454Z 	at java.base/java.lang.Thread.run(Unknown Source)
challengefw-1  | 2024-03-11T20:24:07.284248287Z 2024-03-11 20:24:07,283 WARN  [testcontainers-ryuk] org.testcontainers.utility.RyukResourceReaper: Can not connect to Ryuk at 172.17.0.1:32780
challengefw-1  | 2024-03-11T20:24:07.284280596Z java.net.SocketTimeoutException: Connect timed out
challengefw-1  | 2024-03-11T20:24:07.284284686Z 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
challengefw-1  | 2024-03-11T20:24:07.284288286Z 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
challengefw-1  | 2024-03-11T20:24:07.284291726Z 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
challengefw-1  | 2024-03-11T20:24:07.284295046Z 	at java.base/java.net.Socket.connect(Unknown Source)
challengefw-1  | 2024-03-11T20:24:07.284298316Z 	at org.testcontainers.utility.RyukResourceReaper.lambda$null$1(RyukResourceReaper.java:105)
challengefw-1  | 2024-03-11T20:24:07.284301636Z 	at org.rnorth.ducttape.ratelimits.RateLimiter.doWhenReady(RateLimiter.java:27)
challengefw-1  | 2024-03-11T20:24:07.284305126Z 	at org.testcontainers.utility.RyukResourceReaper.lambda$maybeStart$2(RyukResourceReaper.java:101)
challengefw-1  | 2024-03-11T20:24:07.284308506Z 	at java.base/java.lang.Thread.run(Unknown Source)

---- Meanwhile at the same time I tried to curl and ping within the java container ---

root@servy:~/servy-deploy# docker exec -it ca sh <---- Going into the java container to test the connection manually
/app # curl 172.17.0.1:32780 <---- returns nothing
^C
/app # curl 172.17.0.1:8080 <---- returns nothing
^C
/app # ping 172.17.0.1  <---- seems ok
PING 172.17.0.1 (172.17.0.1): 56 data bytes
64 bytes from 172.17.0.1: seq=0 ttl=64 time=0.075 ms
64 bytes from 172.17.0.1: seq=1 ttl=64 time=0.094 ms
64 bytes from 172.17.0.1: seq=2 ttl=64 time=0.092 ms
64 bytes from 172.17.0.1: seq=3 ttl=64 time=0.108 ms
64 bytes from 172.17.0.1: seq=4 ttl=64 time=0.092 ms
^C
--- 172.17.0.1 ping statistics ---
5 packets transmitted, 5 packets received, 0% packet loss
round-trip min/avg/max = 0.075/0.092/0.108 ms
/app # exit
```

### Additional Information

``` 
# docker ps
CONTAINER ID   IMAGE                                                    COMMAND                  CREATED                  STATUS                  PORTS                                         NAMES
c6ff02716f45   testcontainers/ryuk:0.6.0                                "/bin/ryuk"              Less than a second ago   Up Less than a second   0.0.0.0:32781->8080/tcp, :::32781->8080/tcp   testcontainers-ryuk-7b029969-c32c-45c1-bfc3-2f0e31047ff8
10df19bcb31b   sjc.vultrcr.com/zylregistry/challenge-framework:latest   "java -jar service.j…"   7 seconds ago            Up 6 seconds                                                          zylyty-deploy-challengefw-1
c96e0cb9e3e3   postgres:16                                              "docker-entrypoint.s…"   7 seconds ago            Up 6 seconds            0.0.0.0:5432->5432/tcp, :::5432->5432/tcp     zylyty-deploy-challengedb-1
```

10df19bcb31b Is the java running testcontainers.

This is how I am launching the java container:

```
  challengefw:
    image: '${REPO}/${APP_CF_IMAGE_NAME}:${APP_CF_IMAGE_TAG}'
    restart: always
    environment:
      - APP_CF_DATABASE_HOST=${APP_CF_DATABASE_HOST}
      - APP_CF_DATABASE_PORT=${APP_CF_DATABASE_PORT}
      - APP_CF_DATABASE_DATABASENAME=${APP_CF_DATABASE_DATABASENAME}
      - APP_CF_DATABASE_USERNAME=${APP_CF_DATABASE_USERNAME}
      - APP_CF_DATABASE_PASSWORD=${APP_CF_DATABASE_PASSWORD}
      - TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
    volumes: # This is unsafe!
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - challengedb
```

Notice that I set `/var/run/docker.sock` and Ryuk indeed is created, it is just that the java container can't connect to it afterwards...

Logs of Ryuk:

```
2024/03/11 20:32:29 Pinging Docker...
2024/03/11 20:32:29 Docker daemon is available!
2024/03/11 20:32:29 Starting on port 8080...
2024/03/11 20:32:29 Started!
```

**BUT**, if I add `network_mode: host` to the docker-compose for this container, all works well...

I might be missing some settings in docker?

**Comment by FeatureSpitter** [comment]
@bonomat @bsideup @dajudge @daschl can you have a look?

thanks

**Comment by FeatureSpitter** [comment]
Seems to only happen in Vultr machines for some reason.

Tried with multiple Debian and Docker versions. In DigitalOcean works perfectly.
