### ISSUE TITLE
[Bug]: Failing while building postgresql:1.15.1 version 1.15.1 using ./gradlew build

### ISSUE THREAD

**Issue by shivsrivastava** [testcontainers/testcontainers-java#8557]
### Module

Core

### Testcontainers version

Core

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host Arch

x64

### Docker version

```shell
NA
```

### What happened?

Package artifact id: testcontainers-java

source code url: https://github.com/testcontainers/testcontainers-java/tree/1.15.1

Issue Description: Failing while building postgresql:1.15.1 version 1.15.1 using ./gradlew build

JDK Version: 11

Build CMD: ./gradlew build

MVN Version: NA

Error Log: 

Gradle Test Executor 1 > org.testcontainers.containers.Neo4jContainerTest > shouldDisableAuthentication FAILED
    java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:109)
        at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:136)
        at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:178)
        at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
        at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:310)
        at org.testcontainers.containers.Neo4jContainerTest.shouldDisableAuthentication(Neo4jContainerTest.java:35)

8 tests completed, 6 failed, 1 skipped

> Task :neo4j:test FAILED

FAILURE: Build failed with an exception.
	

attachement: build log attached (jdk 11)

OS: windows 10
 

### Relevant log output

```shell
Attached
```

### Additional Information

log attached
[failed_jdk_11.txt](https://github.com/testcontainers/testcontainers-java/files/15050961/failed_jdk_11.txt)

**Comment by eddumelendez** [comment]
Hi @shivsrivastava, 1.15.1 is an old version, please try with recent versions.

**Comment by shivsrivastava** [comment]
> Hi @shivsrivastava, 1.15.1 is an old version, please try with recent versions.

Hi @eddumelendez , I need this version in our project. Would you like to help me on this version please?

**Comment by shivsrivastava** [comment]
> > Hi @shivsrivastava, 1.15.1 is an old version, please try with recent versions.
> 
> Hi @eddumelendez , I need this version in our project. Would you like to help me on this version please?

Hi @eddumelendez , can you please provide an update on above issue?
