### ISSUE TITLE
Oracle XE container not started on MAC

### ISSUE THREAD

**Issue by ghost** [testcontainers/testcontainers-java#861]
I can not start the OracleTestcontainer on Mac OS X.

The following docker run works:

docker run --shm-size="2g" -p 32783:1521 -d oracle/database:11.2.0.2-xe

```
om.github.dockerjava.api.exception.NotFoundException: {"message":"No such container: ba619cbb71c7c4488c65904c211ccb71b09a6363ce8eae8db0772c1af40fd93f"}

	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:103)
	at com.github.dockerjava.netty.handler.HttpResponseHandler.channelRead0(HttpResponseHandler.java:33)
	at org.testcontainers.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.testcontainers.shaded.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.testcontainers.shaded.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at org.testcontainers.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at org.testcontainers.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at org.testcontainers.shaded.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at org.testcontainers.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1342)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at org.testcontainers.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at org.testcontainers.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:934)
	at org.testcontainers.shaded.io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:593)
	at org.testcontainers.shaded.io.netty.channel.kqueue.KQueueDomainSocketChannel$KQueueDomainUnsafe.readReady(KQueueDomainSocketChannel.java:131)
	at org.testcontainers.shaded.io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:367)
	at org.testcontainers.shaded.io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:198)
	at org.testcontainers.shaded.io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:270)
	at org.testcontainers.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at org.testcontainers.shaded.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
12:25:35.236 [main] DEBUG org.testcontainers.utility.ResourceReaper - Removed container and associated volume(s): oracle/database:11.2.0.2-xe

org.testcontainers.containers.ContainerLaunchException: Container startup failed

	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:231)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:209)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:690)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:83)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:224)
	... 18 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:297)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:226)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
	... 19 more
Caused by: org.rnorth.ducttape.TimeoutException: Timeout waiting for result with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:51)
	at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:119)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:276)
	... 21 more
Caused by: org.testcontainers.containers.ContainerLaunchException: Container failed to start
	at org.testcontainers.containers.JdbcDatabaseContainer.lambda$waitUntilContainerStarted$0(JdbcDatabaseContainer.java:122)
	at org.rnorth.ducttape.unreliables.Unreliables.lambda$retryUntilSuccess$0(Unreliables.java:41)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kiview** [comment]
Hey @rogergl,
have you tried increasing the timeout of the Oracle Testcontainer?
Also do you see any logs from the container? Just check with `docker logs`.

**Comment by pacphi** [comment]
I am facing the same problem.  I am using Spring Boot 2.0.6.RELEASE and Junit 5 with Gradle 4.10.2.  In `src/test/resources/testcontainers.properties`  I have `oracle.container.image=wnameless/oracle-xe-11g:18.04`.

Sample test implementation...

```
ExtendWith(SpringExtension.class)
@SpringBootTest
@ContextConfiguration(
    initializers = { SomeTest.TestContainerInitializer.class })
public class SomeTest {

    private static OracleContainer oracleContainer = 
        (OracleContainer) new OracleContainer()
            .withUsername("admin")
            .withPassword("password");

    @Autowired
    private OrdersRepository ordersRepo;

    @Autowired
    private LineItemsRepository lineItemsRepo;

    @BeforeAll
    public static void startup() {
        oracleContainer.start();
    }

    @AfterAll
    public static void shutdown() {
        oracleContainer.stop();
    }

    @Test
    public void canDoSomething() {
        // test logic and assertions here
    }

    static class TestContainerInitializer implements ApplicationContextInitializer<ConfigurableApplicationContext> {

        @Override
        public void initialize(ConfigurableApplicationContext applicationContext) {
            TestPropertyValues
                .of(
                    "spring.datasource.url=" + oracleContainer.getJdbcUrl(),
                    "spring.datasource.username=" + oracleContainer.getUsername(),
                    "spring.datasource.password=" + oracleContainer.getPassword(),
                    "spring.datasource.driver-class-name=" + oracleContainer.getDriverClassName()
                )
                .applyTo(applicationContext.getEnvironment());
        }
    }
}
```

Here's what I see from Gradle output...

```
> Task :test

foo.SomeTest > classMethod FAILED
    org.testcontainers.containers.ContainerLaunchException at SomeTest.java:38
        Caused by: org.rnorth.ducttape.RetryCountExceededException at SomeTest.java:38
            Caused by: org.testcontainers.containers.ContainerLaunchException at SomeTest.java:38
                Caused by: org.rnorth.ducttape.TimeoutException at SomeTest.java:38
                    Caused by: java.sql.SQLException
                        Caused by: org.rnorth.ducttape.TimeoutException
                            Caused by: java.sql.SQLException
```

If I look at `docker logs {id}` of running container, I see...

```
Starting Oracle Net Listener.
Starting Oracle Database 11g Express Edition instance.

/usr/sbin/startup.sh: ignoring /docker-entrypoint-initdb.d/*
```

Neither of these issues that seem related in Google search helped me.

* https://github.com/docker-library/postgres/issues/193
* https://github.com/docker-library/mariadb/issues/62

Anything else to try?

**Comment by pacphi** [comment]
I moved the needle a bit, and so this is no longer an issue for me.

I swapped container images and specified `oracle.container.image=sath89/oracle-xe-11g:latest` in `testcontainers.properties`. 

Likewise I simplified the way I was instantiating the `OracleContainer` in my test to just be 

```
private static OracleContainer oracleContainer = new OracleContainer();
```

**Comment by kiview** [comment]
See #952

**Comment by eddumelendez** [comment]
the `oracle-xe` module was redesign some time ago. There should not be issue run it on macos.
