### ISSUE TITLE
[Bug]: `NoClassDefFoundError: org.apache.commons.codec.Charsets` error on upgrading commons-compress from 1.25.0 to 1.26.0

### ISSUE THREAD

**Issue by big-andy-coates** [testcontainers/testcontainers-java#8798]
### Module

Core

### Testcontainers version

Tested 1.19.7 - 1.19.8

### Using the latest Testcontainers version?

Yes

### Host OS

MacOS M2 chip

### Host Arch

ARM

### Docker version

```shell
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:04:20 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.26.1 (131620)
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:15 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### What happened?

`java.lang.NoClassDefFoundError` being thrown from `ContainerState.copyFileToContainer` because `org.apache.commons.codec.Charsets` is used by `org.apache.commons.compress.archivers.tar.TarArchiveOutputStream`, but is not available on the classpath at runtime.

### Relevant log output

```
    java.lang.NoClassDefFoundError: org/apache/commons/codec/Charsets
        at org.apache.commons.compress@1.26.0/org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.<init>(TarArchiveOutputStream.java:212)
        at org.apache.commons.compress@1.26.0/org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.<init>(TarArchiveOutputStream.java:157)
        at org.apache.commons.compress@1.26.0/org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.<init>(TarArchiveOutputStream.java:147)
        at testcontainers@1.19.7/org.testcontainers.containers.ContainerState.copyFileToContainer(ContainerState.java:350)
        at testcontainers@1.19.7/org.testcontainers.containers.KafkaContainer.containerIsStarting(KafkaContainer.java:199)
        at testcontainers@1.19.7/org.testcontainers.containers.GenericContainer.containerIsStarting(GenericContainer.java:712)
        at testcontainers@1.19.7/org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:489)
        at testcontainers@1.19.7/org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:354)
        at duct.tape@1.0.8/org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
        at testcontainers@1.19.7/org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:344)
        at testcontainers@1.19.7/org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
        at junit.jupiter@1.19.7/org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.start(TestcontainersExtension.java:280)
        at junit.jupiter@1.19.7/org.testcontainers.junit.jupiter.TestcontainersExtension$StoreAdapter.access$200(TestcontainersExtension.java:267)
        at junit.jupiter@1.19.7/org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$null$4(TestcontainersExtension.java:82)
        at junit.jupiter@1.19.7/org.testcontainers.junit.jupiter.TestcontainersExtension.lambda$startContainers$5(TestcontainersExtension.java:82)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at junit.jupiter@1.19.7/org.testcontainers.junit.jupiter.TestcontainersExtension.startContainers(TestcontainersExtension.java:82)
        at junit.jupiter@1.19.7/org.testcontainers.junit.jupiter.TestcontainersExtension.beforeAll(TestcontainersExtension.java:56)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)

        Caused by:
        java.lang.ClassNotFoundException: org.apache.commons.codec.Charsets
            at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
            at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
            at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
            ... 19 more
```

### Additional Information

I can work around the issue by adding a test dependency for `commons-codec`: 

```kotlin
testImplementation("commons-codec:commons-codec:1.17.0")
```

However, this shouldn't be necessary.  

Running `./gradlew dependencies` doesn't include `commons-codec`:

```
testRuntimeClasspath - Runtime classpath of source set 'test'.
...
|    +--- org.testcontainers:kafka:1.19.7
|    |    \--- org.testcontainers:testcontainers:1.19.7
|    |         +--- junit:junit:4.13.2 (*)
|    |         +--- org.slf4j:slf4j-api:1.7.36 -> 2.0.13
|    |         +--- org.apache.commons:commons-compress:1.24.0 -> 1.26.0 (*)
|    |         +--- org.rnorth.duct-tape:duct-tape:1.0.8
|    |         |    \--- org.jetbrains:annotations:17.0.0
|    |         +--- com.github.docker-java:docker-java-api:3.3.6
|    |         |    +--- com.fasterxml.jackson.core:jackson-annotations:2.10.3 -> 2.17.1 (*)
|    |         |    \--- org.slf4j:slf4j-api:1.7.30 -> 2.0.13
|    |         \--- com.github.docker-java:docker-java-transport-zerodep:3.3.6
|    |              +--- com.github.docker-java:docker-java-transport:3.3.6
|    |              +--- org.slf4j:slf4j-api:1.7.25 -> 2.0.13
|    |              \--- net.java.dev.jna:jna:5.13.0
...
```

I guess this is probably a bug in `commons-compress`, but thought I'd mention it as I'm hitting it using test containers.

**Comment by big-andy-coates** [comment]
Ah, I forgot that I'd already raised this upstream and got a response: https://www.mail-archive.com/dev@commons.apache.org/msg74963.html

The official answer is: add the`commons-codec:commons-codec` dependency in your own project, if its needed.
