### ISSUE TITLE
testcontainers/netty is not honoring system property

### ISSUE THREAD

**Issue by jshort** [testcontainers/testcontainers-java#884]
In my team's CI environment (TeamCity), the /tmp mount must have noexec set:

`[18:27:40][Step 1/2] 18:27:40.539 [main] INFO  o.t.shaded.io.netty.util.internal.NativeLibraryLoader - /tmp/liborg-testcontainers-shaded-netty-transport-native-epoll6066421015344963908.so exists but cannot be executed even when execute permissions set; check volume for "noexec" flag; use -Dio.netty.native.workdir=[path] to set native working directory separately.`

So in my maven surefire plugin config, I'm setting:

`<argLine>-Dio.netty.native.workdir=./</argLine>`

However, in TeamCity, I still see this (with debug logging enabled):

`[18:27:40][Step 1/2] 18:27:40.146 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/data/buildAgent/work/a6ec4b5c2887217f/commons/ocean-commons-db/target/test-classes/testcontainers.properties
[18:27:40][Step 1/2] 18:27:40.154 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/data/buildAgent/work/a6ec4b5c2887217f/commons/ocean-commons-db/target/test-classes/testcontainers.properties
[18:27:40][Step 1/2] 18:27:40.155 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides will be loaded from file:/home/teamcity/.testcontainers.properties
[18:27:40][Step 1/2] 18:27:40.155 [main] DEBUG org.testcontainers.utility.TestcontainersConfiguration - Testcontainers configuration overrides loaded from TestcontainersConfiguration(properties={oracle.container.image=sath89/oracle-xe-11g})
[18:27:40][Step 1/2] 18:27:40.349 [main] INFO  o.t.dockerclient.DockerClientProviderStrategy - Will use 'netty' transport
[18:27:40][Step 1/2] 18:27:40.381 [main] DEBUG o.t.s.i.n.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
[18:27:40][Step 1/2] 18:27:40.397 [main] DEBUG o.t.shaded.io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 4
[18:27:40][Step 1/2] 18:27:40.442 [main] DEBUG o.t.shaded.io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
[18:27:40][Step 1/2] 18:27:40.443 [main] DEBUG o.t.shaded.io.netty.util.internal.PlatformDependent0 - Java version: 8
[18:27:40][Step 1/2] 18:27:40.445 [main] DEBUG o.t.shaded.io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
[18:27:40][Step 1/2] 18:27:40.446 [main] DEBUG o.t.shaded.io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
[18:27:40][Step 1/2] 18:27:40.447 [main] DEBUG o.t.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
[18:27:40][Step 1/2] 18:27:40.447 [main] DEBUG o.t.shaded.io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
[18:27:40][Step 1/2] 18:27:40.449 [main] DEBUG o.t.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
[18:27:40][Step 1/2] 18:27:40.450 [main] DEBUG o.t.shaded.io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
[18:27:40][Step 1/2] 18:27:40.450 [main] DEBUG o.t.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
[18:27:40][Step 1/2] 18:27:40.450 [main] DEBUG o.t.shaded.io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
[18:27:40][Step 1/2] 18:27:40.450 [main] DEBUG o.t.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
[18:27:40][Step 1/2] 18:27:40.450 [main] DEBUG o.t.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
[18:27:40][Step 1/2] 18:27:40.452 [main] DEBUG o.t.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
[18:27:40][Step 1/2] 18:27:40.452 [main] DEBUG o.t.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 1566048256 bytes
[18:27:40][Step 1/2] 18:27:40.452 [main] DEBUG o.t.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
[18:27:40][Step 1/2] 18:27:40.467 [main] DEBUG o.t.shaded.io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
[18:27:40][Step 1/2] 18:27:40.512 [main] DEBUG o.t.shaded.io.netty.util.internal.NativeLibraryLoader - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
[18:27:40][Step 1/2] 18:27:40.512 [main] DEBUG o.t.shaded.io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)`

Specifically that last line, but I put the rest for context.

In my actual test code, I have some logging statements that print all system properties and the `io.netty.native.workdir` property is set to what I overwrite it with and not /tmp.

Any ideas?

**Comment by bsideup** [comment]
Hi @jshort! Have you tried 1.9.1? It comes with OkHttp transport by default instead of Netty :)

**Comment by jshort** [comment]
Tried 1.9.1 and hit a different shared object issue:

```
[19:54:37][Step 1/2]  due to java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: /tmp/jna--1668127416/jna2679415362161863700.tmp: /tmp/jna--1668127416/jna2679415362161863700.tmp: failed to map segment from shared object: Operation not permitted
[19:54:37][Step 1/2] java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: /tmp/jna--1668127416/jna2679415362161863700.tmp: /tmp/jna--1668127416/jna2679415362161863700.tmp: failed to map segment from shared object: Operation not permitted
[19:54:37][Step 1/2] 	at org.rnorth.ducttape.timeouts.Timeouts.callFuture(Timeouts.java:68)
[19:54:37][Step 1/2] 	at org.rnorth.ducttape.timeouts.Timeouts.getWithTimeout(Timeouts.java:43)
[19:54:37][Step 1/2] 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:38)
[19:54:37][Step 1/2] 	at org.testcontainers.dockerclient.DockerClientProviderStrategy.ping(DockerClientProviderStrategy.java:190)
[19:54:37][Step 1/2] 	at org.testcontainers.dockerclient.EnvironmentAndSystemPropertyClientProviderStrategy.test(EnvironmentAndSystemPropertyClientProviderStrategy.java:42)
[19:54:37][Step 1/2] 	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$2(DockerClientProviderStrategy.java:113)
[19:54:37][Step 1/2] 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
[19:54:37][Step 1/2] 	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:302)
[19:54:37][Step 1/2] 	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:731)
```

**Comment by jshort** [comment]
I guess the root of the issue is:

I, a testcontainers-java user, want to use test-containers java but I cannot use `/tmp`.  What system properties or testcontainer configuration can I present such that `/tmp` is not used.

**Comment by jshort** [comment]
A workaround was to set this maven command line option for the TeamCity job: `-Djava.io.tmpdir=%system.teamcity.build.workingDir%/tmp`
