### ISSUE TITLE
[Bug]: cannot access a member of class org.testcontainers.utility.DefaultImageNameSubstitutor

### ISSUE THREAD

**Issue by martinformi** [testcontainers/testcontainers-java#9149]
### Module

Core

### Testcontainers version

1.20.1

### Using the latest Testcontainers version?

Yes

### Host OS

Windows

### Host Arch

amd64

### Docker version

```shell
4.33.1
```

### What happened?

I am unable to run tests that were working before, unfortunately the exception looks very technical and "internal", no idea how to fix this for now. Any hint?

```java
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, classes = {Aaa.class})
@Testcontainers
@AutoConfigureMockMvc
@ActiveProfiles("test")
@Import({TestcontainersConfiguration.class})
abstract class AbtractContainerIntegrationTest {

    static DockerComposeContainer<?> dockerComposeContainer = new DockerComposeContainer<>(new File("docker/docker-compose.yml"))
            .withLocalCompose(true)
            .withExposedService("kafka", 9092,
                    new WaitAllStrategy(WaitAllStrategy.Mode.WITH_INDIVIDUAL_TIMEOUTS_ONLY)
                            .withStrategy(Wait.forListeningPort()));

    private static final String KAFKA_URL = "0.0.0.0:39092";

    @BeforeAll
    static void setup() throws InterruptedException {
        dockerComposeContainer.start();

        //Topics
        var client = AdminClient.create(Map.of("bootstrap.servers", KAFKA_URL));
        client.createTopics(
              .....
        );
        Thread.sleep(2000);
    }

    @DynamicPropertySource
    static void kafkaProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.kafka.bootstrap-servers", () -> KAFKA_URL);
        registry.add("myplant.kafka.bootstrap-servers", () -> KAFKA_URL);
        registry.add("seshat.url", () -> System.getenv("wiremock.server.port"));
    }

}
```

Getting this:

```
Caused by: java.lang.IllegalAccessException: class java.util.ServiceLoader$ProviderImpl (in module java.base) cannot access a member of class org.testcontainers.utility.DefaultImageNameSubstitutor with modifiers "public"
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:489)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
```

**Comment by eddumelendez** [comment]
Hi, make sure you are using only have one Testcontainers version in classpath. Using maven `mvn dependency:tree` or gradle `./gradlew dependencies`. I'd recommend using `testcontainers-bom` to manage dependencies
