### ISSUE TITLE
[Bug]: Azure eventhub emulator does not start

### ISSUE THREAD

**Issue by derek-ko** [testcontainers/testcontainers-java#9168]
### Module

Core

### Testcontainers version

1.20.1

### Using the latest Testcontainers version?

Yes

### Host OS

Mac

### Host Arch

ARM

### Docker version

```shell
Client:
 Version:           27.1.1-rd
 API version:       1.45 (downgraded from 1.46)
 Go version:        go1.21.12
 Git commit:        cdc3063
 Built:             Wed Jul 24 17:06:24 2024
 OS/Arch:           darwin/arm64
 Context:           default

Server:
 Engine:
  Version:          26.1.3
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.22.5
  Git commit:       8e96db1c328d0467b015768e42a62c0f834970bb
  Built:            Sun Jul  7 17:34:20 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.7.17
  GitCommit:        3a4de459a68952ffb703bbe7f2290861a75b6b67
 runc:
  Version:          1.1.12
  GitCommit:        51d5e94601ceffbbd85688df1c928ecccbfa4685
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### What happened?

I`m trying to integrate Azure eventhub emulator with testcontainer. But I met below error message.
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image alpine/socat:1.7.4.3-r0
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:359)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
	at org.testcontainers.containers.ComposeDelegate.startAmbassadorContainer(ComposeDelegate.java:263)
	at org.testcontainers.containers.ComposeContainer.start(ComposeContainer.java:142)
```

This is my kotlin code snippet
```
        private val eventhubs = ComposeContainer(File("src/test/resources/docker-compose-mac.yml"))
            .withEnv(
                mapOf(
                    "CONFIG_PATH" to "./config.json",
                    "ACCEPT_EULA" to "N"
                )
            )
            .withExposedService(
                "emulator", 5672,
                Wait.forListeningPort().withStartupTimeout(Duration.ofSeconds(120))
            )
            .withLocalCompose(true)

        eventhubs.start()
```

And there is a docker compose file
* https://github.com/Azure/azure-event-hubs-emulator-installer/blob/main/Docker-Compose-Template/docker-compose-custom-ports-windows-mac.yml

**Comment by eddumelendez** [comment]
I got some issues initializing eventhubs but don't know why. I'd recommend to use GenericContainer. See my example [here](https://github.com/eddumelendez/testcontainers-samples/blob/main/spring-cloud-azure-eventhubs/src/test/java/com/example/springcloudazureeventhubs/SpringCloudAzureEventHubsApplicationTests.java#L33-L60)

**Comment by eddumelendez** [comment]
FTR

logs using docker compose

```
[19:39:10 WRN] <Trc Id="60006" Ch="Debug" Lvl="Warning" Kw="1000000000011110" UTC="2024-08-27T19:39:10.390Z" Msg="An exception was handled at TenantCacheComponent.OnEndRefresh. Exception message ExceptionId: cfc4b455-9f8a-4294-ad41-e295c08a4073-System.NullReferenceException: Object reference not set to an instance of an object.&#xA;   at a.a.aax.z(IAsyncResult)." />
[19:39:10 WRN] <Trc Id="60000" Ch="Operational" Lvl="Warning" Kw="4000000000011110" UTC="2024-08-27T19:39:10.434Z" Msg="Exception occurred while creating performance counters. Exception message &amp;apos;System.PlatformNotSupportedException: Performance Counters are not supported on this platform.&#xA;   at System.Diagnostics.PerformanceData.CounterSet..ctor(Guid providerGuid, Guid counterSetGuid, CounterSetInstanceType instanceType)&#xA;   at h.hM.ad()&#xA;   at h.hM.ab()&#xA;   at h.hh.A(PerformanceCounterLevel)&amp;apos;." />
[19:39:11 WRN] <Trc Id="60000" Ch="Operational" Lvl="Warning" Kw="4000000000011110" UTC="2024-08-27T19:39:11.457Z" Msg="Exception occurred while creating performance counters. Exception message &amp;apos;System.PlatformNotSupportedException: Performance Counters are not supported on this platform.&#xA;   at System.Diagnostics.PerformanceData.CounterSet..ctor(Guid providerGuid, Guid counterSetGuid, CounterSetInstanceType instanceType)&#xA;   at h.hK.ab()&#xA;   at h.hh.A(PerformanceCounterLevel)&amp;apos;." />
[19:39:11 WRN] <Trc Id="60000" Ch="Operational" Lvl="Warning" Kw="4000000000011110" UTC="2024-08-27T19:39:11.487Z" Msg="Exception occurred while creating performance counters. Exception message &amp;apos;System.PlatformNotSupportedException: Performance Counters are not supported on this platform.&#xA;   at System.Diagnostics.PerformanceData.CounterSet..ctor(Guid providerGuid, Guid counterSetGuid, CounterSetInstanceType instanceType)&#xA;   at h.hK.ab()&#xA;   at h.hh.A(PerformanceCounterLevel)&amp;apos;." />
[19:39:11 WRN] <Trc Id="60006" Ch="Debug" Lvl="Warning" Kw="1000000000011110" UTC="2024-08-27T19:39:11.494Z" Msg="An exception was handled at TenantCacheComponent.OnEndRefresh. Exception message ExceptionId: cedbe2ca-b4e0-4477-80cf-e0c621aed76f-System.NullReferenceException: Object reference not set to an instance of an object.&#xA;   at a.a.aax.z(IAsyncResult)." />
[19:39:11 WRN] <Trc Id="60000" Ch="Operational" Lvl="Warning" Kw="4000000000011110" UTC="2024-08-27T19:39:11.674Z" Msg="Exception occurred while creating performance counters. Exception message &amp;apos;System.PlatformNotSupportedException: Performance Counters are not supported on this platform.&#xA;   at System.Diagnostics.PerformanceData.CounterSet..ctor(Guid providerGuid, Guid counterSetGuid, CounterSetInstanceType instanceType)&#xA;   at h.hp.ac()&#xA;   at h.hp.ab()&#xA;   at h.hh.A(PerformanceCounterLevel)&amp;apos;." />
```

expected
```
info: a.a.aap[0]
      Emulator Service is Launching On Platform:CBL-Mariner/Linux,X64
info: a.a.aap[0]
      Instantiating service components
info: a.a.aap[0]
      Creating namespace, entities and consumer groups
info: a.a.aaw[0]
      Emulator is launching with config : {"LoggingConfig":{"Type":"File"},"NamespaceConfig":[{"Type":"EventHub","Name":"emulatorns1","Entities":[{"Name":"eh1","PartitionCount":2,"ConsumerGroups":[{"Name":"cg1"},{"Name":"$default"}]}]}]}
info: a.a.aap[0]
      Emulator Service is Successfully Up! ; Use connection string : "Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;"
```

Using GenericContainer, got the expected one.

**Comment by derek-ko** [comment]
Now I can start the containers, thank you!
