### ISSUE TITLE
Examples in Couchbase documentation don't work out of the box

### ISSUE THREAD

**Issue by schauder** [testcontainers/testcontainers-java#934]
I've created the following test
```
public class TestcontainerTest {

	@Rule
	public CouchbaseContainer couchbase = new CouchbaseContainer()
			.withClusterAdmin("admin", "admin") // (1) this fixed the first issue
			.withNewBucket(DefaultBucketSettings.builder()
					.enableFlush(true)
					.name("bucket-name")
					.quota(100)
					.type(BucketType.COUCHBASE)
					.build());


	@Test
	public void testSomething() {

	}
}
````

At first without the lines marked (1).
It failed with an `InvalidPasswordException`. Adding the line (1) seemed to have fixed that.
But now gives:
```
11:36:22.628 [main] DEBUG com.github.dockerjava.core.exec.InspectContainerCmdExec - GET: OkHttpWebTarget(okHttpClient=org.testcontainers.shaded.okhttp3.OkHttpClient@16a0ee18, baseUrl=http://localhost:54657/, path=[/containers/a3502be83b42aa255ee0b4f3e76adf9624c6877ab139204d6ff5e068774ba271/json], queryParams={})
11:36:22.631 [ducttape-0] DEBUG com.github.dockerjava.core.command.AbstrDockerCmd - Cmd: a3502be83b42aa255ee0b4f3e76adf9624c6877ab139204d6ff5e068774ba271,false,com.github.dockerjava.core.exec.InspectContainerCmdExec@26f94b3f
11:36:22.631 [ducttape-0] DEBUG com.github.dockerjava.core.exec.InspectContainerCmdExec - GET: OkHttpWebTarget(okHttpClient=org.testcontainers.shaded.okhttp3.OkHttpClient@16a0ee18, baseUrl=http://localhost:54657/, path=[/containers/a3502be83b42aa255ee0b4f3e76adf9624c6877ab139204d6ff5e068774ba271/json], queryParams={})
11:36:22.636 [main] INFO org.testcontainers.containers.wait.strategy.HttpWaitStrategy - /dazzling_poitras: Waiting for 60 seconds for URL: http://localhost:33240/ui/index.html
11:36:32.739 [main] INFO 🐳 [couchbase/server:5.5.1] - Container couchbase/server:5.5.1 started
11:36:32.776 [main] INFO org.testcontainers.containers.wait.strategy.HttpWaitStrategy - /dazzling_poitras: Waiting for 60 seconds for URL: http://localhost:33240/pools/default/
11:37:32.783 [main] ERROR 🐳 [couchbase/server:5.5.1] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://localhost:33240/pools/default/ should return HTTP [200])
	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:197)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.couchbase.CouchbaseContainer.initCluster(CouchbaseContainer.java:231)
	at org.testcontainers.couchbase.CouchbaseContainer.createCouchbaseEnvironment(CouchbaseContainer.java:332)
	at org.testcontainers.couchbase.CouchbaseContainer.getCouchbaseEnvironment(CouchbaseContainer.java:92)
	at org.testcontainers.couchbase.CouchbaseContainer.createCouchbaseCluster(CouchbaseContainer.java:328)
	at org.testcontainers.couchbase.CouchbaseContainer.getCouchbaseCluster(CouchbaseContainer.java:95)
	at org.testcontainers.couchbase.CouchbaseContainer.createBucket(CouchbaseContainer.java:256)
	at org.testcontainers.couchbase.CouchbaseContainer.containerIsStarted(CouchbaseContainer.java:322)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:295)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:237)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:235)
	at org.testcontainers.couchbase.CouchbaseContainer.doStart(CouchbaseContainer.java:130)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:220)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:738)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
11:37:32.784 [main] ERROR 🐳 [couchbase/server:5.5.1] - Container log output (if any) will follow:
11:37:32.792 [tc-okhttp-stream-1188401255] INFO 🐳 [couchbase/server:5.5.1] - STDOUT: Starting Couchbase Server -- Web UI available at http://<ip>:8091
11:37:32.792 [tc-okhttp-stream-1188401255] INFO 🐳 [couchbase/server:5.5.1] - STDOUT: and logs available in /opt/couchbase/var/lib/couchbase/logs
11:37:32.793 [main] DEBUG 🐳 [couchbase/server:5.5.1] - 
+ Profiler [Container startup]
|-- elapsed time [Prepare container configuration and host configuration]     0.000  seconds.
|---+ Profiler [Container startup attempt]
    |-- elapsed time       [Create container]     0.983  seconds.
    |-- elapsed time        [Start container]     0.892  seconds.
    |-- elapsed time   [Inspecting container]     0.004  seconds.
    |-- elapsed time [Call containerIsStarting on subclasses]     0.000  seconds.
    |-- elapsed time [Wait until container has started properly, or there's evidence it failed to start.]     0.004  seconds.
    |-- elapsed time [Wait until container started properly]    70.158  seconds.
    |-- Subtotal     [Container startup attempt]    72.040  seconds.
|-- elapsed time [Container startup attempt]    72.040  seconds.
|-- Total             [Container startup]    72.041  seconds.

11:37:32.805 [main] INFO org.testcontainers.containers.wait.strategy.HttpWaitStrategy - /dazzling_poitras: Waiting for 60 seconds for URL: http://localhost:33240/pools/default/

org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://localhost:33240/pools/default/ should return HTTP [200])

	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:197)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.couchbase.CouchbaseContainer.initCluster(CouchbaseContainer.java:231)
	at org.testcontainers.couchbase.CouchbaseContainer.createCouchbaseEnvironment(CouchbaseContainer.java:332)
	at org.testcontainers.couchbase.CouchbaseContainer.getCouchbaseEnvironment(CouchbaseContainer.java:92)
	at org.testcontainers.couchbase.CouchbaseContainer.createCouchbaseCluster(CouchbaseContainer.java:328)
	at org.testcontainers.couchbase.CouchbaseContainer.getCouchbaseCluster(CouchbaseContainer.java:95)
	at org.testcontainers.couchbase.CouchbaseContainer.stopCluster(CouchbaseContainer.java:188)
	at org.testcontainers.couchbase.CouchbaseContainer.stop(CouchbaseContainer.java:183)
	at org.testcontainers.containers.GenericContainer.finished(GenericContainer.java:760)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:36)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255
```

**Comment by kiview** [comment]
Hey Jens,
can you just check if the following code works? It comes directly from our tests and it should work:
```
new CouchbaseContainer().withClusterAdmin("admin", "foobar");
```
Also I assume you are using Testcontainers 1.9.1?

Worst case you might need to add a breakpoint somewhere and look into the container logs to see why couchbase isn't coming up.

**Comment by schauder** [comment]
Yes, that version does work.
Yes, it's Testcontainers 1.9.1

Unfortunately, I never use Couchbase before either. :-/

I took the code almost literally from the readme page of the couchbase module: https://github.com/testcontainers/testcontainers-java/tree/master/modules/couchbase

**Comment by kiview** [comment]
Again disclaimer, no Couchbase user here, but this works 🙂 
```
CouchbaseContainer couchbaseContainer = new CouchbaseContainer()
            .withClusterAdmin("admin", "foobar")
            .withNewBucket(DefaultBucketSettings.builder()
            .enableFlush(true)
            .name("bucket-name")
            .quota(100)
            .password("foobar")
            .type(BucketType.COUCHBASE)
            .build());
```

Can you give it a try? Basically specifying password for the bucket.

**Comment by bsideup** [comment]
Also, maybe @kaidowei knows what happens

**Comment by schauder** [comment]
Ok, that is interesting.

It does work.
But if you change the two passwords to `admin` it doesn't. So these seem to be a preconfigured user/password.

I thought it would configure a user (and password) to be created.

**Comment by kiview** [comment]
This happens for every bucket:
https://github.com/testcontainers/testcontainers-java/blob/05b3c0100837f3b70aa017e0ebc7e094f2e043ee/modules/couchbase/src/main/java/org/testcontainers/couchbase/CouchbaseContainer.java#L255-L272

Since the classes involved in this operation are not from Testcontainers but from Couchbase, I don't think this is a Testcontainers related problem.
Using `secret` as the password value works by the way, so I maybe Couchbase doesn't allow same value for username and password.

We could probably improve UX by failing early and with more specific errors.

**Comment by schauder** [comment]
Thanks, that clears it up.

Having a dedicated error would indeed help.
Also, the example in the documentation could be fixed.

Thanks again.

**Comment by kiview** [comment]
You are right. I've changed the title of the issue, so that we at least cleanup the examples.
