### ISSUE TITLE
Container restart retried without waiting

### ISSUE THREAD

**Issue by jfdez-s24** [testcontainers/testcontainers-java#942]
Hi, I started using TestContainers today. Thanks a lot. It simplifies the work a lot. However, I'm facing problems.

Im using version 1.9.1 with MySQLContainer. When I run the tests locally it works like a charm.  

However, in the build server from my company, it  may take longer to run and an exception is thrown from `GenericContainer#tryStart` before reaching the invocation of the retry strategy.

So it would be great to invoke the wait strategy also when an exception happens.

The exception is not very clarifying because it might be caused by the container not being started yet:

```
java.lang.IllegalStateException: copyFileToContainer can only be used with created / running container
	at org.testcontainers.containers.GenericContainer.copyFileToContainer(GenericContainer.java:1075)
	at org.testcontainers.containers.GenericContainer.copyFileToContainer(GenericContainer.java:1067)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:262)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:237)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:235)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:220)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:738)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
```

**Comment by kiview** [comment]
Hi @jfdez-s24, sorry for the late reaction.
How do you define and integrate the `MySQLContainer`?

Inside the `tryStart()` method, we are running `copyFileToContainer` after the container has been created, but before it's started.

The `createContainerCmd` is executed in a blocking way, but I think we don't check the execution for failures, which means, the container creation might have failed.

**Comment by guenhter** [comment]
I had a similar issue with copying files into the container. The `copyFiletoContainer` needs the container be started. If you'd like to define the files to copy into the container before the container is actually started, use the function `withCopyFileToContainer(...)` of the `GenericContainer`

cheers

**Comment by jfdez-s24** [comment]
Hi @guenhter. Thanks, but it is not my case. I am not trying to copy any content to the container

**Comment by guenhter** [comment]
Alright. I acutally just looked at the stacktrace `ava.lang.IllegalStateException: copyFileToContainer`...

**Comment by pepelu0** [comment]
Any progress? I got the same ERROR.

And I got
```
2019-10-11  15:24:11.393 [Druid-ConnectionPool-Create-1076642142] ERROR 🐳 [mysql:5.7] - There are no stdout/stderr logs available for the failed container
2019-10-11  15:24:11.394 [Druid-ConnectionPool-Create-1076642142] ERROR com.alibaba.druid.pool.DruidDataSource - create connection RuntimeException
org.testcontainers.containers.ContainerLaunchException: Container startup failed
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:231)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:213)
	at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:118)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:156)
	at com.alibaba.druid.filter.FilterAdapter.connection_connect(FilterAdapter.java:786)
	at com.alibaba.druid.filter.FilterEventAdapter.connection_connect(FilterEventAdapter.java:38)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:218)
	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:150)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1560)
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2468)
Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:83)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:224)
	... 11 common frames omitted
Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:291)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:226)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
	... 12 common frames omitted
Caused by: java.lang.IllegalStateException: copyFileToContainer can only be used with created / running container
	at org.testcontainers.containers.GenericContainer.copyFileToContainer(GenericContainer.java:1065)
	at org.testcontainers.containers.GenericContainer.copyFileToContainer(GenericContainer.java:1057)
	at java.util.HashMap.forEach(HashMap.java:1288)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:248)
	... 14 common frames omitted
```

**Comment by bsideup** [comment]
@pepelu0 you're getting an error because you're not using the API correctly.

See @guenhter's comment:
https://github.com/testcontainers/testcontainers-java/issues/942#issuecomment-499458203

**Comment by pepelu0** [comment]
Thanks @bsideup . But I am not trying to copy file myself. I am just using `org.testcontainers.jdbc.ContainerDatabaseDriver` to start container and connect to mysql. And I am using version 1.11.4

**Comment by bsideup** [comment]
@pepelu0 have you tried the latest (1.12.2 as of today) version by any chance? If not, please do, it may help

**Comment by pepelu0** [comment]
@bsideup , after upgrade to 1.12.2 I can still run my test cases in MAC, but got the same error on my Jenkins node w/ centos 6.5 and docker 1.7.1

**Comment by bsideup** [comment]
@pepelu0 oh... Docker 1.7.1 is waay too old and not supported, consider updating it to the latest.
