### ISSUE TITLE
TC doesn't find the Compose YAML when run in Jenkins + K8s plugin

### ISSUE THREAD

**Issue by kshepitko** [testcontainers/testcontainers-java#948]
Hi, 

I'm struggling to make TestContainers 1.9.1 work in Jenkins running with K8s plugin (https://github.com/jenkinsci/kubernetes-plugin). The plugin spins up a temporary pod for tests, and then deletes it.
So I'm using a Gradle container (https://hub.docker.com/_/gradle/) to run the tests.

In tests I'm starting the app ecosystem using Docker compose, I'm starting it like this in the code:

```
    @ClassRule
    public static DockerComposeContainer ECOSYSTEM =
            new DockerComposeContainer(locateInClasspath("docker/ci-docker-compose.yml"))
                    .withExposedService("one", 1, 8081,
                            Wait.forHttp("/actuator/health").forStatusCode(200))
                    .withExposedService("two", 1, 8082,
                            Wait.forHttp("/api/health").forStatusCode(200))
                    .withLocalCompose(false)
                    .withPull(true)
                    .withTailChildContainers(true);

    private static File locateInClasspath(String pathToFile) {
        URL resource = Resources.getResource(pathToFile);
        try {
            return new File(resource.toURI());
        } catch (URISyntaxException e) {
            throw new RuntimeException(e);
        }
    }


```

So I'm using a containerized Docker compose (`compose.container.image=docker/compose:1.20.1` in `testcontainers.properties`), because Gradle container obviously doesn't have a Compose on board.

This stuff works nice locally, but fails in Jenkins:

```
2018-11-02 14:29:05.598 [testcontainers-ryuk]  DEBUG o.t.u.ResourceReaper : Received 'ACK' from Ryuk
2018-11-02 14:29:05.601 [Test worker]  DEBUG ?.2.1] : Set env COMPOSE_FILE=/home/jenkins/workspace/test/myproject/acceptance-tests/build/resources/main/docker/ci-docker-compose.yml
...........
2018-11-02 14:29:06.709 [Test worker]  DEBUG c.g.d.c.c.AbstrDockerCmd : Cmd: com.github.dockerjava.core.command.CreateContainerCmdImpl@68258217[name=<null>,hostName=<null>,domainName=<null>,user=<null>,attachStdin=<null>,attachStdout=<null>,attachStderr=<null>,portSpecs=<null>,tty=<null>,stdinOpen=<null>,stdInOnce=<null>,env={DOCKER_HOST=unix:///docker.sock,COMPOSE_PROJECT_NAME=gwucaju4kr7s,COMPOSE_FILE=/home/jenkins/workspace/test/myproject/acceptance-tests/build/resources/main/docker/ci-docker-compose.yml},cmd={pull},entrypoint=<null>,image=docker/compose:1.20.1,volumes=com.github.dockerjava.api.model.Volumes@6c5dbeb7,workingDir=/home/jenkins/workspace/test/myproject/acceptance-tests/build/resources/main/docker/,macAddress=<null>,networkDisabled=<null>,exposedPorts=com.github.dockerjava.api.model.ExposedPorts@4a68f92f,stopSignal=<null>,hostConfig=com.github.dockerjava.api.model.HostConfig@2a6a09b0[binds=com.github.dockerjava.api.model.Binds@6e9b03d0,blkioWeight=<null>,blkioWeightDevice=<null>,blkioDeviceReadBps=<null>,blkioDeviceReadIOps=<null>,blkioDeviceWriteBps=<null>,blkioDeviceWriteIOps=<null>,memorySwappiness=<null>,capAdd=<null>,capDrop=<null>,containerIDFile=<null>,cpuPeriod=<null>,cpuShares=<null>,cpuQuota=<null>,cpusetCpus=<null>,cpusetMems=<null>,devices=<null>,diskQuota=<null>,dns=<null>,dnsSearch=<null>,extraHosts={},links=com.github.dockerjava.api.model.Links@6fb2b0b2,logConfig=<null>,lxcConf=<null>,memory=<null>,memorySwap=<null>,memoryReservation=<null>,kernelMemory=<null>,networkMode=<null>,oomKillDisable=<null>,autoRemove=<null>,oomScoreAdj=<null>,portBindings={},privileged=<null>,publishAllPorts=true,readonlyRootfs=<null>,restartPolicy=<null>,ulimits=<null>,volumesFrom={},pidMode=<null>,securityOpts=<null>,cgroupParent=<null>,volumeDriver=<null>,shmSize=<null>,pidsLimit=<null>,runtime=<null>,tmpFs=<null>],labels={org.testcontainers=true, org.testcontainers.sessionId=007f209b-4bea-4894-9cf2-c9761d23d5b4},networkingConfig=<null>,ipv4Address=<null>,ipv6Address=<null>,aliases=<null>,authConfig=AuthConfig[username=...,password=...,email=<null>,registryAddress=https://index.docker.io/v1/,auth=....,registrytoken=<null>],execution=com.github.dockerjava.core.exec.CreateContainerCmdExec@18433f90]
2018-11-02 13:18:38.798 [Test worker]  INFO  ?.2.1] : Container docker/compose:1.20.1 is starting: 3f1911201f506e57b2202ecd6e0fc450a56fa98e629ba3440a204297d3f4f84d
    2018-11-02 13:18:39.653 [Test worker]  ERROR ?.2.1] : Could not start container
    java.lang.IllegalStateException: Container did not start correctly.
    	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:288)
    	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:237)
    	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
    	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:235)
    	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:220)
    	at org.testcontainers.containers.ContainerisedDockerCompose.invoke(DockerComposeContainer.java:553)
    	at org.testcontainers.containers.DockerComposeContainer.runWithCompose(DockerComposeContainer.java:216)
    	at org.testcontainers.containers.DockerComposeContainer.createServices(DockerComposeContainer.java:170)
    	at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:157)
    	at org.testcontainers.containers.DockerComposeContainer.starting(DockerComposeContainer.java:122)
    	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
    	at org.junit.runners.Suite.runChild(Suite.java:128)
    	at org.junit.runners.Suite.runChild(Suite.java:27)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
....................
    	at java.lang.Thread.run(Thread.java:748)
    2018-11-02 13:18:39.673 [Test worker]  ERROR ?.2.1] : Container log output (if any) will follow:
    2018-11-02 13:18:39.686 [tc-okhttp-stream-1852939244]  INFO  ?.2.1] : STDERR: .FileNotFoundError: [Errno 2] No such file or directory: '/home/jenkins/workspace/test/myproject/acceptance-tests/build/resources/main/docker/ci-docker-compose.yml'
```

The strange thing is `/home/jenkins/workspace/test/myproject/acceptance-tests/build/resources/main/docker/ci-docker-compose.yml` actually exists in the Gradle container - I have checked that. So apparently it was't mounted properly into the Compose container.
I see that the mounting is happening in the constructor of `ContainerisedDockerCompose`:

```
        final File dockerComposeBaseFile = composeFiles.get(0);
        final String pwd = dockerComposeBaseFile.getAbsoluteFile().getParentFile().getAbsolutePath();
        final String containerPwd = MountableFile.forHostPath(pwd).getFilesystemPath();
        final List<String> absoluteDockerComposeFiles = composeFiles.stream().map(File::getAbsolutePath).map(MountableFile::forHostPath).map(MountableFile::getFilesystemPath).collect(toList());
        final String composeFileEnvVariableValue = Joiner.on(UNIX_PATH_SEPERATOR).join(absoluteDockerComposeFiles); // we always need the UNIX path separator
        logger().debug("Set env COMPOSE_FILE={}", composeFileEnvVariableValue);

```

Apparently, the directory containing the Compose file was mounted; the expected file is logged above. Unfortunately, the DockerJava logs above do not tell much about the actual volumes and FS bindings.
Any ideas what's wrong? Running the Gradle container in privileged mode doesn't help.

The pipeline definition, if matters:
```
    podTemplate(cloud: 'my-build', label: "${env.PROJECT}-${BUILD_NUMBER}", imagePullSecrets: ['docker-registry'], containers: [
            containerTemplate(name: 'jnlp', image: 'commonimg/jenkins-jnlp-slave:1.6-jenkins3.20-jdk8u171-alpine3.8', command: 'jenkins-slave', args: '${computer.jnlpmac} ${computer.name}'),
            containerTemplate(name: 'gradle', image: 'gradle:4.8', ttyEnabled: true, command: 'cat', args: '/dev/stdin')
    ],
            volumes: [
                    persistentVolumeClaim(claimName: 'gradle-repo', mountPath: '/root/.gradle/'),
                    secretVolume(secretName: 'docker-registry-sock', mountPath: "/home/jenkins/.docker/"),
                    secretVolume(secretName: 'kubectl-context-dev-cluster', mountPath: "/home/jenkins/.kube/"),
                    hostPathVolume(mountPath: "/var/run/docker.sock", hostPath: "/var/run/docker.sock")
            ]) {
        node("${env.PROJECT}-${BUILD_NUMBER}") {
            stage('Checkout') {
                checkoutScm()
            }

            stage('Acceptance tests') {
                container(name: 'gradle') {
                    try {
                        runProjectScript("build")
                    } catch (Exception e) {
                        currentBuild.result = "FAILED"
                    } finally {
                        publishHTML([allowMissing: false, alwaysLinkToLastBuild: true, keepAll: true,
                                     reportDir: "build/reports/tests/test", reportFiles: 'index.html',
                                     reportName: 'Unit Tests HTML Report', reportTitles: ''])

                        allure([includeProperties: false, jdk: '', properties: [], reportBuildPolicy: 'ALWAYS'])
                    }
                }
            }
        }
    }
}

```

**Comment by flostadler** [comment]
We have exactly the same problem running on a windows machine.

**Comment by abhishek-rdm** [comment]
I am facing still facing this issue on test container 1.15.3 with jenkins + kuberntes +docker in docker , could you please have help?

**Comment by Tonicku** [comment]
+1 too follow

**Comment by cpfeiffer** [comment]
Same here with testcontainers 1.17.6
