### ISSUE TITLE
[Bug]: Cannot parse Date when deserializing com.github.dockerjava.api.model.Network object

### ISSUE THREAD

**Issue by gsaviane** [testcontainers/testcontainers-java#9542]
### Module

Core

### Testcontainers version

1.20.3

### Using the latest Testcontainers version?

Yes

### Host OS

Ubuntu 20.04

### Host Arch

x86_64

### Docker version

```shell
Client:
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.21.1
 Git commit:        24.0.7-0ubuntu2~20.04.1
 Built:             Wed Mar 13 20:29:24 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.21.1
  Git commit:       24.0.7-0ubuntu2~20.04.1
  Built:            Wed Mar 13 20:29:24 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.12
  GitCommit:        
 runc:
  Version:          1.1.12-0ubuntu2~20.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### What happened?

We have some integration tests written in Junit5 brining up a GenericContainer for end-to-end tests between components. When the tests are run in a host process the GenericContainer object is created successfully, but when tests are run within a container (like in Jenkins) the GenericContainer fails to build, throwing the exception reported in the log pane.

Debugging the code, it seems the GenericContainer fails to deserialize dates in com.github.dockerjava.api.model.Network object when inspecting the docker network. The date format returned with docker network inspect is indeed "2024-11-13T21:04:48.309416219+0100", but apparently the BaseSettings initialized in ObjectMapper uses a StdDateFormat that is not able to parse it.

Reverting the dependency to testcontainers 1.17.6 made it work. I think this could be a regression.

### Relevant log output

```shell
java.lang.RuntimeException: org.testcontainers.shaded.com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type java.util.Date from String "2024-11-13T21:04:48.309416219+01:00": not a valid representation (error: Failed to parse Date value '2024-11-13T21:04:48.309416219+01:00': Can not parse date "2024-11-13T21:04:48.309416219+0100": while it seems to fit format 'yyyy-MM-dd'T'HH:mm:ss.SSSZ', parsing fails (leniency? null))

 at [Source: N/A; line: -1, column: -1] (through reference chain: com.github.dockerjava.api.model.Network["Created"])
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:77) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.InspectNetworkCmdExec.execute(InspectNetworkCmdExec.java:26) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.InspectNetworkCmdExec.execute(InspectNetworkCmdExec.java:12) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.shaded.com.github.dockerjava.core.command.InpectNetworkCmdImpl.exec(InpectNetworkCmdImpl.java:7) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.resolveDockerHostIpAddress(DockerClientProviderStrategy.java:453) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getDockerHostIpAddress(DockerClientProviderStrategy.java:424) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.DockerClientFactory.dockerHostIpAddress(DockerClientFactory.java:344) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.containers.ContainerState.getHost(ContainerState.java:64) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.containers.wait.strategy.HostPortWaitStrategy.waitUntilReady(HostPortWaitStrategy.java:112) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:52) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:901) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:492) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:346) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar:?]
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:336) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.containers.PortForwardingContainer.createSSHSession(PortForwardingContainer.java:43) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.containers.PortForwardingContainer.getSshConnection(PortForwardingContainer.java:38) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.containers.PortForwardingContainer.exposeHostPort(PortForwardingContainer.java:69) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.containers.PortForwardingContainer.exposeHostPort(PortForwardingContainer.java:63) ~[testcontainers-1.20.3.jar:1.20.3]
	at org.testcontainers.Testcontainers.exposeHostPorts(Testcontainers.java:14) ~[testcontainers-1.20.3.jar:1.20.3]
```

**Comment by gsaviane** [comment]
> This issue has been fixed in jackson-databind 2.9.1 [FasterXML/jackson-databind#1745](https://github.com/FasterXML/jackson-databind/issues/1745) https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.1

Do you mean the Jackson library shaded in testcontainers embeds a prior version with that bug?
In our maven dependencyManagement we link to Jackson 2.17.0. But I don't think it gets picked up by testcontainers, otherwise the entire shaded logic would not work as intended

**Comment by enochdavidson** [comment]
Yes, testcontainers includes an outdated version of the Jackson library. 
Please see https://github.com/testcontainers/testcontainers-java/blob/f7267c7639d2e87c600f40fbb68e72f6268d3e0c/core/build.gradle#L66
Thus, Testcontainers should provide a fix.

**Comment by eddumelendez** [comment]
In the meantime, you can update the dependency by yourself. I have done that in another project and list network wit no issues. Jackson version has not been updated to keep compatibility with other projects using older versions, see https://github.com/testcontainers/testcontainers-java/issues/3433.

**Comment by enochdavidson** [comment]
> In the meantime, you can update the dependency by yourself. I have done that in another project and list network wit no issues. Jackson version has not been updated to keep compatibility with other projects using older versions, see [#3433](https://github.com/testcontainers/testcontainers-java/issues/3433).

@eddumelendez 
How would I override the shaded jackson-databind to 2.9.1?

**Comment by eddumelendez** [comment]
shaded dependencies can not be overridden. jackson dependencies are shaded and transitives dependencies in testcontainers. So, what I meant is just updating the transitives dependencies.

**Comment by EVPA0306** [comment]
I had the same issue when I run TC tests on Jenkins pipeline. 
I downgraded TC version to 1.19.5 and solved the issue!
Hope it helps

**Comment by eddumelendez** [comment]
Can someone share a project that reproduces the issue?

**Comment by EVPA0306** [comment]
I’m sorry, I can’t because it’s corporate project.

**Comment by eddumelendez** [comment]
It doesn't need to be the same project. It can be a small project that has everything needed to reproduce the issue you mention.

**Comment by ZPavel** [comment]
Hi.
I have the same issue. Any chance to be fixed soon please?
Thx, Pavel

**Comment by enochdavidson** [comment]
This temporary workaround worked for a Spring Boot application. 
Copy `com.fasterxml.jackson.databind.util.StdDateFormat` from latest `jackson-databind` to the `org.testcontainers.shaded.com.fasterxml.jackson.databind.util` package in your source code and ensure it loads before other libraries.
Hope this helps!

**Comment by bademux** [comment]
@enochdavidson are you sure it works without recompilation?
Package is different.

**Comment by enochdavidson** [comment]
@bademux 
You need to copy the source (.java) to your project and update the `package` and `import` statements if needed.
<img width="194" alt="Image" src="https://github.com/user-attachments/assets/104f2f5f-fc0d-4fdf-8390-d867ce309f62" />
<img width="337" alt="Image" src="https://github.com/user-attachments/assets/f96a9f5c-1bb1-4a40-a38f-ed085e1cadae" />

**Comment by dvinci-gefi** [comment]
I am also experiencing this issue when running tests on Gitlab CI with a docker executor. I tried to create a project for reproduction, but with no success so far.

It happens when we call the start() method of GenericContainer.

`java.lang.RuntimeException: org.testcontainers.shaded.com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type java.util.Date from String "2025-03-03T14:25:12.722942905+01:00": not a valid representation (error: Failed to parse Date value '2025-03-03T14:25:12.722942905+01:00': Can not parse date "2025-03-03T14:25:12.722942905+0100": while it seems to fit format 'yyyy-MM-dd'T'HH:mm:ss.SSSZ', parsing fails (leniency? null))
 at [Source: N/A; line: -1, column: -1] (through reference chain: com.github.dockerjava.api.model.Network["Created"])
	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.get(DefaultInvocationBuilder.java:77)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.InspectNetworkCmdExec.execute(InspectNetworkCmdExec.java:26)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.InspectNetworkCmdExec.execute(InspectNetworkCmdExec.java:12)
	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:33)
	at org.testcontainers.shaded.com.github.dockerjava.core.command.InpectNetworkCmdImpl.exec(InpectNetworkCmdImpl.java:7)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.resolveDockerHostIpAddress(DockerClientProviderStrategy.java:453)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getDockerHostIpAddress(DockerClientProviderStrategy.java:424)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:208)
	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:108)
	at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:109)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:321)
	at org.testcontainers.lifecycle.Startable$start.call(Unknown Source)`

**Comment by kiview** [comment]
As @eddumelendez pointed out above, can someone please share a minimal reproducer?
I would like to understand if this comes through a combination of different dependencies leading to weird Jackson version mixes, or if it originates from Docker Engine or Kernel versions.

**Comment by gsaviane** [comment]
I am not able to reproduce the issue in a minimal project, but I debugged the code and got more clues about the cause.
If you see the stack trace that I posted in my very first comment, the exception throws when, calling exposePort() reaches InpectNetworkCmdImpl (it's not a typo, I guess it misses an 's'), that is for inspecting the network. The com.github.dockerjava.api.model.Network object gets deserialized from the API call and causes the exception to throw when the Created field gets parsed. The ObjectMapper in the shaded docker-java uses StdDateFormat to parse the date in it, but it fails due to an unexpected format that is 2024-11-13T21:04:48.309416219+01:00 (ISO 8601 with nanos and TZ), whereas StdDateFormat wants  yyyy-MM-dd'T'HH:mm:ss.SSSZ.
If I set ISO8601DateFormat as format, the date is parsed correctly, although I cannot completely hijack the ObjectMapper initialized in Testcontainers to override the deserializer for Network.Created field only.
Note that this situation occurs only when my Testcontainer is run as Docker-in-Docker, If run within a normal host process, there is no inspection of the Network, thus no error. Note also that in the project that I tried to reproduce with the same settings of my project, the Network is inspected but there is no Created field coming up there. Apparently the API does not return the same set of fields in different conditions.
All in all, if the docker API treats dates only with ISO 8601 format, wouldn't it be a possible solution to set the date format to ISO8601DateFormat in Testcontainers ObjectMapper?

**Comment by oneiros-de** [comment]
I'm facing the same issue with 1.21.4 and gitlab runners with the latest docker version

**Comment by snuyanzin** [comment]
>As @eddumelendez pointed out above, can someone please share a minimal reproducer?

@eddumelendez, @kiview I think I have a repro (testcontainers 1.21.4) which fails on java8 and passes on java 11, 17, 21
we have same issue in Apache Flink which is reproducible in our CI pipeline 100%

I tend to think that there are several ways to fix it
1. bump jdk where SimpleDateFormat was improved
2. bump jackson to 2.9.x where these bugs were fixed (https://github.com/FasterXML/jackson-databind/issues/1678, https://github.com/FasterXML/jackson-databind/issues/1745, https://github.com/FasterXML/jackson-databind/issues/1744, https://github.com/FasterXML/jackson-databind/issues/1788)
```java
import org.testcontainers.shaded.com.fasterxml.jackson.databind.ObjectMapper;
import java.util.Date;

// Reproduces the Flink 1.20 Azure CI MinioTestContainerTest failure:
// testcontainers' shaded jackson deserializing Docker's Network["Created"]
// timestamp into java.util.Date. Same string, same jar -> differs by JDK.
public class DateBugRepro {
    public static void main(String[] args) {
        ObjectMapper m = new ObjectMapper(); // default mapper => StdDateFormat (ISO8601)
        String[] inputs = {
            "2022-10-27T14:57:17.758157913+08:00", // Alibaba CI agent: non-UTC offset + 9-digit nanos
            "2022-10-27T06:57:17.758157913Z",      // GitHub runner: UTC, 'Z'
            "2022-10-27T14:57:17.758+08:00"        // offset but only millis
        };
        System.out.println("java.version = " + System.getProperty("java.version"));
        for (String s : inputs) {
            try {
                Date d = m.readValue("\"" + s + "\"", Date.class);
                System.out.println("  OK    " + s + "  ->  " + d);
            } catch (Exception e) {
                String msg = e.getMessage();
                if (msg != null) msg = msg.split("\\n")[0];
                System.out.println("  FAIL  " + s + "  ->  " + e.getClass().getSimpleName());
            }
        }
        System.out.println();
    }
}
```

**Comment by nafis0kle** [comment]
### My workaround: upgrading to Testcontainers 2.0.5

**Environment:** Java 8, Testcontainers 1.21.4, `postgres:15.0-alpine`, Docker Engine 29.4.0 (build on Jenkins). Same `InvalidFormatException` parsing the `Network["Created"]` date.

**Fix:** upgraded `testcontainers.version` to `2.0.5`. The artifact layout changed in 2.x, so dependencies had to be updated:

```xml
<dependency>
    <groupId>org.testcontainers</groupId>
    <artifactId>testcontainers-postgresql</artifactId>
    <version>${testcontainers.version}</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.testcontainers</groupId>
    <artifactId>testcontainers-junit-jupiter</artifactId>
    <version>${testcontainers.version}</version>
    <scope>test</scope>
</dependency>
```

Also had to add explicit Jackson dependencies (2.x apparently needs a newer Jackson than what was on the classpath to correctly parse the Docker API's date format):

```xml
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
</dependency>
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
</dependency>
```

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson</groupId>
            <artifactId>jackson-bom</artifactId>
            <version>2.22.0</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
```

**Note:** if you spin up a Postgres Testcontainer from a build plugin (e.g. `gmavenplus-plugin` for Liquibase codegen), that plugin has its own isolated classpath — you'll need to bump `testcontainers-postgresql` and pin `jackson-databind` there too, otherwise the plugin's own dependency resolution can still pull in the old, broken versions even though your main `test` scope is fixed.
