### ISSUE TITLE
[Bug]: Cassandra package does not exist while running mvn test

### ISSUE THREAD

**Issue by mdharish08** [testcontainers/testcontainers-java#9622]
### Module

Cassandra

### Testcontainers version

1.20.4

### Using the latest Testcontainers version?

Yes

### Host OS

Mac

### Host Arch

x86

### Docker version

```shell
Docker Desktop 4.36.0
```

### What happened?

when running mvn test package org.testcontainers.cassandra does not exist occurs.But for other containers it is working fine.

### Relevant log output

```shell
java.lang.NoClassDefFoundError: org/testcontainers/cassandra/CassandraContainer

	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
	at org.junit.platform.commons.util.ReflectionUtils.getDeclaredFields(ReflectionUtils.java:1470)
	at org.junit.platform.commons.util.ReflectionUtils.findAllFieldsInHierarchy(ReflectionUtils.java:1200)
	at org.junit.platform.commons.util.ReflectionUtils.findFields(ReflectionUtils.java:1188)
	at org.junit.jupiter.engine.descriptor.ExtensionUtils.registerExtensionsFromFields(ExtensionUtils.java:96)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.prepare(ClassBasedTestDescriptor.java:150)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.prepare(ClassBasedTestDescriptor.java:80)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: java.lang.ClassNotFoundException: org.testcontainers.cassandra.CassandraContainer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 41 more
```

**Comment by eddumelendez** [comment]
Using maven execute `mvn dependency:tree` or gradle `./gradlew dependencies` and make sure testcontainers libraries use the same version. I recommend using the Testcontainers BOM.

**Comment by eddumelendez** [comment]
I am not able to reproduce. have you executed `mvn dependency:tree`? That the whole pom.xml file?

**Comment by mdharish08** [comment]
- 
- @eddumelendez 
- org.projectlombok:lombok:jar:1.18.20:provided
[INFO] +- com.datastax.oss:java-driver-mapper-runtime:jar:4.13.0:compile
[INFO] |  +- com.datastax.oss:java-driver-query-builder:jar:4.13.0:compile
[INFO] |  |  \- com.datastax.oss:java-driver-shaded-guava:jar:25.1-jre-graal-sub-1:compile
[INFO] |  +- com.github.stephenc.jcip:jcip-annotations:jar:1.0-1:compile
[INFO] |  \- com.github.spotbugs:spotbugs-annotations:jar:3.1.12:compile
[INFO] |     \- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] +- com.zoho.flow:constants:jar:1.0.0-SNAPSHOT:compile
[INFO] |  +- com.squareup:javapoet:jar:1.13.0:provided
[INFO] |  \- com.datastax.oss:java-driver-core-shaded:jar:4.13.0:compile
[INFO] |     +- com.datastax.oss:native-protocol:jar:1.5.0:compile
[INFO] |     +- com.typesafe:config:jar:1.4.1:compile
[INFO] |     +- com.github.jnr:jnr-posix:jar:3.1.5:compile
[INFO] |     |  \- com.github.jnr:jnr-constants:jar:0.10.1:compile
[INFO] |     +- io.dropwizard.metrics:metrics-core:jar:4.1.18:compile
[INFO] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[INFO] |     \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] +- org.junit.jupiter:junit-jupiter:jar:5.11.3:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-api:jar:5.11.3:test
[INFO] |  |  +- org.opentest4j:opentest4j:jar:1.3.0:test
[INFO] |  |  +- org.junit.platform:junit-platform-commons:jar:1.11.3:test
[INFO] |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-params:jar:5.11.3:test
[INFO] |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.11.3:test
[INFO] |     \- org.junit.platform:junit-platform-engine:jar:1.11.3:test
[INFO] +- org.testcontainers:testcontainers:jar:1.20.4:test
[INFO] |  +- junit:junit:jar:4.13.2:test
[INFO] |  |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.36:compile
[INFO] |  +- org.apache.commons:commons-compress:jar:1.24.0:test
[INFO] |  +- org.rnorth.duct-tape:duct-tape:jar:1.0.8:test
[INFO] |  |  \- org.jetbrains:annotations:jar:17.0.0:test
[INFO] |  +- com.github.docker-java:docker-java-api:jar:3.4.0:test
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.10.3:test
[INFO] |  \- com.github.docker-java:docker-java-transport-zerodep:jar:3.4.0:test
[INFO] |     +- com.github.docker-java:docker-java-transport:jar:3.4.0:test
[INFO] |     \- net.java.dev.jna:jna:jar:5.13.0:test
[INFO] +- org.testcontainers:junit-jupiter:jar:1.20.4:test
[INFO] +- org.testcontainers:cassandra:jar:1.20.4:test
[INFO] |  +- org.testcontainers:database-commons:jar:1.20.4:test
[INFO] |  \- com.datastax.cassandra:cassandra-driver-core:jar:3.10.0:test
[INFO] |     +- io.netty:netty-handler:jar:4.0.56.Final:test
[INFO] |     |  +- io.netty:netty-buffer:jar:4.0.56.Final:test
[INFO] |     |  |  \- io.netty:netty-common:jar:4.0.56.Final:test
[INFO] |     |  +- io.netty:netty-transport:jar:4.0.56.Final:test
[INFO] |     |  \- io.netty:netty-codec:jar:4.0.56.Final:test
[INFO] |     +- com.google.guava:guava:jar:19.0:test
[INFO] |     +- com.github.jnr:jnr-ffi:jar:2.1.7:compile
[INFO] |     |  +- com.github.jnr:jffi:jar:1.2.16:compile
[INFO] |     |  +- com.github.jnr:jffi:jar:native:1.2.16:runtime
[INFO] |     |  +- org.ow2.asm:asm:jar:5.0.3:compile
[INFO] |     |  +- org.ow2.asm:asm-commons:jar:5.0.3:compile
[INFO] |     |  +- org.ow2.asm:asm-analysis:jar:5.0.3:compile
[INFO] |     |  +- org.ow2.asm:asm-tree:jar:5.0.3:compile
[INFO] |     |  +- org.ow2.asm:asm-util:jar:5.0.3:compile
[INFO] |     |  \- com.github.jnr:jnr-x86asm:jar:1.0.2:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-databind:jar:2.7.9.3:test
[INFO] |        \- com.fasterxml.jackson.core:jackson-core:jar:2.7.9:test
[INFO] \- org.testcontainers:mongodb:jar:1.20.4:test
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS

**Comment by eddumelendez** [comment]
interesting. I updated a project and move to the org.testcontainers.cassandra.CassandraContainer with no issues. is the problem happening in your IDE only or terminal as well?

**Comment by mdharish08** [comment]
I will check using other IDE and update here @eddumelendez .
