### ISSUE TITLE
DockerComposeContainer ignores multiple Wait strategies set

### ISSUE THREAD

**Issue by kshepitko** [testcontainers/testcontainers-java#965]
Hi,

I have a few services defined in my compose file:

```
version: '2.1'
services:
    backend:
        image: my/backend:latest
        environment:
        - SPRING_PROFILES=local
        ports:
        - "8081"
        healthcheck:
            test: curl -f http://localhost:8081/actuator/health || exit 1
            interval: 5s
            retries: 100
            timeout: 90s
    two:
        image: my/two:latest
        command: -profile=LOCAL -config=/go/bin/config/local.config.yaml
        ports:
        - "8082"
        volumes:
        - ./two-config/:/go/bin/config/:ro
        depends_on:
            backend:
                condition: service_healthy
    ui:
        image: my/ui:latest
        ports:
        - "80"
        depends_on:
            backend:
                condition: service_healthy

```

So 2 services - `two` and `ui` - are depending on `backend`.

Here's my test rule:

```
@ClassRule
    public static DockerComposeContainer ECOSYSTEM =
            new DockerComposeContainer("docker/ci-docker-compose.yml")
                    .withExposedService("backend", 1, 8081,
                            Wait.forHealthcheck().withStartupTimeout(Duration.ofMinutes(3)))
                    .withExposedService("two", 1, 8082,
                            Wait.forHttp("/api/health").withStartupTimeout(Duration.ofMinutes(3)))
                    .withLocalCompose(false)
                    .withPull(true)
                    .withTailChildContainers(true);
```

As I use the REST API of both `backend` and `two` in my test, I want to make sure they are started before I run my scenarios. That's why I wait for 3 minutes until `backend` is healthy, and for 3 minutes for `two` to start (after backend).

In reality the test fails exactly after the `backend` became healthy (~30 seconds), stating that `two` hasn't started yet. Well of course it hasn't - it was waiting for `backend` to start! But it should be fine, since according to the wait strategy there's still ~2:30 minutes to wait for the `two` startup. 

Nevertheless:

```
2018-11-08 12:35:37.085 [Thread-7]  ERROR 🐳 [docker-compose] : Creating dj3enjpnxssv_backend_1_3d53523e77fc  ... [32mdone[0m
2018-11-08 12:36:13.404 [Thread-7]  ERROR 🐳 [docker-compose] : [1BCreating dj3enjpnxssv_ui_1_e62460bbd6a5       ... 
2018-11-08 12:36:13.413 [Thread-7]  ERROR 🐳 [docker-compose] : Creating dj3enjpnxssv_two_1_8831a282e253   ... 
2018-11-08 12:36:14.106 [Thread-7]  ERROR 🐳 [docker-compose] : [1A[2K
2018-11-08 12:36:14.106 [Thread-7]  ERROR 🐳 [docker-compose] : Creating dj3enjpnxssv_two_1_8831a282e253   ... [32mdone[0m
2018-11-08 12:36:15.116 [Thread-7]  ERROR 🐳 [docker-compose] : [1B[2A[2K
2018-11-08 12:36:15.116 [Thread-7]  ERROR 🐳 [docker-compose] : Creating dj3enjpnxssv_ui_1_e62460bbd6a5       ... [32mdone[0m
2018-11-08 12:36:15.190 [Test worker]  ERROR 🐳 [docker-compose] : [2B
2018-11-08 12:36:15.191 [Test worker]  INFO  🐳 [docker-compose] : Docker Compose has finished running
2018-11-08 12:36:15.197 [Test worker]  DEBUG 🐳 [alpine/socat:latest] : Starting container: alpine/socat:latest
2018-11-08 12:36:15.197 [Test worker]  DEBUG 🐳 [alpine/socat:latest] : Trying to start container: alpine/socat:latest
2018-11-08 12:36:15.199 [Test worker]  DEBUG 🐳 [alpine/socat:latest] : Trying to start container: alpine/socat:latest (attempt 1/1)
2018-11-08 12:36:15.199 [Test worker]  DEBUG 🐳 [alpine/socat:latest] : Starting container: alpine/socat:latest
2018-11-08 12:36:15.199 [Test worker]  INFO  🐳 [alpine/socat:latest] : Creating container for image: alpine/socat:latest
2018-11-08 12:36:15.359 [Test worker]  ERROR 🐳 [alpine/socat:latest] : Could not start container
org.testcontainers.containers.ContainerLaunchException: Aborting attempt to link to container dj3enjpnxssv_two_1 as it is not running
........
```

Looks like DockerComposeContainer waits only for for the first wait strategy to come true - then it looks at other exposed services state, absolutely ignoring the wait strategies defined for them.

I was monitoring the containers' state in another terminal in parallel. The failure in test happened immediately after the backend became healthy - and according to Compose rule `two` began to start up:

```
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS                    PORTS
3d53523e77fc        my/backend:latest      "/opt/docker-wait-..."   34 seconds ago      Up 32 seconds (healthy)   0.0.0.0:32882->8001/tcp
8831a282e253        my/two:latest       "/go/bin/two -p..."   2 seconds ago       Up Less than a second     0.0.0.0:32884->8002/tcp
e62460bbd6a5        my/ui:latest           "nginx -g 'daemon ..."   2 seconds ago       Up Less than a second     0.0.0.0:32883->80/tcp
```

If I start the compose file services manually via Docker-compose, all services start fine.

**Comment by kshepitko** [comment]
OK I guess I figured out the problem:

```
2018-11-08 12:36:14.106 [Thread-7]  ERROR 🐳 [docker-compose] : Creating dj3enjpnxssv_two_1_8831a282e253 
org.testcontainers.containers.ContainerLaunchException: Aborting attempt to link to container dj3enjpnxssv_two_1 as it is not running
```

The Docker Compose version is 1.23.1, and it adds a postfix to the container name, which is not recognized by TC (DockerComposeContainer):
```
    private String getServiceInstanceName(String serviceName) {
        String serviceInstanceName = serviceName;
        if (!serviceInstanceName.matches(".*_[0-9]+")) {
            serviceInstanceName += "_1"; // implicit first instance of this service
        }
        return serviceInstanceName;
    }
```

Is there a way around it, except downgrading the Compose?

**Comment by lcardito** [comment]
Bumping into this (or a very similar issue) however I was pointing at the fact that test containers can't start the socat container:

```
2018-11-08 12:36:15.359 [Test worker]  ERROR 🐳 [alpine/socat:latest] : Could not start container
```

Any other clue?

**Comment by hellozepp** [comment]
@kshepitko Hello, how did you solve it? I'm version 3 now and have this problem too

**Comment by hellozepp** [comment]
docker-compose.yml
```
  hadoop3:
    image: "byzer/hadoop3:latest"
    restart: on-failure
    networks:
      - byzer-network
    healthcheck:
      test: [ "CMD","curl", "-f", "http://127.0.0.1:8088/cluster" ]
      interval: 2s
      timeout: 300s
      retries: 300
      start_period: 60s

  byzer-lang:
    image: "byzer/byzer-lang:3.1.1-2.3.0-SNAPSHOT"
    restart: on-failure
    networks:
      - byzer-network
    depends_on:
      hadoop3:
        condition: service_healthy
    healthcheck:
      test: [ "CMD","curl", "-f", "http://127.0.0.1:9003" ]
      interval: 2s
      timeout: 180s
      retries: 600
      start_period: 120s
```

qc7jcmsxbn4m-byzer-lang-1 should be depending on qc7jcmsxbn4m-hadoop3-1 
```
22/02/23 18:27:51  INFO 🐳 [docker-compose]: Container qc7jcmsxbn4m-hadoop3-1  Creating
22/02/23 18:27:52  INFO 🐳 [docker-compose]: Container qc7jcmsxbn4m-hadoop3-1  Created
22/02/23 18:27:52  INFO 🐳 [docker-compose]: Container qc7jcmsxbn4m-byzer-lang-1  Creating
22/02/23 18:27:53  INFO 🐳 [docker-compose]: Container qc7jcmsxbn4m-byzer-lang-1  Created
22/02/23 18:27:53  INFO 🐳 [docker-compose]: Container qc7jcmsxbn4m-hadoop3-1  Starting
22/02/23 18:28:00  INFO 🐳 [docker-compose]: Container qc7jcmsxbn4m-hadoop3-1  Started
22/02/23 18:34:02  INFO 🐳 [docker-compose]: Container qc7jcmsxbn4m-byzer-lang-1  Starting
22/02/23 18:34:10  INFO 🐳 [docker-compose]: Container qc7jcmsxbn4m-byzer-lang-1  Started
22/02/23 18:34:10  INFO 🐳 [docker-compose]: Docker Compose has finished running
22/02/23 18:34:11  INFO 4-r0]: Creating container for image: alpine/socat:1.7.3.4-r0
22/02/23 18:34:11  ERROR 4-r0]: Could not start container
org.testcontainers.containers.ContainerLaunchException: Aborting attempt to link to container qc7jcmsxbn4m_byzer-lang_1 as it is not running
	at org.testcontainers.containers.GenericContainer.applyConfiguration(GenericContainer.java:815)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:365)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:331)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:329)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:317)
	at org.testcontainers.containers.DockerComposeContainer.startAmbassadorContainers(DockerComposeContainer.java:330)
	at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:178)
	at com.dimafeng.testcontainers.DockerComposeContainer.start(DockerComposeContainer.scala:184)
	at com.dimafeng.testcontainers.ForAllTestContainer.run(ForAllTestContainer.scala:17)
	at com.dimafeng.testcontainers.ForAllTestContainer.run$(ForAllTestContainer.scala:13)
	at tech.mlsql.it.ComposeSpec.run(ComposeSpec.scala:14)
```
