### ISSUE TITLE
Please fix network alias

### ISSUE THREAD

**Issue by denis-zhdanov** [testcontainers/testcontainers-java#973]
Hello,

Could you please take a look at the problem below:
1. [This docker-compose setup](https://github.com/denis-zhdanov/samples/blob/master/docker/testcontainer-kafka-sample/docker-compose.yml) works, i.e. either zookeeper or kafka containers start and there are no errors in logs
2. [This testcontainers setup](https://github.com/denis-zhdanov/samples/blob/master/docker/testcontainer-kafka-sample/src/main/kotlin/org/denis/Start.kt) is assumed to be an equivalent of the *docker-compose* configuration above. Unfortunately, it doesn't work:
```
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: [2018-11-11 10:52:23,721] INFO Initiating client connection, connectString=zookeeper:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@5c5eefef (org.apache.zookeeper.ZooKeeper)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: [2018-11-11 10:52:23,750] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: [2018-11-11 10:52:23,753] INFO Opening socket connection to server zookeeper:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: [2018-11-11 10:52:23,769] WARN Session 0x0 for server zookeeper:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: java.nio.channels.UnresolvedAddressException
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: 	at sun.nio.ch.Net.checkAddress(Net.java:101)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: 	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: 	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: 	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: 	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: [2018-11-11 10:52:24,880] INFO Opening socket connection to server zookeeper:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: [2018-11-11 10:52:24,881] WARN Session 0x0 for server zookeeper:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: java.nio.channels.UnresolvedAddressException
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: 	at sun.nio.ch.Net.checkAddress(Net.java:101)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: 	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: 	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: 	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: 	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
[tc-okhttp-stream-706895319] INFO 🐳 [bitnami/kafka:2.0.0] - STDOUT: 	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
```

Environment:

```
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G3025
```

```
docker -v
Docker version 18.06.1-ce, build e68fc7a
```

**Comment by bsideup** [comment]
zookeeper.network is not set, this is why it doesn't work.

Also, there is Kafka module already, with (optionally) built in Zookeeper:
https://github.com/testcontainers/testcontainers-java/blob/master/modules/kafka/src/test/java/org/testcontainers/containers/KafkaContainerTest.java

**Comment by denis-zhdanov** [comment]
That was it, thanks!

Yeah, I know that there is a kafka container, I'd like to use the same image as the one configured in production though.

**Comment by bsideup** [comment]
Fair enough :) Happy to help! Just be careful with the advertised Kafka
host, it gets tricky with random ports (see KafkaContainer's sources for
the details)

**Comment by denis-zhdanov** [comment]
Yeah, thanks!

I'm refactoring integration tests to run from docker now (to use a fixed environment and allow tests running in parallel). So, the port mapping wouldn't be necessary.

[Not related to the original question] Could you share best practices for running tests from docker? Right now I use the following approach:

1. Environment, target application and tests run in the same docker network
2. Test application dumps test run results into particular directory
3. Test application container is started with bind mount for the test output directory
4. Test harness creates a temporary directory, starts all docker containers and monitors the tmp directory until test results are available

Is there any support for running tests from docker in the *testcontainers*?
