### ISSUE TITLE
testcontainer docker-compose does not work in a docker-in-docker environment

### ISSUE THREAD

**Issue by joerg-pfruender** [testcontainers/testcontainers-java#980]
We do our builds in a docker in docker environment on jenkins. Docker-compose testcontainers has two problems there:

## pull image
Testcontainer's docker-compose can not pull images from our local docker-registry that requires credentials. 
### Workaround
Pre-fetch the images before the build. docker-compose will use the images, that are already there.

## startup seems to fail
The ambassador container can not connect to the services. 

### Workaround
Use a fake WaitStrategy, that does nothing. Then, after compose-up has completed, ensure on your own, that the startup has been correctly. Use your host in the `docker0` network for that, which is in my case 172.17.0.1 . Please pay attention: DockerComposeContainer.getServicePort() might throw an IllegalStateException when the service is not yet started.

**Comment by flpa** [comment]
@joerg-pfruender, I might be affected by similar problems. Could you please provide some details what "startup seems to fail" looks like in your scenario?

In my case it looks like this:
```
[main] ERROR 🐳 [alpine/socat:latest] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Aborting attempt to link to container yd7khfnujpzd_ci_1 as it is not running
        at org.testcontainers.containers.GenericContainer.applyConfiguration(GenericContainer.java:492)
        at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:256)
        at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:237)
        at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:76)
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:235)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:220)
        at org.testcontainers.containers.DockerComposeContainer.startAmbassadorContainers(DockerComposeContainer.java:248)
        at org.testcontainers.containers.DockerComposeContainer.start(DockerComposeContainer.java:158)
        at org.testcontainers.containers.DockerComposeContainer.starting(DockerComposeContainer.java:122)
        at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
[main] INFO 🐳
[Thread-6] ERROR 🐳 [docker-compose] - Stopping yd7khfnujpzd_db_1_cc8870369381 ... done
[Thread-6] ERROR 🐳 [docker-compose] - Removing yd7khfnujpzd_db_1_cc8870369381 ... done
[Thread-6] ERROR 🐳
[Thread-6] ERROR 🐳
[main] INFO 🐳
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 34.134 sec <<< FAILURE!
com.signon.it.test.HeartbeatTest  Time elapsed: 34.133 sec  <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup 
```

**Comment by joerg-pfruender** [comment]
Maybe :-)

The message "Could not start container" is displayed in many
different situations.

I've found my solution by inspecting the status of the containers with
the usual docker commands. `docker ps` tells you which docker containers
are running on which port. Then you can connect to that containers via
http and see if they are healthy. If that is possible, then a fake
WaitStrategy will help you.

But how to inspect the docker commands on the correct time?

On your local machine you could set a breakpoint and debug the test.

On your build server that might not be the way to go. For Debugging
there you can also add a fake WaitStrategy and inside the test adding
`Thread.sleep(1000*60*5)` should give you enough time to look at docker's
status. Yes, you will need console access for that.

Good luck!
