### ISSUE TITLE
MS SQL Server not supported with correct url.

### ISSUE THREAD

**Issue by neetkee** [testcontainers/testcontainers-java#988]
When specifying jdbc url for MS SQL Server like this:
` jdbc:tc:sqlserver:2017-CU12://somehost:someport;databaseName=test `
it will throw an exception:
```
Caused by: java.lang.UnsupportedOperationException: Database name sqlserver not supported
	at org.testcontainers.jdbc.ContainerDatabaseDriver.connect(ContainerDatabaseDriver.java:99) ~[jdbc-1.10.1.jar:na]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:119) ~[HikariCP-3.2.0.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369) ~[HikariCP-3.2.0.jar:na]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198) ~[HikariCP-3.2.0.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467) ~[HikariCP-3.2.0.jar:na]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:541) ~[HikariCP-3.2.0.jar:na]
```
**Reason**: MSSQLServerContainerProvider checks support by comparing variable NAME in  MSSQLServerContainer with database type in url
**Solution**: change NAME to "sqlserver" to support [connection url](https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-2017)
**Example project with error**: https://github.com/neetkee/tc-mssql-naming

**Comment by kiview** [comment]
Fixed by #989
